documentation/docs/api-references/hooks/resource/useMenu.md, packages/core/src/assets/styles/custom-theme.less, packages/core/src/assets/styles/styles.min.css, packages/core/src/components/layoutWrapper/components/sider/index.tsx
[Link to SIDE-MENU-ENHANCEMENT](https://side-me-refine.pankod.com)
closes #1110 
[Link to SIDE-MENU-ENHANCEMENT](https://side-me-doc-refine.pankod.com)
=> remove buggy styles of Sider 

package.json, packages/core/package.json
[Link to MOVE-GENERATE-THEME-TO-CORE](https://move-ge-refine.pankod.com)
closes #1112
=> move and rename theming script

examples/refine-next/pages/_app.tsx, examples/refine-next/pages/users/index.tsx, packages/core/src/components/layoutWrapper/index.tsx, packages/nextjs-router/src/index.ts
It handles warning when there are unsaved changes.
=> Prompt for nextjs-router

packages/core/package.json
Changing this line allows Vite to bundle properly.
closes #1122
=> Fix module import string 

examples/fineFoods/admin/src/App.tsx, examples/fineFoods/admin/src/components/index.ts, examples/fineFoods/admin/src/components/offLayoutArea/index.tsx, examples/fineFoods/admin/src/components/offLayoutArea/style.less, examples/fineFoods/client/pages/_app.tsx, examples/fineFoods/client/src/components/index.ts, examples/fineFoods/client/src/components/offLayoutArea/index.tsx, examples/fineFoods/client/src/components/offLayoutArea/style.less
[Link to DEMO-SWITCH-TOGGLE](https://demo-sw-refine.pankod.com)
Hey, I'm client! Test me! 'ALPHA'
[Link to DEMO-SWITCH-TOGGLE](https://demo-sw-client.refine.pankod.com)
=> Switch Toggle for Demo Pages

README.md, documentation/src/components/hero/index.js, documentation/src/components/hero/styles.module.css
[Link to ADD-PRODUCTHUNT-BADGE](https://add-pro-doc-refine.pankod.com)
=> Add Product Hunt Badge

documentation/docs/migration-guide.md, documentation/versioned_docs/version-2.xx.xx/migration-guide.md
resolves #1227
[Link to ADD-LINK-MIGRATION-DOCS](https://add-lin-doc-refine.pankod.com)
=> add docs for Link

documentation/blog/2021-11-12-issue-tracker-refine.md
Test documentation! 'BLOG'
[Link to BLOG-EDIT](https://blog-ed-doc-refine.pankod.com)
=> blog image changed

documentation/blog/2021-10-4-admin-panel-with-nestjs.md, documentation/blog/2021-11-12-issue-tracker-refine.md
[Link to BLOGS-EDIT](https://blogs-e-doc-refine.pankod.com)
=> blog repo url  and title edited

documentation/docs/api-references/components/buttons/clone.md, documentation/docs/api-references/components/refine-config.md, documentation/docs/api-references/hooks/form/useForm.md, documentation/versioned_docs/version-2.xx.xx/api-references/components/buttons/clone.md, documentation/versioned_docs/version-2.xx.xx/api-references/components/refine-config.md, documentation/versioned_docs/version-2.xx.xx/api-references/hooks/form/useForm.md, packages/core/src/components/buttons/clone/index.spec.tsx, packages/core/src/hooks/form/useCloneForm/useCloneForm.spec.tsx, packages/core/src/hooks/form/useCloneForm/useCloneForm.ts, packages/core/src/hooks/form/useDrawerForm/useDrawerForm.ts, packages/core/src/hooks/form/useEditForm/useEditForm.ts, packages/core/src/hooks/form/useForm.ts, packages/core/src/hooks/form/useModalForm/useModalForm.ts, packages/core/src/hooks/navigation/index.spec.tsx, packages/core/src/hooks/navigation/index.ts, packages/core/src/interfaces/resourceRouterParams.ts, packages/nextjs-router/src/nextRouteComponent.tsx, packages/react-location/src/resourceComponent.tsx, packages/react-location/src/routerComponent.tsx, packages/react-router/src/routeProvider.tsx
[Link to USE-FORM-ACTION-FIX](https://use-for-refine.pankod.com)
[Link to USE-FORM-ACTION-FIX](https://use-for-client.refine.pankod.com)
#1260
=> fix useForm action on nested pages

examples/fineFoods/admin/package-lock.json, examples/fineFoods/admin/package.json, packages/core/package-lock.json, packages/core/package.json
[Link to PEER-DEPENDENCIES-FIX](https://peer-de-refine.pankod.com)
We moved dayjs and andtd dependencies to peerDependencies
#1259
=> add dayjs and antd to peerDependencies

documentation/docs/comparison.md, documentation/sidebars.js, documentation/versioned_docs/version-2.xx.xx/comparison.md, documentation/versioned_sidebars/version-2.xx.xx-sidebars.json
[Link to COMPARISON-ADMIN-PANEL](https://compari-doc-refine.pankod.com)
=> comparison table

packages/core/src/hooks/form/useEditForm/useEditForm.ts
[Link to FIX-USE-FORM-METADATA](https://fix-use-refine.pankod.com)
closes #1299
=> pass metadata to mutate from useEditForm

packages/supabase/src/index.ts, packages/supabase/test/getList/index.mock.ts
[Link to FIX-SUPABASE-CONTAINS-NCONTAINS-FILTER-OPERATOR](https://fix-sup-client.refine.pankod.com)
Contains and containss filters fixed
#1282
=> [Bug] Fix supabase contains containss filter operator

documentation/docs/examples/web3/signin-ethereum.md, documentation/sidebars.js, documentation/versioned_docs/version-2.xx.xx/examples/web3/signin-ethereum.md, documentation/versioned_sidebars/version-2.xx.xx-sidebars.json
[Link to WEB3-EXAMPLE](https://web3-ex-doc-refine.pankod.com)
=> web3 login example added

documentation/docs/guides-and-concepts/data-provider/graphql.md, documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/data-provider/graphql.md, examples/dataProvider/strapi-graphql/src/pages/posts/edit.tsx, examples/dataProvider/strapi-graphql/src/pages/posts/show.tsx
closes #1184
[Link to GRAPHQL-REFRESH-BUTTON-DOCS](https://graphql-doc-refine.pankod.com)
=> update example and docs for RefreshButton

examples/dataProvider/airtable/src/App.tsx, examples/dataProvider/airtable/src/pages/posts/list.tsx, examples/dataProvider/airtable/src/pages/posts/show.tsx
Fixed bugs that prevented the Airtable example from working.
- #1385
=> [Bug] Fix Airtable example

packages/altogic/src/index.ts, packages/appwrite/src/index.ts, packages/appwrite/test/getList/index.spec.ts, packages/simple-rest/src/index.ts, packages/supabase/src/index.ts, packages/supabase/test/getList/index.spec.ts
[Link to HANDLE-NOT-IMPLEMENTED-FILTER-OPERATORS](https://handle--client.refine.pankod.com)
Error is now thrown for unsupported filters in Data Providers.
- #1390
=> handle not supporeted filter operators on data providers

documentation/docs/guides-and-concepts/data-provider/strapi-v4.md
Typo fix - Releations to Relations
=> Typo fix - Releations to Relations

packages/core/src/components/containers/refine/index.tsx
Fix typo notifcationConfig into notificationConfig
=> Fix typo types

documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/data-provider/strapi-v4.md
[Link to FIX-TYPO-GUIDE](https://fix-typ-doc-refine.pankod.com)
=> Typo fix - Releations to Relations in versioned docs

examples/multi-tenant/cakeHouse/src/components/product/create.tsx, examples/multi-tenant/cakeHouse/src/pages/orders/create.tsx, examples/multi-tenant/cakeHouse/src/pages/products/list.tsx
=> unnecessary used any type fixed

documentation/docusaurus.config.js, documentation/src/css/custom.css
[Link to DOCS-ANNOUNCEMENT-BAR](https://docs-an-doc-refine.pankod.com)
=> added announcementBar to docs

documentation/docusaurus.config.js
[Link to EDIT-ANNOUNCEMENT-BAR](https://edit-an-doc-refine.pankod.com)
=> announcementBar edited

documentation/docusaurus.config.js
[Link to DOCS-LINK-EDITS](https://docs-li-doc-refine.pankod.com)
=> docs link edited

packages/core/src/hooks/auth/useLogin/index.ts
[Link to FIX-USE-LOGIN-QUERYSTRING-UNDEFINED](https://fix-use-refine.pankod.com)
handle query string undefined case on `useLogin` hook
=> handle querystring undefined case on useLogin hook

documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/custom-layout.md
=> fix: 🐛 fixed custom-layout.md typo error

examples/refine-next/next-env.d.ts, packages/nextjs-router/src/nextRouteComponent.tsx
[Link to HANDLE-CUSTOM-ROUTES-NEXTJS-ROUTER](https://handle--refine.pankod.com)
Issue: #1442 
- closes #1442
=> Handle custom route option on @pankod/refine-nextjs-router

examples/tailwind/src/pages/posts/list.tsx, packages/antd/src/hooks/table/useTable/useTable.ts, packages/core/src/hooks/useTable/index.ts, packages/react-table/jest.config.js, packages/react-table/package.json, packages/react-table/src/useTable/index.spec.ts, packages/react-table/src/useTable/index.ts, packages/react-table/test/dataMocks.ts, packages/react-table/test/index.tsx, packages/react-table/tsconfig.json, packages/react-table/tsconfig.test.json
[Link to REACT-TABLE-TESTS](https://react-t-refine.pankod.com)
=> Add Refine React Table Unit Tests

examples/tailwind/src/pages/posts/list.tsx, packages/antd/src/hooks/table/useTable/useTable.ts, packages/core/src/hooks/useTable/index.ts, packages/react-table/src/useTable/index.ts
Hey, I'm client! Test me! 'ALPHA'
[Link to USE-TABLE-UNION-FILTERS-AND-SORTERS](https://use-tab-client.refine.pankod.com)
[Link to USE-TABLE-UNION-FILTERS-AND-SORTERS](https://use-tab-refine.pankod.com)
=> Update useTable's setFilter and setSorter Functions with Union

packages/core/src/components/fields/date/index.tsx
This closes #1451 
Can someone please review this code changes?
=> fix DateField to receive TextProps

documentation/docs/guides-and-concepts/real-time.md
=> refine-ably import packages uptade

documentation/docs/guides-and-concepts/upload/base64-upload.md
[Link to BASE64-DOCS-UPDATE](https://base64--doc-refine.pankod.com)
=> base64 import packages update

documentation/docs/guides-and-concepts/search/search.md
[Link to REFINE-SEARCH-DOCS-UPDATE](https://refine--doc-refine.pankod.com)
=> refine-search import packages update

documentation/docs/guides-and-concepts/search/table-search.md
[Link to TABLE-SEARCH-DOCS-UPDATE](https://table-s-doc-refine.pankod.com)
=> table-search import packages update

documentation/docs/guides-and-concepts/import-export/csv-import.md
[Link to CSV-IMPORT-DOCS-UPDATE](https://csv-imp-doc-refine.pankod.com)
=> csv-import docs import packages update

documentation/docs/guides-and-concepts/forms/custom-form-validation.md
[Link to CUSTOM-VALIDATION-DOCS-UPDATE](https://custom--doc-refine.pankod.com)
=> custom-validation import packages update

documentation/docs/guides-and-concepts/import-export/csv-export.md
[Link to CSV-EXPORT-DOCS-UPDATE](https://csv-exp-doc-refine.pankod.com)
=> csv-export docs import packages update

documentation/docs/guides-and-concepts/web3/ethereum-signin.md
[Link to ETHEREUM-SIGNIN-DOCS-UPDATE](https://ethereu-doc-refine.pankod.com)
=> ethereum-signin import packages update

documentation/docs/guides-and-concepts/multi-tenancy/appwrite.md
=> appwrite multi-tenancy import packages update

documentation/docs/guides-and-concepts/multi-tenancy/strapi.md
[Link to STRAPI-MULTI-TENANCY-DOCS-UPDATE](https://strapi--doc-refine.pankod.com)
=> strapi multi-tenancy import packages update

documentation/docs/guides-and-concepts/mutation-mode.md
[Link to MUTATION-MODE-DOCS-UPDATE](https://mutatio-doc-refine.pankod.com)
=> mutation-mode import package update

documentation/docs/guides-and-concepts/custom-layout.md
[Link to CUSTOM-LAYOUT-DOCS-UPDATE](https://custom--doc-refine.pankod.com)
=> custom-layout import packages update

documentation/docs/guides-and-concepts/custom-pages.md
[Link to CUSTOM-PAGES-DOCS-UPDATE](https://custom--doc-refine.pankod.com)
=> custom-pages import packages update

documentation/docs/guides-and-concepts/theme.md
[Link to THEME-DOCS-UPDATE](https://theme-d-doc-refine.pankod.com)
=> theme-docs import package update

documentation/docs/guides-and-concepts/auth/auth0.md
=> auth0 import packages update

documentation/docs/tutorial.md
[Link to TUTORIAL-DOCS-UPDATE](https://tutoria-doc-refine.pankod.com)
=> refine-tutorial-example import packages update

documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/ssr-nextjs.md
=> Tweaked a few typos and grammar

packages/supabase/src/index.ts
This closes #1480
General error handling implementation for the Supabase data provider.
=> Supabase data provider error handling

packages/strapi-v4/src/dataProvider.ts
#1482 
This pull request is for useUpdate fix  strapiV4 data provider bug on user collection
Strapi v4 doesn't require passing a data key at the beginning of the payload. that resulted in to update being successful but changes don't happen on strapi ( only in user collection)
I've only removed the data on the code and my put request successfully  change in the strapi
- #1483 1482
=> fix useUpdate now saving strapi v4

packages/supabase/src/index.ts
This closes #1489
Metadata (select) support for the Supabase data provider
=> Metadata (select) support for the Supabase data provider

documentation/docs/guides-and-concepts/data-provider/appwrite.md, packages/appwrite/src/index.ts
=> Update Dataprovider for Appwrite >0.12 #1453

documentation/docs/getting-started/learn-basics.md, documentation/sidebars.js
[Link to REFINE-LEARN-BASICS](https://refine--doc-refine.pankod.com)
=> refine learn basics docs created

documentation/docs/core/tutorial.md, documentation/docs/tutorial.md, documentation/docs/ui-frameworks/antd/tutorial.md
=> duplicate tutorial content issue fixed

packages/core/src/components/buttons/clone/index.tsx, packages/core/src/components/buttons/delete/index.tsx, packages/core/src/components/buttons/edit/index.tsx, packages/core/src/components/buttons/refresh/index.tsx, packages/core/src/components/buttons/show/index.tsx, packages/core/src/hooks/form/useCloneForm/useCloneForm.ts
[Link to DECODE-ID-FIX](https://decode--client.refine.pankod.com)
Actually, I think there is no harm in making `decodeURIComponent` even if it is read from Route or given by the user
- #1506 
- #1506
=> [Bug] Decode id fix on buttons and cloneForm

documentation/docs/migration-guide.md, packages/codemod/src/transformations/refine2-to-refine3.ts
[Link to MIGRATION-GUIDE-V3](https://migrati-doc-refine.pankod.com)
=> added migration guide for v3.x.x

documentation/docs/getting-started/learn-basics.md
=> Fix data-provider-customizer url.

documentation/docs/guides-and-concepts/multi-tenancy/strapi.md, documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/multi-tenancy/strapi-v4.md
=> Typo fix - multi-tenancy-strapi guide

documentation/docs/core/hooks/auth/useLogin.md, documentation/docs/core/hooks/auth/useLogout.md, packages/core/src/contexts/auth/IAuthContext.ts, packages/core/src/contexts/auth/index.tsx, packages/core/src/hooks/auth/useCheckError/index.spec.ts, packages/core/src/hooks/auth/useCheckError/index.ts, packages/core/src/hooks/auth/useLogin/index.spec.ts, packages/core/src/hooks/auth/useLogin/index.ts, packages/core/src/hooks/auth/useLogout/index.spec.ts, packages/core/src/hooks/auth/useLogout/index.ts
[Link to CUSTOM-REDIRECT-ON-LOGIN](https://custom--client.refine.pankod.com)
[Link to CUSTOM-REDIRECT-ON-LOGIN](https://custom--refine.pankod.com)
[Link to CUSTOM-REDIRECT-ON-LOGIN](https://custom--client.refine.pankod.com)
[Link to CUSTOM-REDIRECT-ON-LOGIN](https://custom--refine.pankod.com)
fix #1529
=> Custom redirect on login

packages/strapi-v4/src/dataProvider.ts
Replacing normalizeData with new internal implementation keeping function interface. 
Original code was flattening only one layer of data[].attributes, proposed code goes recursively into nested structure. 
This pull req. solves issue : [ #1485](https://github.com/pankod/refine/issues/1485)
To make correct normalization of data we need to make deep inspection of objects and flatten them all. Populated data keep the data/attributes structure strapi-v4 introduced. This is inconsistent with TS interfaces.
Code was alpha tested, some other unit tests might be neededin scope of Refine project.
example input : https://jsoneditoronline.org/#left=cloud.b7bc52c573a744fd82e0d051b5ad7e5b
example output : https://jsoneditoronline.org/#left=cloud.6ef201011b6849afb749ff552c7095e …
=> WIP : deep strapi-v4 data normalization closes #1485

packages/core/src/contexts/data/IDataContext.ts
To fix issue https://github.com/pankod/refine/issues/1537
=> Added new CrudOperators to support directus

documentation/docs/ui-frameworks/antd/tutorial.md
Allows App.tsx to find page functions.
=> Added explanation and instruction for required index.tsx files

documentation/docs/core/components/refine-config.md, documentation/docs/core/hooks/resource/useResource.md, documentation/docs/core/hooks/resource/useResourceWithRoute.md, documentation/versioned_docs/version-3.xx.xx/core/components/refine-config.md, documentation/versioned_docs/version-3.xx.xx/core/hooks/resource/useResource.md, documentation/versioned_docs/version-3.xx.xx/core/hooks/resource/useResourceWithRoute.md, packages/core/src/components/containers/refine/index.tsx, packages/core/src/contexts/resource/IResourceContext.ts, packages/core/src/hooks/resource/useResource/index.spec.tsx, packages/nextjs-router/src/nextRouteComponent.tsx, packages/react-location/src/resourceComponent.tsx, packages/react-router/src/routeProvider.tsx
[Link to DYNAMIC-RESOURCE-OPTIONS](https://dynamic-refine.pankod.com)
[Link to DYNAMIC-RESOURCE-OPTIONS](https://dynamic-client.refine.pankod.com)
[Link to DYNAMIC-RESOURCE-OPTIONS](https://dynamic-refine.pankod.com)
It is aimed that the options we give in the source object would be dynamic type and can be accessed on the crud pages with this development.
Fix #1513
=> Dynamic resource options

documentation/blog/2022-02-14-refine-ecommerce-blog.md
=> update ecommerce blog

documentation/Dockerfile, documentation/docs/contributing.md, documentation/versioned_docs/version-3.xx.xx/contributing.md, examples/fineFoods/admin/Dockerfile, examples/fineFoods/client/Dockerfile, package-lock.json, packages/codemod/package-lock.json, packages/codemod/package.json, packages/react-location/src/prompt.tsx
[Link to NODE-16-NPM-8](https://node-16-refine.pankod.com)
[Link to NODE-16-NPM-8](https://node-16-client.refine.pankod.com)
we upgrade node@16 and npm@8
=> upgrade refine node@16 and npm@8

documentation/blog/2022-02-21-build-low-code-customizable-and-authorization-ready-accesscontrol-admin-panel-with-nestjs.md
[Link to AUTH-BLOG](https://auth-bl-doc-refine.pankod.com)
=> New Blog Post -> Build low-code, customizable and authorization ready (accesscontrol) admin panel with NestJS.

documentation/blog/2022-02-21-build-internal-tools-with-refine.md
Adding new blog post.
[Link to BUILD-INTERNAL-TOOLS-BLOG-POST](https://build-i-doc-refine.pankod.com)
=> New Blog Post - Build internal tools using low-code with Refine

documentation/blog/2022-02-21-become-production-hero.md, documentation/blog/authors.yml
[Link to BLOG-BECOME-PRODUCTION-HERO](https://blog-be-doc-refine.pankod.com)
=> New Blog Post -> How to Become A Production Hero as Developer with Refine in 2022

documentation/docs/guides-and-concepts/real-time.md
=> Fixed name of link

packages/react-router-v6/src/routeProvider.tsx
[Link to REACT-ROUTER-V6-OPTIONS-FIX](https://react-r-refine.pankod.com)
=> [Fix] React Router v6 resource options

packages/antd/package.json
=> Updated Ant Design version to 4.18.8

documentation/docs/core/providers/router-provider.md, documentation/docs/guides-and-concepts/custom-pages.md
[Link to ROUTER-PROVIDER-DOCS-UPDATE](https://router--doc-refine.pankod.com)
=> Router provider document update

documentation/blog/2022-02-22-refine-invoice-genarator.md
[Link to BLOG-LINK-PART2](https://blog-li-doc-refine.pankod.com)
=> refine-invoice-blog-p1 to p2 link added

documentation/docs/examples/access-control/casbin.md, documentation/docs/examples/access-control/cerbos.md, documentation/docs/examples/auth-provider/auth0.md, documentation/docs/examples/auth-provider/google-auth.md, documentation/docs/examples/auth-provider/otpLogin.md, documentation/docs/examples/authorization.md, documentation/docs/examples/custom-pages.md, documentation/docs/examples/data-provider/airtable.md, documentation/docs/examples/data-provider/altogic.md, documentation/docs/examples/data-provider/appwrite.md, documentation/docs/examples/data-provider/hasura.md, documentation/docs/examples/data-provider/multiple.md, documentation/docs/examples/data-provider/nestjsxCrud.md, documentation/docs/examples/data-provider/nhost.md, documentation/docs/examples/data-provider/strapi-graphql.md, documentation/docs/examples/data-provider/strapi-v4.md, documentation/docs/examples/data-provider/strapi.md, documentation/docs/examples/data-provider/supabase.md, documentation/docs/examples/live-provider/ably.md, documentation/docs/examples/tutorial.md
[Link to EXAMPLE-DOCS-DESCRIPTION](https://example-doc-refine.pankod.com)
=> descriptions for refine examples

packages/antd/src/components/crud/create/index.tsx, packages/core/src/hooks/form/useForm.ts
=> Fix Using multiple hooks in the same component will init wrong request

packages/core/package.json, packages/core/tsup.config.ts, packages/nextjs-router/package.json, packages/nextjs-router/tsup.config.ts
[Link to FIX-NEXTJS-ROUTER-DEPENDENCY](https://fix-nex-refine.pankod.com)
An error occurred when trying to use nextjs-router package with "yarn".
=> fix nextjs-router package

examples/fineFoods/admin/src/components/product/productCategoryFilter.tsx, examples/fineFoods/admin/src/pages/products/list.tsx
[Link to FIX-FINE-FOOD-SYNC-BUG](https://fix-fin-refine.pankod.com)
=> Fix finefood sync location bug on products page

documentation/docs/ui-frameworks/antd/components/buttons/delete.md
Test documentation! 'ADD-CONFIRM-TITLE-DELETE-BUTTON'
[Link to ADD-CONFIRM-TITLE-DELETE-BUTTON-DOC](https://add-con-doc-refine.pankod.com)
=> DeleteButton props updated in the related docs

packages/antd/src/components/buttons/clone/index.tsx, packages/antd/src/components/buttons/create/index.tsx, packages/antd/src/components/buttons/edit/index.tsx, packages/antd/src/components/buttons/list/index.tsx, packages/antd/src/components/buttons/refresh/index.tsx, packages/antd/src/components/buttons/show/index.tsx
[Link to FIX-ANTD-BUTTONS-ON-CLICK](https://fix-ant-refine.pankod.com)
"onClick" was working incorrectly as we spread all parameters. Now this is handled differently for onClick.
- #1630
=> fix onClick event issue for antd buttons

documentation/docs/examples/customization/customFooter.md, documentation/docs/examples/customization/customLogin.md, documentation/docs/examples/customization/customSider.md, documentation/docs/examples/customization/offLayoutArea.md, documentation/docs/examples/customization/rtl.md, documentation/docs/examples/customization/topMenuLayout.md, documentation/docs/examples/e2e-testing.md, documentation/docs/examples/import-export.md, documentation/docs/examples/javascript.md, documentation/docs/examples/multi-tenancy/appwrite.md, documentation/docs/examples/multi-tenancy/strapi-v4.md, documentation/docs/examples/theme.md, documentation/docs/examples/web3/signin-ethereum.md
[Link to DESCRIPTION-FOR-EXAMPLES](https://descrip-doc-refine.pankod.com)
=> Description for examples

packages/antd/src/components/crud/create/index.tsx, packages/antd/src/hooks/form/useDrawerForm/useDrawerForm.ts, packages/core/src/hooks/form/useForm.ts
[Link to REMOVE-TAGS-FEATURE-FOR-CLONE](https://remove--client.refine.pankod.com)
We don't need the `clone` tag to be displayed
- #1646
=> Remove tags feature for clone

packages/antd/src/components/buttons/show/index.tsx
[Link to FIX-ANTD-SHOW-BUTTON-TOOLTIP-ISSUE](https://fix-ant-refine.pankod.com)
<ShowButton /> doesn't work with the Tooltip (Ant Design) component
- #1630
=> Fix <ShowButton /> doesn't work with the Tooltip (Ant Design) component

packages/core/src/hooks/data/useUpdate.ts, packages/core/src/hooks/form/useForm.ts
Same problem as in https://github.com/pankod/refine/pull/1632, just for updating the data.
Should be the last one I think (at least for the `useForm()` hook) :-)
=> Fix missing dataProviderName for update in useForm hook

documentation/blog/2022-03-22-refine-with-react95.md
[Link to FIX-WIN95-TYPO](https://fix-win-doc-refine.pankod.com)
=> typo fixed and added missing title

examples/blog/invoiceGenerator/package.json
=> fixed spelling

documentation/docs/ui-frameworks/antd/hooks/table/useTable.md
[Link to INITIAL-SORTER-DESCRIPTION](https://initial-doc-refine.pankod.com)
=> explanation of getDefaultSortOrder for initialSorter

documentation/docs/core/hooks/resource/useResource.md
[Link to USE-RESOURCE-DOCS](https://use-res-refine.pankod.com)
=> useResource Document update

documentation/docs/core/hooks/resource/useResource.md, packages/antd/src/components/buttons/clone/index.tsx, packages/antd/src/components/buttons/create/index.tsx, packages/antd/src/components/buttons/delete/index.tsx, packages/antd/src/components/buttons/edit/index.tsx, packages/antd/src/components/buttons/list/index.tsx, packages/antd/src/components/buttons/refresh/index.tsx, packages/antd/src/components/buttons/show/index.tsx, packages/core/src/contexts/resource/index.tsx, packages/core/src/hooks/resource/useResource/index.spec.tsx, packages/core/src/hooks/resource/useResource/index.ts
[Link to USE-RESOURCE-REFACTOR](https://use-res-client.refine.pankod.com)
[Link to USE-RESOURCE-REFACTOR](https://use-res-refine.pankod.com)
[Link to USE-RESOURCE-REFACTOR](https://use-res-client.refine.pankod.com)
[Link to USE-RESOURCE-REFACTOR](https://use-res-refine.pankod.com) …
=> useResource hook refactor

packages/simple-rest/src/index.ts
Adding the use of variables as `data` to the delete handlers (as per issue #1635 )
=> add values as body to delete

packages/antd/src/components/fields/email/index.spec.tsx, packages/antd/src/components/fields/email/index.tsx
=> fix: add value to mailto attribute of emailfield

packages/react-hook-form/jest.config.js, packages/react-hook-form/package.json, packages/react-hook-form/src/useStepsForm/index.spec.ts, packages/react-hook-form/src/useStepsForm/index.ts, packages/react-hook-form/test/dataMocks.ts, packages/react-hook-form/test/index.tsx, packages/react-hook-form/tsconfig.json, packages/react-hook-form/tsconfig.test.json
[Link to HEADLESS-USE-STEPS-FORM](https://headles-refine.pankod.com)
=> create useStepsForm for headless usage with react-hook-form

packages/antd/src/components/pages/error/index.tsx, packages/core/src/components/pages/error/index.tsx
[Link to FIX-USE-LAYOUT-EFFECT-ISSUE](https://fix-use-refine.pankod.com)
- #1493
=> Fix useLayoutEffect issue for Next.js

packages/antd/src/components/table/components/filterDropdown/index.spec.tsx, packages/antd/src/components/table/components/filterDropdown/index.tsx
[Link to FIX-ANTD-FILTER-DROPDOWN-CHANGE-ISSUE](https://fix-ant-client.refine.pankod.com)
[Link to FIX-ANTD-FILTER-DROPDOWN-CHANGE-ISSUE](https://fix-ant-refine.pankod.com)
- #1711 
- #1711
=> Fix Antd <FilterDropdown> can only be applied immediately

packages/antd/src/hooks/form/useForm.ts
[Link to ANTD-USE-FORM-RESET-FIX](https://antd-us-refine.pankod.com)
- #1738
- #1738
=> [Bug] Fix Ant Design form reset issue

documentation/docs/core/hooks/import-export/useImport.md, documentation/docs/core/interfaces.md, packages/core/src/hooks/import/index.tsx, packages/core/src/interfaces/menuItem.ts
Hey, I'm client! Test me! 'REFACTOR-USE-IMPORT'
[Link to USE-IMPORT-DOC](https://use-imp-client.refine.pankod.com)
Test me! 'REFACTOR-USE-IMPORT'
[Link to USE-IMPORT-DOC](https://use-imp-refine.pankod.com)
Test …
=> Use import doc

documentation/docs/core/hooks/import-export/useImport.md, documentation/docs/core/interfaces.md, packages/antd/src/hooks/import/index.tsx, packages/core/src/hooks/import/index.tsx, packages/core/src/interfaces/menuItem.ts
[Link to REFACTOR-USE-IMPORT](https://refacto-client.refine.pankod.com)
[Link to REFACTOR-USE-IMPORT](https://refacto-refine.pankod.com)
[Link to REFACTOR-USE-IMPORT](https://refacto-client.refine.pankod.com)
[Link to REFACTOR-USE-IMPORT](https://refacto-refine.pankod.com)
Demonstrate …
=> inputProps added to useImport return values

documentation/docs/packages/react-hook-form.md
=> Remove function call in Edit View

packages/core/src/definitions/table/index.spec.ts, packages/core/src/definitions/table/index.ts, packages/core/src/hooks/useTable/index.ts
[Link to TABLE-FILTER-ISSUE](https://table-f-refine.pankod.com)
- #1746
- #1746
=> [Fix] Pagination does not take over filter conditions

documentation/docs/faq.md, documentation/sidebars.js
The page where we will answer the most asked questions by the Community
[Link to ADD-FAQ-PAGE](https://add-faq-doc-refine.pankod.com)
=> Add FAQ page

packages/react-hook-form/src/useModalForm/index.spec.ts, packages/react-hook-form/src/useModalForm/index.ts, packages/react-hook-form/src/useStepsForm/index.spec.ts, packages/react-hook-form/src/useStepsForm/index.ts
[Link to FIX-REACT-HOOK-FORM-HOOKS](https://fix-rea-refine.pankod.com)
=> Fix props type and return types on react-hook-form hooks

documentation/docs/core/hooks/import-export/useImport.md, documentation/docs/core/interfaces.md, packages/core/src/hooks/import/index.tsx
[Link to REFACTOR-USE-IMPORT-CORE](https://refacto-client.refine.pankod.com)
[Link to REFACTOR-USE-IMPORT-CORE](https://refacto-refine.pankod.com)
[Link to REFACTOR-USE-IMPORT-CORE](https://refacto-client.refine.pankod.com)
[Link to REFACTOR-USE-IMPORT-CORE](https://refacto-refine.pankod.com)
**Test plan …
=> inputProps return type and onChange prop fix

packages/antd/src/hooks/form/useForm.ts
[Link to FIX-ID-PROP-USE-FORM](https://fix-id--refine.pankod.com)
- https://github.com/pankod/refine/pull/1749#issuecomment-1106522509
=> [Fix] Add support for "id" prop in Ant Design "useForm" hook

documentation/docs/faq.md
Hello @omeraplak! I've added the dependent queries to the documentation, please let me know what you think :)
This pertains to [issue #1735](https://github.com/pankod/refine/issues/1735)
<br> 
=> Update FAQ - dependent queries

packages/react-table/src/useTable/index.ts
[Link to FIX-REACT-TABLE-RETURN-TYPE](https://fix-rea-refine.pankod.com)
Fixed return type of `useTable`
=> Fix react-table return type

documentation/docs/core/providers/accessControl-provider.md, documentation/docs/examples/access-control/permify.md, documentation/sidebars.js
[Link to ADD-PERMIFY-EXAMPLE](https://add-per-doc-refine.pankod.com)
=> [Doc] Add permify example

documentation/blog/2022-04-29-open-source-adv-disadv.md
[Link to BLOG-POST-HACKATHON](https://blog-po-doc-refine.pankod.com)
=> [Blog] The Advantages and Disadvantages of Working on Open Source Projects

examples/dataProvider/nhost/src/App.tsx, packages/nhost/src/index.ts
[Link to HANDLE-NHOST-DATA-PROVIDER-ERROR](https://handle--refine.pankod.com)
- #1794
- #1794
=> [Bug] Fix error handling on nhost data provider

packages/antd/src/components/buttons/delete/index.tsx
=> Delete Button resourceNameOrRoute added

examples/fineFoods/admin/mui/src/App.tsx, examples/fineFoods/admin/mui/src/components/product/item.tsx, examples/fineFoods/admin/mui/src/components/store/index.tsx, examples/fineFoods/admin/mui/src/components/store/storeProducts.tsx, examples/fineFoods/admin/mui/src/pages/stores/create.tsx, examples/fineFoods/admin/mui/src/pages/stores/edit.tsx, examples/fineFoods/admin/mui/src/pages/stores/index.tsx, examples/fineFoods/admin/mui/src/pages/stores/list.tsx
Hey, I'm client! Test me! 'MUI'
[Link to MUI-FINE-FOODS-STORE](https://mui-fin-client.refine.pankod.com)
Test me! 'MUI'
[Link to MUI-FINE-FOODS-STORE](https://mui-fin-refine.pankod.com)
Hey, I'm client! Test me! 'MUI'
[Link to MUI-FINE-FOODS-STORE](https://mui-fin-client.refine.pankod.com)
Test me! 'MUI'
[Link to MUI-FINE-FOODS-STORE](https://mui-fin-refine.pankod.com)
[Link to MUI-FINE-FOODS-STORE](https://mui-fin-refine.pankod.com)
Explain the **details** for making this change. What …
=> Mui - fine foods example stores page created

examples/fineFoods/admin/mui/public/locales/de.json, examples/fineFoods/admin/mui/public/locales/en.json, examples/fineFoods/admin/mui/src/App.tsx, examples/fineFoods/admin/mui/src/components/product/create.tsx, examples/fineFoods/admin/mui/src/components/product/edit.tsx, examples/fineFoods/admin/mui/src/components/product/item.tsx, examples/fineFoods/admin/mui/src/components/store/storeProducts.tsx, examples/fineFoods/admin/mui/src/pages/products/list.tsx, examples/fineFoods/admin/mui/src/pages/stores/create.tsx, examples/fineFoods/admin/mui/src/pages/stores/edit.tsx, packages/mui/src/components/crud/create/index.tsx, packages/mui/src/components/crud/edit/index.tsx, packages/mui/src/components/crud/list/index.tsx, packages/mui/src/components/crud/show/index.tsx
Test me! 'MUI'
[Link to MUI-FINE-FOODS-STORE2](https://mui-fin-refine.pankod.com)
Test me! 'MUI'
[Link to MUI-FINE-FOODS-STORE2](https://mui-fin-client.refine.pankod.com)
Fixing the reviews on the stores' page that prepared for the fine food example.
=> Mui fine foods stores page reviews resolved

examples/blog/ecommerce/next.config.js, examples/i18n/nextjs/next.config.js, examples/refine-next/next.config.js, packages/antd/src/components/buttons/clone/index.tsx, packages/antd/src/components/buttons/create/index.tsx, packages/antd/src/components/buttons/edit/index.tsx, packages/antd/src/components/buttons/list/index.tsx, packages/antd/src/components/buttons/show/index.tsx, packages/antd/src/components/layout/sider/index.tsx, packages/antd/src/hooks/table/useTable/paginationLink.tsx
[Link to NEXTJS-LINK-COMPONENT-UPDATES](https://nextjs--client.refine.pankod.com)
[Link to NEXTJS-LINK-COMPONENT-UPDATES](https://nextjs--refine.pankod.com)
Updates for PR #1709  Next.js compatibility
=> Make links more accessible for Next.js integration

documentation/docs/examples/calendar.md, documentation/sidebars.js, examples/calendar/package.json, examples/calendar/src/App.tsx, examples/calendar/src/interfaces/index.d.ts, examples/calendar/src/pages/calendar/index.tsx
I added a REST API to the example made by @nrikiji.
- #1828
[Link to IMPROVEMENT-ANTD-CALENDAR-EXAMPLE](https://improve-doc-refine.pankod.com)
=> Improvement Ant Design calendar example

examples/fineFoods/admin/mui/src/components/dashboard/orderTimeline/index.tsx
In this PR, the colors we created in the theme were used instead of the harcoded colors.
[Link to FIX-HARDCODED-COLOR](https://fix-har-doc-refine.pankod.com)
=> Fix hardcoded color 

.github/workflows/automerge.yml, .github/workflows/pull-request.yml, .github/workflows/reviewer-lottery.yml
Status checks were failing in Fork PRs. This was also confusing for outside contributors.
=> fix(ci): fork pr's status check failures

.changeset/perfect-parrots-roll.md, packages/mui/src/components/pages/ready/index.tsx
In this PR, I fixed the mui ready page to be responsive for mobile screens.
=> style: mui ready page to be responsive for mobile screens

packages/mui/package.json
@pankod/refine-mui package should not depend on antd and dayjs
=> chore: change @pankod/refine-mui peerDependencies

.changeset/large-shrimps-begin.md, examples/fineFoods/admin/mui/src/pages/couriers/list.tsx, examples/fineFoods/admin/mui/src/pages/stores/list.tsx, packages/mui/src/definitions/dataGrid/index.ts
Fixed the `useDatagrid` filter bug that the selected filter was not displayed.
=> fix: `useDatagrid` filter bug

.changeset/silver-spoons-battle.md, packages/mui/src/components/layout/index.tsx, packages/mui/src/components/layout/sider/index.spec.tsx, packages/mui/src/components/layout/sider/index.tsx
In this PR, We have fixed the Sider component as default in Layout with internal states that provide from the `@pankod/refine-mui` package.
=> refactor: mui default sider

.changeset/real-planets-confess.md, packages/mui/src/components/layout/index.tsx, packages/mui/src/components/pages/ready/index.tsx, packages/mui/src/hooks/useDataGrid/index.ts, packages/mui/src/providers/refineSnackbarProvider/index.tsx, packages/mui/src/theme/index.ts, packages/mui/src/theme/palette/darkPalette.ts, packages/mui/src/theme/palette/lightPalette.ts
Updated `@pankod/refine-mui` theme with `refine`'s base colors.
=> refactor: `@pankod/refine-mui` theme update

examples/fineFoods/admin/mui/src/App.tsx
Updated `examples/mui-fine-foods` with newly exported `RefineSnackbarProvider` and replaced `StyledSnackbarProvider`
=> refactor: Update `mui-fine-foods` example with `RefineSnackbarProvider`

examples/form/mui/useDrawerForm/src/App.tsx, examples/form/mui/useModalForm/src/App.tsx, examples/form/mui/useStepsForm/src/App.tsx
Added CssBaseline and GlobalStyles for Material UI examples.
=> feat: add CssBaseline and GlobalStyles for Material UI examples

documentation/docs/examples/table/mui/advanced.md, documentation/docs/examples/table/mui/useDataGrid.md, documentation/sidebars.js
In this PR, I added material ui advanced table example documentation.
=> docs: mui advanced table example

packages/mui/src/components/buttons/delete/index.tsx, packages/mui/src/components/buttons/export/index.tsx, packages/mui/src/components/buttons/import/index.tsx, packages/mui/src/components/buttons/refresh/index.tsx, packages/mui/src/components/buttons/save/index.tsx
In this PR, We have fixed variants, colors, and loading positions of buttons.
=> style(buttons): fixing loading position, variant and colors

.changeset/long-spies-tie.md
In this PR, We have created a change set for the development of buttons in the loading state.
=> chore(buttons): changeset created

examples/fineFoods/admin/mui/src/components/dashboard/dailyOrders/index.tsx, examples/fineFoods/admin/mui/src/components/dashboard/dailyRevenue/index.tsx, examples/fineFoods/admin/mui/src/components/dashboard/newCustomers/index.tsx, examples/fineFoods/admin/mui/src/components/product/create.tsx, examples/fineFoods/admin/mui/src/components/product/edit.tsx
Minor bug fixes for Material UI FineFoods example
- Fix TextArea and Price inputs on products create/edit pages
- Fix Dashboard responsive issue
=> Fix: Material UI FineFoods minor issues

documentation/src/components/perfect-implementation/index.js
We want to try StackBlitz in our documents as an alternative to CodeSandbox.
=> feat: stackblitz embed for refine landing demo

examples/fineFoods/admin/mui/src/pages/couriers/create.tsx, examples/fineFoods/admin/mui/src/pages/couriers/edit.tsx, examples/fineFoods/admin/mui/src/pages/couriers/list.tsx
In this PR, I fixed the change avatar and default value of gender on the courier edit page
=> fix: material ui fine foods courier avatar and gender

examples/fineFoods/admin/mui/src/components/product/categoryFilter.tsx, examples/fineFoods/admin/mui/src/components/product/item.tsx, examples/fineFoods/admin/mui/src/pages/categories/list.tsx
fixed some style bugs in material ui fine foods example
=> fix: material ui fine foods style fixes categories and products page

examples/fineFoods/admin/mui/public/locales/de.json, examples/fineFoods/admin/mui/public/locales/en.json, examples/fineFoods/admin/mui/src/components/dashboard/recentOrders/index.tsx, examples/fineFoods/admin/mui/src/components/header/index.tsx, examples/fineFoods/admin/mui/src/pages/categories/list.tsx, examples/fineFoods/admin/mui/src/pages/couriers/list.tsx, examples/fineFoods/admin/mui/src/pages/couriers/show.tsx, examples/fineFoods/admin/mui/src/pages/orders/list.tsx, examples/fineFoods/admin/mui/src/pages/orders/show.tsx, examples/fineFoods/admin/mui/src/pages/reviews/list.tsx, examples/fineFoods/admin/mui/src/pages/stores/list.tsx, examples/fineFoods/admin/mui/src/pages/users/list.tsx, examples/fineFoods/admin/mui/src/pages/users/show.tsx, examples/form/mui/useDrawerForm/src/pages/posts/list.tsx
Material UI FineFoods example fixes.
=> fix:material ui fine foods examples add missing translates and columns renderCell functions

documentation/docs/ui-frameworks/mui/customization/theme.md, documentation/docs/ui-frameworks/mui/tutorial.md
In this PR, We have updated with information about how to customize and apply font family in your Refine application in the `Customization Theme` and `Tutorial` documentation of Material UI.
=> docs(theme): updated related docs with adding font family

examples/fineFoods/admin/mui/src/pages/stores/edit.tsx
In this PR, fix edit store page `<Avatar>` responsivity for Material UI **FineFoods** example
=> fix: material ui finefoods edit store page avatar responsivity

examples/fineFoods/admin/mui/src/components/product/item.tsx
use **Material UI** `<TextField>` for **Finfoods** store products edit modal stock update input.
=> fix: use material ui input for store product update

documentation/docs/ui-frameworks/mui/customization/sider.md
Minor fixes in the Material UI Sider document
=> docs: Material UI sider doc improvement

examples/fineFoods/admin/mui/public/locales/de.json, examples/fineFoods/admin/mui/public/locales/en.json, examples/fineFoods/admin/mui/src/components/product/categoryFilter.tsx, examples/fineFoods/admin/mui/src/components/product/item.tsx, examples/fineFoods/admin/mui/src/components/store/storeProducts.tsx, examples/fineFoods/admin/mui/src/pages/products/list.tsx
In this PR, I've added the condition that the product is not found when searching in the **Material UI Fine Foods** example product list page
=> fix:material ui finefoods example add no products case on product list page and modal

examples/fineFoods/admin/mui/src/components/product/item.tsx
fix **Material UI** FineFoods example product page items title font size.
=> fix: product item title font size fix

packages/mui/src/components/buttons/clone/index.tsx, packages/mui/src/components/buttons/create/index.tsx, packages/mui/src/components/buttons/delete/index.tsx, packages/mui/src/components/buttons/edit/index.tsx, packages/mui/src/components/buttons/export/index.tsx, packages/mui/src/components/buttons/import/index.tsx, packages/mui/src/components/buttons/list/index.tsx, packages/mui/src/components/buttons/refresh/index.tsx, packages/mui/src/components/buttons/save/index.tsx, packages/mui/src/components/buttons/show/index.tsx, packages/mui/src/components/crud/create/index.tsx, packages/mui/src/components/crud/edit/index.tsx, packages/mui/src/components/crud/list/index.tsx, packages/mui/src/components/crud/show/index.tsx, packages/mui/src/components/fields/boolean/index.tsx, packages/mui/src/components/fields/date/index.tsx, packages/mui/src/components/fields/email/index.tsx, packages/mui/src/components/fields/file/index.tsx, packages/mui/src/components/fields/markdown/index.tsx, packages/mui/src/components/fields/number/index.tsx, packages/mui/src/components/fields/tag/index.tsx, packages/mui/src/components/fields/text/index.tsx, packages/mui/src/components/fields/url/index.tsx
In this PR, We have updated components' TSDocs with related links
=> refactor(components): update TSDocs

documentation/blog/2021-10-25-mail-subscription-with-refine.md, documentation/blog/2021-10-4-admin-panel-with-nestjs.md, documentation/blog/2021-10-4-feedback-admin-panel.md, documentation/blog/2021-11-12-issue-tracker-refine.md, documentation/blog/2022-02-12-implement-darkmode.md, documentation/blog/2022-02-21-react-antd-admin.md, documentation/blog/2022-02-22-refine-invoice-genarator.md, documentation/docs/core/tutorial.md, documentation/docs/ui-frameworks/antd/tutorial.md, documentation/docs/ui-frameworks/mui/tutorial.md
Fixed **superplate** question and answer texts according to the new **superplate** version.
=> docs: Fix superplate questions and answers

examples/fineFoods/admin/mui/src/components/product/item.tsx, examples/fineFoods/admin/mui/src/pages/products/list.tsx
In this PR, We have fixed the grid layout for the large screen and product item component's header font size.
=> style(product-page): fix the grid layout for responsive behaviour

examples/fineFoods/admin/mui/public/locales/de.json, examples/fineFoods/admin/mui/public/locales/en.json, examples/fineFoods/admin/mui/src/components/dashboard/deliveryMap/index.tsx, examples/fineFoods/admin/mui/src/components/dashboard/recentOrders/index.tsx, examples/fineFoods/admin/mui/src/pages/categories/list.tsx, examples/fineFoods/admin/mui/src/pages/couriers/edit.tsx
=> fix: material UI finefoods example bugs

.changeset/orange-singers-drop.md, examples/fineFoods/admin/mui/src/pages/couriers/create.tsx, examples/fineFoods/admin/mui/src/pages/couriers/edit.tsx, examples/fineFoods/admin/mui/src/pages/stores/create.tsx, examples/fineFoods/admin/mui/src/pages/stores/edit.tsx, packages/core/src/hooks/import/index.tsx
Fixed `useImport` `onFinish` twice call bug.
=> fix: `useImport` `onFinish` twice call bug

examples/fineFoods/admin/mui/src/pages/orders/list.tsx
AutoComplete's selected values were not working correctly on the Orders page
- #2053
- #2053
=> fix: AutoComplete selection issue on  finefoods example

documentation/docusaurus.config.js
with this update the entire category tree is shown in the search results
=> docs: update algolia search results

examples/accessControl/cerbos/package.json, examples/accessControl/cerbos/src/App.tsx
This bumps the Cerbos access control demo to use the latest SDK version
=> docs: example cerbos update

README.md
I noticed some misuses of the language and I found some parts hard to understand at README.md file so I wanted to fix them for enhancement.
=> docs: typo fixes and grammar corrections at README.MD

documentation/docs/examples/search/search.md, documentation/docs/ui-frameworks/antd/customization/sider.md, documentation/docs/ui-frameworks/mui/customization/sider.md, documentation/docusaurus.config.js, documentation/package-lock.json, documentation/package.json, documentation/redirects.json
I updated docusaurus version to `beta.21`
=> refactor: upgrade docusaurus version to beta.21

.changeset/good-boats-enjoy.md, .github/workflows/master-push.yml, .github/workflows/next-push.yml
`@pankod/refine-codemod` was not build during release pipeline
- #2112
=> fix:  build issue of @pankod/refine-codemod package

documentation/docs/ui-frameworks/antd/customization/sider.md
useLogout should be inside @pankod/refine-core instead of @pankod/refine-antd.
=> useLogout should be in @pankod/refine-core

.changeset/bright-steaks-serve.md, packages/strapi-v4/src/dataProvider.ts, packages/strapi-v4/test/dataProvider/index.mock.ts
=> fix: add pageSize support for getMany of strapi-v4

.changeset/beige-cows-move.md, packages/core/package.json, packages/core/src/hooks/breadcrumb/index.ts, packages/mui/package.json, packages/mui/src/hooks/useDataGrid/index.ts
Now 'console.warn' warns are only triggered once.
=> refactor: warn once when occur console warns

documentation/blog/2021-11-26-refine-vs-react-admin.md
I've not created an issue for this, but hopefully it doesn't require a discussion. 🙂
=> docs(blog): Fix typo

examples/blog/material-ui/src/App.tsx
I updated Material UI admin panel example app login page.
=> refactor(examples): mui example new login page

documentation/blog/2022-07-21-admin-panel-with-materialui-and-strapi.md
I fixed some typos in MUI blog.
=> docs(blog): fix mui blog typo

.changeset/flat-trainers-peel.md, packages/medusa/src/authProvider/index.ts, packages/medusa/src/index.ts
Fixed mismatch in `authProvider.login` for email and username
=> fix: medusa authProvider

documentation/docs/guides-and-concepts/multi-level-menu/multi-level-menu.md
the / has been removed in multi-level example in the docs. With the / in front of it the routing won't work
-   [ 1  ] Corresponding issues are created/updated or not needed
-   [ 1 ] Docs are updated/provided or …
=> Update on options -> routing in caution part of file multi-level-menu.md

documentation/docs/getting-started/learn-basics.md
Extend Learn the Basics section in documentation.
=> docs: add additional information to learn the basics doc

documentation/blog/2022-07-20-refine-writer-program.md
I add minor edits to writer program blog
=> docs(blog): refactor writer program blog

documentation/docs/core/providers/data-provider.md
=> docs: add stringify package tip on data provider

documentation/docs/core/hooks/data/useCreate.md, documentation/docs/core/hooks/data/useCreateMany.md, documentation/docs/core/hooks/data/useCustomMutation.md, documentation/docs/core/hooks/data/useDelete.md, documentation/docs/core/hooks/data/useDeleteMany.md, documentation/docs/core/hooks/data/useUpdate.md, documentation/docs/core/hooks/data/useUpdateMany.md
Added code examples to the `tip` annotation about the lifecycle of mutations
=> docs: add code examples for mutation lifecycle tip

documentation/blog/2021-11-26-refine-vs-react-admin.md, documentation/blog/2021-11-29-refine-vs-admin-bro.md, documentation/blog/2022-02-14-refine-ecommerce-blog.md, documentation/docs/core/providers/router-provider.md, documentation/docs/examples/next-js/next-js.md, documentation/docs/guides-and-concepts/custom-pages.md, documentation/docs/guides-and-concepts/ssr/nextjs.md, documentation/docs/guides-and-concepts/ssr/remix.md, documentation/redirects.json, documentation/sidebars.js
Guide to configuring Remix SSR and Authentication flows
=> docs: add remix docs

documentation/docs/guides-and-concepts/ssr/remix.md
Self service cookie section added to Remix Server Side Authentication doc
=> docs: improvement remix authentication doc

documentation/blog/2022-08-04-mocking-api-calls.md, documentation/blog/2022-08-17-using-next-image.md, documentation/blog/authors.yml
I added new blog post named "Nextjs image optimization with examples"
=> Add next image blog

documentation/blog/2022-08-19-temporal-api.md, documentation/blog/authors.yml
A new post added to the blog page.
=> docs(blog): add temporal api blog post

documentation/docs/ui-frameworks/antd/components/basic-views/create.md, documentation/docs/ui-frameworks/antd/components/basic-views/edit.md, documentation/docs/ui-frameworks/antd/components/basic-views/list.md, documentation/docs/ui-frameworks/antd/components/basic-views/show.md
=> docs(antd-basic-views): add subTitle props to headerProps

.changeset/late-ants-trade.md, packages/hasura/package.json, packages/hasura/src/dataProvider/index.ts, packages/hasura/test/getList/index.mock.ts, packages/hasura/test/getList/index.spec.ts, packages/hasura/tsup.config.ts
Add nested filter support to `Hasura` data provider.
closes #2320
=> feat: nested filter support in Hasura

.changeset/violet-rabbits-roll.md, packages/hasura/tsup.config.ts, packages/nhost/package.json, packages/nhost/src/dataProvider/index.ts
Add nested filter support to `nhost` data provider.
=> feat: added nested filter support

.changeset/selfish-plants-teach.md, examples/cloud/src/App.tsx, examples/cloud/src/interfaces/index.d.ts, examples/cloud/src/pages/categories/create.tsx, examples/cloud/src/pages/categories/edit.tsx, examples/cloud/src/pages/categories/index.tsx, examples/cloud/src/pages/categories/list.tsx, examples/cloud/src/pages/categories/show.tsx, examples/cloud/src/pages/products/create.tsx, examples/cloud/src/pages/products/edit.tsx, examples/cloud/src/pages/products/index.tsx, examples/cloud/src/pages/products/list.tsx, examples/cloud/src/pages/products/show.tsx, packages/cloud/src/hooks/index.ts, packages/cloud/src/hooks/useCloudMutation/index.ts, packages/cloud/src/hooks/useCloudQuery/index.ts, packages/sdk/src/client.ts, packages/sdk/src/services/cloud-query.ts, packages/sdk/src/services/index.ts
Added cloud query support with refine cloud.
=> feat: cloud query support

documentation/docs/core/tutorial.md, documentation/docs/guides-and-concepts/ssr/nextjs.md, documentation/docs/guides-and-concepts/ssr/remix.md, documentation/docs/ui-frameworks/antd/tutorial.md, documentation/docs/ui-frameworks/mui/tutorial.md, packages/antd/README.md, packages/mui/README.md
I added preset support to `superplate-cli` commands in our documentation
=> docs: add preset option for superplate command

.changeset/eight-spiders-buy.md, .changeset/silent-knives-dance.md, documentation/docs/core/components/refine-config.md, examples/base/antd/tsconfig.json, packages/core/src/components/containers/refine/index.tsx, packages/core/src/components/layoutWrapper/index.spec.tsx, packages/core/src/contexts/refine/IRefineContext.ts, packages/core/src/contexts/refine/index.tsx, packages/core/src/definitions/helpers/handleRefineOptions/index.spec.ts, packages/core/src/definitions/helpers/handleRefineOptions/index.ts, packages/core/src/definitions/helpers/index.ts, packages/core/src/definitions/helpers/redirectPage/index.spec.ts, packages/core/src/definitions/helpers/redirectPage/index.ts, packages/core/src/hooks/data/useList.spec.tsx, packages/core/src/hooks/data/useMany.spec.tsx, packages/core/src/hooks/data/useOne.spec.tsx, packages/core/src/hooks/form/useForm.ts, packages/core/src/hooks/live/useLiveMode/index.spec.ts, packages/core/src/hooks/live/useLiveMode/index.ts, packages/core/src/hooks/live/useResourceSubscription/index.spec.ts, packages/core/src/hooks/refine/useMutationMode.ts, packages/core/src/hooks/refine/useRefineContex.ts, packages/core/src/hooks/refine/useSyncWithLocation.ts, packages/core/src/hooks/refine/useWarnAboutChange/index.ts
Refactor provide options methods in refine containers component. Revert all hook changes in #2352.
All tests passed.
.
=> refactor: refine's way of providing options properties

documentation/blog/2022-08-31-google-lighthouse.md
=> docs(blog): add missing image

documentation/blog/2022-06-10-weve-raised-dollar1m-seed-funding.md, documentation/blog/2022-07-21-admin-panel-with-materialui-and-strapi.md, documentation/blog/2022-08-29-usestate-mistakes.md, documentation/blog/2022-08-31-google-lighthouse.md
Update truncates & cover sections
=> Add missing truncates

.changeset/popular-chairs-raise.md, packages/antd/src/hooks/form/useModalForm/useModalForm.ts
=> fix: useModalForm reset issue after successful submit

.changeset/forty-dolls-drum.md, .changeset/warm-pots-sing.md, _changeset/real-planes-float.md, examples/authentication/headless/src/App.tsx, examples/fineFoods/admin/antd/src/App.tsx, packages/core/src/components/containers/refine/index.tsx, packages/core/src/components/pages/auth/components/login/index.tsx, packages/core/src/components/pages/auth/components/register/index.tsx, packages/core/src/components/pages/auth/components/resetPassword/index.tsx, packages/core/src/components/pages/auth/components/updatePassword/index.tsx, packages/nextjs-router/src/nextRouteComponent.tsx, packages/react-location/src/routerComponent.tsx, packages/react-router-v6/src/routeProvider.tsx, packages/remix/src/routeComponent.tsx
Fixed `<AuthPage>` and `<Refine>` components props for authentication flows.
=> fix: Auth Page

documentation/blog/2022-09-02-sveltekit-crud-app.md
=> docs(blog): update description

documentation/blog/2022-04-29-open-source-adv-disadv.md
This fixes some grammar and markdown formatting in the "The Advantages and Disadvantages of Working on Open Source Projects" blogpost. Came across the post via Reddit and saw some issues so thought I'd make a PR to fix.
BTW, your repo is very very large for such a young project. See a fair amount of binary content in there but may be other things blowing out the size too.
None
Does not close anything
=> Updated grammar/text in open-source-adv-disadv post

packages/ably/.npmignore, packages/airtable/.npmignore, packages/altogic/.npmignore, packages/antd-audit-log/.npmignore, packages/antd/.npmignore, packages/appwrite/.npmignore, packages/cloud/.npmignore, packages/core/.npmignore, packages/demo-sidebar/.npmignore, packages/graphql/.npmignore, packages/hasura/.npmignore, packages/kbar/.npmignore, packages/medusa/.npmignore, packages/mui/.npmignore, packages/nestjsx-crud/.npmignore, packages/nextjs-router/.npmignore, packages/nhost/.npmignore, packages/react-hook-form/.npmignore, packages/react-location/.npmignore, packages/react-router-v6/.npmignore, packages/react-table/.npmignore, packages/remix/.npmignore, packages/sdk/.npmignore, packages/simple-rest/.npmignore, packages/strapi-graphql/.npmignore, packages/strapi-v4/.npmignore, packages/strapi/.npmignore, packages/supabase/.npmignore, packages/ui-tests/.npmignore, packages/ui-types/.npmignore
Updated `.npmignore` for wrong file (`tsup.config.js` instead of `ts` 🤦) and `**.{test, spec}.{ts,tsx}` files.
=> chore: `.npmignore` updates

.github/workflows/pull-request-doc.yml, .github/workflows/pull-request-previews.yml, documentation/docs/testing.md, examples/fineFoods/admin/antd/README.md
=> build: test PR previews action

.changeset/many-toes-compare.md, .changeset/mean-pianos-drive.md, .changeset/sharp-camels-wink.md, documentation/docs/core/interfaces.md, packages/core/src/contexts/data/IDataContext.ts, packages/hasura/src/dataProvider/index.ts, packages/nhost/src/dataProvider/index.ts
Add new CRUD Filter which are supported by various Data Provider
Added startswith,nstartswith,endswith,nendswith
Close #2455
=> [FEAT] add more CRUD filter #2455

examples/store/src/components/product/ProductSidebar/ProductSidebar.module.css, examples/store/src/components/product/ProductSidebar/ProductSidebar.tsx, examples/store/src/components/product/ProductView/ProductView.tsx
Fixed the style of `Add to Cart` button.
These change does not affect tests.
=> style(product-view): add button 

.changeset/tasty-penguins-happen.md, packages/core/src/contexts/refine/index.tsx
The `AuthPage` component, which we haven't released yet, was the default login page.
=> fix: default login page issue

documentation/blog/2022-08-26-react-content-filtering.md, documentation/blog/2022-08-28-js-currying-functions.md, documentation/blog/2022-08-29-usestate-mistakes.md, documentation/blog/2022-08-30-flexbox-vs-grid.md, documentation/blog/2022-08-31-google-lighthouse.md, documentation/blog/2022-09-01-framer-text-animations.md, documentation/blog/2022-09-02-sveltekit-crud-app.md, documentation/blog/2022-09-04-next-link.md, documentation/blog/2022-09-05-mui-button.md, documentation/blog/2022-09-06-nodejs-developer.md, documentation/blog/2022-09-07-next-env.md, documentation/blog/2022-09-08-swag-store.md, documentation/blog/2022-09-09-react-18.md, documentation/blog/2022-09-11-next-refine-pwa.md, documentation/blog/2022-09-12-next-typescript.md
=> docs(blog): remove social images

documentation/docusaurus.config.js, documentation/src/components/landing/section-hero/index.tsx, documentation/src/css/custom.css, documentation/src/theme/Footer/Layout/index.js, documentation/src/theme/Footer/Links/MultiColumn/index.js, documentation/src/theme/Footer/Logo/index.js, documentation/tailwind.config.js
- Added contact info to footer
- Updated footer logo sag
- Updated terms and privacy links
- Added custom fields to get footer texts dynamically from `docusaurus.config.js`
- Updated *Scroll Down* icon position in landing hero
=> docs: landing page updates

examples/customization/customSider/src/components/sider/index.tsx
Added missing `collapsed` prop to render method of `CustomSider` component in the **refine-custom-sider-example**.
Does not affect tests.
=> fix: added missing collapsed prop

documentation/src/components/blog/featured-blog-post-item/index.js, documentation/src/components/landing/section-hero/index.tsx, documentation/src/components/landing/section-no-constraints/index.tsx, documentation/src/theme/BlogPostItem/index.js
Fixed couple of issues with the landing page and the blog list page.
=> docs(landing): minor fixes

documentation/blog/2021-11-12-issue-tracker-refine.md, documentation/src/assets/examples.ts, examples/blog/issueTracker/package.json
We updated the "issue tracker blog" example we developed using refine@2 with refine@3
=> docs: update issue tracker blog

documentation/docs/benchmarks.md, documentation/docs/licence.md, documentation/package-lock.json, documentation/sidebars.js
=> docs: adding benchmarks & licence pages

.changeset/happy-monkeys-hang.md, examples/cloud/src/pages/posts/create.tsx, examples/cloud/src/pages/posts/edit.tsx, examples/cloud/src/utility/normalize.ts, packages/sdk/src/client.ts, packages/sdk/src/services/auth.ts, packages/sdk/src/services/draft-resource.ts, packages/sdk/src/services/index.ts, packages/sdk/src/services/log.ts, packages/sdk/src/services/storage.ts
Add storage support on refine cloud.
=> feat: sdk storage support

documentation/docs/core/hooks/data/useCustom.md, documentation/docs/core/hooks/data/useCustomMutation.md
Added examples for request's config in useCustom and useCustomMutation docs
https://discord.com/channels/837692625737613362/896336798429642785/1020100970367164456
=> docs: improvement useCustom and useCustomMutation

documentation/blog/2022-06-10-weve-raised-dollar1m-seed-funding.md, documentation/blog/2022-08-17-using-next-image.md, documentation/blog/2022-08-24-mui-icons.md, documentation/blog/2022-08-29-usestate-mistakes.md, documentation/blog/2022-08-31-google-lighthouse.md, documentation/blog/2022-09-01-framer-text-animations.md, documentation/blog/2022-09-02-sveltekit-crud-app.md, documentation/blog/2022-09-04-next-link.md, documentation/blog/2022-09-05-mui-button.md, documentation/blog/2022-09-06-nodejs-developer.md, documentation/blog/2022-09-08-swag-store.md, documentation/blog/2022-09-12-next-typescript.md, documentation/src/components/blog/blog-post-page/index.js, documentation/src/components/blog/featured-blog-post-item/index.js, documentation/src/theme/BlogPostItem/index.js
Add imgix.net for dynamic images for blog posts
=> docs: dynamic image sizes

documentation/package-lock.json, documentation/package.json, documentation/src/components/blog/github-banner/index.js, documentation/src/components/landing/section-hero/index.tsx, documentation/src/components/landing/section-no-constraints/index.tsx, documentation/src/theme/MDXComponents/A.js, documentation/src/theme/NavbarItem/DefaultNavbarItem.js, documentation/yarn.lock
We removed `noreferrer` from links so we can track traffic to our GitHub repository
=> docs: fix noreferrer for github links

.changeset/modern-donuts-end.md, examples/authentication/antd/src/App.tsx, examples/authentication/antd/src/pages/auth/forgotPassword/index.tsx, examples/authentication/antd/src/pages/auth/index.tsx, examples/authentication/antd/src/pages/auth/login/index.tsx, examples/authentication/antd/src/pages/auth/register/index.tsx, examples/authentication/antd/src/pages/auth/updatePassword/index.tsx, packages/antd/src/components/pages/auth/components/register/index.tsx, packages/ui-types/src/types/auth.tsx
Add `providers` support on `<AuthPage />` **register** component.
=> feat: add providers support on authpage register component.

examples/fineFoods/admin/antd/public/index.html, examples/fineFoods/admin/mui/public/index.html, examples/fineFoods/client/pages/_app.tsx, examples/fineFoods/client/src/components/footer.tsx
I added missing links and refactor example app titles
=> Add missing example links

documentation/src/css/custom.css
Updated primary color of Docusaurus to `#1890FF` and its variants.
=> docs(theme): update primary color to refine blue

documentation/blog/2022-09-27-react-hook-form-validation.md, examples/blog/refine-react-hook-form/src/App.tsx, examples/blog/refine-react-hook-form/src/pages/create.tsx
I updated react hook form post
=> docs(blog): update hook form post

documentation/docs/api-reference/core/hooks/useForm.md, documentation/docs/api-reference/mantine/hooks/form/useDrawerForm.md, documentation/docs/api-reference/mantine/hooks/form/useForm.md, documentation/docs/api-reference/mantine/hooks/form/useModalForm.md, documentation/docs/api-reference/mantine/hooks/form/useStepsForm.md, documentation/docs/examples/form/mantine/useDrawerForm.md, documentation/docs/examples/form/mantine/useForm.md, documentation/docs/examples/form/mantine/useModalForm.md, documentation/docs/examples/form/mantine/useStepsForm.md, documentation/sidebars.js, examples/form/mantine/useStepsForm/src/pages/posts/edit.tsx
Created Mantine form hooks documents.
=> docs: create mantine form hooks documents

.changeset/spotty-mails-exist.md, packages/core/src/hooks/menu/useMenu.spec.tsx, packages/core/src/hooks/menu/useMenu.tsx
=> fix: useMenu hook is not reacting to locale change

examples/store/README.MD
=> chore: update readme

documentation/docusaurus.config.js, documentation/src/css/custom.css, documentation/src/theme/Navbar/Layout/index.js, documentation/src/theme/Navbar/Layout/index.tsx
Added PH announcement to the top of the pages with hiding animation at scroll.
PH Link needs to be updated. Currently it's set to `tomorrow` mode so no need for a link 😅
=> docs: product hunt announcement

documentation/docusaurus.config.js, documentation/src/css/custom.css, documentation/src/theme/Navbar/Content/styles.module.css
Added **refine**'s GitHub link to the Navbar
=> docs: add GitHub link to Navbar

README.md, documentation/docusaurus.config.js, documentation/src/components/landing/section-hero/index.tsx, documentation/src/theme/Navbar/Layout/index.tsx, packages/antd/README.md, packages/core/README.md, packages/mantine/README.md, packages/mui/README.md, packages/ui-tests/README.md, packages/ui-types/README.md
=> docs: change announcement to today

.github/workflows/pull-request.yml
We've updated `commitlint` action
=> fix: commitlint action

examples/authentication/mantine/src/pages/posts/list.tsx, examples/base/mantine/src/pages/posts/list.tsx, examples/customization/customTheme/mantine/src/pages/posts/list.tsx, examples/form/mantine/useDrawerForm/src/pages/posts/list.tsx, examples/form/mantine/useForm/src/pages/posts/list.tsx, examples/form/mantine/useModalForm/src/pages/posts/list.tsx, examples/form/mantine/useStepsForm/src/pages/posts/list.tsx, examples/importExport/mantine/src/pages/posts/list.tsx, examples/table/mantine/advanced/src/pages/posts/list.tsx, examples/table/mantine/basic/src/pages/posts/list.tsx, examples/tutorial/mantine/src/pages/posts/list.tsx, examples/upload/mantine/base64/src/pages/posts/list.tsx, examples/upload/mantine/multipart/src/pages/posts/list.tsx
Add category column to Mantine examples.
Test are not effected.
.
=> fix: add category column to Mantine examples

documentation/src/components/landing/section-hero/index.tsx
Updated Product Hunt badge on landing hero section to product of the day badge 🎉
=> docs: add product of the day badge

documentation/blog/2021-10-4-admin-panel-with-nestjs.md
=> fixed typos

.changeset/quiet-terms-run.md, examples/fineFoods/admin/antd/src/pages/auth/index.tsx, examples/fineFoods/admin/mui/public/locales/en.json, examples/fineFoods/admin/mui/src/App.tsx, examples/fineFoods/admin/mui/src/authProvider.ts, examples/fineFoods/admin/mui/src/pages/auth/index.tsx, examples/fineFoods/admin/mui/src/pages/login/index.tsx, packages/antd/src/components/pages/index.tsx, packages/core/src/components/pages/index.tsx, packages/mui/src/components/index.tsx, packages/mui/src/components/pages/auth/components/forgotPassword/index.tsx, packages/mui/src/components/pages/auth/components/login/index.tsx, packages/mui/src/components/pages/auth/components/register/index.tsx, packages/mui/src/components/pages/auth/components/styles.ts, packages/mui/src/components/pages/auth/components/updatePassword/index.tsx, packages/mui/src/components/pages/index.tsx
We integrate AuthPage into our finefoods example
=> refactor: Material UI Finefoods example AuthPage integration

documentation/src/utils/split-code.ts
-   [ x] Corresponding issues are created/updated or not needed
-   [ x] Docs are updated/provided or not needed
-   [ x] Examples are updated/provided or not needed
-   [ x] TypeScript definitions are …
=> fix: typo inside split-code.ts

documentation/docs/api-reference/mantine/hooks/useSelect.md, documentation/sidebars.js
Added the Mantine useSelect hook doc.
=> docs(mantine): add useSelect doc

README.md
=> grammatical error in readme fixed

README.md
Added Link of Discord Server in the contribution section so that the contributors can discuss their doubts in the Discord Server.
closes  #2729
=> Add Links To Readme

.changeset/wicked-walls-rule.md, packages/react-table/package.json
Removed unused peer dependency.
.
=> fix(react-table): remove unused peer dependency

.changeset/strange-bobcats-teach.md, .changeset/tall-walls-hunt.md, documentation/docs/api-reference/antd/components/basic-views/edit.md, documentation/docs/api-reference/antd/components/basic-views/show.md, documentation/docs/api-reference/mantine/components/basic-views/create.md, documentation/docs/api-reference/mantine/components/basic-views/edit.md, documentation/docs/api-reference/mantine/components/basic-views/list.md, documentation/docs/api-reference/mantine/components/basic-views/show.md, documentation/sidebars.js, packages/mantine/src/components/crud/create/index.tsx, packages/mantine/src/components/crud/edit/index.tsx, packages/mantine/src/components/crud/list/index.tsx, packages/mantine/src/components/crud/show/index.tsx, packages/mantine/src/components/index.ts, packages/ui-types/src/types/crud.tsx
=> docs: add mantine basic view docs

.changeset/angry-cars-share.md, packages/mantine/src/components/pages/error/index.tsx
Fixed `<ErrorComponent />` responsive design.
.
=> fix(mantine):`<ErrorComponent />` responsive design

documentation/src/theme/Footer/Layout/index.js
=> fix(docs): footer text typo

README.md
Corrected the link to point to CODE_OF_CONDUCT.md file
=> Update Contributor Covenant Link

documentation/docs/api-reference/core/components/refine-config.md
Fixed errors in refine-config.md
Run the doc preview
closes #2761
-   [x] Examples are …
=> fix: grammatical, spelling and contextual errors

documentation/blog/2022-08-17-using-next-image.md, documentation/blog/2022-08-18-auth-with-nextauth.md, documentation/blog/2022-09-04-next-link.md, documentation/blog/2022-09-07-next-env.md, documentation/blog/2022-09-11-next-refine-pwa.md, documentation/blog/2022-09-12-next-typescript.md, documentation/blog/2022-10-05-next-api-routes.md, documentation/blog/2022-10-13-pnpm-post.md, documentation/src/css/custom.css
New banners are added to Next.js article.
=> docs(blog): add new banner to next posts

documentation/blog/2022-09-27-react-hook-form-validation.md
Fixes grammatical errors and typos in react-hook-form-validation.md under blogs
fixes #2773 
-   [x] …
=> fix: fixed errors and typos [react-hook-form-validation]

documentation/blog/2022-09-09-react-18.md
=> fix: importing component

.changeset/cuddly-cows-sniff.md, documentation/docs/api-reference/antd/components/buttons/delete.md, documentation/docs/api-reference/antd/components/buttons/export.md, documentation/docs/api-reference/antd/components/buttons/import.md, documentation/docs/api-reference/antd/components/buttons/list.md, documentation/docs/api-reference/antd/components/buttons/save.md, documentation/docs/api-reference/antd/components/buttons/show.md, documentation/docs/api-reference/mantine/components/basic-views/create.md, documentation/docs/api-reference/mantine/components/basic-views/edit.md, documentation/docs/api-reference/mantine/components/basic-views/list.md, documentation/docs/api-reference/mantine/components/basic-views/show.md, documentation/docs/api-reference/mantine/components/buttons/clone.md, documentation/docs/api-reference/mantine/components/buttons/create.md, documentation/docs/api-reference/mantine/components/buttons/delete.md, documentation/docs/api-reference/mantine/components/buttons/edit.md, documentation/docs/api-reference/mantine/components/buttons/export.md, documentation/docs/api-reference/mantine/components/buttons/import.md, documentation/docs/api-reference/mantine/components/buttons/list.md, documentation/docs/api-reference/mantine/components/buttons/refresh.md, documentation/docs/api-reference/mantine/components/buttons/save.md, documentation/docs/api-reference/mantine/components/buttons/show.md, documentation/sidebars.js, packages/mantine/src/components/buttons/save/index.tsx, packages/ui-types/src/types/crud.tsx
Added following button docs:
.
=> docs(mantine): button docs

documentation/docs/api-reference/mui/components/auth-page.md
Add default refine theme on MUI Auth pages.
=> docs(mui): Add default refine theme on Auth pages.

documentation/docs/contributing.md, documentation/docs/faq.md, documentation/docs/migration-guide.md
Nothing significant -- just a few typos in the documentation.
=> docs: typo fixes

documentation/docs/api-reference/antd/components/auth-page.md, documentation/docs/api-reference/core/components/auth-page.md, documentation/docs/api-reference/mantine/components/auth-page.md, documentation/docs/api-reference/mui/components/auth-page.md
Fix links in the usage section.
=> docs(authPage): Fix links in the usage section.

.changeset/tidy-masks-reply.md, examples/base/antd/src/pages/posts/list.tsx, packages/medusa/src/dataProvider/index.ts, packages/simple-rest/src/index.ts
Fixed using `data` in `axios'` `delete` function
=> fix: data property usage of delete function in axios

.changeset/silent-lions-melt.md, documentation/docs/api-reference/mantine/components/fields/boolean.md, documentation/docs/api-reference/mantine/components/fields/date.md, documentation/docs/api-reference/mantine/components/fields/email.md, documentation/docs/api-reference/mantine/components/fields/file.md, documentation/docs/api-reference/mantine/components/fields/markdown.md, documentation/docs/api-reference/mantine/components/fields/number.md, documentation/docs/api-reference/mantine/components/fields/tag.md, documentation/docs/api-reference/mantine/components/fields/text.md, documentation/docs/api-reference/mantine/components/fields/url.md, documentation/sidebars.js, packages/mantine/src/components/fields/boolean/index.spec.tsx, packages/mantine/src/components/fields/boolean/index.tsx, packages/mantine/src/components/fields/date/index.tsx, packages/mantine/src/components/fields/email/index.tsx, packages/mantine/src/components/fields/markdown/index.tsx, packages/mantine/src/components/fields/number/index.tsx, packages/mantine/src/components/fields/tag/index.tsx, packages/mantine/src/components/fields/text/index.spec.tsx, packages/mantine/src/components/fields/text/index.tsx, packages/mantine/src/components/fields/url/index.tsx
Added field components documentation.
The tests are not affected.
.
=> docs(mantine): add field component docs

documentation/src/components/github-floating-cta/index.tsx, documentation/src/components/landing/icons/arrow-icon.tsx, documentation/src/components/landing/icons/cancel-icon.tsx, documentation/src/components/landing/icons/index.ts, documentation/src/components/landing/index.tsx, documentation/src/components/landing/section-hero/index.tsx, documentation/src/components/landing/section-no-constraints/index.tsx, documentation/src/context/GithubContext/index.tsx, documentation/src/theme/Layout/index.js, documentation/src/theme/NavbarItem/NavbarNavLink.js, documentation/src/theme/Root.tsx, documentation/tailwind.config.js
- Product Hunt - 1# Product of the Day Banner added
- Border radius added to section hero tiles and arrow icon
- Github floating banner added.
=> feat(docs): add GitHub floating banner

examples/store/src/components/ui/Modal/Modal.module.css
Made necessary changes to make auth model responsive
This is how it looks now - 
closes #2797 
=> fix(auth-model): changes made for model to be responsive in store

examples/store/src/components/search.tsx
When filtered data by searching, if count of the product is not equal 0, we shouldn't have shown `There are no products ...` message to user.
-   [ ] …
=> fix: store searching fixed #2694

documentation/docs/api-reference/mantine/customization/theme.md, documentation/sidebars.js
Added the theme customization documentation.
The doc changes don't affected the tests.
.
=> docs(mantine): add theme customization doc

documentation/docs/api-reference/mantine/components/basic-views/create.md, documentation/docs/api-reference/mantine/components/basic-views/edit.md, documentation/docs/api-reference/mantine/components/basic-views/list.md, documentation/docs/api-reference/mantine/components/basic-views/show.md, documentation/docs/api-reference/mantine/components/buttons/clone.md, documentation/docs/api-reference/mantine/components/buttons/create.md, documentation/docs/api-reference/mantine/components/buttons/delete.md, documentation/docs/api-reference/mantine/components/buttons/edit.md, documentation/docs/api-reference/mantine/components/buttons/export.md, documentation/docs/api-reference/mantine/components/buttons/import.md, documentation/docs/api-reference/mantine/components/buttons/list.md, documentation/docs/api-reference/mantine/components/buttons/refresh.md, documentation/docs/api-reference/mantine/components/buttons/save.md, documentation/docs/api-reference/mantine/components/buttons/show.md
Used `setRefineProps` to reduce repetitive code.
The test are not affected.
.
=> docs(mantine): refactor live codes

documentation/docs/further-readings/telemetry.md
Hi, no big issues just fixed some typos and wording to improve the documentation for telemetry.
=> docs: fix wording and typos in telemetry doc

documentation/docs/api-reference/mantine/customization/layout.md, documentation/sidebars.js
Added the mantine layout customization doc.
Change of the docs don't affect the tests.
.
=> docs(mantine): add layout customization doc

examples/store/src/components/account/AccountNav/AccountNav.tsx
1. Increased size of Account text and made it bold.
2. Underlined the AccountNavLink on click.
closes #2823
=> fix(account): changes made to account text

documentation/docs/advanced-tutorials/ssr/nextjs.md
Adjust type for user
-   [ ] TypeScript …
=> Update types on docs

documentation/docs/advanced-tutorials/access-control.md, documentation/docs/api-reference/core/providers/audit-log-provider.md, documentation/docs/api-reference/core/providers/auth-provider.md, documentation/docs/api-reference/core/providers/data-provider.md, documentation/docs/api-reference/core/providers/live-provider.md, documentation/docs/tutorials/antd.md
=> Fix several typos in documentation

packages/core/src/hooks/data/useList.ts
refer link link was wrong, Fixed
=> fix(docs): fix useListConfig refer link

documentation/src/theme/Footer/Layout/index.js
#2882 
The copyrights year in the footer is hardcoded to 2022. Devs will have to update it every year which would be not effective.
I have  automated this via js. 
very small change made, tested locally all test cases passed.
-   [x] Docs …
=> fixed #2882

README.md
Closes #2878
Fixed the minor grammatical issue.
Please check all items below before reviewing.
-   x ] TypeScript definitions are updated/provided or not needed
=> Fixed the grammar in readme.md

examples/store/src/components/product/ProductSliderControl/ProductSliderControl.module.css
**Before:**
**After:**
closes #2739
=> fix(btn): changed opacity and height of btn to make responsive in store

documentation/blog/2021-12-22-base64-upload.md, documentation/blog/2021-12-27-multipart-upload.md, documentation/blog/2022-01-18-csv-import.md, documentation/blog/2022-07-21-admin-panel-with-materialui-and-strapi.md, documentation/blog/2022-08-04-mocking-api-calls.md, documentation/blog/2022-08-18-auth-with-nextauth.md, documentation/blog/2022-09-19-router-use-navigate.md, documentation/blog/2022-09-28-docker-build-args.md, documentation/blog/2022-10-19-mui-autocomplete.md, documentation/blog/2022-10-21-tailwind-grid.md
New banners added and some posts banners updated
=> docs(blog): add & update banners

documentation/docs/tutorials.md
I made a few improvements on our tutorial page
=> docs: improve tutorial page

documentation/blog/2022-09-16-react-use-memo.md
=> Minor typo.

documentation/docs/contributing.md
I added annotations to the "Contributing" document
=> docs: improve contributing docs

README.md
Now the user can go to the "http://localhost:3000" just by one click on image. Minor but impactful
Thank you!!
-   [ ] Docs are updated/provided or …
=> Hyperlinked the image in readme.md

examples/store/src/components/common/UserNav/UserNav.module.css, examples/store/src/components/common/UserNav/UserNav.tsx, examples/store/src/components/icons/User.tsx
Replaced avatar component with user icon component.
On hover: 
closes #2777 
=> fix(icon): changed profile icon as user icon in store

CODE_OF_CONDUCT.md, README.md
Fixes grammatical errors in CODE_OF_CONDUCT.md and README.md
Closes #2906 
=> Fix Grammatical Errors in docs

documentation/docs/api-reference/core/providers/data-provider.md, documentation/docs/tutorials/core.md
It was not clear that we're talking about **refine**'s headless features with just "headless".
Stating it clearly and adding reference to TailwindCSS points to the context and what the article achieves.
-----------
Please check all items below before …
=> Bring clarity about headless core

documentation/package-lock.json, documentation/package.json, documentation/src/components/blog/featured-blog-post-item/index.js, documentation/src/components/newsletter-cta/index.tsx, documentation/src/theme/BlogPostItem/index.js, documentation/tsconfig.json
We've updated the newsletter CTAs
=> docs: add newsletter cta

README.md
- updated contribution section in readme.
closes #2918 
=> updated contribution section  in readme

README.md, documentation/src/components/landing/section-hero/index.tsx
=> feat :  Added cursor pointer to scroll down button 

documentation/src/theme/Footer/Layout/index.js
=> Add smooth scroll effect on icons

documentation/docs/tutorials/antd.md
Fixed typos and grammatical errors. Fixes #2923 @saimaheshtaduri Please review.
closes #2923 
-   [X] …
=> Fixed documentation errors in antd.md

documentation/src/components/blog/post-paginator/index.js, documentation/src/theme/BlogPostItem/index.js, documentation/src/theme/MDXComponents/A.js, documentation/src/theme/NavbarItem/DefaultNavbarItem.js, documentation/src/utils/link-rel.ts
Added `dofollow` for internal links
=> feat: add dofollow for internal links

documentation/src/pages/about/index.tsx
inital -> initial
https://github.com/refinedev/refine/issues/2967
=> docs: fix typo in about/index.tsx

documentation/src/pages/become-a-refine-expert/index.tsx
icons aligned
page title grammer fixed
=> fix(docs): align become a refine expert icons

packages/live-previews/pages/preview.tsx
Updated module checks in code blocks to include import-less module usage.
=> fix(live-preview): module resolve logic

documentation/docs/examples/data-provider/elide-rest.md, documentation/sidebars.js
Updated docs to add Elide data provider. 
https://github.com/refinedev/refine/issues/2994
=> docs: added support for Elide Data Provider

documentation/src/assets/integrations.ts, documentation/src/pages/integrations/index.tsx
Issue: https://github.com/refinedev/refine/issues/3003
=> docs: elide added to data provider under integrations, fixed typo

package.json
Updated nuke script, to include nested directories (examples)
=> chore: update nuke script

documentation/docs/examples/tutorial/antd-tutorial.md
=> Fix typo in antd-tutorial.md

.changeset/tame-coats-fix.md, packages/core/src/hooks/show/useShow.ts
Add queryOptions param on useShow hook.
Put closes #3023 in your comment to auto-close the issue that your PR fixes (if such).
=> feat: add queryOptions param on useShow hook

documentation/docusaurus.config.js, documentation/plugins/intercom.js, documentation/src/theme/Layout/index.js
Added intercom integration for the website
=> feat: add intercom

documentation/docs/contributing.md
Added "changeset" section to "contributing" document
=> docs: add changeset section

examples/store/src/components/cart/CartSidebarView/CartSidebarView.tsx
Removed link tag for my cart text
closes #3037 
=> fix(cart): removed hyper link for my cart text

.changeset/wicked-months-visit.md, packages/cli/package.json, packages/create-refine-app/src/index.ts
- Fix `create-refine-app` argument error.
- Add bin params on `refine-cli` package.json
=> fix: cli argument error

documentation/docs/tutorials/mantine.md
Corrected 'Material UI' to 'Mantine'
closes #3051 …
=> docs(tutorials/mantine): fix typo

.changeset/chilly-carpets-whisper.md, packages/cli/package-lock.json, packages/cli/src/commands/runner/build/index.ts, packages/cli/src/commands/runner/dev/index.ts, packages/cli/src/commands/runner/start/index.ts, packages/cli/src/commands/runner/utils/index.ts
=> feat(cli): runner descriptions changed according to project type

.changeset/three-cooks-tease.md, packages/cli/src/commands/create-resource/index.ts, packages/cli/src/utils/resource/index.ts
Added unique check on `create-resource` with `refine-cli`.
=> fix: unique check on create-resource with refine-cli

packages/react-router-v6/src/index.ts
=> fix(react-router-v6): lint issue

.changeset/good-coins-film.md, packages/cli/package.json, packages/cli/src/index.ts
=> chore(cli): add figlet types

README.md, documentation/blog/2022-09-23-refine-article-guideline.md, documentation/docs/advanced-tutorials/data-provider/supabase.md, documentation/docs/advanced-tutorials/ssr/nextjs.md, documentation/docs/advanced-tutorials/ssr/remix.md, documentation/docs/getting-started/quickstart.md, documentation/docs/tutorials/antd.md, documentation/docs/tutorials/chakra-ui.md, documentation/docs/tutorials/core.md, documentation/docs/tutorials/mantine.md, documentation/docs/tutorials/mui.md, examples/tutorial/antd/README.md, packages/antd/README.md, packages/chakra-ui/README.md, packages/core/README.md, packages/inferencer/README.md, packages/mantine/README.md, packages/mui/README.md, packages/ui-tests/README.md, packages/ui-types/README.md
I replace `superplate` commands with `create refine app`
=> docs: superplate to create refine-app

README.md
=> chore: add link tracker

.changeset/gentle-knives-fold.md, packages/cli/src/telemetry/index.ts, packages/cli/src/utils/env/index.test.tsx, packages/cli/src/utils/env/index.ts
=> feat(cli): undefined `NODE_ENV` set to the `development` from `production`

.changeset/few-walls-beg.md, packages/create-refine-app/package.json
Upgrade superplate-cli version
=> chore: upgrade superplate-cli version

.changeset/fluffy-cherries-nail.md, packages/cli/src/index.ts
For the CLI, we had an intro with a random figlet font at every start. But this caused an error for some users. No more jokes.
- https://discord.com/channels/837692625737613362/896336798429642785/1047187495890206803
=> chore: no more jokes for CLI

documentation/docs/packages/list-of-packages.md
=> docs(packages): update subheadings

documentation/src/components/landing/section-ready/index.tsx
=> fix(docs): home page ready section text color

documentation/docs/packages/documentation/cli.md
Added swizzle results to swizzle section in CLI doc.
The docs changes not affected the tests.
.
=> docs(cli-swizzle): add swizzle result to cli doc

.changeset/warm-peas-report.md, packages/react-location/src/index.ts, packages/react-router-v6/src/index.ts
=> fix: react extract incorrect resource from encoded pathname

.changeset/purple-balloons-peel.md, packages/cli/src/commands/create-resource/index.ts, packages/cli/src/utils/compile/index.ts, packages/cli/src/utils/project/index.ts, packages/cli/templates/resource/create.tsx.hbs, packages/cli/templates/resource/edit.tsx.hbs, packages/cli/templates/resource/list.tsx.hbs, packages/cli/templates/resource/show.tsx.hbs
Removed ui framework difficulty in `create-resource` command.
=> refactor: remove uiFramework difficulty `@pankod/refine-cli`

.changeset/afraid-months-exercise.md, packages/cli/src/telemetry/index.ts
=> fix(cli): add await to telemetry fetch

README.md, documentation/docs/api-reference/antd/customization/theme.md, documentation/docs/api-reference/core/providers/i18n-provider.md, documentation/docs/api-reference/mui/customization/theme.md, documentation/docs/comparison.md, documentation/docs/getting-started/overview.md, documentation/docs/packages/documentation/command-palette.md, packages/antd/README.md, packages/chakra-ui/README.md, packages/core/README.md, packages/inferencer/README.md, packages/mantine/README.md, packages/mui/README.md
=> docs: add new key features

.changeset/funny-pots-sip.md, packages/cli/package.json
Downgrade `jscodeshift` 0.14.0 to 0.13.1 for `@pankod/refine-cli`.
=> fix: downgrade `jscodeshift` 0.14.0 to 0.13.1 for `@pankod/refine-cli`

.changeset/friendly-trainers-press.md, packages/sdk/tsconfig.json
Update compiler option on target `es6` for `@pankod/refine-sdk`.
=> fix: compiler option target `es6` for `@pankod/refine-sdk`

examples/store/package.json, examples/store/src/components/account/OverviewTemplate/OverviewTemplate.tsx, examples/store/src/components/cart/CartItem/CartItem.tsx, examples/store/src/components/common/Thumbnail/Thumbnail.tsx, examples/store/src/components/common/UserNav/CustomerMenuContent/CustomerMenuContent.module.css, examples/store/src/components/common/UserNav/CustomerMenuContent/CustomerMenuContent.tsx, examples/store/src/components/product/ProductCard/ProductCard.tsx, examples/store/src/components/product/ProductView/ProductView.tsx, examples/store/src/components/ui/Dropdown/Dropdown.tsx
Fixed Next.js 13 compatibility issues
- #3168 
=> fix: swag store example Next.js 13 compatibility issues

documentation/docs/tutorials/mui.md
=> [BUG] Updated first step to show create command

documentation/docs/api-reference/mantine/hooks/form/useStepsForm.md
Existing code in documentation (https://refine.dev/docs/api-reference/mantine/hooks/form/useStepsForm/) had incorrect import statements.  Synced documentation with the code that works in accompanying stackblitz.
Documentation update.  Sync with stackblitz example
Markup change.  Preview rendered correctly
`closes #3193` 
-   [x] Examples are updated/provided …
=> refine-mantine API Documentation update for 'useStepForm' hook.

documentation/blog/2022-12-09-json-error.md, documentation/blog/authors.yml
=> docs(blog): json error post

documentation/blog/2022-12-09-json-error.md
=> Reuben Conclusion section

.github/workflows/master-push.yml
=> feat: added DO action for uploading static files to CDN

documentation/blog/2022-12-14-conditional-rendering.md
I added conditional rendering post
=> docs(blog): add conditional rendering post

documentation/docs/api-reference/antd/migration-guide/v4-to-v5.md, documentation/sidebars.js
=> feat: antd v5 migration guide

documentation/blog/2022-12-15-mui-checkbox.md
I added MUI checkbox component post
=> docs(blog): add mui post

.changeset/silver-mangos-cough.md, packages/cli/src/commands/runner/build/index.ts, packages/cli/src/commands/runner/runScript.ts
For some reasons the build always exit with code 0 even if it failed to compile.
- #3234 
=> fix: build command was exiting with "0" exit code on error

examples/pixels/README.md
=> chore: add pixels app readme

documentation/blog/2022-09-04-next-link.md, documentation/blog/2022-09-16-react-use-memo.md, documentation/blog/2022-09-27-react-hook-form-validation.md, documentation/blog/2022-09-28-docker-build-args.md, documentation/blog/2022-10-30-mui-select.md
=> docs(blog): update banners

documentation/src/theme/Navbar/Content/index.js, documentation/src/theme/Navbar/MobileSidebar/PrimaryMenu/index.js
- Fixed align issue for menu item icons
- Fixed when the user navigate, the menu not close issue
- Added empty area to sider for mobile view
=> docs: fix popover menu issues

packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap
Updated `@pankod/refine-inferencer` snapshot tests
=> chore(inferencer): update snapshots

documentation/blog/2022-12-14-conditional-rendering.md
=> Added Conclusion

documentation/docs/api-reference/core/providers/router-provider.md
related: https://github.com/refinedev/refine/issues/3207
=> docs: add a note about `react-location` problems with `basepath`

documentation/blog/2022-12-20-git-switch.md
=> docs(blog): add git switch post

examples/finefoods-client/src/components/categoryCard.tsx, examples/finefoods-client/src/components/footer.tsx, examples/finefoods-client/src/components/header.tsx, examples/finefoods-client/src/components/promotional.tsx
[Next.js 13 Migration Guide](https://beta.nextjs.org/docs/upgrade-guide#link-component)
=> fix(finefoods-client): remove child <a> from <Link>

.changeset/quiet-pots-travel.md, packages/antd/src/components/antd/antd.ts
I've added exports for [new Ant Design components](https://github.com/ant-design/ant-design/releases/tag/5.1.0)
=> feat: add exports for new Ant Design components

examples/finefoods-client/next.config.js, packages/live-previews/next.config.js
fixed: swcMinify disabled due to tanstack table issue: https://github.com/TanStack/table/issues/4615
=> feat: swcMinify disabled

documentation/docs/tutorial/0-introduction/0-intro.md, documentation/docs/tutorial/0-introduction/1-prequisite.md, documentation/docs/tutorial/0-introduction/2-select-framework.md
Added new tutorial introduction section.
=> docs: add new tutorial introduction section

documentation/blog/2022-12-21-em-vs-rem.md, documentation/blog/authors.yml, packages/live-previews/package.json
=> docs(blog): add em vs rem post

documentation/blog/2022-12-21-em-vs-rem.md
I added a conclusion to the em vs rem article.
=> Update 2022-12-21-em-vs-rem.md: Added conclusion

documentation/docs/api-reference/antd/migration-guide/v4-to-v5.md
=> feat(docs): add compile errors solution to migration guide

.github/workflows/pull-request.yml, documentation/src/components/live-preview/index.tsx, packages/inferencer/src/inferencers/antd/__tests__/create.test.tsx, packages/inferencer/src/inferencers/antd/__tests__/edit.test.tsx, packages/inferencer/src/inferencers/antd/__tests__/index.test.tsx, packages/inferencer/src/inferencers/antd/__tests__/list.test.tsx, packages/inferencer/src/inferencers/antd/__tests__/show.test.tsx, packages/live-previews/pages/preview.tsx, packages/live-previews/src/utils/check-package.ts, packages/live-previews/src/utils/use-code.ts
- Added `checkPackage` helper to combine UI package checks.
- Added TailwindCSS via CDN with `tailwind` URL param.
- DOCS: added `tailwind` prop to live code blocks.
````
```tsx live tailwind
render(
<div className="p-5 bg-red-500">
<p className="font-bold text-2xl text-white">test</p>
</div>
);
````
=> feat: live previews tailwindcss

documentation/blog/2022-12-28-docker-copy.md
=> docs(blog): add docker post

packages/core/src/index.tsx
=> chore: re-exported react-query

documentation/docs/tutorial/3-understanding-resources/0-intro.md
Added new tutorial page's unit four
=> docs: add new tutorial unit four

.changeset/pink-balloons-live.md, documentation/docs/api-reference/core/hooks/resource/useResource.md, packages/core/src/hooks/resource/useResource/index.spec.tsx, packages/core/src/hooks/resource/useResource/index.ts
`useResource` hook can now also return the current `action`
=> feat: useResource hook can now also return the current action

.changeset/serious-pets-punch.md, packages/strapi-v4/src/dataProvider.ts
=> fix: wrong mapping of case insensitive CRUD operators

documentation/blog/2023-01-03-use-swr.md
=> docs(blog): add useswr post

examples/table-mantine-advanced/src/pages/posts/list.tsx
Fixed Mantine Advanced table example 
- https://github.com/refinedev/refine/actions/runs/3835600399/jobs/6528968230
=> fix: mantine advanced table example

documentation/blog/2022-12-15-mui-checkbox.md, documentation/blog/2022-12-28-docker-copy.md, documentation/blog/2023-01-04-mui-card.md
=> docs(blog): add mui card post

documentation/docs/api-reference/antd/hooks/form/useForm.md
=> fix(docs): antd useForm live mode section is not nested under properties

.changeset/two-flies-listen.md, packages/cli/src/utils/package/index.ts
=> WIP: fix: ignoring npm ls error, closes #3348 

documentation/src/components/blog/blog-post-page/index.js
I've disabled the newsletter CTA widget
=> chore: disable newsletter CTA

.changeset/small-ties-juggle.md, packages/nextjs-router/src/common/refine-link.tsx
=> fix(nextjs-router): forwarding ref on RefineLink component

documentation/blog/2023-01-06-hackaton-january.md, documentation/blog/authors.yml, documentation/docusaurus.config.js, documentation/src/assets/nav-menu.ts, documentation/src/components/blog/blog-post-page/index.js, documentation/src/css/custom.css, documentation/src/theme/BlogListPage/index.js, documentation/src/theme/NavbarItem/NavbarNavLink.js
=> docs(blog): add hackathon content

documentation/src/assets/nav-menu.ts, documentation/src/assets/popover-icons/chevron-down.tsx
=> docs: fix navbar item gap issue

documentation/docs/api-reference/core/hooks/useTable.md
=> docs: Fix typo in filtering section

documentation/blog/2023-01-06-hackaton-january.md
=> Fixed Twitter link

documentation/blog/2023-01-06-hackaton-january.md, hackathon/hackathon-january.md
=> docs(blog): add new hackathon file

documentation/docs/tutorial/2-understanding-dataprovider/0-intro.md, documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md, documentation/docs/tutorial/4-adding-crud-pages/headless/adding-sort-and-filters.md
Fix grammar and typo in tutorial
=> docs(tutorial): fix grammar

documentation/blog/2023-01-17-airtable-crud-app.md, documentation/blog/2023-01-23-redwood-vs-refine.md
I added post for comparing redwood and refine
=> Add redwood vs refine post

documentation/docs/examples/multi-tenancy/appwrite.md, documentation/docs/examples/multi-tenancy/strapi-v4.md, documentation/docs/examples/table/antd/table-filter.md, documentation/docs/examples/table/antd/useDeleteMany.md, documentation/docs/examples/table/antd/useEditableTable.md, documentation/docs/examples/table/antd/useUpdateMany.md, documentation/docs/examples/table/chakra-ui/advanced.md, documentation/docs/examples/table/chakra-ui/basic.md, documentation/docs/examples/table/handsontable/basic.md, documentation/docs/examples/table/mantine/advanced.md, documentation/docs/examples/table/mantine/basic.md, documentation/docs/examples/table/mui/filter.md, documentation/docs/examples/table/mui/useDeleteMany.md, documentation/docs/examples/table/mui/useUpdateMany.md, documentation/docs/examples/table/react-table/advanced.md, documentation/docs/examples/table/react-table/basic.md
Fix `example-tag` names for example page.
=> docs: fix example tag names

documentation/blog/2023-01-06-hackaton-january.md, hackathon/hackathon-january.md
I update hackathon submission links
=> docs(blog): update submission links

hackathon/refine-hackathon.md
=> chore: update hackathon content

documentation/blog/2023-01-06-hackaton-january.md, documentation/docusaurus.config.js, documentation/src/assets/nav-menu.ts, documentation/src/theme/BlogListPage/index.js, hackathon/hackathon-january.md
=> docs(blog): update hackathon links

documentation/docs/api-reference/core/hooks/invalidate/useInvalidate.md
added: [useInvalidate documentation](https://refine.dev/docs/api-reference/core/hooks/invalidate/useInvalidate/)
=> feat(docs): add useInvalidate doc

documentation/blog/2023-01-30-compare-form-libraries.md
I added form libraries comparison
=> docs(blog): add forms post

documentation/docs/api-reference/antd/hooks/form/useStepsForm.md
added: ["How can I change the form data before submitting it to the API?"](http://refine.dev/docs/api-reference/antd/hooks/form/useStepsForm/#how-can-i-change-the-form-data-before-submitting-it-to-the-api) example to useStepsForm's FAQ section
=> feat(docs): add example of change form data to `useStepsForm`

documentation/docs/api-reference/core/hooks/data/useDataProvider.md
Updated the `useDataProvider` doc.
=> fix: update `useDataProvider` doc

documentation/docs/api-reference/core/hooks/navigation/useNavigation.md
Updated the `useNavigation` doc.
=> docs: update `useNavigation` doc

documentation/docs/api-reference/antd/hooks/field/useSelect/basic-usage-live-preview.md, documentation/docs/api-reference/antd/hooks/field/useSelect/crud-live-preview.md, documentation/docs/api-reference/antd/hooks/field/useSelect/default-value-live-preview.md, documentation/docs/api-reference/antd/hooks/field/useSelect/index.md, documentation/docs/api-reference/antd/hooks/field/useSelect/on-search-live-preview.md, documentation/docs/api-reference/antd/hooks/field/useSelect/sort-live-preview.md, documentation/docs/api-reference/core/hooks/useSelect/basic-usage-live-preview.md, documentation/docs/api-reference/core/hooks/useSelect/default-value-live-preview.md, documentation/docs/api-reference/core/hooks/useSelect/index.md, documentation/docs/api-reference/core/hooks/useSelect/on-search-live-preview.md, documentation/docs/api-reference/core/hooks/useSelect/sort-live-preview.md
Fix `useSelect` (antd,core) live preview
=> docs: fix `useSelect` (antd,core) live preview

documentation/docs/api-reference/antd/hooks/list/basic-usage-live-preview.md, documentation/docs/api-reference/antd/hooks/list/filtering-live-preview.md, documentation/docs/api-reference/antd/hooks/list/search-live-preview.md, documentation/docs/api-reference/antd/hooks/list/sorting-live-preview.md, documentation/docs/api-reference/antd/hooks/list/useSimpleList.md
Updated the `useSimpleList` doc.
=> feat: update `useSimpleList` doc

documentation/docs/tutorial/1-getting-started/antd/2-create-project.md, documentation/docs/tutorial/1-getting-started/chakra-ui/2-create-project.md, documentation/docs/tutorial/1-getting-started/headless/2-create-project.md, documentation/docs/tutorial/1-getting-started/mantine/2-create-project.md, documentation/docs/tutorial/1-getting-started/mui/2-create-project.md
Add supported `yarn@1` version on docs.
=> docs: add supported yarn version

documentation/docs/api-reference/core/hooks/resource/useResource.md, documentation/docs/api-reference/core/hooks/resource/useResourceWithRoute.md
- Updated the `useResource` doc.
- Updated the `useResourceWithRoute` doc.
=> docs: update resource hook docs

documentation/docs/packages/list-of-packages.md
Fix the typo for react table package.
=> docs: Fix typo from kbar to React Table

documentation/docs/api-reference/core/providers/auth-provider.md, documentation/docs/tutorial/5-understanding-authprovider/0-intro.md, documentation/src/partials/auth-provider-examples-links.md
added: https://refine.dev/docs/api-reference/core/providers/auth-provider
=> docs(auth-provider): update descriptions and refer to tutorial

documentation/docs/api-reference/core/providers/i18n-provider.md
added: https://refine.dev//docs/api-reference/core/providers/i18n-provider
=> docs(i18n-provider): update i18n provider doc

documentation/docs/api-reference/core/hooks/import-export/useExport.md, documentation/docs/api-reference/core/hooks/import-export/useImport.md
- Updated `useExport` hook doc
- Updated `useImport` hook doc
=> docs: update `useExport` and `useImport` hook docs

documentation/docs/api-reference/core/hooks/live/usePublish.md, documentation/docs/api-reference/core/interfaces.md
added: https://refine.dev/docs/api-reference/core/hooks/live/usePublish/
=> docs(use-publish): update usePublish doc

documentation/blog/2022-12-23-dynamic-hook-form.md, documentation/blog/2023-01-17-airtable-crud-app.md, documentation/blog/2023-02-01-uri-vs-url.md, examples/blog-refine-airtable-crud/src/pages/post/list.tsx
Updated Airtable docs and add URL vs URI doc
=> Add url vs uri post

documentation/docs/api-reference/core/hooks/live/useSubscription.md
added : https://refine.dev/docs/api-reference/core/hooks/live/useSubscription/
=> docs(use-subsciption): update useSubscription doc

documentation/docs/api-reference/core/hooks/ui/useModal.md
added: https://refine.dev/docs/api-reference/core/hooks/ui/useModal/
=> docs(use-modal): update useModal doc

documentation/docs/api-reference/core/components/auth-page.md
added : https://refine.dev/docs/api-reference/core/components/auth-page
=> docs(auth-page): add info of called method of the provider

documentation/docs/api-reference/antd/hooks/form/useForm.md, documentation/docs/api-reference/core/hooks/useForm.md, documentation/docs/api-reference/mantine/hooks/form/useForm.md, documentation/docs/packages/documentation/react-hook-form/useForm.md
resource prop and code examples updated
=> docs(use-form): update similar to others

.changeset/wicked-queens-move.md, packages/core/src/hooks/useTable/index.ts, packages/react-table/src/useTable/index.spec.ts
Default value was wrong on `useTable` jsDoc
=> fix(core): wrong initial current value on useTable jsDoc

packages/core/src/index.tsx, packages/core/src/interfaces/bindings/access-control.ts, packages/core/src/interfaces/bindings/auth.ts, packages/core/src/interfaces/bindings/data.ts, packages/core/src/interfaces/bindings/i18n.ts, packages/core/src/interfaces/bindings/index.ts, packages/core/src/interfaces/bindings/live.ts, packages/core/src/interfaces/bindings/notifications.ts, packages/core/src/interfaces/bindings/resource.ts, packages/core/src/interfaces/bindings/router.ts, packages/core/src/interfaces/index.ts
Add new interfaces for refine v4 bindings. Not used for now but will be in future 😅 
=> feat(v4): add new binding types

examples/auth-headless/src/pages/posts/list.tsx, examples/base-headless/src/pages/posts/list.tsx, examples/finefoods-mui/src/components/dashboard/orderTimeline/index.tsx, examples/table-mui-advanced/src/pages/table/index.tsx, examples/table-react-table-advanced/src/pages/posts/list.tsx, examples/with-persist-query/src/pages/posts/list.tsx, examples/with-react-toastify/src/pages/posts/list.tsx, examples/with-remix-headless/app/pages/posts/list.tsx
Fix `getColumn` is possibly `undefined`
=> fix: `getColumn` is possibly `undefined`

documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
this PR address #3535 but not only
> Given it's a doc "fix" so not sure an issue is useful
Context:
- Some code is out of context (example: [here](https://refine.dev/docs/tutorial/understanding-dataprovider/create-dataprovider/#getlist:~:text=...%0A%5D-,In%20the%20first%20step,-%2C%20we%27ll%20return%20the))
Some is in context (example [here](Now let's get the metaData parameter from the data provider.))
Which is way easier, especially at the beginning (like the `getList` example) to know where to put things.
- some code have syntax errors. (example [here](https://refine.dev/docs/tutorial/understanding-dataprovider/create-datapro …
=> docs: tutorial, unit3, p3 - Fix indentation, code contexts and syntax

documentation/blog/2023-02-08-compare-cms.md
=> docs(blog): add CMS article

documentation/blog/2023-02-08-compare-cms.md
=> Update post desc

documentation/docs/api-reference/antd/components/auth-page.md, documentation/docs/api-reference/chakra-ui/components/auth-page.md, documentation/docs/api-reference/core/components/auth-page.md, documentation/docs/api-reference/mantine/components/auth-page.md, documentation/docs/api-reference/mui/components/auth-page.md
=> docs(auth-page): update auth page doc

documentation/docs/api-reference/core/components/accessControl/canAccess.md
added: https://refine.dev/docs/api-reference/core/components/accessControl/can-access/
=> docs(can-access): update can access doc

documentation/docs/api-reference/core/hooks/data/useInfiniteList/index.md
=> Fix Tanstack useInfiniteQuery URL

documentation/docs/advanced-tutorials/import-export/csv-export.md, documentation/docs/advanced-tutorials/import-export/csv-import.md
Updated import and export doc on advanced tutorials.
=> docs: update advance tutorial import-export docs

documentation/blog/2021-10-4-simple-web-application.md, documentation/blog/2022-03-22-refine-with-react95.md, documentation/docs/advanced-tutorials/data-provider/supabase.md, examples/blog-issue-tracker/src/authProvider.ts, examples/blog-refine-supabase-auth/src/pages/Login.tsx, examples/blog-refineflix/src/pages/admin/movies/create.tsx, examples/blog-refineflix/src/pages/admin/movies/edit.tsx
Fix build error on supabase example apps.
=> fix(supabase-examples): build errors

documentation/docs/advanced-tutorials/data-provider/supabase.md, examples/blog-hackathonize/src/authProvider.ts, examples/blog-issue-tracker/src/authProvider.ts, examples/blog-refine-supabase-auth/src/authProvider.ts, examples/blog-refineflix/src/authProvider.ts, examples/blog-win95/src/authProvider.ts, examples/data-provider-supabase/src/App.tsx, examples/pixels-admin/src/providers/authProvider.ts, examples/pixels/src/providers/authProvider.ts
Fix Supabase auth provider checkAuth method.
=> fix: supabase auth provider checkAuth method

packages/inferencer/src/components/live/index.tsx, packages/inferencer/src/create-inferencer/index.tsx, packages/inferencer/src/inferencers/antd/error.tsx, packages/inferencer/src/inferencers/chakra-ui/error.tsx, packages/inferencer/src/inferencers/headless/error.tsx, packages/inferencer/src/inferencers/mantine/error.tsx, packages/inferencer/src/inferencers/mui/error.tsx, packages/inferencer/src/types/index.ts, packages/inferencer/src/use-infer-fetch/index.tsx
Updated error messages in Inferencer components to be more descriptive. Also added links to the GitHub issues and the documentation.
=> feat(inferencer): descriptive error messages

.changeset/tasty-beds-reflect.md
Added the missing changeset of PR #3596
=> chore(inferencer): add missing changeset

documentation/src/pages/week-of-refine/index.tsx
=> docs(refineweek): fixed dates

.changeset/mighty-olives-wait.md, examples/data-provider-supabase/src/App.tsx, packages/supabase/src/index.ts
Fixed live provider subscription issue without filters.
=> fix(supabase): realtime features with empty filters

documentation/src/assets/integration-icons/chakra.tsx, documentation/src/assets/integration-icons/index.ts, documentation/src/assets/integrations.ts
I added chakra to integrations
=> docs(integrations): add chakra

examples/pixels/src/providers/authProvider.ts
fixed: pixels `checkAuth` logic
=> fix(pixels): checkout logic

documentation/docs/tutorial/4-adding-crud-pages/mui/add-edit-page.md
=> docs: fix typo in tutorial

.changeset/dull-kiwis-travel.md, packages/inferencer/src/field-inferencers/number.ts, packages/inferencer/src/inferencers/chakra-ui/create.tsx, packages/inferencer/src/inferencers/chakra-ui/edit.tsx, packages/inferencer/src/inferencers/headless/create.tsx, packages/inferencer/src/inferencers/headless/edit.tsx, packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/index.test.tsx.snap, packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/list.test.tsx.snap, packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/create.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/edit.test.tsx.snap, packages/inferencer/src/inferencers/mui/create.tsx, packages/inferencer/src/inferencers/mui/edit.tsx
Updated the number field checks for the inferencer, now string values will also be checked for numeric values.
Resolves #3550
=> fix(inferencer): update number field checks

documentation/blog/2023-02-18-refine-pixels-5.md, documentation/src/pages/week-of-refine/index.tsx
=> docs(blog): add refine-week part 5

documentation/blog/2023-02-18-refine-pixels-5.md, documentation/blog/2023-02-19-refine-pixels-6.md, documentation/src/pages/week-of-refine/index.tsx
=> docs(blog): add refineWeek part 6

.changeset/tender-ravens-battle.md, packages/inferencer/src/field-inferencers/date.test.ts, packages/inferencer/src/field-inferencers/date.ts
=> fix: update date inferencer to check existence of date separators

documentation/blog/2023-02-20-refine-pixels-7.md, documentation/src/pages/week-of-refine/index.tsx
I added the refine pixels last article
=> docs(blog): add refine pixels 7

.changeset/slow-readers-wait.md, packages/antd/src/components/pages/index.tsx, packages/antd/src/components/pages/welcome/index.spec.tsx, packages/antd/src/components/pages/welcome/index.tsx, packages/chakra-ui/src/components/pages/index.ts, packages/chakra-ui/src/components/pages/welcome/index.spec.tsx, packages/chakra-ui/src/components/pages/welcome/index.tsx, packages/core/src/components/pages/index.tsx, packages/core/src/components/pages/welcome/index.spec.tsx, packages/core/src/components/pages/welcome/index.tsx, packages/mantine/src/components/pages/index.ts, packages/mantine/src/components/pages/welcome/index.spec.tsx, packages/mantine/src/components/pages/welcome/index.tsx, packages/mui/src/components/pages/index.tsx, packages/mui/src/components/pages/welcome/index.spec.tsx, packages/mui/src/components/pages/welcome/index.tsx
- `<ReadyPage>` is deprecated.
- Created `<WelcomePage>` component to welcome users.
=> feat(v4): add `WelcomePage`, deprecate `ReadyPage`

examples/pixels/src/components/color-select/index.tsx, examples/pixels/src/pages/canvases/show.tsx, examples/table-react-table-advanced/src/react-table-config.d.ts, packages/cli/src/commands/swizzle/index.tsx, packages/mantine/src/hooks/form/useForm/index.ts
Ran `lint:fix` on the codebase. 
=> chore: run lint:fix on codebase

documentation/blog/2023-02-28-hackathon-january-winners.md, hackathon/refine-hackathon.md
I added winner announcement post
=> docs(blog): add winner announcement

documentation/blog/2023-02-28-hackathon-january-winners.md
=> docs(blog): fix indentation

documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
=> docs: Fix typo in documentation of logout tutorial.

documentation/docs/api-reference/mui/components/buttons/show.md
=> docs: Update show.md to remove the API Reference section as code block.

packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/create.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/edit.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/show.test.tsx.snap
=> test(inferencer): update snapshots

.changeset/curvy-geese-visit.md, packages/core/src/hooks/data/useUpdate.ts
closes https://github.com/refinedev/refine/issues/3652
=> Fix optimistic updates of lists

.changeset/happy-maps-double.md, packages/cli/src/utils/swizzle/provideCliHelpers.ts
=> fix(cli): swizzle type issue

documentation/docs/api-reference/core/hooks/data/useCustomMutation/index.md
=> docs: fix typo in useCustomMutation

.changeset/spicy-days-fly.md, packages/create-refine-app/package.json
I've updated superplate@1.12.3 for branch arg support
=> chore: bump superplate@1.12.3 for branch arg support

.changeset/spicy-swans-float.md, packages/core/src/components/gh-banner/index.tsx, packages/core/src/components/gh-banner/styles.ts, packages/core/src/components/index.ts
=> feat: add `GitHubBanner` component to `refine-core`

packages/codemod/src/transformations/refine3-to-refine4.ts, packages/codemod/src/transformations/v4/fix-v4-deprecations.ts, packages/codemod/src/transformations/v4/replace-pankod-imports-with-refinedev.ts
=> chore(v4): merge v4 deprecations and organization rename codemods

documentation/blog/2023-03-03-ra-chakra-tutorial.md, examples/blog-ra-chakra-tutorial/package.json
I added missing live code example
=> docs(blog): add live example

packages/codemod/src/transformations/v4/replace-pankod-imports-with-refinedev.ts
=> fix: codemod replace package names

examples/data-provider-airtable/src/App.tsx, examples/data-provider-appwrite/src/App.tsx, examples/data-provider-appwrite/src/pages/posts/create.tsx, examples/data-provider-appwrite/src/pages/posts/edit.tsx, examples/data-provider-appwrite/src/pages/posts/list.tsx, examples/data-provider-appwrite/src/pages/posts/show.tsx, examples/data-provider-hasura/src/App.tsx, examples/data-provider-hasura/src/pages/categories/create.tsx, examples/data-provider-hasura/src/pages/categories/edit.tsx, examples/data-provider-hasura/src/pages/categories/list.tsx, examples/data-provider-multiple/src/App.tsx, examples/data-provider-nestjsx-crud/src/App.tsx, examples/data-provider-nhost/src/App.tsx, examples/data-provider-nhost/src/pages/categories/create.tsx, examples/data-provider-nhost/src/pages/categories/edit.tsx, examples/data-provider-nhost/src/pages/categories/list.tsx, examples/data-provider-strapi-graphql/src/App.tsx, examples/data-provider-strapi-v4/src/App.tsx, examples/data-provider-strapi-v4/src/pages/users/index.ts, examples/data-provider-strapi-v4/src/pages/users/list.tsx, examples/data-provider-strapi/src/App.tsx, examples/data-provider-supabase/src/App.tsx
Updated all data provider examples.
=> fix(v4): Migrate data provider examples to new router

documentation/docs/advanced-tutorials/access-control.md
In [Access Control](https://github.com/refinedev/refine/blob/next/documentation/docs/advanced-tutorials/access-control.md#adding-policy-and-model) the link for `here` is broken . I fixed it by updating it to [here](https://casbin.org/docs/how-it-works)
closes #3743 
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes …
=> docs(access-control): updated broken link

documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
=> fix(docs): create auth provider tutorial

examples/antd-audit-log/src/App.tsx, examples/auth-antd/src/App.tsx, examples/blog-mail-subscription/src/components/header/index.tsx, examples/blog-mail-subscription/src/components/sider/index.tsx, examples/blog-mail-subscription/src/interfaces/index.d.ts, examples/blog-ra-chakra-tutorial/src/components/layout/header/index.tsx, examples/blog-ra-chakra-tutorial/src/interfaces/index.d.ts, examples/blog-refine-supabase-auth/src/pages/Layout.tsx, examples/blog-refine-supabase-auth/src/pages/Login.tsx, examples/blog-refineflix/src/components/sider/index.tsx, examples/blog-win95/src/authProvider.ts, examples/blog-win95/src/components/footer/index.tsx, examples/customization-sider/src/components/sider/index.tsx, examples/finefoods-antd/src/App.tsx, examples/finefoods-antd/src/components/header/index.tsx, examples/finefoods-antd/src/interfaces/index.d.ts, examples/finefoods-mui/src/App.tsx, examples/finefoods-mui/src/components/header/index.tsx, examples/finefoods-mui/src/interfaces/index.d.ts, examples/multi-tenancy-appwrite/src/components/sider/index.tsx, examples/multi-tenancy-strapi/src/components/sider/index.tsx, examples/pixels/src/components/canvas/create.tsx, examples/with-cloud/src/pages/login/index.tsx, examples/with-web3/src/pages/dashboard.tsx
fixed: Some auth hooks had remained in legacy usage. migrated to the new version."
fixed: dashboard route added to finefoods-mui and finefodos-antd
---------
=> fix(examples): fix broken examples

packages/core/src/components/authenticated/index.tsx
Updated `Authenticated` component for invalid React state update call.
=> fix(core): defer redirect until render phase is finished

documentation/docs/api-reference/mui/components/fields/text.md
=> fix(docs): wrong import in mui components fields text docs

documentation/docs/api-reference/mui/components/auth-page.md
Updated `contentProps` values in live preview to match https://mui.com/material-ui/api/card-content/#props
Resolves #3749
=> docs(auth-page): update `refine-mui`'s `contentProps` example

examples/antd-audit-log/src/App.tsx, examples/auth-antd/src/App.tsx, examples/blog-hackathonize/src/App.tsx, examples/blog-issue-tracker/src/App.tsx, examples/finefoods-antd/src/App.tsx, examples/finefoods-mui/src/App.tsx, examples/with-cypress/src/App.tsx, examples/with-web3/src/App.tsx
label added to dashboard resource
=> fix(v4-examples): add label to dashboard resource

examples/finefoods-antd/src/pages/products/list.tsx
=> fix(v4-finefoods): finefoods antd pagination on products

examples/finefoods-antd/src/pages/couriers/create.tsx, examples/finefoods-antd/src/pages/products/list.tsx, examples/finefoods-mui/src/pages/couriers/create.tsx
on couriers page steps from, buttons usage was wrong. due to this issue, users cannot create courier
=> fix(finefoods): couriers page incorrect usage of save button

examples/access-control-casbin/src/App.tsx, examples/access-control-cerbos/src/App.tsx, examples/antd-audit-log/src/App.tsx, examples/audit-log-provider/src/App.tsx, examples/auth-antd/src/App.tsx, examples/auth-auth0/src/App.tsx, examples/auth-chakra-ui/src/App.tsx, examples/auth-google-login/src/App.tsx, examples/auth-headless/src/App.tsx, examples/auth-keycloak/src/App.tsx, examples/auth-mantine/src/App.tsx, examples/auth-mui/src/App.tsx, examples/auth-otp/src/App.tsx
=> fix(v4): update examples that start with "a"
