documentation/docs/api-references/providers/auth-provider.md
packages/core/src/components/containers/refine/index.tsx
packages/core/src/contexts/auth/index.tsx
packages/core/src/hooks/auth/useAuthenticated/index.spec.ts

[Link to ADD-CHECK-AUTH-REDIRECT-PATH-SUPPORT](https://add-che-refine.pankod.com)
We should be able to customize the URL where the user will be redirected when `checkAuth` fails.
It is redirected to root by default.
```
checkAuth: () => {
localStorage.getItem("auth") ? Promise.resolve() : Promise.reject({ redirectPath: "/custom-login-page" });
},
```
#1126 
[Link to ADD-CHECK-AUTH-REDIRECT-PATH-SUPPORT](https://add-che-doc-refine.pankod.com)

add checkAuth redirectPath support

---

packages/core/src/hooks/form/useEditForm/useEditForm.spec.tsx
packages/core/src/hooks/form/useEditForm/useEditForm.ts
packages/core/src/hooks/form/useModalForm/useModalForm.spec.tsx
packages/core/src/hooks/show/useShow.spec.tsx
packages/core/src/hooks/show/useShow.ts

[Link to FIX-ID-OF-HOOKS](https://fix-id--refine.pankod.com)
closes #958

fix id return value of some hooks 

---

documentation/docs/api-references/components/refine-config.md
packages/core/src/components/containers/refine/index.tsx

[Link to CUSTOMIZABLE-REACT-QUERY](https://customi-refine.pankod.com)
React Query Devtools can now be customized passing `reactQueryDevtoolConfig` property.
closes #1197
[Link to CUSTOMIZABLE-REACT-QUERY](https://customi-doc-refine.pankod.com)

Customizable React Query Devtools

---

documentation/docs/guides-and-concepts/ssr-nextjs.md
examples/refine-next/pages/[resource]/index.tsx
packages/nextjs-router/src/nextRouteComponent.tsx

Hey, I'm client! Test me! 'ALPHA'
[Link to PAGE-DATA-TO-INITIAL-DATA](https://page-da-client.refine.pankod.com)

update pageData to initialData

---

examples/fineFoods/client/package.json
examples/i18n/nextjs/package.json
examples/refine-next/package.json
examples/refine-next/tsconfig.json
packages/nextjs-router/package.json

[Link to UPGRADE-NEXTJS-12](https://upgrade-refine.pankod.com)
Added support for next.js@12
Unable to use next.js 12 with refine. now refine-nextjs-router depends on next@12
#1233

upgrade refine-nextjs-router - next.js@12

---

examples/fineFoods/client/package-lock.json
examples/fineFoods/client/package.json
examples/fineFoods/client/tsconfig.json
examples/i18n/nextjs/package.json
examples/refine-next/package.json
examples/refine-next/tsconfig.json
lerna.json
packages/nextjs-router/package.json

[Link to ALPHA](https://alpha-client.refine.pankod.com)
Now, nextjs is added as peerDependency.
Put `closes #1233`

nextjs 12 support

---

packages/core/types/sunflower.d.ts

[Link to OMIT-DEFAULT-FORM-VALUES-USE-MODAL-FORM](https://omit-de-refine.pankod.com)
"defaultFormValues" from sunflower library is not used by refine but exported as type. It is now Omited. Form component's `initialValues` property can be used
#1263

omit defaultFormValues prop on useModalForm

---

examples/dataProvider/strapi/package.json
packages/strapi-graphql/src/index.ts
packages/strapi/src/dataProvider.ts

Strapi REST and GraphQL APIs don't need a suffix for the "eq" filter. With this change, we can now support Strapi Draft Content filters.
closes #1273

update "eq" filter operator on strapi & strapi-graphql data providers

---

packages/react-router/src/routeProvider.tsx

[Link to FIX-LAYOUT-WRAPPER-FOR-CUSTOM-PAGASE](https://fix-lay-client.refine.pankod.com)
`customPages` were wrapped in `LayoutWrapper` by default. Now the user can specify himself whether to wrap it in LayoutWrapper or not.
closes #1279

fix custom routes wrapped layout wrapper

---

packages/core/src/components/buttons/list/index.spec.tsx
packages/core/src/components/buttons/list/index.tsx
packages/core/src/components/crud/create/index.spec.tsx
packages/core/src/components/crud/create/index.tsx
packages/core/src/components/crud/edit/index.spec.tsx
packages/core/src/components/crud/edit/index.tsx
packages/core/src/components/crud/list/__snapshots__/index.spec.tsx.snap
packages/core/src/components/crud/list/index.spec.tsx
packages/core/src/components/crud/list/index.tsx
packages/core/src/components/crud/show/index.spec.tsx
packages/core/src/components/crud/show/index.tsx

[Link to USE-LABEL-BEFORE-RESOURCE](https://use-lab-refine.pankod.com)
[Link to USE-LABEL-BEFORE-RESOURCE](https://use-lab-client.refine.pankod.com)
closes #1298

Use label before resource

---

packages/core/src/hooks/table/useTable/useTable.ts

[Link to FIX-USE-TABLE-LOADING-STATE](https://fix-use-client.refine.pankod.com)
The `useTable` should show a loading animation based on the `isFetching` state of react-query. `isLoading` should only be considered when `liveMode` is `auto`.
closes #1316

fix useTable loading state

---

packages/airtable/package.json
packages/airtable/src/index.ts
packages/airtable/test/getList/index.mock.ts
packages/airtable/test/getList/index.spec.ts

Adds support for filters in Airtable by using Airtable's `filterByFormula` feature.
**Note**: I was not sure how the `null` filter works from the [documentation](https://refine.dev/docs/api-references/interfaceReferences/#crudfilters) (I assumed value is `false` for `field is not null` and `true` for `field is null`). 
This provides feature parity with other data providers by making simple filtering in a table possible. 
Some things that could still be added: 
- Support for array lookups (Airtable filters don't understand arrays so this requires matching on the string Airtable generates (comma separated list) …

Add filter support to the airtable data provider

---

packages/core/src/hooks/table/useTable/useTable.ts

Changes the `isFetching` flag to the inverted `isFetched` flag instead for setting the loading property. `loading` will thus be true when fetching new data, but set to false if the data is already cached (and react-query is merely re-fetching in the background to update the cache).
See above
1. Open App
2. Observe initial loading animation
3. Click on a new page (second page) - observe loading animation appear
4. Click on the previous page (first page) - no loading animation (cached result shown, react-query refetches in the background)
5. Click on another new page (third page)
6. Observe …

Change flag for controlling useTable's loading property to isFetched

---

packages/hasura/src/index.ts

Aggregation Filters patch
Aggregation Operation Spelling
Put `closes #1377` in your comment to auto-close the issue that your PR fixes (if such).

Fix Hasura Count Aggregation Filter

---

documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/data-provider/appwrite.md

In the appwrite implementation, it uses `writePermissions` and `readPermissions` instead of `writeAccess` and `readAccess`:
https://github.com/pankod/refine/blob/master/packages/appwrite/src/index.ts#L141

Docs: Fix appwrite docs

---

examples/dataProvider/strapi-graphql/src/App.tsx
examples/dataProvider/strapi-graphql/src/pages/posts/edit.tsx
packages/strapi-graphql/src/index.ts
packages/strapi-graphql/test/gqlClient.ts
packages/strapi-graphql/test/update/index.mock.ts
packages/strapi-graphql/test/update/index.spec.ts
packages/strapi-graphql/test/updateMany/index.spec.ts

[Link to FIX-STRAPI-GRAPHQL-UPDATE-MUTATION](https://fix-str-client.refine.pankod.com)
[Link to FIX-STRAPI-GRAPHQL-UPDATE-MUTATION](https://fix-str-refine.pankod.com)
Strapi only returns the `id` field when updating. `useEditForm` was throwing an error as it was sent all fields to the `useUpdate` mutation.
- #1396

Fix strapi-graphql useUpdate mutation

---

packages/core/src/components/buttons/clone/index.tsx
packages/core/src/components/buttons/create/index.tsx
packages/core/src/components/buttons/edit/index.tsx
packages/core/src/components/buttons/list/index.tsx
packages/core/src/components/buttons/show/index.tsx
packages/core/src/hooks/resource/useResourceWithRoute/index.ts

[Link to FIX-BUTTONS-RESOURCE-NAME-PROP](https://fix-but-client.refine.pankod.com)
Button's `resourceName` prop was ignored. Navigation was broken when using a custom path in resources. I  updated the `useNavigation` hook for that too.
- #1387 
- #1400

fix buttons resourceName prop issue

---

packages/core/src/hooks/resource/useMenu/index.tsx

[Link to FIX-USE-MENU-SELECTED-KEY](https://fix-use-refine.pankod.com)
The `useMenu` hook was returning the wrong `selectedKey` if I defined multiple resources with the same resource name.
Checking as strict instead of checking with startsWith
- #1432 
- #1283

fix useMenu selected key issue

---

packages/core/src/hooks/table/useTable/useTable.ts

[Link to FIX-USETABLE-FORM-RETURN-TYPE](https://fix-use-refine.pankod.com)
`useTable` was returning `FormInstance` as formProps. Actually `FormProps` should have returned.
1. #1436

Fix useTable returning FormInstance as formProps

---

packages/core/src/components/buttons/clone/index.tsx
packages/core/src/components/buttons/delete/index.tsx
packages/core/src/components/buttons/edit/index.tsx
packages/core/src/components/buttons/refresh/index.tsx
packages/core/src/components/buttons/show/index.tsx
packages/core/src/components/crud/edit/index.tsx
packages/core/src/components/crud/show/index.tsx
packages/core/src/hooks/form/useCloneForm/useCloneForm.ts
packages/core/src/hooks/form/useEditForm/useEditForm.ts
packages/core/src/hooks/navigation/index.spec.tsx
packages/core/src/hooks/navigation/index.ts
packages/core/src/hooks/show/useShow.ts
packages/nextjs-router/src/nextRouteComponent.tsx
packages/react-location/src/resourceComponent.tsx
packages/react-router/src/routeProvider.tsx

[Link to ENCODE-DECODE-ID-PARAM](https://encode--refine.pankod.com)
[Link to ENCODE-DECODE-ID-PARAM](https://encode--client.refine.pankod.com)
Now id parameters are used by encoding and decoding.
So lets say my record.style_code returns a value like ABC/2 then it'll redirect to /products/ABC/2 instead of something like /products/ABC%2F2
- #1467

encode & decode id params

---

packages/supabase/src/index.ts

This closes #1499 
Allow overriding the `id` selector via metaData in the Supabase data provider.
Example of usage:
```
const tenantUsersQueryResult = useMany<ITenantUsers>({
resource: "tenant_users",
ids: [editId ?? ""],
metaData: {
id: "tenant_id",
},
queryOptions: {
enabled: editId ? true : false,
},
});
```

Supabase: Allow overriding the id selector via metaData #1499

---

documentation/versioned_docs/version-3.xx.xx/guides-and-concepts/multi-tenancy/strapi.md

Example of a StrapiV4 readme had a typo. `StoreContext` was duplicated.

version 3.xx.xx multi-tenancy strapi.md typo fix.

---

packages/antd/src/components/buttons/clone/index.tsx
packages/antd/src/components/buttons/edit/index.tsx
packages/antd/src/components/buttons/export/index.tsx
packages/antd/src/components/buttons/import/index.tsx
packages/antd/src/components/buttons/list/index.tsx
packages/antd/src/components/buttons/refresh/index.tsx
packages/antd/src/components/buttons/save/index.tsx
packages/antd/src/components/buttons/show/index.tsx

As I mentioned in the issue (#1553) some of the antd button don´t export their extended prop types, this PR adds an export for those types
closes #1553

adds export to antd button extended props types

---

documentation/docs/core/components/layout-wrapper.md
examples/dataProvider/nhost/package.json
examples/dataProvider/nhost/src/App.tsx
packages/antd/src/components/layout/index.tsx
packages/core/src/components/layoutWrapper/index.tsx

[Link to REMOVE-UNUSED-DASHBOARD-PROP](https://remove--client.refine.pankod.com)
[Link to REMOVE-UNUSED-DASHBOARD-PROP](https://remove--refine.pankod.com)
We've removed unnecessary `dashboard` property of `<LayoutWrapper />` component

remove unused dashboard property of LayoutWrapper component

---

documentation/docs/ui-frameworks/antd/components/buttons/delete.md
packages/antd/src/components/buttons/delete/index.tsx

[Link to ADD-CONFIRM-TITLE-DELETE-BUTTON](https://add-con-refine.pankod.com)
Co-authored-by: Melih Özkalay <ozkalai@users.noreply.github.com>

add popconfirm text props to delete button

---

packages/core/src/hooks/form/useForm.ts

When using the useForm hook with a non-default data provider (i.e., setting the dataProviderName param) on an edit-page, it still tries to load the data via the default data provider.
This PR fixes this problem by passing the dataProviderName param down to the internally used useOne hook.
See related issue to see how to reproduce the bug.
Closes https://github.com/pankod/refine/issues/1631

Fix dataProviderName in useForm hook

---

documentation/docs/core/interfaces.md
packages/airtable/src/index.ts
packages/airtable/test/getList/index.spec.ts

Adds support for OR filter (https://github.com/pankod/refine/issues/1417) in the airtable data provider. Also fix the changed `null`/`nnull` handling and ammend its documentation in https://refine.dev/docs/core/interfaceReferences/#crudfilters
Complements https://github.com/pankod/refine/issues/1417
Tests available at `packages/airtable/test/getList/index.spec.ts`

Airtable data or filter

---

packages/core/src/contexts/resource/IResourceContext.ts

This allows the user to add a type-definition to the `IResourceComponentsProps` for the `options` prop instead of defaulting to `any`.
Example usage:
```tsx
<Refine
resources=[{
name: "posts",
options: {
dataProviderName: "my-custom-dataprovider",
}
}]
...
/>
```
```ts
export const PostList: React.FC<IResourceComponentsProps<{ dataProviderName: string }>> = (props) => {
const { tableProps, searchFormProps, filters, ...rest } = useTable<IPost>({
dataProviderName: props.options?.dataProviderName
});
// ...
}
```
If no generic param is provided, it default to the previous `[key: string]: any` definition.

Make OptionsProps generic

---

packages/react-router-v6/src/routeProvider.tsx

[Link to FIX-REACT-ROUTER-V6-NO-ROUTE-WARNING](https://fix-rea-refine.pankod.com)
It was because we returned an "empty route" during the authentication process.
- #1638

Fix react-router-v6 not matched route warning

---

packages/react-router-v6/src/routeProvider.tsx

[Link to FIX-REACT-ROUTER-V6-RESOURCE-MATCH](https://fix-rea-client.refine.pankod.com)
The router was looking by `name` and `route` when selecting the resource. Now we're just looking at the route.
- #1642

Fix react-router-v6 resource name match

---

packages/antd/src/hooks/form/useDrawerForm/useDrawerForm.ts
packages/core/src/hooks/form/useForm.ts

useForm was losing `id` value after successful mutation.
- #1646

fix wrong set id after mutation on useForm

---

documentation/docs/ui-frameworks/antd/components/buttons/clone.md
documentation/docs/ui-frameworks/antd/components/buttons/create.md
documentation/docs/ui-frameworks/antd/components/buttons/delete.md
documentation/docs/ui-frameworks/antd/components/buttons/edit.md
documentation/docs/ui-frameworks/antd/components/buttons/list.md
documentation/docs/ui-frameworks/antd/components/buttons/refresh.md
documentation/docs/ui-frameworks/antd/components/buttons/show.md
examples/base/src/App.tsx
packages/antd/src/components/buttons/clone/index.spec.tsx
packages/antd/src/components/buttons/clone/index.tsx
packages/antd/src/components/buttons/create/index.spec.tsx
packages/antd/src/components/buttons/create/index.tsx
packages/antd/src/components/buttons/delete/index.spec.tsx
packages/antd/src/components/buttons/delete/index.tsx
packages/antd/src/components/buttons/edit/index.spec.tsx
packages/antd/src/components/buttons/edit/index.tsx
packages/antd/src/components/buttons/list/index.spec.tsx
packages/antd/src/components/buttons/list/index.tsx
packages/antd/src/components/buttons/refresh/index.tsx
packages/antd/src/components/buttons/show/index.spec.tsx
packages/antd/src/components/buttons/show/index.tsx
packages/antd/src/components/crud/edit/index.tsx
packages/antd/src/components/crud/list/index.tsx
packages/antd/src/components/crud/show/index.tsx
packages/core/src/hooks/resource/useResourceWithRoute/index.ts

[Link to FIX-ROUTES-HANDLE-CRUD-AND-BUTTONS](https://fix-rou-client.refine.pankod.com)
Buttons such as create, edit, show that were added automatically when using the custom route in resource definitions were going to the wrong route.  We have to add the unit tests.
- #1618 
[Link to FIX-ROUTES-HANDLE-CRUD-AND-BUTTONS](https://fix-rou-doc-refine.pankod.com)

handle custom routes on CRUD componenets and buttons

---

documentation/docs/core/components/refine-config.md

Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

Fix correction of example code for components catchAll

---

documentation/docs/core/hooks/useSelect.md
documentation/docs/ui-frameworks/antd/hooks/field/useSelect.md
packages/core/src/hooks/useSelect/index.spec.ts
packages/core/src/hooks/useSelect/index.ts

[Link to FEATURE-USE-SELECT-DEFAULT-VALUE](https://feature-refine.pankod.com)
In the useSelect hook, When the `defaultValue` property is given, the `useMany` data hook is called for the selected records. With this property, you can change the options of this query. If not given, the values given in queryOptions will be used.
- #1673

Add fallback for defaultValueQueryOptions on useSelect hook

---

documentation/docs/core/providers/auth-provider.md

First version of updated docs for the `Authorization Credentials` section of `core/providers/auth-provider`. 
I added some language about the importance of a singular Axios instance and another method for setting credentials. 
I also fixed a typo in the original example. Switching from `axiosInstance.defaults.headers` -> ` axiosInstance.defaults.headers.common`.
One possible issue is that the example interceptor code is synchronous and Axios has some special docs about this. I was unable to get their example working though. See [here](https://github.com/axios/axios#interceptors) for more information.
I also  think it could be useful to provide an example for something that is _not_ Bearer style authorization. I'm not sure what the next most common authorization format would be -- but if a …

Updated docs regarding setting Authorization Credentials

---

packages/core/src/definitions/table/index.spec.ts
packages/core/src/definitions/table/index.ts
packages/core/src/hooks/useTable/index.ts

[Link to UPDATE-UNION-FILTERS-PARAMS](https://update--client.refine.pankod.com)
[Link to UPDATE-UNION-FILTERS-PARAMS](https://update--refine.pankod.com)

Remove unnecessary 'prevFilters' param on 'unionFilters' function

---

packages/core/src/hooks/show/useShow.spec.tsx
packages/core/src/hooks/show/useShow.ts

[Link to USE-SHOW-HOOK-HANDLE-ID](https://use-sho-refine.pankod.com)
`useShow` hook was getting wrong "id" during initialize when route and resource are different
- #1701

Fix useShow id handle

---

documentation/docs/core/hooks/import-export/useExport.md
packages/core/src/hooks/export/index.spec.ts
packages/core/src/hooks/export/index.ts

[Link to HANDLE-ERROR-USE-EXPORT](https://handle--refine.pankod.com)
If there was an error in `getList` while using the useExport hook, the user would not be aware of it and the loading state would stay `true` forever
- #1716

[Bug] handle error state on useExport hook

---

packages/core/src/hooks/form/useForm.ts

[Link to USE-FORM-REFACTOR](https://use-for-refine.pankod.com)
If mutation mode equals to `pessimistic`, form mutation will wait before resolved. In other mutation modes the mutation instantly resolve without waiting.

resolve useForm mutation according to mutation mode

---

packages/react-hook-form/package.json
packages/react-hook-form/src/index.ts
packages/react-hook-form/src/useForm/index.ts
packages/react-hook-form/src/useModalForm/index.spec.ts
packages/react-hook-form/src/useModalForm/index.ts

[Link to HEADLESS-USE-MODAL-FORM](https://headles-client.refine.pankod.com)
[Link to HEADLESS-USE-MODAL-FORM](https://headles-refine.pankod.com)

create useModalForm hook for headless usage with react-hook-form 

---

packages/react-hook-form/src/useForm/index.ts

[Link to HANDLE-SET-WARN-WHEN-REACT-HOOK-FORM](https://handle--refine.pankod.com)
When using the `@pankod/refine-react-hook-form`, `setWarnWhen` was not marked as `false` during `onSubmit`. If the user would not `create` or `edit` with the form (eg login page), `setWarnWhen` would stay `true`.

[Bug] Fix setWarnWhen on @pankod/refine-react-hook-form

---

packages/react-router-v6/src/index.ts
packages/react-router-v6/src/routerComponent.tsx

[Link to REACT-ROUTER-V6-HASH-ROUTER-SUPPORT](https://react-r-refine.pankod.com)
Added hash router support for react-router v6

Add hash router support for react-router-v6

---

documentation/docs/core/interfaces.md
documentation/docs/ui-frameworks/antd/components/filter-dropdown.md
documentation/docs/ui-frameworks/antd/hooks/table/useTable.md
examples/base/src/pages/posts/list.tsx
examples/dataProvider/hasura/src/pages/posts/list.tsx
examples/dataProvider/multiple/src/pages/posts/list.tsx
examples/dataProvider/nhost/src/pages/posts/list.tsx
examples/dataProvider/strapi/src/pages/posts/list.tsx
examples/fineFoods/admin/src/pages/orders/list.tsx
examples/fineFoods/admin/src/pages/products/list.tsx
examples/multi-level-menu/src/pages/posts/list.tsx
examples/table/useTable/src/pages/posts/list.tsx
examples/vite/src/pages/posts/list.tsx
packages/antd/src/definitions/table/index.ts
packages/core/src/contexts/data/IDataContext.ts
packages/core/src/definitions/table/index.spec.ts
packages/core/src/definitions/table/index.ts
packages/core/src/index.tsx

[Link to REFACTOR-GET-DEFAULT-FILTER-AND-SORTER](https://refacto-refine.pankod.com)
We also needed the getDefaultFilter and getDefaultSorter helper functions in the "@pankod/refine-mui" package. We moved these two functions from `@pankod/refine-antd` package to `@pankod/refine-core`. We also marked it as deprecated in the `@pankod/refine-antd` package but this does not cause a Breaking Change 🎉

[Improvement] Move getDefaultFilter and getDefaultSorter to core package

---

documentation/docs/packages/react-hook-form.md
packages/react-hook-form/src/useForm/index.ts
packages/react-hook-form/src/useModalForm/index.ts

[Link to ADD-REACT-HOOK-FORM-SAVE-BUTTON-PROPS](https://add-rea-refine.pankod.com)
While doing the `@pankod/refine-mui package`, We noticed that the `@pankod/refine-react-hook-form` package does not provide `saveButtonProps` to make it easy to use with `CRUD` components. We thought it would be easier to use if it provided this. 🎉

Add  saveButtonProps for @pankod/refine-react-hook-form

---

packages/core/src/hooks/useTable/index.ts

[Link to USE-TABLE-SYNC-WITH-LOCATION-BUG](https://use-tab-refine.pankod.com)
[Link to USE-TABLE-SYNC-WITH-LOCATION-BUG](https://use-tab-client.refine.pankod.com)
[Link to USE-TABLE-SYNC-WITH-LOCATION-BUG](https://use-tab-refine.pankod.com)
In the `useTable` hook `sycnWithLocation` was not watching the URL changes. As a result, the values followed by the URL, such as pagination, were not reset to initial values when the same resource was selected from the Sider. The `useTable` hook now watches the URL and the filters can be reset.
- #1810

[Bug] Fix syncWithLocation reset issue on useTable hook

---

packages/antd/src/hooks/form/useDrawerForm/useDrawerForm.ts
packages/antd/src/hooks/form/useModalForm/useModalForm.ts
packages/antd/src/hooks/form/useStepsForm/useStepsForm.ts

[Link to ANTD-FORM-INITIAL-VALUES](https://antd-fo-refine.pankod.com)
`initalValues` is always empty in Ant Design forms (useModalForm, useStepsForm and useDrawerForm).
- #1826 
- #1826

[Bug] Fix Antd form initialValues issue on useDrawerForm, useModalForm

---

packages/core/src/hooks/useTable/index.ts

Follow-up to #1710. 
This makes sure that hotlinking will work even if `syncWithLocation` is not used.

Parse query string even without syncWithLocation

---

.changeset/fluffy-dolphins-tell.md
packages/antd/src/hooks/table/useTable/useTable.ts

Fix #1858 `useTable` creating nested `<a>` tag in `Pagination` component. 
@rassie, if you have time could you review it? Thank you!
- #1858

fix(useTable): useTable creating nested <a> tag in Pagination component

---

.changeset/polite-impalas-attack.md
examples/fineFoods/admin/mui/src/pages/users/list.tsx
packages/mui/src/components/buttons/clone/index.tsx
packages/mui/src/components/buttons/create/index.tsx
packages/mui/src/components/buttons/delete/index.tsx
packages/mui/src/components/buttons/edit/index.tsx
packages/mui/src/components/buttons/export/index.tsx
packages/mui/src/components/buttons/import/index.tsx
packages/mui/src/components/buttons/list/index.tsx
packages/mui/src/components/buttons/refresh/index.tsx
packages/mui/src/components/buttons/save/index.tsx
packages/mui/src/components/buttons/show/index.tsx
packages/mui/src/components/fields/date/index.tsx
packages/mui/src/components/fields/text/index.tsx

In this PR, We have been passed svgIconProps to all buttons that served from @pankod/refine-mui.

refactor(buttons): svgIconProps passed to buttons

---

.changeset/young-bags-knock.md
examples/base/mui/src/App.tsx
packages/mui/src/components/pages/error/index.tsx

In this PR, I fixed the `<ErrorComponent/>` to be responsive to mobile screens.

fix: mui error component responsive style

---

packages/core/src/hooks/breadcrumb/index.ts

The `useBreadcrumb` hook was throwing an error if the resource was undefined (eg next.js custom route).

fix: if the resource is undefined useBreadcrumb throws error

---

.changeset/orange-islands-leave.md
examples/fineFoods/admin/mui/src/App.tsx
packages/mui/src/providers/notificationProvider/index.spec.tsx
packages/mui/src/providers/notificationProvider/index.tsx

Renamed `notificationProviderHandle` in `@pankod/refine-mui` to `notificationProvider` for consistency across packages.

refactor: rename mui notification provider

---

examples/base/mui/src/pages/useModalForm/list.tsx
examples/base/mui/src/pages/useStepsForm/list.tsx
examples/baseHeadless/src/pages/posts/list.tsx
examples/blog/win95/src/pages/posts/list.tsx
examples/field/useSelect/mui/src/pages/posts/list.tsx
examples/fineFoods/admin/mui/src/pages/categories/list.tsx
examples/fineFoods/admin/mui/src/pages/couriers/list.tsx
examples/fineFoods/admin/mui/src/pages/couriers/show.tsx
examples/fineFoods/client/pages/[id]/[category]/index.tsx
examples/reactTable/advanced/src/pages/posts/list.tsx
examples/reactToastify/src/pages/posts/list.tsx
examples/table/mui/advancedTable/src/pages/table/list.tsx
examples/tutorial/headless/src/pages/posts/list.tsx

In most cases, we ignored eslint's `react/display-name` rule. We've updated our examples to respect this rule

fix: eslint react/display-name issue on examples

---

.changeset/red-chefs-remain.md
examples/field/useSelect/mui/src/pages/posts/list.tsx
examples/fineFoods/admin/mui/src/pages/orders/list.tsx
examples/fineFoods/admin/mui/src/pages/users/list.tsx
packages/mui/src/components/buttons/clone/index.tsx
packages/mui/src/components/buttons/create/index.tsx
packages/mui/src/components/buttons/delete/index.tsx
packages/mui/src/components/buttons/edit/index.tsx
packages/mui/src/components/buttons/export/index.tsx
packages/mui/src/components/buttons/import/index.tsx
packages/mui/src/components/buttons/list/index.tsx
packages/mui/src/components/buttons/refresh/index.tsx
packages/mui/src/components/buttons/save/index.tsx
packages/mui/src/components/buttons/show/index.tsx

Add default `sx` property for Material UI buttons.
```tsx
const { sx, ...restProps } = rest;
<Button sx={{ minWidth: 0, ...sx }} {...restProps} />;
```

Add default `sx` property for Material UI buttons

---

.changeset/mean-colts-check.md
packages/mui/src/components/pages/error/index.tsx
packages/react-location/src/resourceComponent.tsx
packages/react-router-v6/src/routeProvider.tsx

In this PR, fixed the cathing no resource error in `@pankod/refine-react-router-v6`

fix: react router v6 catch no resource error 

---

.changeset/old-pumpkins-attack.md
examples/dataProvider/nhost/package.json
packages/graphql/package.json
packages/hasura/package.json
packages/nhost/package.json
packages/strapi-graphql/package.json

The `graphql-request` package was not added as a `peerDependency` in the packages `@pankod/refine-graphql`, `@pankod/refine-hasura` and `@pankod/refine-strapi-graphql`. This was causing issue #1929 .
- #1929

fix: add graphql-request dependency to peerDependencies

---

documentation/docs/ui-frameworks/mui/tutorial.md
examples/fineFoods/admin/mui/src/App.tsx
examples/form/mui/useDrawerForm/src/App.tsx
examples/form/mui/useModalForm/src/App.tsx
examples/form/mui/useStepsForm/src/App.tsx
examples/tutorial/mui/src/App.tsx

Fix `<CssBaseline>` import order for Material UI examples and docs

fix: update <CssBaseline> component import order

---

.changeset/nice-rice-flow.md
packages/antd/src/components/buttons/clone/index.tsx
packages/antd/src/components/buttons/create/index.tsx
packages/antd/src/components/buttons/edit/index.tsx
packages/antd/src/components/buttons/list/index.tsx
packages/antd/src/components/buttons/show/index.tsx
packages/mui/src/components/buttons/clone/index.tsx
packages/mui/src/components/buttons/create/index.tsx
packages/mui/src/components/buttons/edit/index.tsx
packages/mui/src/components/buttons/list/index.tsx
packages/mui/src/components/buttons/show/index.tsx

Could not stop `e.preventDefault()` redirection in Next.js `<Link>` component. So we added in `e.stopPropagation()` for [Ant Design Buttons](https://refine.dev/docs/ui-frameworks/antd/components/buttons/clone-button/) and [Material UI Buttons](https://refine.dev/docs/ui-frameworks/mui/components/buttons/clone-button/)
- #1944

fix: stop event bubbling for Link component on buttons

---

.changeset/gorgeous-yaks-dream.md
examples/blog/ecommerce/package.json
examples/fineFoods/client/package.json
examples/i18n/nextjs/package.json
examples/refine-next/package.json
examples/refine-next/src/components/posts/list.tsx
packages/antd/src/components/buttons/clone/index.tsx
packages/antd/src/components/buttons/create/index.tsx
packages/antd/src/components/buttons/edit/index.tsx
packages/antd/src/components/buttons/list/index.tsx
packages/antd/src/components/buttons/show/index.tsx
packages/mui/src/components/buttons/clone/index.tsx
packages/mui/src/components/buttons/create/index.tsx
packages/mui/src/components/buttons/edit/index.tsx
packages/mui/src/components/buttons/list/index.tsx
packages/mui/src/components/buttons/show/index.tsx
packages/nextjs-router/package.json

We are upgrading our Next.js version and reverting the no longer required PR #1945

fix: revert "stop event bubbling for Link component on buttons"

---

.changeset/old-rules-switch.md
packages/strapi-v4/src/dataProvider.ts
packages/strapi-v4/test/dataProvider/index.mock.ts
packages/strapi-v4/test/dataProvider/index.spec.ts

Added `populate`, `fields`, `locale` and `publicationState` support for `@pankod/refine-strapi-v4` data provider's `getMany` function
- #1956

fix: add populate support for strapi-v4 data provider

---

documentation/docs/packages/react-hook-form/useForm.md
documentation/docs/packages/react-hook-form/useModalForm.md
documentation/docs/packages/react-hook-form/useStepsForm.md

Fix broken codesandbox links in react hook form package documentation. Close #1960

docs: fix broken codesandbox links

---

examples/fineFoods/admin/mui/src/components/header/index.tsx

Centering language select on `<Header>` component in Material UI Fine Foods example.

fix(mui-fine-foods): centering language select on the header

---

.changeset/stupid-toes-hear.md
packages/mui/src/components/crud/create/index.tsx
packages/mui/src/components/crud/edit/index.tsx
packages/mui/src/components/crud/list/__snapshots__/index.spec.tsx.snap
packages/mui/src/components/crud/list/index.tsx
packages/mui/src/components/crud/show/index.tsx

In this PR, We have fixed the spacing of `<CardHeader>` actions and `<CardAction>` components in crud components.

style(crud): spacing fix at the crud components 

---

.changeset/sweet-tigers-pay.md
documentation/docs/guides-and-concepts/multi-tenancy/appwrite.md
documentation/docs/guides-and-concepts/multi-tenancy/strapi.md
documentation/docs/guides-and-concepts/real-time.md
documentation/docs/ui-frameworks/antd/customization/sider.md
examples/ably/src/components/sider/index.tsx
examples/customization/customSider/src/components/sider/index.tsx
examples/customization/offLayoutArea/src/components/sider/index.tsx
examples/multi-tenancy/appwrite/src/components/sider/index.tsx
examples/multi-tenancy/strapi/src/components/sider/index.tsx
packages/antd/src/components/layout/sider/index.tsx
packages/antd/src/hooks/useMenu/index.tsx
packages/core/src/hooks/menu/useMenu.spec.ts
packages/core/test/index.tsx

While updating `useMenu` tests, I've noticed that `<Sider/>` in `@pankod/refine-antd` uses the same key for all items and resulting in opening all menus at once initially.

test: update `useMenu` tests

---

packages/mui/src/components/layout/header/index.tsx
packages/mui/src/components/layout/index.tsx

In this PR, We have created the header component in the layout. If the user identifications are defined ( user name, avatar ) that we reached from   `useGetIdentity()`, the header component is rendered with the username and avatar by default.

feat(header): default header component and state of render in layout

---

documentation/docs/ui-frameworks/mui/tutorial.md

In this PR, We have updated the `tutorial` document that was created for Material UI with information about the `react-hook-form`.

docs(tutorial): tutorial updated with react-hook-form info

---

.changeset/sweet-wolves-act.md
documentation/docs/ui-frameworks/mui/customization/sider.md
packages/mui/src/components/layout/sider/index.tsx

Dashboard icon changed from `<ListOutlined>` to `<Dashboard>` in `<Sider>` for **Material UI** package

Mui sider dashboard icon

---

.changeset/smart-horses-cheer.md
documentation/docs/core/providers/router-provider.md
packages/nextjs-router/src/index.ts
packages/nextjs-router/src/routerProvider.ts

Added `legacyBehavior: false` to `defaultProps` to `<Link/>` component in `@pankod/refine-nextjs-router`

feat: new link behavior in nextjs router

---

.changeset/funny-onions-itch.md
packages/core/src/components/pages/login/index.tsx
packages/mui/src/components/pages/login/index.tsx

In this PR, We have updated text of login pages in Material UI and Headless.

refactor(default-login-pages): updating texts with translations

---

.changeset/calm-sloths-pretend.md
packages/core/src/hooks/breadcrumb/index.ts

add translate support to [`useBreadcrumb`](https://refine.dev/docs/core/hooks/useBreadcrumb/)

feat(core): add translate support to useBreadcrumb

---

.changeset/metal-hotels-tap.md
examples/tutorial/mui/src/pages/posts/list.tsx
packages/mui/src/components/buttons/delete/index.tsx
packages/mui/src/components/crud/edit/index.tsx

In this PR, We fixed the delete button component default variant and the variant of the delete button in the action buttons of the edit crud component.

refactor(buttons-variant): fix the variant of delete button

---

examples/fineFoods/admin/mui/src/components/product/categoryFilter.tsx
examples/fineFoods/admin/mui/src/pages/products/list.tsx
examples/fineFoods/admin/mui/src/pages/stores/create.tsx
examples/fineFoods/admin/mui/src/pages/stores/edit.tsx

- add`<InputMask>` for gsm input on store create/edit 
- products filters default values from syncWithLocation

Fix: Material UI fine foods products page default filter values

---

documentation/docs/ui-frameworks/mui/customization/sider.md
documentation/redirects.json
documentation/sidebars.js

- Added `useMenu` redirect from `antd > hooks` to `core > hooks`
- Fixed wrong url in `material ui > customization > sider`

docs: use menu redirects

---

.changeset/friendly-feet-play.md
documentation/docs/ui-frameworks/antd/components/filter-dropdown.md
documentation/docs/ui-frameworks/antd/hooks/table/useEditableTable.md
documentation/docs/ui-frameworks/antd/hooks/table/useTable.md
packages/antd/src/hooks/table/useEditableTable/useEditableTable.ts

I updated the `id` type to `BaseKey` for `isEditing` and `editButtonProps` properties in `useEditableTable` hook

fix: useEditableTable id type

---

.changeset/dry-weeks-trade.md
packages/mui/package.json
packages/mui/src/index.tsx

Updated missing exports from `@mui/material/styles` and replaced one deprecated one `ThemeInput` in `@pankod/refine-mui`

fix: material UI exported types

---

.changeset/serious-papayas-share.md
documentation/docs/core/hooks/useBreadcrumb.md
documentation/docs/core/providers/i18n-provider.md
examples/fineFoods/admin/antd/public/locales/de.json
examples/fineFoods/admin/antd/public/locales/en.json
examples/fineFoods/admin/mui/public/locales/de.json
examples/fineFoods/admin/mui/public/locales/en.json
examples/i18n/nextjs/public/locales/en/common.json
examples/i18n/react/public/locales/de/common.json
examples/i18n/react/public/locales/en/common.json
packages/core/src/hooks/breadcrumb/index.ts

Add translate support for `CRUD` components (`<List>`, `<Create>`, `<Edit>`, `<Show>`) actions in [`useBreadcrumb`](https://refine.dev/docs/core/hooks/useBreadcrumb/) hook.

feat: add breadcrumb actions translate support

---

.changeset/lemon-moose-matter.md
examples/dataProvider/supabase/src/pages/posts/list.tsx
packages/supabase/src/index.ts
packages/supabase/test/getList/index.spec.ts

In this PR, Add `foreignTable` propery to the **supabase** order statement to access relational data. For more information, you can check the 🔗[documentation](https://supabase.com/docs/reference/javascript/order).

feat(supabase-dataProvider): add relational order for getList hook

---

documentation/docs/getting-started/overview.md
documentation/docs/ui-frameworks/antd/tutorial.md

The missing `value` argument type on `createdAt` column was throwing a typeError during compiling phase. So I added proper type to doc example.
In addition, selecting the UI Framework option as an `Ant Design` during the CLI creation phase needed to be mentioned in the doc since the overview example uses the Ant Design feature.

docs(getting-started): add overview example missing type and CLI option information

---

.changeset/nine-chefs-camp.md
packages/core/src/hooks/breadcrumb/index.ts

`useBreadcrumb` hook throws `console.warn` even if `i18nProvider` is not used
- #2103

fix: console.warn even if i18n provider is not used

---

.changeset/hot-apples-complain.md
packages/antd/src/components/crud/edit/index.tsx
packages/antd/src/components/crud/show/index.tsx
packages/mui/src/components/crud/edit/index.tsx
packages/mui/src/components/crud/show/index.tsx

Added `dataProviderName` for `<RefreshButton>` and `<DeleteButton>` in `<Edit>` and `<Show>` CRUD components
- #2096

fix: add dataProviderName support for edit and show crud components

---

.changeset/clever-tomatoes-shake.md
.gitignore
packages/antd/src/hooks/useFileUploadState/index.ts

Updated `useFileUploadState` in `@pankod/refine-antd` to fix #2134. [antd@4.21.6](https://github.com/ant-design/ant-design/tree/4.21.6) updates the type `UploadFileStatus` and removes `removed` from the union which breaks the `@pankod/refine-antd` because of the unused cases in the switch block.

fix: `antd` type error for `useFileUploadState`

---

.github/pull_request_template.md

Updated PR Template with a simple checklist to make sure we don't skip any steps before merge.

chore: add PR checklist to PR template

---

documentation/docs/guides-and-concepts/access-control.md
examples/accessControl/casbin/package.json
examples/accessControl/casbin/src/App.tsx
examples/accessControl/casbin/src/accessControl.ts

Update casbin example with up to date casbin package. Used [`node-casbin`](https://github.com/casbin/node-casbin) instead of [`casbin.js`](https://github.com/casbin/casbin.js).
> **Note**
> `casbin` packages doesn't support react-script 5 so we downgraded react-script for this example.
closes #2140

fix: update casbin example

---

.changeset/rare-ghosts-invite.md
packages/antd/src/hooks/form/useForm.ts

Fixed the `Unhandled Promise` error on console for `useForm` with failed requests (Resolves #2156).
This fix only catches the errors triggered by submitting the form, requests by invoking `onFinish` function should be handled by the user.
Tests are unaffected.
closes #2156 

fix: `unhandled promise` in `@pankod/refine-antd#useForm`

---

.changeset/eighty-zoos-lie.md
packages/hasura/src/dataProvider/index.ts

Support adding multiple filters on fields in a graphql query:
```
{
"where": {
"createdAt": {
"lte": "2022-07-20T05:20:00Z"
"gte": "2022-07-20T00:00:00Z"
}
}
}  
```
```
@pankod/refine-hasura: Test Suites: 10 passed, 10 total
@pankod/refine-hasura: Tests:       18 passed, 18 total
@pankod/refine-hasura: Snapshots:   0 total
@pankod/refine-hasura: Time:        22.228 s, estimated 24 s
@pankod/refine-hasura: Ran all test suites.
```
-   [x] Changesets are provided or not …

fix: #2154 support combination filters on graphql fields

---

.changeset/kind-falcons-move.md
packages/nhost/src/dataProvider/index.ts

When using multiple filter with a same field name, it is not apply both of them it is only accept the latest. This PR fix the issue.

fix(nhost): same field name filters not working with together

---

.changeset/poor-coats-sleep.md
packages/core/src/hooks/form/useForm.ts

Fix redirection after submit in `useForm`. Both `edit` and `create` will redirect to `list` (it was `edit` previously)
Tests are not affected
Resolves #2123

fix: `useForm` redirecting to wrong url

---

.changeset/neat-badgers-exist.md
.changeset/shiny-crews-flow.md
.changeset/ten-feet-end.md
packages/antd-audit-log/package.json
packages/demo-sidebar/package.json
packages/kbar/package.json

In this PR, Fixed `react` and `react-dom` dependency versions.
- "@pankod/refine-demo-sidebar"
- "@pankod/refine-kbar"
```diff
- "react-dom": "^17.0.4"
+ "react-dom": "^17.0.0 || ^18.0.0"
```
- "@pankod/refine-antd-audit-log"
```diff
- "react": "^17.0.2",
- "react-dom": "^17.0.4"
+ "react": "^17.0.0 || ^18.0.0",
+ "react-dom": "^17.0.0 || ^18.0.0"
```

Fix react-dom dependency version

---

.changeset/beige-numbers-wash.md
documentation/docs/core/interfaces.md
packages/core/src/hooks/data/useCreate.ts
packages/core/src/hooks/data/useCreateMany.ts
packages/core/src/hooks/data/useCustom.ts
packages/core/src/hooks/data/useDelete.ts
packages/core/src/hooks/data/useDeleteMany.ts
packages/core/src/hooks/data/useList.ts
packages/core/src/hooks/data/useMany.ts
packages/core/src/hooks/data/useOne.ts
packages/core/src/hooks/data/useUpdate.ts
packages/core/src/hooks/data/useUpdateMany.ts
packages/core/src/interfaces/successErrorNotification.ts

Update notification props in data hooks of `@pankod/refine-core` to cover dynamic notifications.
Now users will be able to show notifications according to the API response by assigning a function which returns `OpenNotificationParams` instead of an `OpenNotificationParams` object.
```tsx
{
const { mutate } = useCreate({
/* ... */
successNotification: (data, values, resource) => ({
message: data?.message ?? "Success!",
type: "success",
description: data?.description;
}),
errorNotification: (error, values, resource) => ({
message: error?.message ?? error?.code ?? "Error!",
type: "error",
description: error?.reason;
})
/* ... */
});
}
```
Resolves #2131 - Rest of this issue is going to be marked as not planned to encourage error handling on data providers.
Please …

feat: success/error notifications by API response

---

documentation/docs/core/tutorial.md

Fixed the filename typo in the **Tutorial** of `@pankod/refine-core`
Resolves #2192

docs(headless): fix filename type on tutorial

---

.changeset/breezy-teachers-smile.md
packages/antd/src/hooks/modal/useModal/index.tsx

fix: useModal hook doesn't return "modalProps"

---

.changeset/nasty-grapes-reflect.md
packages/ably/package.json
packages/airtable/package.json
packages/altogic/package.json
packages/antd/package.json
packages/appwrite/package.json
packages/cloud/package.json
packages/demo-sidebar/package.json
packages/graphql/package.json
packages/hasura/package.json
packages/kbar/package.json
packages/mui/package.json
packages/nestjsx-crud/package.json
packages/nextjs-router/package.json
packages/nhost/package.json
packages/react-hook-form/package.json
packages/react-location/package.json
packages/react-router-v6/package.json
packages/react-table/package.json
packages/simple-rest/package.json
packages/strapi-graphql/package.json
packages/strapi-v4/package.json
packages/strapi/package.json
packages/supabase/package.json

All of the refine packages have dependencies on the `@pankod/refine-core` package. So far we have managed these dependencies with `peerDependencies` + `dependencies` but this causes issues like #2183. (having more than one @pankod/refine-core version in node_modules and creating different instances)
Managing as `peerDependencies` + `devDependencies` seems like the best way for now to avoid such issues.
- #2183
-   [x] Tests are …

fix: internal packages dependencies

---

.changeset/serious-terms-fetch.md
documentation/docs/core/hooks/data/useCustomMutation.md
packages/core/src/hooks/data/useCustomMutation.ts

Added `config` parameter to `useCustomMutationHook` to send headers.

feat(customMutationHook): add config param

---

.changeset/large-kids-greet.md
packages/core/src/contexts/auth/index.tsx

Fixed invalidation of authentication caches every time `checkAuth` is run.
- #2272 

Fix: Invalidation of authentication caches every time `checkAuth` is run

---

.changeset/early-penguins-cheer.md
packages/core/src/components/containers/refine/index.tsx
packages/core/src/hooks/deepMemo/index.spec.tsx
packages/core/src/hooks/deepMemo/index.tsx
packages/core/src/hooks/memoized/index.spec.tsx
packages/core/src/hooks/memoized/index.tsx

Updated `<Refine/>` component in `refine-core` package with memoized props to avoid re-renders and unnecessary calculations/transforms.
Fixed: In `next.js` projects, `react-query`'s cache was being reset on every route changes and causing it to reload all previous data.
Added two internal hooks to achieve better memoizations (`useMemoized` and `useDeepMemo`)

refactor: missing memoizations in `refine-core`

---

.changeset/angry-rabbits-speak.md
packages/core/src/hooks/accessControl/useCan/index.ts

Fix **useCan** hook params keys. Related issue is #2232

fix(core): remove icon from useCan hook params

---

.changeset/brave-fireants-grow.md
documentation/docs/packages/react-hook-form/useForm.md
documentation/docs/packages/react-hook-form/useModalForm.md
packages/react-hook-form/src/useForm/index.ts
packages/react-hook-form/src/useModalForm/index.ts

Fixed: 'handleSubmit' triggering instantly when hook init
-

fix: 'handleSubmit' triggering instantly when hook init on react-hook-form package

---

.changeset/sweet-boxes-wave.md
documentation/docs/core/interfaces.md
packages/core/src/hooks/data/useCustom.ts
packages/core/src/hooks/data/useList.ts
packages/core/src/hooks/data/useMany.ts
packages/core/src/hooks/data/useOne.ts
packages/core/src/hooks/useSelect/index.spec.ts
packages/core/src/interfaces/metaData/metaDataQuery.ts

Added [QueryFunctionContext](https://tanstack.com/query/v4/docs/guides/query-functions#queryfunctioncontext)'s values to queryContext in metaData.
All test are passed.
-

feat: add query context function params to `metaData`

---

.changeset/flat-scissors-own.md
packages/react-hook-form/src/useForm/index.ts

Added type checking to fix fields reset bug

fix: useForm fields reset bug

---

.changeset/cold-cougars-marry.md
packages/mui/package.json

Updated `peerDependencies` in `@pankod/refine-mui#package.json` to support React 17.

fix: add missing react 17 versions to peer depps

---

examples/web3/ethereumLogin/package.json

I downgraded to react-scripts@4 because the `web3` package doesn't support WebPack5
- #2309 

fix: downgrade react-scripts 5 to 4 for web 3 example

---

.changeset/long-lobsters-cough.md
documentation/docs/core/components/refine-config.md
packages/core/src/components/containers/refine/index.tsx

Updated `reactQueryDevtoolConfig` prop type and added `false` option to disable the React Query Devtools.

feat(core): disable react query devtools

---

.changeset/brave-carpets-work.md
packages/core/src/hooks/accessControl/useCan/index.ts

Fixed react-query devtools was consuming high CPU when AccessControlProvider was not used
Original Discord message: https://discord.com/channels/837692625737613362/906206669787234334/1009922875114917960

fix: react-query devtools was consuming high CPU 

---

documentation/docs/ui-frameworks/mui/tutorial.md

Fix wrong use of `React.useMemo` in documentation.
Tests are not affected
closes #2339

docs: fix mui tutorial

---

.changeset/honest-cheetahs-study.md
packages/antd/src/components/crud/edit/index.tsx

Added `<Space>` wrapper to `Crud#Edit#footerButtons` component in `@pankod/refine-antd` which was there before the refactoring changes and missed during the refactor and this leads to broken styles in the footer buttons.

fix: wrap default footer buttons to `<Space>`

---

.changeset/few-dragons-swim.md
packages/core/src/definitions/helpers/redirectPage/index.spec.ts
packages/core/src/definitions/helpers/redirectPage/index.ts

when redirect prop is **false** on **useForm**, **redirectPage()** function returns **list** because of **falsy** value.
**False** test case added.
closes #2378

fix(core): return given props if redirect false

---

packages/antd/tsup.config.ts
packages/mui/tsup.config.ts

Since we're using test ids to handle the UI components in the tests (Unified for both UI framework integrations) we're not removing those in the build phase. Added a custom `esbuild` plugin to remove `data-testid` properties from the `*.js` outputs of `refine-antd` and `refine-mui` packages.
Not sure If we should update the versions by adding a changeset or should we wait until the next release to see the plugin in action 🤔 
💡 We can also consider releasing this plugin as an external package for `esbuild`
Tests are not affected from the build script. …

build: update `tsup` config and remove `data-testid` properties

---

.changeset/happy-hornets-pump.md
documentation/docs/core/components/refine-config.md
documentation/docs/core/hooks/resource/useResource.md
documentation/docs/core/hooks/ui/useMenu.md
packages/core/src/contexts/resource/IResourceContext.ts
packages/core/src/definitions/helpers/treeView/createTreeView/index.ts
packages/core/src/hooks/menu/useMenu.spec.tsx
packages/core/src/hooks/menu/useMenu.tsx

Add an option to hide `resources` from the `Sider` menu
- #2388 

feat: add an option to hide `resources` from the `Sider` menu

---

.changeset/calm-garlics-rush.md
packages/antd/src/components/layout/sider/index.tsx
packages/mui/src/components/layout/sider/index.tsx

Since parent menu items were not wrapped with `<CanAccess />`, they could not be controlled by the `accessControl Provider`.
Usage:
```tsx
<Refine
accessControlProvider={{
can: async ({ action, resource }) => {
// console.log({ action, resource });
// output: {action: "list", resource: "cms" } 
return { can: true };
},
}}
resources={[
{
name: "CMS",
},
{
name: "posts",
parentName: "CMS",
list: PostList,
},
]}
/>
```
-   [x] Tests are …

fix: wrap with CanAccess component to parent sider items

---

.changeset/rich-points-explode.md
packages/antd/src/hooks/form/useStepsForm/useStepsForm.ts

useStepsForm's submit function must be overridable
- #2407

fix: cannot override useStepsForm's submit function

---

.changeset/slow-actors-marry.md
packages/core/src/hooks/useTable/index.ts

fix: syncWithLocation not tracking when useTable filters were reset

---

.changeset/stale-dolls-play.md
packages/core/package.json
packages/core/src/definitions/helpers/humanizeString/index.spec.tsx
packages/core/src/definitions/helpers/humanizeString/index.ts

Remove `decamelize` dependency from `humanizeString` helper and replace the functionality with regExp.

refactor: remove `decamelize`

---

.changeset/young-monkeys-film.md
packages/core/src/hooks/import/index.tsx

`dataProviderName` as defined as a property but it was not passed to `create` and `createMany` mutations in the `useImport` hook.
Closes #2449 

fix: pass `dataProviderName` in `useImport`

---

.changeset/fast-rocks-fly.md
.changeset/silver-coins-accept.md
packages/antd/src/definitions/table/index.spec.ts
packages/antd/src/definitions/table/index.ts
packages/hasura/src/dataProvider/index.ts
packages/nhost/src/dataProvider/index.ts

I've split on commas here in order to directly support the `dataIndex` array in table columns. It seems to work for me.
This is related to Issue 2426 [https://github.com/pankod/refine/issues/2426](url) adding the ability to sort based on nested fields used in array type dataIndex values in table columns
This would require creating a list view with nested data as shown in the feature request and adding a sorter …

feat: Issue #2426 Add nesting sorting

---

.changeset/metal-needles-impress.md
packages/core/src/hooks/form/useForm.spec.tsx
packages/core/src/hooks/form/useForm.ts
packages/core/src/hooks/show/useShow.spec.tsx
packages/core/src/hooks/show/useShow.ts

`id` prop was set to a state at the initial render therefore it was not reflecting the future changes. In cases like dynamic or asynchronous `id` operations, `useShow` and `useForm` was failing to update the query by the new `id` property.
Resolves #2463 

fix: check and reflect for `id` from props changes

---

.changeset/dull-cobras-relax.md
packages/core/src/definitions/helpers/handleRefineOptions/index.ts

Fix import of react-query `DevtoolsOptions` interface

fix: react-query DevtoolsOptions import

---

.changeset/curly-mice-kick.md
.changeset/kind-planets-knock.md
.changeset/nasty-oranges-sell.md
.changeset/nine-boxes-joke.md
packages/antd/src/components/layout/sider/index.tsx
packages/mui/src/components/layout/sider/index.tsx
packages/ui-tests/src/tests/layout/sider.tsx
packages/ui-types/src/types/layout.tsx

`@pankod/refine-antd` `@pankod/refine-mui`
Added `render` prop to `Sider` component. You can get `dashboard`, `logout` and `items` from `render` props to customize the `Sider` component.
`@pankod/refine-ui-types`
Updated `Sider` types for `render` props.
`@pankod/refine-ui-tests`
Updated `Sider` test for `render` props.
closes #2453

feat: added render prop to Sider components

---

.changeset/nasty-points-breathe.md
.changeset/nervous-meals-clap.md
.changeset/nice-meals-grab.md
packages/antd/src/components/layout/sider/index.tsx
packages/mui/src/components/layout/sider/index.tsx
packages/ui-types/src/types/layout.tsx

**@pankod/refine-ui-types**
Updated `render` method type with `collapsed` prop in `RefineLayoutSiderProps`.
**@pankod/refine-mui**
Passed `collapsed` prop to `render` method in `Sider` component.
**@pankod/refine-antd**
Passed `collapsed` prop to `render` method in `Sider` component
There is no corresponding issue.

fix: collapsed prop passed to render method of Sider components

---

.changeset/brave-melons-push.md
documentation/docs/guides-and-concepts/data-provider/strapi-v4.md
documentation/docs/guides-and-concepts/multi-tenancy/strapi.md
examples/dataProvider/strapi-v4/src/App.tsx
packages/mantine/package.json
packages/mui/package.json
packages/strapi-v4/src/dataProvider.ts
packages/strapi-v4/src/helpers/auth.ts
packages/strapi-v4/test/auth/index.mock.ts

If you have relations on your user-permissions or media files, you need to populate. Here is an example of query url:
https://localhost:1337/api/users/me?populate=*
I propose some changes to the AuthHelper function to allow this behaviour. 

Allows populate auth.getUserIdentity() by changing AuthHelper 

---

.changeset/heavy-flowers-lay.md
packages/antd/package.json
packages/cloud/package.json
packages/core/package.json
packages/kbar/package.json
packages/mantine/package.json
packages/mui/package.json
packages/react-hook-form/package.json
packages/react-router-v6/package.json
packages/react-table/package.json
packages/ui-tests/package.json

With react-router 6.4 we are not ready for changes yet, we are fixing the version to 6 to avoid errors until it is ready

fix: fix react-router version to 6

---

documentation/src/components/landing/section-bullets/index.tsx

Fixed landing page height issue on features section for grid container

docs(landing): fix safari grid row height issue

---

.changeset/big-guests-move.md
.changeset/big-guests-run.md
examples/fineFoods/admin/antd/src/App.tsx
examples/fineFoods/admin/antd/src/pages/auth/index.tsx
packages/antd/src/components/pages/auth/components/login/index.tsx
packages/antd/src/components/pages/auth/components/register/index.tsx
packages/antd/src/components/pages/auth/components/resetPassword/index.tsx
packages/antd/src/components/pages/auth/components/updatePassword/index.tsx
packages/antd/src/components/pages/auth/index.tsx
packages/ui-types/src/types/auth.tsx

Added `formProps` property support for AuthPage component
```tsx
<AuthPage
type="login"
formProps={{
initialValues: {
email: "demo@refine.dev",
password: "demo",
},
}}
/>
```

feat: add formProps support for AuthPage component

---

.changeset/brave-crabs-peel.md
packages/antd/src/components/breadcrumb/index.tsx

Fixed the spacing between `icon` and `breadcrumb label` in `Breadcrumb` component.

fix: breadcrumb item spacing

---

documentation/src/components/landing/section-no-constraints/index.tsx

Normally, it's 24/7, not 7/24 (ref: https://en.wikipedia.org/wiki/24/7_service)

Use more common expression for 24/7

---

.changeset/tall-garlics-fly.md
packages/antd/src/hooks/form/useModalForm/useModalForm.ts
packages/antd/src/hooks/form/useStepsForm/useStepsForm.ts
packages/antd/src/index.tsx
packages/antd/src/types/sunflower.d.ts

Fixed `useModalForm` & `useStepsForm` return type
only type fix
- #2550 

fix: useModalForm & useStepsForm return type

---

.changeset/quiet-chicken-care.md
packages/core/src/definitions/helpers/index.ts
packages/core/src/definitions/helpers/sequentialPromises/index.ts
packages/core/src/hooks/import/index.tsx
packages/core/tsconfig.json

Updated `useImport` hook API calls with sequentially resolving Promises and handled progress with resolve/reject statuses.
(Added `sequentialPromises` helper function)
Haven't had a chance to try the updated `useImport` hook in examples yet. 
#2513 

fix: `useImport` not working properly

---

.changeset/tall-bugs-boil.md
packages/core/src/components/undoableQueue/index.spec.tsx
packages/core/src/components/undoableQueue/index.tsx
packages/core/src/contexts/undoableQueue/undoableQueueContext.tsx

When updating multiple records at the same time whose mutationMode is undoable, the doMutation() method is called multiple times leading to duplicate API calls for the dataProvider.
for more details #2556 
- #2556 

fix: undoable mutation is called many times

---

documentation/docs/tutorials/core.md

Updated the `summary` field to have an explanation and wrapped with a `<strong>` to avoid people missing this section.
Resolves #2575 

docs(tutorial-headless): add explanation for `icons.ts` file

---

documentation/docs/examples/form/mantine/useDrawerForm.md
documentation/docs/examples/form/mantine/useForm.md
documentation/docs/examples/form/mantine/useModalForm.md
documentation/docs/examples/form/mantine/useStepsForm.md
documentation/docs/examples/form/mui/useDrawerForm.md
documentation/docs/examples/form/mui/useForm.md
documentation/docs/examples/form/mui/useModalForm.md
documentation/docs/examples/form/mui/useStepsForm.md
documentation/docs/examples/table/mantine/advanced.md
documentation/docs/examples/table/mantine/basic.md
documentation/docs/examples/upload/mantine/base64.md
documentation/docs/examples/upload/mantine/multipart.md
documentation/sidebars.js

Mantine examples added to documents.

docs: add Mantine examples

---

.changeset/big-clouds-burn.md
.changeset/cuddly-teachers-grin.md
packages/antd/src/components/crud/create/index.tsx
packages/antd/src/components/crud/edit/index.tsx
packages/antd/src/components/crud/show/index.tsx
packages/mui/src/components/crud/create/index.tsx
packages/mui/src/components/crud/edit/index.tsx
packages/mui/src/components/crud/show/index.tsx

Updated `disabled` attribute of buttons in CRUD components according to `isLoading` prop.

fix: update `disabled` attribute of buttons in CRUD components 

---

examples/real-world-example/src/dataProvider.ts

I updated the `deleteOne` function of dataProvider

fix: deleteOne function type issue of realworld example

---

documentation/plugins/docgen.js
documentation/plugins/docgen.ts
documentation/src/hooks/use-dynamic-import.ts
documentation/src/theme/Navbar/Logo/index.js

Added an env flag `DISABLE_DOCGEN` for disabling docgen script to run on dev mode which was slowing down the whole process. Also updated the dynamic import hook for a better catch condition

docs: perf. fixes on dev mode

---

documentation/src/components/prop-tag/index.tsx
documentation/src/components/props-table/index.tsx
documentation/src/components/tooltip/index.tsx
documentation/src/css/custom.css

1. Required prop tag changed to asterisks.
2. Deprecated label removed from prop name, description of deprecation added as a tooltip. text-decoration changed to line-through. [Example page](https://refine.dev/docs/api-reference/antd/components/basic-views/create/#props)
3. When props have no default value, column removed from <TableProps/>

feat(docs): <PropsTable/> UI improvements

---

.changeset/sixty-bikes-sit.md
packages/mui/src/components/index.tsx

This is a fix for issue #2631 which was preventing me from importing the Header component into a custom layout.

fix(material-ui): fix missing header export

---

documentation/docs/api-reference/core/hooks/useSelect.md
documentation/plugins/docgen.js
documentation/plugins/docgen.ts
documentation/src/components/props-table/index.tsx
packages/core/src/hooks/useSelect/index.ts
packages/core/src/interfaces/live/LiveModeProps.ts

1. <PropsTable/> added to useSelect doc. [Example page](https://refine.dev/docs/api-reference/core/hooks/useSelect/#properties)
2. [docusaurus](https://docusaurus.io/) don't have cache mechanicsm. because of that hot reload times are very long. To solve this problem, we wrote a function where we can filter out packages we don't need.  Kudos to @aliemir 🚀 .
Simply add the packages you need to the env. Only the ones you need will be built in the hot reload. 
`INCLUDED_PACKAGES=antd,core,ui-types npm run start:docs`
- …

feat(docs): add props table to `useSelect()` docs

---

documentation/src/theme/Navbar/Logo/index.js

Added redirect to figma assets file when users try to right click on the logo

docs: open assets on right click to header logo

---

.changeset/fuzzy-elephants-notice.md
packages/react-table/src/index.ts

`UseTableProps` and `UseTableReturnType` are exported as `type`. 
Could potentially solve this problem -> https://discord.com/channels/837692625737613362/1027142928797286411

fix: react-table export type

---

documentation/docs/api-reference/core/hooks/data/useCreate.md
documentation/docs/api-reference/core/hooks/data/useCustom.md
documentation/docs/api-reference/core/hooks/data/useDataProvider.md
documentation/docs/api-reference/core/hooks/data/useDelete.md
documentation/docs/api-reference/core/hooks/data/useList.md
documentation/docs/api-reference/core/hooks/data/useMany.md
documentation/docs/api-reference/core/hooks/data/useOne.md
documentation/docs/api-reference/core/hooks/data/useUpdate.md
documentation/docs/api-reference/core/hooks/useTable.md
documentation/plugins/docgen.js
documentation/plugins/docgen.ts
packages/core/src/hooks/data/useCreate.ts
packages/core/src/hooks/data/useCustom.ts
packages/core/src/hooks/data/useDataProvider.tsx
packages/core/src/hooks/data/useList.ts
packages/core/src/hooks/data/useMany.ts
packages/core/src/hooks/data/useOne.ts
packages/core/src/hooks/data/useUpdate.ts
packages/core/src/hooks/import/index.tsx

<PropsTable/> added to following docs.
1. [useCreate](https://refine.dev/docs/api-reference/core/hooks/useCreate/)
2. [useCustom](https://refine.dev/docs/api-reference/core/hooks/useCustom/)
5. [useMany](https://refine.dev/docs/api-reference/core/hooks/useMany/)
6. [useOne](https://refine.dev/docs/api-reference/core/hooks/useOne/)

feat(docs): add <PropsTable/> to core data hooks

---

.changeset/wet-dots-shave.md
packages/core/src/contexts/data/IDataContext.ts
packages/core/src/hooks/data/useCustom.ts
packages/core/src/hooks/data/useDelete.ts
packages/core/src/hooks/data/useDeleteMany.ts
packages/core/src/hooks/data/useList.ts

hooks was giving type errors because generic type parameters not passed

fix(core): data hooks type errors

---

documentation/docs/advanced-tutorials/ssr/remix.md

This closes #2671 
Problem:
In [Remix SSR Doc](https://github.com/pankod/refine/blob/master/documentation/docs/advanced-tutorials/ssr/remix.md)
it should say that `Refine` wraps Outlet, and not vice versa
Solution: 
This rewords the doc

[DOC] Update Refine wraps Outlet

---

.changeset/strange-emus-begin.md
documentation/docs/api-reference/core/components/refine-config.md
packages/core/src/components/containers/refine/index.tsx
packages/core/src/contexts/refine/IRefineContext.ts
packages/core/src/definitions/helpers/handleRefineOptions/index.spec.ts
packages/core/src/definitions/helpers/handleRefineOptions/index.ts

From now, **refine** can take react-query's [QueryClient](https://tanstack.com/query/v4/docs/reference/QueryClient) as a prop for more flexible react-query implementations.
Thanks to @jsbrain for the idea 🚀 
[Documentation Page](https://refine.dev/docs/api-reference/core/components/refine-config/#reactquery)
closes #2665

feat(core): add query client prop to refine

---

documentation/docs/api-reference/core/hooks/live/useSubscription.md
documentation/docs/api-reference/core/hooks/resource/useResource.md
documentation/docs/api-reference/core/hooks/resource/useResourceWithRoute.md
documentation/docs/api-reference/core/hooks/ui/useModal.md
packages/core/src/hooks/live/useSubscription/index.ts
packages/core/src/hooks/modal/useModal/index.tsx
packages/core/src/hooks/resource/useResource/index.ts

<PropsTable/> added to following docs.
1. [useSubscription](https://refine.dev/docs/api-reference/core/hooks/live/useSubscription/)
2. [useResource](https://refine.dev/docs/api-reference/core/hooks/resource/useResource/)
5. [useModal](https://refine.dev/docs/examples/ui/useModal/)

feat(docs): add props table to core hooks

---

.changeset/hot-jokes-lick.md
documentation/docs/api-reference/core/components/refine-config.md
documentation/docs/api-reference/core/interfaces.md
packages/core/src/contexts/resource/IResourceContext.ts
packages/core/src/definitions/helpers/index.ts
packages/core/src/definitions/helpers/pickDataProvider/index.spec.ts
packages/core/src/definitions/helpers/pickDataProvider/index.ts
packages/core/src/hooks/data/useCreate.ts
packages/core/src/hooks/data/useCreateMany.ts
packages/core/src/hooks/data/useDelete.ts
packages/core/src/hooks/data/useDeleteMany.ts
packages/core/src/hooks/data/useList.ts
packages/core/src/hooks/data/useMany.ts
packages/core/src/hooks/data/useOne.ts
packages/core/src/hooks/data/useUpdate.ts
packages/core/src/hooks/data/useUpdateMany.ts
packages/core/src/hooks/export/index.ts
packages/core/src/hooks/invalidate/index.tsx

Added `dataProviderName` property to resource options. This way we can define default data providers per resource.

feat: `dataProviderName` in `resource.options`

---

.changeset/rude-laws-lie.md
packages/core/src/contexts/data/IDataContext.ts

Mark `default` key as required for multiple data providers in `dataProvider` prop of `<Refine />` component.
Docs will be updated in a separate branch.

feat(core): mark `default` key required for multiple data providers

---

.changeset/rotten-pets-approve.md
packages/mantine/src/hooks/useSelect/index.ts

Add the clearable prop to useSelect return value.
The test are not effected.
.

feat(mantine): add clearable prop to useSelect

---

.changeset/metal-nails-shop.md
packages/core/src/hooks/useSelect/index.ts

`queryOptions` was override `useMany`'s enabled prop. Because of that `useMany` was triggering without `defaultValues` and and it was fetching all the data.
@vinclou Thanks for the issue 🚀 
closes #2692

fix(core) : `useSelect` fetches all data

---

.changeset/stupid-trains-smile.md
packages/core/src/hooks/useSelect/index.spec.ts
packages/core/src/hooks/useSelect/index.ts

`useSelect()`'s overridden `onSearch` function is not calling when value is empty.
To solve that, conditions flow reordered.

fix(core): `useSelect`'s overriden `onSearch` prop not calling when value is empty

---

.changeset/stupid-carrots-exercise.md
packages/antd/src/components/pages/auth/components/login/index.tsx
packages/antd/src/components/pages/auth/components/register/index.tsx
packages/mantine/src/components/pages/auth/components/login/index.tsx
packages/mantine/src/components/pages/auth/components/register/index.tsx
packages/mui/src/components/pages/auth/components/login/index.tsx
packages/mui/src/components/pages/auth/components/register/index.tsx

Divider renders when empty array is sent to providers

fix: providers property empty array state

---

documentation/docs/api-reference/core/hooks/data/useCreateMany.md
documentation/docs/api-reference/core/hooks/data/useDeleteMany.md
documentation/docs/api-reference/core/hooks/data/useMany.md
documentation/docs/api-reference/core/hooks/data/useUpdateMany.md
documentation/docs/api-reference/core/providers/data-provider.md
examples/dataProvider/multiple/src/App.tsx

- Added Multiple data providers section to the data provider document.
- Added multiple data provider live preview
- Added usage of `resource.options.dataProviderName` to examples
- Marked `*Many` properties as optional in the documentation
- Added `*Many` note in the documentation

docs: refactor data provider docs

---

README.md

The link for tailwind tutorial was pointing towards ant design tutorial which was misleading.
I have added the correct link that points towards the tailwind tutorial so that people don't get confused!

Add Correct Link for Tailwind Tutorial in Readme

---

documentation/docs/api-reference/core/components/accessControl/canAccess.md
documentation/docs/api-reference/core/components/auth-page.md
documentation/docs/api-reference/core/components/auth/authenticated.md
documentation/docs/api-reference/core/components/layout-wrapper.md
documentation/docs/api-reference/core/components/refine-config.md
packages/core/src/components/authenticated/index.tsx
packages/core/src/components/canAccess/index.tsx
packages/core/src/components/containers/refine/index.tsx
packages/core/src/components/layoutWrapper/index.tsx
packages/core/src/interfaces/auth.tsx

<PropsTable/> added to following docs.
1. [CanAccess](https://refine.dev/docs/api-reference/core/components/accessControl/can-access/)
2. [AuthPage](https://refine.dev/docs/api-reference/core/components/auth-page/)
3. [Refine](https://refine.dev/docs/api-reference/core/components/refine-config/)
4. [Authenticated](https://refine.dev/docs/api-reference/core/components/auth/authenticated/)

feat(docs): add `<PropsTable>` to core components

---

packages/core/src/hooks/export/index.ts

Options's documentation link added [Options](https://github.com/alexcaza/export-to-csv)

feat(docs): add docs link to useExport options prop

---

documentation/src/pages/about/styles.module.css

Text colour #2A2A2A has been added to style module of about page.
closes #2734 

fix for text colour in about page when switched to dark mode

---

.changeset/sharp-rice-film.md
packages/nhost/src/dataProvider/index.ts

Added missing implementations for `nnull`, `startswith`, `startswiths`, `nstartswith`, `nstartswiths`, `endswith`, `endswiths`, `nendswith` and `nendswiths` filters by `_similar`, `_nsimilar`, `_regex` and `_iregex` filters from Nhost.
Added nested property filter support for `or` filters.

feat(nhost): add missing filters

---

.changeset/tender-bottles-chew.md
packages/hasura/src/dataProvider/index.ts

Added nested property filter support for `or` filters.

fix(hasura): add missing nested field support to or filters

---

.changeset/blue-turkeys-hear.md
packages/mantine/src/components/pages/auth/components/forgotPassword/index.tsx
packages/mantine/src/components/pages/auth/components/register/index.tsx
packages/mantine/src/components/pages/auth/components/updatePassword/index.tsx

- Updated forgotPassword in refine-mantine to use the expected hook `useForgotPassword()`
- Updated resetPassword in refine-mantine to use the expected hook `useResetPassword()`
- Updated updatePassword in refine-mantine to use the expected hook `useUpdatePassword()`
closes #2768 

fix(mantine): use correct hooks in auth pages

---

.changeset/tough-masks-fly.md
packages/react-router-v6/src/index.ts

Add missing `BrowserRouterComponent` export to `@pankod/refine-react-router-v6` package.

fix: missing exports on `@pankod/refine-react-router-v6`

---

.changeset/happy-keys-return.md
packages/mui/src/components/pages/auth/components/forgotPassword/index.tsx

Fix login link alignment on forgot password page.

fix(mui): login link alignment on forgot password

---

documentation/docs/api-reference/mantine/components/breadcrumb.md
documentation/sidebars.js

Added `<BreadCrumb/>` documentation.
When the documents change, the tests do not affect.
.

docs(mantine): add breadcrumb component doc

---

CODE_OF_CONDUCT.md

Fixed the link to Mozilla enforcement ladder doc in CODE_OF_CONDUCT.md
Closes #2804 

docs: Fix enforcement ladder link in CODE_OF_CONDUCT.md

---

documentation/docs/further-readings/benchmarks.md

Fixed some punctuation mistakes in benchmark documentation.

docs: fix punctuation mistakes in benchmarks doc

---

.changeset/pink-files-explain.md
examples/store/pages/_app.tsx
packages/medusa/src/dataProvider/index.ts

By default, we added `/store` suffix to the end of Medusa API URL. This prevented the user from using a different path.
- #2822

fix: "/store" suffix to the end of Medusa API URL

---

documentation/src/components/example-list/index.tsx

Added search params to `docs/examples` to sync selected tags with the filter state, easy to share.

docs(examples-list): add ability to persist tags in url search params

---

.changeset/weak-mice-change.md
documentation/docs/api-reference/antd/components/fields/date.md
packages/antd/src/components/fields/date/index.tsx
packages/mantine/src/components/fields/date/index.tsx
packages/mui/src/components/fields/date/index.tsx
packages/ui-tests/src/tests/fields/date.tsx
packages/ui-types/src/types/field.tsx

The `locales` prop was not given to dayjs. It is now given
To use dayjs localization, user need to import supported locales on demand. Is this explanation enough for the this feature or should i create full example ?

feat: add locales prop to `<DateField/>`

---

.husky/pre-commit
package.json

Pre-commit hook was not working as expected and linting all files without cache which was increasing the verification duration to ~15-20 secs. Updated `lint-staged` configuration to lint only staged files to save us some development time. 
This change should not have any effects on CI and other checks.

build: configure `lint-staged`

---

.changeset/seven-mirrors-brush.md
packages/mantine/src/components/pages/auth/index.tsx

fixed: Mantine UserFormInput requires 2 type argument(s).

fix(mantine): `userFormInput` generic type

---

documentation/docs/packages/documentation/command-palette.md
documentation/docs/packages/documentation/react-hook-form/useForm.md
documentation/docs/packages/documentation/react-hook-form/useModalForm.md
documentation/docs/packages/documentation/react-hook-form/useStepsForm.md
documentation/docs/packages/documentation/react-table.md
documentation/src/components/tooltip/index.tsx
documentation/src/components/tooltip/styles.module.css
packages/antd/src/components/buttons/clone/index.tsx
packages/react-hook-form/src/useForm/index.ts
packages/react-hook-form/src/useModalForm/index.ts
packages/react-hook-form/src/useStepsForm/index.ts
packages/react-table/src/useTable/index.ts

1. [React Table](https://refine.dev/docs/packages/documentation/react-table/)
2. [useForm](https://refine.dev/docs/packages/documentation/react-hook-form/useForm/)
3. [useModalForm](https://refine.dev/docs/packages/documentation/react-hook-form/useModalForm/)
4. [useStepsForm](https://refine.dev/docs/packages/documentation/react-hook-form/useStepsForm/)
Before
After

feat: add `<PropsTable/>` to packages

---

examples/authentication/mantine/src/App.tsx
examples/authentication/mantine/src/pages/posts/index.ts
examples/authentication/mantine/src/pages/posts/list.tsx
examples/authentication/mantine/src/pages/posts/show.tsx
examples/base/mantine/src/App.tsx
examples/base/mantine/src/pages/posts/index.ts
examples/base/mantine/src/pages/posts/list.tsx
examples/base/mantine/src/pages/posts/show.tsx
examples/customization/customTheme/mantine/src/App.tsx
examples/customization/customTheme/mantine/src/pages/posts/index.ts
examples/customization/customTheme/mantine/src/pages/posts/list.tsx
examples/customization/customTheme/mantine/src/pages/posts/show.tsx
examples/upload/mantine/base64/src/App.tsx
examples/upload/mantine/base64/src/pages/posts/index.ts
examples/upload/mantine/base64/src/pages/posts/list.tsx
examples/upload/mantine/base64/src/pages/posts/show.tsx
examples/upload/mantine/multipart/src/App.tsx
examples/upload/mantine/multipart/src/pages/posts/index.ts
examples/upload/mantine/multipart/src/pages/posts/list.tsx
examples/upload/mantine/multipart/src/pages/posts/show.tsx

Added the show page to mantine examples.

fix(mantine): add show pages to examples

---

examples/store/src/assets/main.css
examples/store/src/components/auth/LoginView.tsx
examples/store/src/components/auth/SignUpView.tsx

Problem was that tailwindcss base styling was affecting button with submit type so overridden main.css base layer with bg-color as black.
Closes #2821 

Fix(button): changes made to make button background colour appear

---

documentation/docs/advanced-tutorials/data-provider/supabase.md

Some typo in a tutorial. An `index.ts` is required to expose the components in the subdirectory

fixed missing index.ts

---

packages/chakra-ui/src/components/breadcrumb/index.tsx

Added `href` property to breadcrumb links for the Nextjs compatibility.

fix(chakra-ui): add href prop to breadcrumb link for nextjs compatibility

---

.changeset/old-planets-flash.md
documentation/docs/api-reference/core/providers/auth-provider.md
packages/core/src/hooks/auth/useCheckError/index.spec.ts
packages/core/src/hooks/auth/useCheckError/index.ts
packages/core/src/hooks/auth/useLogout/index.spec.ts
packages/core/src/hooks/auth/useLogout/index.ts

- fixed: The "onSuccess" parameters were wrong.
- fixed: value overriding. [Redirection path given to checkError overrides the one on logout.](https://refine.dev/docs/api-reference/core/providers/auth-provider/#redirection-after-error)
-  `onSuccess: (data, variables) => {}`
data comes from: `logout:() => Pormise<any>`
variables comes from: `checkError:() => Pormise<any>`
closes #2927 

fix(core): `useLogout` `onSuccess` behaviour

---

documentation/src/components/github-floating-cta/index.tsx

> This issue occurs in only `firefox` and `safari`
Since "Github Floating Cta" was `position:sticky`. When the page was at the bottom it would leave a space after the footer.
Changing `position:sticky` to `position:fixed` solved the problem.
before
after 

fix(docs): footer cannot snap to bottom

---

.changeset/hungry-peas-pump.md
.changeset/proud-mayflies-divide.md
packages/chakra-ui/src/components/pages/error/index.tsx
packages/mantine/src/components/pages/ready/index.tsx

- Fixed responsive style for error page in `refine-chakra-ui` package.
- Added padding to ReadyPage component in `refine-mantine` package.
All tests run successfully.

fix: page components

---

.changeset/ninety-melons-appear.md
.changeset/tricky-tigers-push.md
examples/table/mui/advancedTable/src/pages/dataGrid/index.tsx
examples/table/mui/advancedTable/src/pages/table/index.tsx
examples/table/mui/dataGridPro/src/pages/posts/list.tsx
examples/table/mui/tableFilter/src/pages/posts/list.tsx
examples/table/mui/useDataGrid/src/pages/posts/list.tsx
examples/table/mui/useDeleteMany/src/pages/posts/list.tsx
examples/table/mui/useUpdateMany/src/pages/posts/list.tsx
packages/core/src/hooks/useSelect/index.ts
packages/mui/src/hooks/useDataGrid/index.ts

- Prevented server request when empty filter value is provided.
- Added `singleSelect` type column to category and status columns in Material UI examples for filter accordingly to relational data.
All tests run successfully.

fix: empty filter value request issue for `useDataGrid`

---

.changeset/pretty-buttons-stare.md
.changeset/stupid-radios-agree.md
packages/chakra-ui/src/components/fields/number/index.tsx
packages/mantine/src/components/fields/number/index.tsx

Added missing generic type to `<NumberField />` type in `@pankod/refine-chakra-ui` and `@pankod/refine-mantine`

fix: `chakra-ui` and `mantine` number field props

---

.changeset/red-cobras-care.md
packages/ui-tests/src/tests/buttons/create.tsx

Updated `CreateButton` tests to handle `disabled`check.

test(ui-tests): `CreateButton` disabled state check

---

.changeset/polite-pillows-leave.md
packages/cli/src/commands/create-resource/index.ts
packages/cli/src/commands/generate/resource/index.ts
packages/cli/src/index.ts

- Rename command name `generate:resource` to `create-resource`.
- Removed the requirement for the `resource name` parameter. Ask for `resource name` and `actions` with `inquirer`.
- Add multiple resource create support. (`refine create-resource post category user`)

feat: create multiple resource support for refine-cli

---

.changeset/fast-turtles-roll.md
packages/inferencer/src/inferencers/antd/__tests__/__snapshots__/edit.test.tsx.snap
packages/inferencer/src/inferencers/antd/edit.tsx

Added `undefined` check for date field values in `@pankod/refine-inferencer/antd`'s `EditInferencer` component to prevent setting it to current date when it's not provided.

fix: date fields of `antd/edit` in `inferencer` 

---

.changeset/short-mice-fry.md
packages/core/src/hooks/show/useShow.ts

A recent PR #3030 added a feature to accept queryOptions as a parameter to the `useShow` hook. It however was not passed in correctly through the `useShow` hook to the `useOne` hook (spread in the useOne props bag instead of the queryOptions bag, see further details in #3072.
Change fixes the bug.
Tests pass.
Verified locally that the queryOptions are passed through to `useOne` from `useShow`.
closes #3072

fix(useShow): Pass queryOptions correctly through useShow hook

---

.changeset/sixty-suns-agree.md
packages/react-router-v6/src/index.ts

Please provide enough information so that others can review your pull request: quick fix for annoying ts error when using `useParams` through `routerProvider`

fix TS errors when 'useParams' set to 'any

---

.changeset/wicked-squids-pay.md
packages/cli/package.json

chore(cli): move figlet to dependencies from devDependencies

---

.changeset/breezy-suns-sort.md
packages/create-refine-app/src/index.ts

Added argument support
before:
```bash
npm create refine-app -- -o refine-antd tutorial
```
after:
```bash
npm create refine-app -o refine-antd tutorial
```

feat: add argument support for create-refine-app

---

.changeset/tasty-llamas-joke.md
packages/mui/src/index.tsx

closes #3055
> Currently, I have to install @mui/material manually to be able to use its translation files. It's not ideal. Especially because you have i18n provider, I assume this library is globally adopted so exporting locale files is essential.

feat: export material-ui localization files

---

.changeset/seven-terms-design.md
packages/core/src/components/containers/refine/index.tsx

Updated `notificationProvider` prop usage in `<Refine />` component to handle hook calls inside function values. This was causing warnings on console in `@pankod/refine-mui` and `@pankod/refine-chakra-ui`.
Resolves #3089 

fix(core): notification provider with hooks

---

.changeset/angry-ladybugs-laugh.md
packages/simple-rest/package.json

Added missing `refine.config.js` file to `files` property in `package.json` of `@pankod/refine-simple-rest`

fix: `@pankod/refine-simple-rest` files config

---

.changeset/spotty-mirrors-cough.md
packages/antd/src/components/crud/create/index.tsx
packages/antd/src/components/crud/edit/index.tsx
packages/antd/src/components/crud/list/index.tsx
packages/antd/src/components/crud/show/index.tsx
packages/chakra-ui/src/components/crud/create/index.tsx
packages/chakra-ui/src/components/crud/edit/index.tsx
packages/chakra-ui/src/components/crud/list/index.tsx
packages/chakra-ui/src/components/crud/show/index.tsx
packages/mantine/src/components/crud/create/index.tsx
packages/mantine/src/components/crud/edit/index.tsx
packages/mantine/src/components/crud/list/index.tsx
packages/mantine/src/components/crud/show/index.tsx
packages/mui/src/components/crud/create/index.tsx
packages/mui/src/components/crud/edit/index.tsx
packages/mui/src/components/crud/list/index.tsx
packages/mui/src/components/crud/show/index.tsx

When import `crud types` like `import { ShowProps } from @components` tsup not exporting these types on build. 
Import paths changed from  `import "ShowProps" from @components` to  `import { ShowProps } from ../types`

fix: crud components import path

---

documentation/plugins/docgen.js
documentation/plugins/docgen.ts
documentation/plugins/examples.js

Updated `docgen` plugin for conflicting exports causing `@pankod/refine-antd`'s `List` props to be removed.

docs: add filter for conflicting namespaces

---

packages/antd/src/components/pageHeader/index.tsx

`PageHeader` component comes from `@ant-design/pro-layout` and because of that dosen't respect `ConfigProvider` from `antd`. This cause `theme` conflicts.
To sovle that, we passed default `antd` components inside `PageHeader`. 

feat(antd): antd `PageHeader` theme

---

examples/fineFoods/admin/mui/src/components/dashboard/orderTimeline/index.tsx
examples/fineFoods/admin/mui/src/pages/couriers/create.tsx
examples/fineFoods/admin/mui/src/pages/couriers/edit.tsx
examples/fineFoods/admin/mui/src/pages/stores/create.tsx
examples/fineFoods/admin/mui/src/pages/stores/edit.tsx

Added `ts-expect-error` to known type errors in `examples/fineFoods/admin/mui`.

fix(finefoods): remove type errors

---

.changeset/old-swans-sell.md
packages/inferencer/package.json
packages/inferencer/src/components/live/index.tsx
packages/live-previews/package.json
packages/live-previews/pages/preview.tsx
packages/live-previews/src/components/live-error.tsx

Replaced `react-live` package with`@aliemir/react-live` to keep TypeScript support and resolve the issue with GitHub registry packages.
Resolves #3161 

chore: replace `react-live` with `@aliemir/react-live`

---

.changeset/tasty-cameras-smell.md
examples/multi-tenancy/appwrite/src/authProvider.ts
examples/multi-tenancy/appwrite/src/components/product/create.tsx
examples/multi-tenancy/appwrite/src/components/product/edit.tsx
examples/multi-tenancy/appwrite/src/components/sider/index.tsx
examples/multi-tenancy/appwrite/src/utility/appwriteClient.ts
packages/inferencer/src/create-inferencer/index.tsx
packages/inferencer/src/field-transformers/basic-to-relation.ts
packages/inferencer/src/field-transformers/index.ts
packages/inferencer/src/inferencers/antd/__tests__/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/antd/index.tsx
packages/inferencer/src/inferencers/chakra-ui/__tests__/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/chakra-ui/index.tsx
packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/mantine/index.tsx
packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/mui/index.tsx
packages/inferencer/src/types/index.ts
packages/inferencer/src/use-relation-fetch/index.ts
packages/inferencer/src/utilities/component-name/index.test.ts
packages/inferencer/src/utilities/component-name/index.ts

- Updated component naming convention to be unique between resources
- Added `fieldTransformer` prop to inferencer components to let users transform or hide the field to be rendered.
- Hide networks errors caused by the relation detection process.
- Added the ability to detect relations from basic types like `"text"` and `"number"`.

feat(inferencer): Ability to transform/ignore fields in inferencer components

---

.changeset/modern-crabs-change.md
packages/react-hook-form/src/index.ts

Export `UseFieldArrayReplace` type from `react-hook-form`.

fix: export `UseFieldArrayReplace` type

---

.changeset/silly-numbers-camp.md
packages/antd/src/components/table/components/filterDropdown/index.spec.tsx
packages/antd/src/components/table/components/filterDropdown/index.tsx

By default, Ant Design expected filtered keys should be an array or string but in case value is a number, it will be treated as invalid and stop on filtering.
https://github.com/ant-design/ant-design/blob/77ea4038d169d033dcd4d29da1df9ab21b23ebb9/components/table/hooks/useFilter/FilterDropdown.tsx#L229-L233
1. Apply filter dropdown on Select component with mode "single" and list option included number value
For example: `{ label: "A", value: 1 }`
2. Perform select and filter on multiple items of Select component
3. Check API for filtering is called with correct selected value
Referer: https://stackblitz.com/edit/refinedev-refine-jydkgh?file=src%2Fpages%2Fposts%2Flist.tsx&preset=node
closes …

chore: support filter dropdown number value

---

.changeset/fifty-chefs-drive.md
packages/antd/src/definitions/table/index.spec.ts
packages/antd/src/definitions/table/index.ts
packages/antd/src/hooks/table/useTable/useTable.ts
packages/core/src/hooks/useTable/index.ts

By default, "Clear" action from Filter Dropdown is handled by Ant Design by removing filter column value out from list filter. If there is a new value on the filter column again, the mapping has no context on initial filters to restore correct operator.
By providing a map of initial filters, mapping new filters can restore operator in case previous filters is empty or no data on target filter column.
1. Initialize example "refine-airtable-example" with initial filter on column "Title" with `{ field: 'title', operator: 'contains', value: '' }`
2. Perform filter on column "Title" with keyword "Hello" to see correct results of the keyword
3. Click "Clear" button then "Filter" button to see …

chore: restore filter operator after clearing on filter dropdown

---

.changeset/little-tigers-deny.md
packages/antd/refine.config.js

After swizzling the `Layout` component, the import name and usage were wrong. Fixed with correct values.

fix(swizzle): wrong import and usage on swizzled antd layout

---

.changeset/grumpy-apes-breathe.md
documentation/docs/api-reference/antd/migration-guide/v4-to-v5.md
packages/antd/src/components/layout/sider/index.tsx

Set the `theme="dark"` of the `Menu` component in `Sider` by default.

fix: antd menu theme

---

.changeset/rare-feet-walk.md
packages/hasura/src/dataProvider/index.ts

`contains`, `ncontains`, `containss` and `ncontainss` filters were passing the value without wrapping it to `%` characters. This caused the filters to not work as expected. Added a case to the filter value handler to wrap the value with `%` characters.
Resolves #3245 

fix: add missing `contains` value handlers to `@pankod/refine-hasura`

---

documentation/src/components/landing/section-no-constraints/header.tsx

- Decrease title zIndex to prevent hoverable menu override

fix: decrease title zIndex to prevent hoverable menu override

---

.changeset/serious-beers-hope.md
packages/cli/src/commands/whoami/index.ts
packages/cli/src/telemetry/index.ts
packages/cli/src/update-notifier/index.tsx
packages/cli/src/utils/package/index.ts

`npm -ls` always throws an error. now returns `null` and `error` handling can be done anywhere

feat(cli): npm ls should not throw error

---

.changeset/thin-moles-obey.md
packages/antd/src/hooks/form/useDrawerForm/useDrawerForm.ts
packages/antd/src/hooks/form/useModalForm/useModalForm.ts

Remove `getContainer: false` from `useModalForm` and `useDrawerForm` and let it fallback to the default value. Users wanting to override the default value can still do so by passing `getContainer` prop to the `Modal` and `Drawer` components.

refactor(antd): remove `getContainer` from `useModalForm` and `useDrawerForm`

---

documentation/docs/api-reference/core/providers/data-provider.md

Replaced the `DataProvider` type import with `@pankod/refine-core` instead of the local file.

docs(data-provider): fix `DataProvider` type import

---

.changeset/modern-tips-hang.md
packages/strapi-v4/src/dataProvider.ts

Mapping of nnul crud operator to notNull in strapi-v4 is missing

fix: mapping nnul crud operator to notNull

---

.changeset/friendly-mails-smile.md
packages/react-hook-form/src/useStepsForm/index.ts

Fixed resetting values on step changes
- #3290

fix: keepValues true for react-hook-form

---

documentation/docs/advanced-tutorials/custom-pages.md
documentation/docs/advanced-tutorials/ssr/nextjs.md
documentation/docs/advanced-tutorials/ssr/remix.md

Added a small tip for showing custom pages/routes in `<Sider/>` without customizing it. 

docs(custom-page): add sider trick tip

---

.changeset/nervous-planets-deny.md
packages/cli/src/commands/runner/runScript.ts

I create this PR to fix :
1. dev server keeps running after exiting on Windows 
2. Terminal output log has no color 
I've patched **refine-cli** to test this change and it works well
- #3175 

Fix(cli): ctrl+c not killing running server on Windows

---

.changeset/calm-schools-train.md
.changeset/fifty-dodos-arrive.md
packages/antd/src/hooks/form/useForm.ts
packages/core/src/hooks/auditLog/useLog/index.ts
packages/core/src/hooks/auth/useForgotPassword/index.ts
packages/core/src/hooks/auth/useLogin/index.ts
packages/core/src/hooks/auth/useLogout/index.ts
packages/core/src/hooks/auth/useRegister/index.ts
packages/core/src/hooks/auth/useUpdatePassword/index.ts
packages/core/src/hooks/data/useCreate.ts
packages/core/src/hooks/data/useCreateMany.ts
packages/core/src/hooks/data/useCustomMutation.ts
packages/core/src/hooks/data/useDelete.ts
packages/core/src/hooks/data/useDeleteMany.ts
packages/core/src/hooks/data/useUpdate.ts
packages/core/src/hooks/data/useUpdateMany.ts
packages/core/src/hooks/form/useForm.ts

Added the ability to pass mutation options to `useMutation` hooks in mutation hooks:
- `useCreate` (data)
- `useUpdate` (data)
- `useDelete` (data)
- `useDeleteMany` (data)
- `useUpdateMany` (data)
- `useCreateMany` (data)
- `useCustomMutation` (data)
- `useLogin` (auth)
- `useLogout` (auth)
- `useRegister` (auth)
- `useForgotPassword` (auth)
- `useUpdatePassword` (auth)
- `useForm` (form)
- `useLog` (audit log)
Also includes changes in `@pankod/refine-antd` for:
- `useForm`
- `useStepsForm`
- `useModalForm`
- `useDrawerForm`
hooks.
Users now can pass `mutationOptions` config property to pass custom options to the `useMutation` hooks.
**Warning**
This PR is marked as draft to make sure buttons in UI packages are also compatible with the latest changes.
Please check all items below before …

feat: `mutationOptions` in core hooks

---

.changeset/breezy-panthers-study.md
packages/cli/src/commands/swizzle/index.tsx

Updated the prompt for the component selection to be skipped when there's a single item to swizzle. Such as `@pankod/refine-simple-rest` which has a single `Data Provider` item to swizzle but users are still prompted to select.

feat(cli): fast swizzle for single item packages

---

.changeset/sixty-spiders-thank.md
packages/inferencer/src/use-infer-fetch/index.tsx

Fix type inconsistency in `useInferFetch` due to changes in `@pankod/refine-core`'s `useResource` hook.

fix: `@pankod/refine-inferencer` `BaseKey` type issue

---

.changeset/heavy-rules-kick.md
packages/inferencer/src/use-infer-fetch/index.tsx

Update `useInferFetch` hook logic to work without `id` in `list` and `create` type of inferencer.

fix(inferencer): mark `recordItemId` as nullable

---

documentation/docs/tutorials/core.md

The first command in https://refine.dev/docs/tutorials/headless-tutorial/#setting-up is missing `--` before the arguments.

docs(tutorials): fix headless install command

---

.changeset/chilly-mails-deny.md
packages/core/src/contexts/resource/IResourceContext.ts

Replaced `React.FunctionComponent` with `React.ComponentType` for wider compatibility. Such as cases in #3357 with `next/dynamic`

fix:core resource action component type

---

.changeset/thin-buckets-hammer.md
packages/cli/src/update-notifier/index.tsx
packages/cli/src/utils/encode/index.ts

fix(cli): use `Buffer.from` when `btoa` is `"undefined"` for `base64` encoding

---

.changeset/small-students-compare.md
packages/inferencer/src/inferencers/chakra-ui/__tests__/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/chakra-ui/__tests__/__snapshots__/list.test.tsx.snap
packages/inferencer/src/inferencers/headless/list.tsx

removed repeated `react` import in `headless` inferencer's `List`.

fix(inferencer): remove repeated react import

---

documentation/src/components/live-preview/styles.module.css

fix(docs): live preview header button text not visible on dark mode

---

.changeset/twenty-beers-impress.md
documentation/docs/api-reference/mantine/components/auth-page.md
packages/mantine/src/components/pages/auth/index.tsx

fix: `onSubmit` is set to nullable on [`<AuthPage>`](https://refine.dev/docs/api-reference/mantine/components/mantine-auth-page/)
- https://discord.com/channels/837692625737613362/1063845396910178314

fix: onSubmit is set to nullable on AuthPage

---

packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/create.test.tsx.snap
packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/edit.test.tsx.snap
packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/list.test.tsx.snap
packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/show.test.tsx.snap
packages/live-previews/next.config.js

We've added production source maps to live-previews so we can identify the errors if any happens in the documentation which uses the production build but now for some reason, enabling `productionBrowserSourceMaps` hangs the live-previews build process and fails the pipelines. 
Disabled for now but will be looking for a workaround for this.

chore(live-previews): disable sourcemaps in production

---

documentation/src/css/custom.css
documentation/src/theme/Footer/Layout/index.js

Fixed the scroll snapping to footer when navigating to other pages from landing.

docs: fix safari scroll issue on navigation

---

documentation/docs/api-reference/antd/hooks/form/useForm.md
documentation/docs/api-reference/antd/hooks/form/useModalForm.md
documentation/docs/api-reference/antd/hooks/form/useStepsForm.md
documentation/docs/api-reference/mantine/hooks/form/useForm.md
documentation/docs/api-reference/mantine/hooks/form/useModalForm.md
documentation/docs/api-reference/mantine/hooks/form/useStepsForm.md
documentation/docs/packages/documentation/react-hook-form/useModalForm.md
documentation/docs/packages/documentation/react-hook-form/useStepsForm.md

The documentation of form hooks differed from each other. Updated to be in the same format as each other.

feat(docs): update all documentation of form hooks in same format

---

.changeset/clever-hornets-raise.md
packages/nestjsx-crud/src/index.ts

Added ability to pass `join` parameter through `metaData` to queries.
**Example**
```ts
useList({
metaData: {
join: {
select: ["id","name"],
field: "categories",
},
}
});
useList({
metaData: {
join: ["categories", ["id", "name"]],
}
});
useList({
metaData: {
join: [
["categories", ["id", "name"]],
{
select: ["id", "label"],
field: "tags",
}
],
}
});
```

feat(nestjsx-crud): added ability to `join` through `metaData`

---

documentation/src/css/custom.css

Fixed broken arrow in navbar version dropdown caused by `::after` style conflict between arrow and hover line

docs(version-dropdown): fix arrow on hover

---

.changeset/rich-buttons-clean.md
packages/core/src/hooks/data/useCustom.ts
packages/core/src/hooks/data/useCustomMutation.ts
packages/core/src/hooks/data/useList.ts

fix: default i18n namespace set in the some hooks

---

.changeset/odd-pianos-brush.md
packages/core/refine.config.js

Added swizzle support for `@pankod/refine-core` package.
Swizzleable components:
-   `Authenticated`
-   `CanAccess`
-   `ErrorPage`
-   Authentication Pages
-   `Login`
-   `Logout`
-   `Register`
-   `ForgotPassword`
-   `UpdatePassword`

feat: add swizzle support for `@pankod/refine-core` package

---

.changeset/young-plums-fold.md
packages/cloud/src/hooks/useAuthProviderWithCloudConfig/index.spec.tsx
packages/core/src/contexts/auth/IAuthContext.ts

Made the auth provider's `usePermissions` method optional.

fix: make `getPermissions` of auth provider optional

---

.changeset/three-timers-pretend.md
packages/core/src/hooks/data/useInfiniteList.ts

Fix error translation key on `useInfiniteList` hook.

fix: Error translation key on `useInfiniteList` hook

---

documentation/src/components/live-preview/styles.module.css
documentation/src/css/custom.css
documentation/src/theme/DocItem/Layout/index.js

Added a simple button at top of the articles to add a link to the source code.
Also fixed the invisible "Show Code" label in dark mode for `BrowserWindow` component.
**Usage**
```md
---
id: useApiUrl
title: useApiUrl
source: https://github.com/refinedev/refine/blob/next/packages/core/src/hooks/data/useApiUrl.ts
---
```
or
```md
---
id: useCreate
title: useCreate
source: packages/core/src/hooks/data/useCreate.ts
siderbar_label: useCreate
description: useCreate data hook from refine is a modified version of react-query's useMutation for create mutations
---
```
**Output**
-   [x] …

docs: add source code link option

---

documentation/docs/api-reference/core/hooks/data/useApiUrl.md
documentation/docs/api-reference/core/hooks/data/useCreate/index.md
documentation/docs/api-reference/core/hooks/data/useCreateMany/index.md
documentation/docs/api-reference/core/hooks/data/useCustom/index.md
documentation/docs/api-reference/core/hooks/data/useCustomMutation/index.md
documentation/docs/api-reference/core/hooks/data/useDataProvider.md
documentation/docs/api-reference/core/hooks/data/useDelete/index.md
documentation/docs/api-reference/core/hooks/data/useDeleteMany/index.md
documentation/docs/api-reference/core/hooks/data/useInfiniteList/index.md
documentation/docs/api-reference/core/hooks/data/useList/index.md
documentation/docs/api-reference/core/hooks/data/useMany/index.md
documentation/docs/api-reference/core/hooks/data/useOne/index.md
documentation/docs/api-reference/core/hooks/data/useUpdate/index.md
documentation/docs/api-reference/core/hooks/data/useUpdateMany/index.md

- Fixed grammar mistakes
- Rename react-query to Tanstack Query
- Add source-code button to data hook docs

docs: fix grammar mistakes on data hook docs

---

documentation/docs/api-reference/core/hooks/accessControl/useCan.md

added: return values and properties to [`useCan` doc](https://refine.dev/docs/api-reference/core/hooks/accessControl/useCan/)

feat(docs): add props and return values description to `useCan`

---

documentation/docs/examples/remix/antd.md
documentation/docs/examples/remix/headless.md

fixed: **remix** example links
https://refine.dev/docs/examples/remix/remix-headless/
https://refine.dev/docs/examples/remix/remix-antd/

docs(remix): fix links in remix examples

---

.changeset/violet-months-buy.md
packages/mui/src/components/layout/sider/index.tsx

fix: `@pankod/refine-mui` multi level `Sider` menu. 
Closes #3505

fix: `@pankod/refine-mui` multi level `Sider` menu

---

documentation/docs/api-reference/core/providers/notification-provider.md

Fixing typo: "type" parameter not defined in example message.

typo: add type to toast message

---

documentation/docs/faq.md

added: https://refine.dev/docs/faq/#why-are-api-calls-triggering-twice

docs(faq): add why are api calls triggering twice

---

documentation/docs/advanced-tutorials/data-provider/supabase.md

Added a caution for Supabase data provider's realtime support. Due to behavioral differences, multiple subscriptions to tables are not well supported.

docs(supabase): add admonition for multiple subscriptions

---

.changeset/friendly-actors-hear.md
packages/core/src/definitions/helpers/index.ts
packages/core/src/definitions/helpers/pickNotDeprecated/index.spec.ts
packages/core/src/definitions/helpers/pickNotDeprecated/index.ts
packages/core/src/index.tsx

Created a helper function for picking not deprecated values.
```ts
const sorter = undefined;
const sorters = [{ id: 1 }];
const value = pickNotDeprecated(sorter, sorters) ?? [{ id: 5 }]; // [{ id: 1 }]
```

feat(v4): add pick not deprecated

---

.changeset/tidy-turkeys-float.md
examples/blog-refineflix/src/pages/admin/movies/create.tsx
examples/blog-refineflix/src/pages/admin/movies/edit.tsx
packages/demo-sidebar/src/components/DemoSidebar/index.tsx

Antd [<Drawer>](https://ant.design/components/drawer) `handler` prop changed to extra

fix(demo-sidebar): handler prop changed to extra

---

.changeset/popular-toys-run.md
.changeset/strong-seahorses-kiss.md
packages/antd/src/components/buttons/delete/index.tsx
packages/mantine/src/components/buttons/delete/index.tsx

Fixed the `disabled` state not reflected in popovers in `DeleteButton` components in `@pankod/refine-antd` and `@pankod/refine-mantine` packages.
Resolves #3605 

fix(antd-mantine): `disabled` state in `DeleteButton`s

---

examples/with-nextjs/next.config.js

Created `next.config.js` on nextjs examples.

fix: add `next.config.js` file on nextjs examples

---

packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/list.test.tsx.snap

Updated failing snapshots for Mantine Inferencer.

test(inferencer): update snapshots for mantine

---

documentation/docs/migration-guide.md

added: Auth Provider migration guide

feat(v4-docs): `authProvider` migration guide

---

packages/core/src/contexts/auth/index.tsx

If auth provider methods return a rejected promise, auth hook function logic does not work.
A console warning has been added to inform the user.

feat(v4-core): add "expects resolved promise"  warning to `authProvider`

---

.github/workflows/pull-request.yml

Bootstrapping before tests had missing packages, causing tests to fail.

build(CI): fix bootstrap before test run

---

packages/create-refine-app/src/index.ts

Fixed hard coded `--project` command on `create-refine-app`.

fix(create-refine-app): fix hard coded `--project` command

---

.changeset/big-dingos-fix.md
.changeset/slimy-planets-walk.md
packages/nextjs-router/src/app/index.ts
packages/nextjs-router/src/common/parse-table-params.ts
packages/nextjs-router/src/pages/index.ts
packages/remix/src/index.ts
packages/remix/src/parse-table-params.ts

Added `parseTableParams` helper export to let users handle persisting the `syncWithLocation` feature in tables.
- In Remix, users can use it in `loader`s.
- In Next.js, users can use it in `getServerSideProps` functions.

feat(v4): `parseTableParams` helper in SSR routers

---

packages/core/src/interfaces/bindings/resource.ts

Removed the `keepParentPrefix` from the interface of the resource `meta`. It was not used in the app.
No changesets are required because it wasn't released already.

refactor(v4): remove unused `keepParentPrefix` meta

---

packages/core/src/hooks/navigation/index.ts

fixed: The`listUrl` function had a typo. "show" was returning URL instead of "list"

fix(core):`listUrl` returns show url string

---

packages/react-router-v6/src/catch-all-navigate.tsx
packages/react-router-v6/src/index.ts

Added `CatchAllNavigate` component to handle navigation at catch-all routes and keep the current route in `to` query parameter.
**Example**
```tsx
import { CatchAllNavigate } from "@refinedev/react-router-v6"; 
<Route path="*" element={<CatchAllNavigate to="/login" />} />
```
When user is at `/posts` route, it will navigate to the `/login?to=/posts`

feat(v4-router): `<CatchAllNavigate />`

---

examples/base-antd/src/App.tsx
examples/base-chakra-ui/src/App.tsx
examples/base-mantine/src/App.tsx
examples/base-mui/src/App.tsx
examples/calendar-app/src/App.tsx
examples/command-palette-kbar/src/App.tsx
examples/command-palette-kbar/tsconfig.json
examples/core-use-import/src/App.tsx
examples/core-use-menu/src/App.tsx
examples/core-use-menu/src/components/layout/index.tsx
examples/core-use-modal/src/App.tsx
examples/core-use-select/src/App.tsx
examples/customization-footer/src/App.tsx
examples/customization-login/src/App.tsx
examples/customization-rtl/src/App.tsx
examples/customization-sider/src/App.tsx
examples/customization-sider/src/components/sider/index.tsx
examples/customization-theme-antd/src/App.tsx
examples/customization-theme-chakra-ui/src/App.tsx
examples/customization-theme-mantine/src/App.tsx
examples/customization-theme-mui/src/App.tsx
examples/customization-top-menu-layout/src/App.tsx
examples/customization-top-menu-layout/src/components/sider/index.tsx

- base-antd
- base-chakra-ui
- base-headless
- base-mantine
- base-mui
- calendar-app
- command-palette-kbar
- core-use-import
- core-use-menu
- core-use-modal
- core-use-select
- customization-footer
- customization-login
- customization-offlayout-area
- customization-rtl
- customization-sider
- customization-theme-antd
- customization-theme-chakra-ui
- customization-theme-mantine
- customization-theme-mui
- customization-top-menu-layout
---------- 
-   [x] Changesets are …

feat(v4-examples): migrate router provider examples starts with "c" and "b"

---

documentation/docs/api-reference/mui/hooks/useDataGrid/index.md

Fixed the typo in `useDataGrid` docs.
Closes #3744

docs(use-data-grid): fix `useTable` usage

---

examples/customization-offlayout-area/src/components/sider/index.tsx
examples/pixels-admin/src/pages/auth/index.tsx

link from useRouterContext is deprecated

fix(v4-examples): remove use router context on examples

---

packages/react-router-v6/src/legacy/prompt.tsx
packages/remix/src/legacy/prompt.tsx

- Updated broken legacy prompt in `react-router-v6` in the latest updates.
- Updated remix's legacy prompt with `useBlocker`

fix(router): fix legacy prompts

---

examples/antd-audit-log/src/App.tsx
examples/auth-antd/src/App.tsx
examples/auth-auth0/src/App.tsx
examples/auth-chakra-ui/src/App.tsx
examples/auth-google-login/src/App.tsx
examples/auth-headless/src/App.tsx
examples/auth-keycloak/src/App.tsx
examples/auth-mantine/src/App.tsx
examples/auth-mui/src/App.tsx
examples/auth-otp/src/App.tsx
examples/customization-login/src/App.tsx
examples/data-provider-appwrite/src/App.tsx
examples/data-provider-nhost/src/App.tsx
examples/data-provider-strapi-graphql/src/App.tsx
examples/data-provider-strapi-v4/src/App.tsx
examples/data-provider-strapi/src/App.tsx
examples/data-provider-supabase/src/App.tsx
examples/finefoods-antd/src/App.tsx
examples/finefoods-antd/src/authProvider.ts
examples/finefoods-mui/src/App.tsx
examples/finefoods-mui/src/authProvider.ts

"When an unauthenticated user visited an undefined route, 'login?to=' was not added to the URL. It was only added if a route was defined. This has now changed and 'login?to=' is being added regardless of whether a route is defined or not."
For example as an unauthenticated user:
Let's say our defined routes are `post`, `users`, and `login`. Previously, if a user typed `localhost:3000/not-defined-route` in the URL, they would be redirected to `localhost:3000/login`. With this change, they will now be redirected to `localhost:3000/login?to=not-defined-route`.
-   [x] TypeScript …

fix(examples): auth redirect logic

---

.changeset/chilled-seas-press.md
packages/remix/src/prompt.tsx

`Prompt` component from the `@pankod/refine-remix-router`'s `routerProvider` was broken with the latest releases in the remix packages. We're now using the `useBlocker` from `@remix-run/react`

fix(remix): update broken prompt component

---

packages/core/src/hooks/auth/useLogin/index.spec.ts
packages/core/src/hooks/auth/useLogin/index.ts

fix(v4): fix `useLogin` redirection

---

examples/field-antd-use-checkbox-group/src/App.tsx
examples/field-antd-use-radio-group/src/App.tsx
examples/field-antd-use-select-basic/src/App.tsx
examples/field-antd-use-select-infinite/src/App.tsx
examples/field-mui-use-autocomplete/src/App.tsx
examples/finefoods-antd/src/App.tsx
examples/finefoods-mui/src/App.tsx
examples/form-antd-custom-validation/src/App.tsx
examples/form-antd-use-drawer-form/src/App.tsx
examples/form-antd-use-drawer-form/src/pages/posts/list.tsx
examples/form-antd-use-form/src/App.tsx
examples/form-antd-use-modal-form/src/App.tsx
examples/form-antd-use-steps-form/src/App.tsx
examples/form-chakra-ui-use-drawer-form/src/App.tsx
examples/form-chakra-ui-use-form/src/App.tsx
examples/form-chakra-use-modal-antd-form/src/App.tsx
examples/form-core-use-form/src/App.tsx
examples/form-mantine-use-drawer-form/src/App.tsx
examples/form-mantine-use-form/src/App.tsx
examples/form-mantine-use-modal-form/src/App.tsx
examples/form-mantine-use-steps-form/src/App.tsx
examples/form-mui-use-drawer-form/src/App.tsx
examples/form-mui-use-form/src/App.tsx
examples/form-mui-use-modal-form/src/App.tsx
examples/form-mui-use-steps-form/src/App.tsx
examples/form-react-hook-form-use-form/src/App.tsx
examples/form-react-hook-form-use-modal-form/src/App.tsx
examples/form-react-hook-form-use-steps-form/src/App.tsx
examples/form-save-and-continue/src/App.tsx

added: `<UnsavedChangesNotifier/>` to examples starts with "f"

feat(examples): add `<UnsavedChangesNotifier/>` to examples starts with "f"

---

examples/base-antd/src/App.tsx
examples/base-chakra-ui/src/App.tsx
examples/base-headless/src/App.tsx
examples/base-mantine/src/App.tsx
examples/base-mui/src/App.tsx

Added default `options` and `UnsavedChangesNotifier`to examples start with "b" except blog examples.

feat(v4): add default `options` to examples start with "b" 

---

packages/codemod/src/transformations/refine3-to-refine4.ts
packages/codemod/src/transformations/v4/resourceName-to-resource.ts

ast explorer for debug
https://astexplorer.net/#/gist/f18703c7479f27c6b7c1579541add9c0/6e5d216a1a9d0168633a7254797e26a835e34ca4
before: 
```ts
const TestComponent = ({ resourceName }) => {
return (
<div>
<DeleteButton
size="small"
recordItemId={row.id}
resource={otherMockName}
></DeleteButton>
<ShowButton resourceNameOrRouteName="testname"></ShowButton>
<EditButton resourceNameOrRouteName={MOCK_NAME}></EditButton>
<CloneButton resourceName="testname"></CloneButton>
<ListButton resourceName={MOCK_NAME}></ListButton>
<RefreshButton resourceName={`${MOCK_NAME}-1`}/>
<OtherComponent resourceName="otherResource"/> 
</div>
);
};
```
after:
```ts
const TestComponent = ({ resourceName }) => {
return (
<div>
<DeleteButton
size="small"
recordItemId={row.id}
resource={otherMockName}
></DeleteButton> …
```

feat(v4-codemod): `resourceName` or `resourceNameOrRouteName` transformation for buttons

---

packages/core/src/hooks/form/useForm.ts

If the detected action is not `edit` or `clone`, it is set as `create`. This also allows for the detection of `create` in the list route by default.

fix(v4-core): use form default action

---

packages/core/src/definitions/helpers/menu/__tests__/create-resource-key.test.ts
packages/core/src/definitions/helpers/menu/__tests__/create-tree.test.ts
packages/core/src/definitions/helpers/menu/create-resource-key.ts
packages/core/src/definitions/helpers/menu/create-tree.ts
packages/core/src/hooks/menu/useMenu.spec.tsx
packages/core/src/hooks/menu/useMenu.tsx

- Updated `selectedKey` value with `/` for both legacy and new usage.
- Fixed the `route` not being checked for legacy routers.

fix(use-menu-v4): keys not properly working for legacy

---

packages/react-router-v6/src/legacy/routeProvider.tsx

With no params to identify the request as the route provider call, use of `Authenticated` component in the route causes the invalidation of the `useIsAuthenticated` hook, which refreshes the router. Which eventually causes the `Authenticated` to re-render and loop.

fix(react-router-v6): fix legacy route rendering invalidation issue

---

packages/react-router-v6/src/legacy/prompt.tsx
packages/react-router-v6/src/unsaved-changes-notifier.tsx
packages/react-router-v6/src/use-prompt-workaround.ts

Fixed `UnsavedChangesNotifier` internal effect for multiple listener subscriptions.

fix(v4-react-router): Update `usePrompt` and `UnsavedChangesNotifier`

---

documentation/docs/migration-guide/3x-to-4x.md
documentation/docs/packages/documentation/routers/react-router-v6.md
documentation/docs/packages/documentation/routers/remix-router.md

Added basic and advances use examples to `@refinedev/react-router-v6` docs.

docs(v4-routers): add examples for `react-router-v6` usage

---

packages/codemod/src/transformations/v4/fix-v4-deprecations.ts

before:
```ts
const PostsList = () => {
const select1 = useSelect({
resource: "categories",
});
const select2 = useSelect({
resource: "categories",
pagination: {
mode: "off",
},
});
const select3 = useSelect({
resource: "categories",
pagination: {
mode: "server",
},
});
const select4 = useSelect({
resource: "categories",
hasPagination: true,
});
const select5 = useSelect({
resource: "categories",
hasPagination: false,
});
return null;
};
```
after:
```ts
const PostsList = () => {
const select1 = useSelect({
resource: "categories",
pagination: {
mode: "server"
}
});
const select2 = useSelect({
resource: "categories",
pagination: {
mode: "off",
},
});
const select3 = useSelect({
resource: "categories",
pagination: {
mode: "server",
},
});
const select4 = useSelect({
resource: "categories", …
```

fix(codemod): if use-select has pagination property, dont add

---

packages/core/src/hooks/menu/useMenu.tsx

`useMenu` not reacting to every other change in `translate` function, which causes `<Sider>` components to use wrong language in renders.

fix(core): add missing key in dependency array for translations in `useMenu`

---

documentation/docs/migration-guide/3x-to-4x.md

Added missing info about `useRouterContext` to the migration guide

docs(migration-guide): add `useRouterContext` to migration guide

---

.changeset/stupid-pears-eat.md
packages/core/src/definitions/helpers/legacy-resource-transform/index.ts

Added missing `meta.label` check to resource transform helper.

fix(core): add `meta` and `options` to pick `label`

---

examples/access-control-casbin/config-overrides.js

access-control-casbin example was giving following error:
```ts
Module not found: Error: Can't resolve 'process/browser' in '/Users/alicanerdurmaz/Desktop/refine/node_modules/uvu/node_modules/kleur'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```
added: webpack rule solve this issue.
---
Thanks @DoguhanOzgurAkca for this issue 🚀

fix(examples): access control casbin mjs not resolved

---

.changeset/five-bats-chew.md
packages/core/src/hooks/accessControl/useCan/index.spec.ts
packages/core/src/hooks/accessControl/useCan/index.ts

resource's icon parameter sanitized on useCan hook
- #3681

fix: resource's icon parameter sanitized on useCan hook

---

packages/nextjs-router/src/app/index.ts

Small fix for incorrect import in the new v4 RefineRoutes.
Closes #3862

fix: correct import of RefineRoutes for Next.js appDir

---

examples/multi-tenancy-appwrite/src/components/sider/index.tsx

Fixed the `<Menu>` component theme by passing "dark".

fix: update sider's menu theme on the example

---

documentation/docs/migration-guide/3x-to-4x.md
documentation/docs/migration-guide/router-provider.md

Added a section about customized `<Sider>` components and necessary changes related to router providers.

docs(migration-guide): add custom `<Sider>` section

---

.changeset/sixty-comics-smash.md
examples/form-mui-use-steps-form/src/App.tsx
examples/form-mui-use-steps-form/src/pages/posts/create.tsx
examples/form-mui-use-steps-form/src/pages/posts/edit.tsx
packages/react-hook-form/src/useStepsForm/index.ts

With #3307 change, steps form was not working expected in "edit" mode.
The `keepValues` is prevent the change form initial values. That's why I removed it.
I reproduced the #3290 issue, if the user uses `setValue` instead of `update` it's fine.

fix(react-hook-form):  update steps form `reset` options and fix minor issues on the example

---

.changeset/few-mirrors-think.md
.changeset/strange-rivers-learn.md
examples/form-chakra-ui-use-drawer-form/src/components/createPostDrawer/index.tsx
examples/form-chakra-ui-use-drawer-form/src/components/editPostDrawer/index.tsx
examples/form-chakra-use-modal-antd-form/src/components/editPostModal/index.tsx
packages/chakra-ui/src/components/crud/create/index.tsx
packages/chakra-ui/src/components/crud/edit/index.tsx
packages/chakra-ui/src/components/crud/list/index.tsx
packages/chakra-ui/src/components/crud/show/index.tsx
packages/core/src/components/authenticated/index.tsx
packages/ui-tests/src/tests/crud/create.tsx
packages/ui-tests/src/tests/crud/edit.tsx
packages/ui-tests/src/tests/crud/list.tsx
packages/ui-tests/src/tests/crud/show.tsx

fixed(chakra-ui): When `title` prop is `false` in crud components, the default `title` was rendered. It should not render anything.
All test passed. 

fix(chakra-ui): when title prop is false in crud components, should not render

---

documentation/src/components/live-preview/styles.module.css

When live-previews are `headless`, live-preview's background color was black.
With this fix, the background will be white.
Dark mode toggle example still works as expected

fix(docs): add white background to live-preview when theme is dark

---

.changeset/odd-shoes-push.md
.changeset/smooth-planets-suffer.md
examples/form-antd-use-form/src/App.tsx
examples/form-antd-use-modal-form/src/App.tsx
packages/antd/src/hooks/form/useModalForm/index.spec.tsx
packages/antd/src/hooks/form/useModalForm/useModalForm.ts
packages/antd/src/types/sunflower.d.ts
packages/core/src/hooks/form/useForm.ts

`autoSubmitClose` and `autoResetForm` were not working even though they had these properties.
Now, both of them work properly.

fix: `useModalForm`'s `autoSubmitClose` and `autoResetForm` features

---

.changeset/chatty-squids-approve.md
packages/mantine/src/hooks/form/useForm/index.ts

Fixed an issue where the dirty state was not reset after setting initial values. This caused the form to be dirty even though changes were not made. For this reason, the UnSavedChangesNotifier was always shown when the user tried to leave the page.

fix(mantine): reset dirty state after setting initial values

---

.changeset/tricky-fishes-smile.md
packages/antd/src/components/fields/number/index.tsx
packages/chakra-ui/src/components/fields/number/index.tsx
packages/mantine/src/components/fields/number/index.tsx
packages/mui/src/components/fields/number/index.tsx
packages/ui-tests/src/tests/fields/number.tsx

Fixed an issue where the `<NumberField />` component would throw an error if the `value` prop was set to `undefined`.

fix: update `<NumberField>`'s number conversion

---

.changeset/selfish-sloths-itch.md
packages/antd/src/components/themedLayout/title/index.tsx

Fixed: `<ThemedTitle>` font size was can't be changed from parent because `<Space>` has the default font size.

fix(antd): themed title font size

---

.changeset/thin-candles-jump.md
packages/cli/src/cli.ts
packages/cli/src/commands/runner/projectScripts.ts
packages/cli/src/commands/runner/runScript.ts
packages/cli/src/definitions/projectTypes.ts
packages/cli/src/utils/project/index.ts
packages/cli/src/utils/resource/index.ts
packages/cli/tsup.config.ts

fixed: refine --version doesn't return refine cli's version.
fixed: add error message if user tries to run script with unsupported package.
fixed: added "unknown" project type as fallback.
feat: added parcel support

fix(cli): wrong version output, added unknown project type, added parcel support

---

examples/form-antd-use-steps-form/src/pages/posts/create.tsx
examples/form-antd-use-steps-form/src/pages/posts/edit.tsx

To fix deprecated values., remove `<Steps>` component on examples and used `items` instead.

fix: remove `Steps` on examples and use `items` instead

---

packages/antd/src/components/breadcrumb/index.tsx

To fix deprecated usage, `Breadcrumb` component was updated according to antd docs.

fix(antd): update `Breadcrumb` to fix deprecated usage

---

documentation/docs/api-reference/core/hooks/data/useCustom/index.md
documentation/docs/api-reference/core/hooks/data/useCustomMutation/index.md

Removed the `resource` arg on `successNotification` and `errorNotification` of the `useCustom` hook.

docs: remove the unreceived argument

---

documentation/docs/api-reference/core/hooks/data/useCustom/index.md

Added FAQ section to `useCustom` hook about how to invalidate a custom query.

docs: add FAQ section about how to invalidate a custom query

---

documentation/docs/api-reference/chakra-ui/components/basic-views/create.md
documentation/docs/api-reference/chakra-ui/components/basic-views/edit.md
documentation/docs/api-reference/chakra-ui/components/basic-views/show.md
documentation/docs/api-reference/chakra-ui/components/fields/boolean.md
documentation/docs/api-reference/chakra-ui/theming.md
documentation/docs/api-reference/mantine/components/fields/boolean.md
documentation/docs/api-reference/mantine/theming.md
documentation/docs/api-reference/mui/components/fields/boolean.md
documentation/docs/api-reference/mui/theming.md
packages/live-previews/package.json
packages/live-previews/src/scope/antd.tsx
packages/live-previews/src/scope/map.tsx
packages/live-previews/src/scope/mui.tsx
packages/live-previews/src/scope/tabler-icons.tsx
packages/live-previews/src/utils/check-package.ts

Added missing icons from `@tabler/icons` and `@ant-design/icons`.
Only adding the ones that are used in `create-refine-app` templates.

fix(live-previews): missing icons in live previews

---

packages/live-previews/src/utils/development-cookie.ts
packages/live-previews/src/utils/replace-imports.ts

Added a simple method to reveal the incoming and used code blocks in live previews. 
Enabled by setting the `refine-live-preview-development-mode` cookie to `true`

feat(live-previews): add code reveal cookie

---

documentation/docs/packages/documentation/routers/nextjs-router.md

Removed redundant empty title from nextjs-router documentation.
Closes #4011

fix: remove empty title

---

.changeset/honest-balloons-call.md
.changeset/seven-numbers-divide.md
.changeset/wild-humans-float.md
packages/antd/src/components/themedLayout/title/index.tsx
packages/chakra-ui/src/components/themedLayout/title/index.tsx
packages/mui/src/components/themedLayout/sider/index.tsx
packages/mui/src/components/themedLayout/title/index.tsx
packages/mui/src/theme/palette/index.tsx

chakra-ui
-   Added: `wrapperStyles` prop to `<ThemedTitle>` component to allow for custom styles to be passed in.
-   Added: `textDecoration: none` to `<ThemedTitle>` component.
antd
-   Added: `wrapperStyles` prop to `<ThemedTitle>` component to allow for custom styles to be passed in.
-   Added: `textDecoration: none` to `<ThemedTitle>` component.
mui
- Added: default `gap: 8px` to `<ThemedTitle>` component.

feat(mui-themed-title): add default flex gap

---

documentation/docs/examples/auth-provider/google-auth.md

Add a note on adding URLs to OAuth app settings in Google Auth example.
**Doc View**

docs:  add note on adding URLs to OAuth app settings in example

---

.changeset/unlucky-jeans-know.md
packages/mui/src/components/themedLayout/header/index.tsx
packages/mui/src/components/themedLayout/sider/index.tsx

The color of the toggle button in the `<ThemedSider>` and `<ThemedHeader>` does not meet the contrast ratio. This is now fixed.

fix(mui): sider toggle button color

---

packages/live-previews/pages/preview.tsx
packages/live-previews/src/scope/google.tsx
packages/live-previews/src/utils/replace-imports.ts

Added a simple mock for google auth in live previews.

feat(live-previews): add mock google auth

---

.changeset/hot-bobcats-bow.md
packages/mantine/src/components/themedLayout/sider/index.tsx

The `wrapperStyles` properties of `<ThemedSider>`'s `<ThemedTitle>` have been moved to the parent component. As a result, it is now possible to pass a custom `<Title>` component to `<ThemedLayout>` that will be styled correctly.

fix(mantine): custom themed title styles

---

examples/blog-invoice-generator/src/components/client/item.tsx
examples/finefoods-antd/src/components/header/index.tsx
examples/i18n-nextjs/src/components/header/index.tsx
examples/i18n-react/src/components/header/index.tsx

Fixed deprecated `<Dropdown>` prop. To solve it, used `menu` instead of the deprecated `overlay`.

fix: use `menu` instead of the deprecated `overlay` to remove warn

---

.changeset/five-kids-double.md
packages/inferencer/src/inferencers/mui/list.tsx

Update the wrong import path.
close #4087

fix: `Checkbox` import path in Mui inferencer

---

.changeset/dull-ducks-brake.md
.changeset/red-monkeys-beam.md
.changeset/unlucky-penguins-dance.md
packages/antd/src/hooks/form/useDrawerForm/index.spec.tsx
packages/antd/src/hooks/form/useDrawerForm/useDrawerForm.ts
packages/antd/src/hooks/form/useModalForm/index.spec.tsx
packages/antd/src/hooks/form/useModalForm/useModalForm.ts
packages/mantine/src/hooks/form/useModalForm/index.ts
packages/react-hook-form/src/useModalForm/index.spec.ts
packages/react-hook-form/src/useModalForm/index.ts

Updated `useModalForm` and `useDrawerForm` hook's `show` method to check if there's an `id` present or provided. If there is, it will continue to show the modal. If not, the modal will not show. 
Resolves #4062

fix(use-modal-form): add `id` check to `show` method

---

.changeset/cool-vans-raise.md
.changeset/olive-rabbits-wave.md
.changeset/thin-ravens-smoke.md
packages/antd/src/hooks/form/useDrawerForm/useDrawerForm.ts
packages/antd/src/hooks/form/useModalForm/useModalForm.ts
packages/mantine/src/hooks/form/useModalForm/index.ts
packages/react-hook-form/src/useModalForm/index.spec.ts
packages/react-hook-form/src/useModalForm/index.ts

Fixed `create` action not working issue with `useModalForm` and `useDrawerForm`.

fix(form): `useModalForm` and `useDrawerForm` with `create` action

---

.changeset/plenty-cows-love.md
packages/core/src/hooks/data/useMany.ts

With the `@refinedev/core`'s new version, we've replaced the `metaData` property with `meta`. This change was missed in the `useMany` hook, causing a break in the functionality of passing `meta` to data provider's `getMany`.

fix(core): add missing `meta` in `useMany`

---

documentation/docs/tutorial/4-adding-crud-pages/antd/add-edit-page.md

fix(docs): `configProvider` was missing from the antd edit page example, so i added it.

fix(docs): added config provider to antd edit page

---

documentation/docs/packages/documentation/inferencer.md

Added a section to the inferencer docs for the `hideCodeViewerInProduction` prop.

docs(inferencer): add section for `hideCodeViewerInProduction`

---

.changeset/nervous-seals-sit.md
packages/nextjs-router/src/pages/unsaved-changes-notifier.tsx

When using the `UnsavedChangesNotifier` component from the nextjs-router package, it is currently failing to block browser refreshes with a prompt. Normal router changes is working fine.
Issue is the incorrect callback from the `UseEffect` handling this part. `window.removeEventListener` returns undefined.

fix(nextjs-router) unsaved changes notifier, not blocking browser refreshes with prompt

---

.changeset/brown-birds-stare.md
packages/simple-rest/refine.config.js
packages/simple-rest/src/index.ts
packages/simple-rest/test/utils/generateFilter.spec.ts
packages/simple-rest/test/utils/generateSort.spec.ts
packages/simple-rest/test/utils/mapOperator.spec.ts

feat: `requiredPackages` added to refine.config.js
Now with that, CLI automatically installs the required packages for the project.
chore: deprecated warning added to `stringify` export. Users should use from `query-string` package instead.

feat(simple-rest): install required packages after swizzle

---

.changeset/smart-waves-remember.md
packages/core/src/definitions/helpers/router/__tests__/compose-route.ts
packages/core/src/definitions/helpers/router/__tests__/prepare-route-params.ts
packages/core/src/definitions/helpers/router/compose-route.ts
packages/core/src/definitions/helpers/router/prepare-route-params.ts
packages/core/src/hooks/breadcrumb/index.ts
packages/core/src/hooks/navigation/index.ts
packages/core/src/hooks/router/use-get-to-path/index.ts
packages/core/src/hooks/useSelect/index.spec.ts

When creating the routes with parameters internally, we were missing the `resource.meta` values which causes missing parameters when user defines a default parameter value in `resource.meta` and doesn't have any values in current `meta` or `params`.

fix(core): missing resource `meta` in route creation

---

.changeset/clean-actors-arrive.md
packages/hasura/src/dataProvider/index.ts
packages/hasura/test/getList/index.mock.ts

From the hasura documentation [here](https://hasura.io/docs/latest/schema/postgres/naming-convention/), for the graphql-default naming convention, the naming convention for enums is upper-cased. Currently the request are being made with the lowercase enum and not uppercase. 
The change mainly affects `sort`, desc gets changed to DESC and asc gets changed to ASC. the request from the refine client interface maintains the underscore and convertion to uppercase is only done at the API request layer. 
Current test have been updated to use UPPERCASE and not lowercase for graphql-default naming convention tests. 
closes #3482 
-   [x] Corresponding …

fix: change enum from lowercase to UPPERCASE in api request for hasura graphql default naming convention 

---

.changeset/curly-pandas-jump.md
.changeset/swift-worms-pump.md
packages/cli/src/commands/runner/projectScripts.ts
packages/cli/src/commands/swizzle/index.tsx
packages/cli/src/utils/package/index.ts
packages/cli/tsup.config.ts

- Updated the runner commands to look for all available `node_modules` to resolve the `.bin` instead of hard coded `./node_modules`. 
- Updated the swizzle command to look for all available `node_modules` to resolve refine package paths instead of hard coded `./node_modules`.

refactor(cli): add monorepo support

---

documentation/docs/tutorial/2-understanding-dataprovider/1-swizzle.md
documentation/package-lock.json
documentation/package.json
documentation/src/components/tutorial-toc/index.tsx

Made it possible to have markdown on the tutorial tracker 
from:
to:
It works for *cursive*, **bold**, ***cursive+bold*** and `code`. Additional markdowns can be added to the  `markdownConverter` function if needed
For the main titles(Create Data Provider with `swizzle` in this case) to work and convert properly, they need to be brought down from the front matter and placed below it with a # below. I am planning to go through all titles in tutorial soon anyways, so i can do those changes myself when i do that. 
If there is a way to keep them in the front matter yet use markdown, that can be implemented too but the Docusaurus discord said that it is not possible

feat(docs): added markdown feature to tutorial tracker

---

.changeset/brown-cameras-flow.md
packages/cli/src/commands/swizzle/index.tsx
packages/cli/src/utils/package/index.ts

Updated the package find logic and added file system check for double checking if the package is installed or not. This only takes effect in `swizzle` command.

fix(cli): add file system check to find installed packages

---

.changeset/silent-countries-jump.md
packages/mui/src/hooks/useAutocomplete/index.ts

`useAutocomplete` now resets the search value when the option is selected.
fixed #4164

fix(useAutocomplete): reset the search value when the option is selected

---

documentation/docs/faq.md
documentation/docs/packages/documentation/react-hook-form/useForm.md

added: MUI and Chakra UI example to `How can I change the form data before submitting it to the API?` section

feat(docs): add Material UI and Chakra UI example to faq

---

.changeset/clever-bananas-refuse.md
examples/finefoods-mui/src/pages/couriers/edit.tsx
packages/react-hook-form/src/useForm/index.ts
packages/react-hook-form/src/useStepsForm/index.spec.ts
packages/react-hook-form/src/useStepsForm/index.ts

fixed: The values of the registered fields were set using the `reset()` function. This has been changed to use `getValues()` instead. This fixes an issue where the values of the registered fields' dirty state were not being set correctly.
you can use this edit form component to test:
https://pastebin.mozilla.org/vUOT6sUX#L4
closes #4126

fix: use steps form dirty state

---

.changeset/flat-spiders-double.md
.changeset/slimy-buses-brush.md
.github/workflows/build-example-chunks.js
examples/monorepo-with-lerna-bootstrap/apps/my-refine-app/package.json
examples/monorepo-with-lerna/apps/my-refine-app/package.json
examples/monorepo-with-turbo/apps/my-refine-app/package.json
packages/chakra-ui/src/components/pages/error/index.tsx
packages/mantine/src/components/pages/error/index.tsx
packages/nextjs-router/src/pages/unsaved-changes-notifier.tsx

Fixed the `ErrorComponent` heights to not interfere with the header above when used inside `Layout` components.

fix(mantine-chakra-ui): overflow issue in `ErrorComponent`

---

examples/base-mantine/src/interfaces/index.d.ts
examples/base-mantine/src/pages/posts/create.tsx
examples/base-mantine/src/pages/posts/edit.tsx
examples/base-mantine/src/pages/posts/show.tsx
examples/field-antd-use-select-basic/src/interfaces/index.d.ts
examples/field-antd-use-select-basic/src/pages/posts/create.tsx
examples/field-antd-use-select-basic/src/pages/posts/edit.tsx
examples/field-antd-use-select-basic/src/pages/posts/show.tsx
examples/field-mui-use-autocomplete/src/interfaces/index.d.ts
examples/field-mui-use-autocomplete/src/pages/posts/create.tsx
examples/field-mui-use-autocomplete/src/pages/posts/edit.tsx

added: Material UI, Mantine, Ant Design multi-select usage examples to
- base-mantine
- field-antd-use-select
- field-mui-use-autocomplete

feat(examples): add multi select usage examples

---

.changeset/beige-toys-change.md
documentation/docs/api-reference/antd/components/themed-layout.md
documentation/docs/api-reference/chakra-ui/components/themed-layout.md
documentation/docs/api-reference/mantine/components/themed-layout.md
documentation/docs/api-reference/mui/components/themed-layout.md
packages/antd/src/components/themedLayoutV2/index.tsx
packages/antd/src/components/themedLayoutV2/sider/index.tsx
packages/antd/src/contexts/themedLayoutContext/index.tsx
packages/chakra-ui/src/components/themedLayoutV2/index.tsx
packages/chakra-ui/src/contexts/themedLayoutContext/index.tsx
packages/mantine/src/components/themedLayoutV2/index.tsx
packages/mantine/src/contexts/themedLayoutContext/index.tsx
packages/mui/src/components/themedLayoutV2/index.tsx
packages/mui/src/contexts/themedLayoutContext/index.tsx
packages/ui-types/src/types/layout.tsx

feat: `initialSiderCollapsed` added to `RefineThemedLayoutV2Props` to control initial state of `<ThemedSiderV2>`.
From now on, you can control the initial collapsed state of `<ThemedSiderV2>` by passing the `initialSiderCollapsed` prop to `<ThemedLayoutV2>`.
```tsx
<ThemedLayoutV2
initialSiderCollapsed={true} // This will make the sider collapsed by default
>
{/* .. */}
</ThemedLayoutV2>
```

feat: add `initialSiderCollapsed` prop to themed layout

---

documentation/docs/api-reference/core/hooks/auth/useOnError.md

added: An explanation of how **refine** internally uses `useOnError`.

feat(docs): update use-on-error documentation

---

.changeset/seven-seahorses-exercise.md
packages/antd/src/contexts/themedLayoutContext/index.tsx

fixed: `<ThemedSiderV2>` default collapsed value is true. should be false

fix(antd): sider default collapsed value is true. should be false

---

documentation/docs/examples/remix/oauth.md

fix(docs): with-remix-auth wrong example link

---

.changeset/sweet-tables-laugh.md
packages/core/src/hooks/data/useDelete.ts
packages/core/src/hooks/data/useDeleteMany.ts
packages/core/src/hooks/data/useUpdate.ts

Fix `queryKey` method params for `useDelete`, `useDeleteMany` and `useUpdate`

fix: `queryKey` method params for `useDelete`, `useDeleteMany` and `useUpdate`

---

.changeset/proud-rivers-rule.md
documentation/docs/api-reference/antd/components/themed-layout.md
documentation/docs/api-reference/chakra-ui/components/themed-layout.md
documentation/docs/api-reference/mantine/components/themed-layout.md
documentation/docs/api-reference/mui/components/themed-layout.md
packages/antd/src/components/themedLayoutV2/header/index.tsx
packages/chakra-ui/src/components/themedLayoutV2/header/index.tsx
packages/mantine/src/components/themedLayoutV2/header/index.tsx
packages/mui/src/components/themedLayoutV2/header/index.tsx
packages/ui-types/src/types/layout.tsx

Rename the header prop of `isSticky` to `sticky`. To provide backward compatibility `isSticky` has been deprecated.

fix: rename the header prop of `isSticky` to `sticky`

---

.changeset/loud-hats-reply.md
documentation/docs/advanced-tutorials/multi-tenancy/appwrite.md
documentation/docs/advanced-tutorials/multi-tenancy/strapi.md
documentation/docs/api-reference/antd/hooks/form/useDrawerForm.md
documentation/docs/api-reference/antd/hooks/form/useModalForm.md
documentation/docs/api-reference/antd/hooks/form/useStepsForm.md
documentation/docs/api-reference/mantine/hooks/form/useDrawerForm.md
documentation/docs/api-reference/mantine/hooks/form/useModalForm.md
documentation/docs/api-reference/mantine/hooks/form/useStepsForm.md
examples/blog-invoice-generator/src/components/company/create.tsx
examples/blog-invoice-generator/src/components/company/edit.tsx
examples/multi-tenancy-appwrite/src/components/product/create.tsx
examples/multi-tenancy-appwrite/src/components/product/edit.tsx
examples/multi-tenancy-strapi/src/components/product/create.tsx
examples/multi-tenancy-strapi/src/components/product/edit.tsx
examples/refine-week-invoice-generator/src/components/company/create.tsx
examples/refine-week-invoice-generator/src/components/company/edit.tsx
packages/antd/src/hooks/form/useDrawerForm/index.spec.tsx
packages/antd/src/hooks/form/useDrawerForm/useDrawerForm.ts
packages/antd/src/hooks/form/useModalForm/index.spec.tsx
packages/antd/src/hooks/form/useModalForm/useModalForm.ts

Form submit problem when `onFinish` is overridden in `useModalForm` and `useDrawerForm`

fix: `useModalForm` and `useDrawerForm` use `onFinish` prop

---

.changeset/fast-pianos-rest.md
packages/airtable/package.json
packages/appwrite/package.json
packages/graphql/package.json
packages/hasura/package.json
packages/medusa/package.json
packages/nestjsx-crud/package.json
packages/strapi-v4/package.json
packages/supabase/package.json

fixed: `./refine.config.js` added to `files` in `package.json` to include it in the npm package
closes #4282

fix(swizzle): add missing refine-config to npm files

---

packages/live-previews/package.json

added `--max-http-header-size` to live previews start and dev scripts to prevent 431 status code.

fix(live-previews): add max-http-header to start script

---

.changeset/curvy-carpets-push.md
.changeset/plenty-ducks-learn.md
.changeset/tidy-poems-hear.md
packages/antd/src/hooks/form/useDrawerForm/useDrawerForm.ts
packages/antd/src/hooks/form/useModalForm/useModalForm.ts
packages/mantine/src/hooks/form/useModalForm/index.ts
packages/react-hook-form/src/useModalForm/index.ts

`syncWithLocation.syncId` default to `true` for `useDrawerForm` and `useModalForm`

feat: `syncWithLocation.syncId` default to `true` for `useDrawerForm` and `useModalForm`

---

.changeset/smooth-goats-knock.md
packages/antd/src/components/buttons/save/index.tsx
packages/chakra-ui/src/components/buttons/delete/index.tsx
packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/create.test.tsx.snap
packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/edit.test.tsx.snap
packages/mantine/src/components/buttons/create/index.tsx
packages/mui/src/components/buttons/save/index.tsx

This fixes some of the classNames added in PR #4312.

fix: wrong className

---

cypress/support/commands/antd/index.ts
cypress/support/commands/refine/index.ts
cypress/support/commands/resource.ts
cypress/support/e2e.ts
cypress/support/index.d.ts
examples/form-antd-custom-validation/cypress.config.ts
examples/form-antd-custom-validation/cypress/e2e/all.cy.ts
examples/form-antd-custom-validation/package.json
examples/form-antd-use-drawer-form/cypress.config.ts
examples/form-antd-use-drawer-form/cypress/e2e/all.cy.ts
examples/form-antd-use-drawer-form/package.json
examples/form-antd-use-form/cypress.config.ts
examples/form-antd-use-form/cypress/e2e/all.cy.ts
examples/form-antd-use-form/package.json
examples/form-antd-use-modal-form/cypress.config.ts
examples/form-antd-use-modal-form/cypress/e2e/all.cy.ts
examples/form-antd-use-modal-form/package.json
examples/form-antd-use-modal-form/src/pages/posts/list.tsx
examples/form-antd-use-steps-form/cypress.config.ts
examples/form-antd-use-steps-form/cypress/e2e/all.cy.ts
examples/form-antd-use-steps-form/package.json

End-to-end (e2e) tests are added to examples.
Adding e2e tests to our examples will prevent us from introducing bugs when developing new features.
WIP

test(examples): add e2e to antd forms

---

packages/live-previews/src/scope/antd.tsx
packages/live-previews/src/scope/chakra.tsx
packages/live-previews/src/scope/mantine.tsx
packages/live-previews/src/scope/mui.tsx

`ThemedTitle` was mocked on live-previews to allow changing the title and the icon dynamically on the interactive builder (refine.new).
While making the switch from `ThemedTitle` to `ThemedTitleV2`, we've forgot to update the mocks to use the V2 component which broke the title and logo inputs which no longer updates the live preview accordingly. 

fix(live-previews): replace `ThemedTitle` mock with `ThemedTitleV2`

---

cypress/support/commands/material-ui/index.ts
cypress/support/e2e.ts
cypress/support/index.d.ts
examples/form-material-ui-use-drawer-form/cypress.config.ts
examples/form-material-ui-use-drawer-form/cypress/e2e/all.cy.ts
examples/form-material-ui-use-drawer-form/package.json
examples/form-material-ui-use-drawer-form/src/components/createPostDrawer.tsx
examples/form-material-ui-use-drawer-form/src/components/editPostDrawer.tsx
examples/form-material-ui-use-form/cypress.config.ts
examples/form-material-ui-use-form/cypress/e2e/all.cy.ts
examples/form-material-ui-use-form/package.json
examples/form-material-ui-use-form/src/App.tsx
examples/form-material-ui-use-form/src/pages/posts/create.tsx
examples/form-material-ui-use-form/src/pages/posts/edit.tsx
examples/form-material-ui-use-modal-form/cypress.config.ts
examples/form-material-ui-use-modal-form/cypress/e2e/all.cy.ts
examples/form-material-ui-use-modal-form/package.json
examples/form-material-ui-use-modal-form/src/components/createPostModal.tsx
examples/form-material-ui-use-modal-form/src/components/editPostModal.tsx
examples/form-material-ui-use-steps-form/cypress.config.ts
examples/form-material-ui-use-steps-form/cypress/e2e/all.cy.ts
examples/form-material-ui-use-steps-form/package.json
examples/form-material-ui-use-steps-form/src/pages/posts/create.tsx
examples/form-material-ui-use-steps-form/src/pages/posts/edit.tsx

End-to-end (e2e) tests are added to examples.
Adding e2e tests to our examples will prevent us from introducing bugs when developing new features.

test(examples): add e2e tets to Material UI form examples

---

packages/core/src/hooks/auth/useForgotPassword/index.spec.ts
packages/core/src/hooks/auth/useIsAuthenticated/index.spec.ts
packages/core/src/hooks/auth/useLogin/index.spec.ts
packages/core/src/hooks/auth/useLogout/index.spec.ts
packages/core/src/hooks/auth/useOnError/index.spec.ts
packages/core/src/hooks/auth/useRegister/index.spec.ts
packages/core/src/hooks/auth/useUpdatePassword/index.spec.ts

Refactor auth hook tests: 
| Before | After |
|--------|--------|
|`const { mutate: forgotPassword } = result.current ?? { mutate: () => 0, };` | `const { mutate: forgotPassword } = result.current;` |
| `const { mutateAsync: logout } = result.current!;` | `const { mutateAsync: logout } = result.current;` | 

refactor: remove `mutate: () => 0,` method and minor changes

---

packages/live-previews/src/scope/map.tsx
packages/live-previews/src/utils/replace-imports.ts

Added a package import replacement logic for subpath imports such as `@mui/material/*` and `@mui/icons-material/*`. Since we're replacing the imports with variables from our scope, we'll be translating the subpath imports into named imports to `@mui/material` or `@mui/icons-material` etc.

fix(live-previews): subpath import supports for material ui packages

---

.changeset/little-boats-complain.md
packages/inferencer/src/create-inferencer/index.tsx
packages/inferencer/src/use-infer-fetch/index.tsx

Updated the inference process for `list` and `create` actions to use all items in the list instead of just the first item. This is done to avoid breaking the output when a single record is corrupted or wrongfully inferred.
Now, for the `list` and `create` actions, each item in the list response will be used to infer the fields then the most repeated fields will be accepted as the type for the field. 
All snapshots are passing with no required changes.
Resolves #4330
- …

feat(inferencer): use multiple records for inference

---

.changeset/nasty-toys-doubt.md
packages/inferencer/src/inferencers/mantine/create.tsx
packages/inferencer/src/inferencers/mantine/edit.tsx

Fixed the code generation issue with Mantine's `create` and `edit` inferencers when used with `meta` values.

fix(inferencer): redundant braces in Mantine forms with `meta`

---

.changeset/sour-camels-switch.md
packages/mantine/src/components/pages/auth/components/forgotPassword/index.tsx
packages/mantine/src/components/pages/auth/components/register/index.tsx
packages/mantine/src/components/pages/auth/components/updatePassword/index.tsx

added: name attribute to input fields in `forgotPassword`, `register` and `updatePassword` forms.

feat(mantine): add name attribute to input fields in auth components

---

packages/live-previews/public/locales/de/common.json
packages/live-previews/public/locales/en/common.json

Added missing locale for live previews.
In `strapi-v4` templates, we have `blog-posts` resource which has no match in `live-previews` and caused `i18n` to fail.
In some data providers we have `created_at` instead of `createdAt` and `category_id` or `categoryId` instead of `category`.

fix(live-previews): add missing translations

---

.changeset/healthy-chairs-sneeze.md
packages/inferencer/src/inferencers/chakra-ui/list.tsx
packages/inferencer/src/inferencers/headless/list.tsx
packages/inferencer/src/inferencers/mantine/list.tsx
packages/inferencer/src/inferencers/mui/list.tsx

`translate` key was missing in table columns hooks, which causes headers of the table to not to change when selected locale is changed.

fix(inferencer): add missing `translate` to dependency arrays

---

.changeset/chilled-actors-sneeze.md
.changeset/unlucky-teachers-type.md
documentation/docs/api-reference/core/providers/i18n-provider.md
documentation/docs/packages/documentation/routers/nextjs-router.md
documentation/docs/packages/documentation/routers/react-router-v6.md
packages/core/src/definitions/helpers/generateDocumentTitle/index.spec.ts
packages/core/src/definitions/helpers/generateDocumentTitle/index.ts

Added missing `clone` action for document title generation. This fixes the issue of the document title not being generated when the `clone` action is used.
This change introduces the `documentTitle.{resourceName}.clone` key to the list of `i18n` keys that are used to generate the document title.
Default title for the `clone` action is `"#{{id}} Clone {{resourceName}} | refine"`.
Fixed the issue of `label` not taken into account with auto generated document titles. `label` will be prioritized over the resource name when generating the document title and the `label` will not be capitalized.
-   [x] Examples are updated/provided or not …

fix(core): missing `clone` action on document title generation

---

.changeset/famous-houses-compete.md
packages/react-router-v6/src/bindings.tsx

Fix the issue of `matchPath` when the resource action is defined as a function or an object. Switched to using matched route string instead of using the route value from the `resource` definition.

fix(react-router-v6): `params` fallback with `matchedRoute`

---

documentation/docs/api-reference/core/providers/live-provider.md

Added a part about graphql subscriptions to live provider doc.

docs: add graphql subscriptions section in live provider doc

---

.changeset/wise-jobs-rush.md
packages/core/src/hooks/useSelect/index.spec.ts
packages/core/src/hooks/useSelect/index.ts

`useMany` used to get default values data on `useSelect`.`queryOptions` were not being sent to `useMany`. From now, users can send `queryOptions` to `useMany`
closes #4408

fix(core): pass `queryOptions`or `defaultValueQueryOptions` to `useMany` on `useSelect`

---

documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md
documentation/docs/tutorial/1-getting-started/chakra-ui/3-generate-crud-pages.md
documentation/docs/tutorial/1-getting-started/headless/3-generate-crud-pages.md
documentation/docs/tutorial/1-getting-started/mantine/3-generate-crud-pages.md
documentation/docs/tutorial/1-getting-started/mui/3-generate-crud-pages.md
documentation/docs/tutorial/4-adding-crud-pages/antd/add-create-page.md
documentation/docs/tutorial/4-adding-crud-pages/antd/add-edit-page.md
documentation/docs/tutorial/5-understanding-authprovider/antd/2-auth-pages.md
documentation/docs/tutorial/5-understanding-authprovider/chakra-ui/2-auth-pages.md
documentation/docs/tutorial/5-understanding-authprovider/headless/2-auth-pages.md
documentation/docs/tutorial/5-understanding-authprovider/mantine/2-auth-pages.md
documentation/docs/tutorial/5-understanding-authprovider/mui/2-auth-pages.md

Added missing root page navigation to the first resource's list route in tutorial previews; this was causing the refine logo to navigate to a 404 page.

docs(tutorial): add missing root page navigation to previews

---

.changeset/little-buttons-try.md
packages/codemod/package.json

Fixed babel issue with codemod.

fix: lock @npmcli/package-json version to prevent babel issue

---

.changeset/curvy-shirts-smash.md
packages/inferencer/src/index.tsx
packages/inferencer/src/inferencers/antd/edit.tsx
packages/inferencer/src/inferencers/antd/show.tsx
packages/inferencer/src/inferencers/chakra-ui/__tests__/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/chakra-ui/edit.tsx
packages/inferencer/src/inferencers/chakra-ui/show.tsx
packages/inferencer/src/inferencers/headless/__tests__/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/headless/edit.tsx
packages/inferencer/src/inferencers/headless/show.tsx
packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/mantine/edit.tsx
packages/inferencer/src/inferencers/mantine/show.tsx
packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/mui/edit.tsx
packages/inferencer/src/inferencers/mui/show.tsx
packages/inferencer/src/utilities/id-quote-wrapper/index.test.ts
packages/inferencer/src/utilities/id-quote-wrapper/index.ts
packages/inferencer/src/utilities/index.ts

- fixed: Inferencer assumes `id` is number in custom pages.
From now on, if `id` is `typeof string`, and `inferencer` will infer it as `string`.
- snapshot tests updated
closes #4390 

fix(inferencer): assumes id is number in custom pages

---

.changeset/heavy-bugs-tan.md
packages/create-refine-app/package.json
packages/create-refine-app/src/index.ts

Waits on https://github.com/pankod/superplate/pull/345
Ability to disable telemetry through `--disable-telemetry` flag 

chore(create-refine-app): disable telemetry by flag

---

.changeset/fast-squids-kiss.md
packages/nextjs-router/src/app/bindings.tsx

There was an unhandled case for `pathname` returned from `usePathname` hook in `appDir` router of `@refinedev/nextjs-router`. The `usePathname` hook can return `string` or `null`. Only `string` was handled. Now added proper handling for `null` value as well.

fix(nextjs): unhandled `null` in `pathname` for `appdir`

---

documentation/src/components/example-list/index.tsx

fixed: margins
fixed: prose css class cannot override in production

fix: examples page css

---

.changeset/lucky-seals-yell.md
packages/inferencer/src/components/shared-code-viewer/index.tsx

Updated media query condition to 449px.

fix(inferencer): `show code` button isn't visible on tutorials.

---

documentation/src/refine-theme/css/fonts.css
documentation/tailwind.config.js

feat: code block font updated
left is source code pro(new), right is roboto mono (old)

feat(docs): update code block font to source-code-pro

---

documentation/src/refine-theme/doc-sidebar.tsx

On mobile devices, the sidebar tree renders slowly. to fix this issue we disable collapsed items rendering

feat(docs): do not render sidebar item if its collapsed

---

.changeset/perfect-students-knock.md
packages/core/src/hooks/export/index.spec.ts
packages/core/src/hooks/export/index.ts

fixed: `useExport`'s `resource` props is not working.
With this fix, `useExport` will now work with `resource` props.
```ts
useExport({
resource: "users",
});
```
#4479 

fix(core): pass resource from props to useExport

---

.changeset/calm-waves-smile.md
packages/ui-tests/src/tests/layout/header.tsx

Updated the common header tests to fallback to `img` role if `presentation` does not exists.

fix(ui-tests): update header layout tests

---

.changeset/pink-pugs-walk.md
packages/mui/src/theme/index.ts

Fix `Button` text color on [`RefineThemes`](https://refine.dev/docs/api-reference/mui/theming/#predefined-themes)

fix: `@refinedev/mui` Button text color

---

.github/workflows/e2e-examples.js

Cypress grouping feature wasn't working as expected since it was waiting 30 seconds to finalize the `group run` and wouldn't accept new results to the group. Now I've increased this wait time to 5 minutes, so our tests should be able to grouped together.
After this PR, cypress results page looks way more readable
https://cloud.cypress.io/projects/sq5j3e/runs/9304

chore: remove ci-build-id and update group param for cypress

---

packages/mui/src/theme/index.ts

Material-ui `contained` and `primary` button color

fix: material-ui `contained` and `primary` button color

---

examples/inferencer-antd/cypress/e2e/all.cy.ts
examples/inferencer-chakra-ui/cypress/e2e/all.cy.ts
examples/inferencer-headless/cypress/e2e/all.cy.ts
examples/inferencer-mantine/cypress/e2e/all.cy.ts
examples/inferencer-material-ui/cypress/e2e/all.cy.ts

The inferencer tests were not passing because it couldn't find the getCategories intercept. getCategories intercept deleted because it is not needed

fix(examples): inferencer e2e wait category intercept

---

.changeset/tame-parents-behave.md
packages/react-hook-form/src/useForm/index.ts

fixed: `handleSubmitReactHookForm` now returns a Promise without awaiting it.
With this change, unhandled errors will propagate to the caller.

fix(react-hook-form): unhandled error on submit

---

documentation/src/components/blog/featured-blog-post-item/index.js
documentation/src/theme/BlogPostItem/index.js

Replaced `<label>`s with `<Link>` components to make tags clickable.

docs(blog): add links to blog post item tags list

---

.changeset/great-ducks-pay.md
packages/core/src/definitions/helpers/sanitize-resource/index.spec.ts
packages/core/src/definitions/helpers/sanitize-resource/index.ts
packages/core/src/hooks/accessControl/useCan/index.spec.tsx
packages/core/src/hooks/accessControl/useCan/index.ts
packages/core/src/hooks/useMeta/index.ts

Added the missing `resource` value in the `params` of the `useCan` calls. Resource value was sanitized but not passed properly to the `can` function of the `accessControlProvider`.
```sh
Test Suites: 124 passed, 124 total
Tests:       992 passed, 992 total
Snapshots:   18 passed, 18 total
Time:        86.508 s
Ran all test suites.
```

fix(core): add missing `resource` to `params` in `useCan` calls

---

documentation/docs/api-reference/general-concepts.md

Fix minor typo in `general-concepts` documentation.

docs: fix typo in general-concepts documentation

---

documentation/docs/api-reference/antd/components/basic-views/create.md
documentation/docs/api-reference/antd/components/basic-views/edit.md
documentation/docs/api-reference/antd/components/basic-views/show.md
documentation/docs/api-reference/chakra-ui/components/basic-views/create.md
documentation/docs/api-reference/chakra-ui/components/basic-views/edit.md
documentation/docs/api-reference/chakra-ui/components/basic-views/show.md
documentation/docs/api-reference/mantine/components/basic-views/create.md
documentation/docs/api-reference/mantine/components/basic-views/edit.md
documentation/docs/api-reference/mantine/components/basic-views/show.md
documentation/docs/api-reference/mui/components/basic-views/create.md
documentation/docs/api-reference/mui/components/basic-views/edit.md
documentation/docs/api-reference/mui/components/basic-views/show.md

Fixed live-previews where the `goBack` prop doesn't work.

docs: fix live-previews where the `goBack` prop doesn't work

---

.changeset/tidy-ads-rest.md
documentation/docs/api-reference/antd/components/breadcrumb.md
packages/antd/src/components/breadcrumb/index.tsx

Fixed the issue that the `icon` and `label` to be misaligned in the `Breadcrumb` component.
The tests are not affected.

fix(antd): `icon` and `label` alignment in `Breadcrumb` component

---

.changeset/loud-bears-yell.md
packages/inferencer/src/compose-inferencers/index.test.ts
packages/inferencer/src/compose-inferencers/index.ts
packages/inferencer/src/compose-transformers/index.test.ts
packages/inferencer/src/compose-transformers/index.ts
packages/inferencer/src/create-inferencer/index.tsx
packages/inferencer/src/field-inferencers/array.ts
packages/inferencer/src/field-inferencers/object.ts
packages/inferencer/src/field-transformers/relation-to-fieldable.ts
packages/inferencer/src/types/index.ts

Updated inferencer functions to check for relational fields with representable values. If the inferencer type is `show` or `list`, the inferencer will use the available properties to show the field instead of trying to fetch the relational data.
```tsx
// posts/1
{
id: 1,
name: "Post 1",
tags: [
{
id: 5,
name: "Tag 5"
},
{
id: 6,
name: "Tag 6"
}
],
content: "...",
}
```
Above structure will show the `tags` field in list and show inferencers using the `name` property instead of trying to fetch the relational data. But `edit` and `create` inferencers will still work with the relational data.
Resolves #4575 
-   [x] Examples are …

fix(inferencer): skip relation when field has fieldable properties

---

documentation/blog/2023-06-12-astro-js.md

[The blog post ](https://refine.dev/blog/astro-js-guide/#installation-and-setup)provides incorrect syntax, not related to Astrojs.

Fix Astro.js iteration expression in blog post on Astro.js

---

.changeset/long-zoos-decide.md
packages/mantine/src/providers/notificationProvider.tsx

fixed: `description` prop does not show up in Mantine notification.
With this fix, you can now use `description` prop to show a description in the notification.
```tsx
import { useNotification } from "@refinedev/core";
const { open } = useNotification();
open?.({
description: "This is a description",
message: "This is a message",
type: "progress",
});
```

fix(mantine): notification description does not work

---

examples/table-antd-use-table/cypress/e2e/all.cy.ts

Sometimes the test will fail because the table data is not enough to paginate, so I clear the table filter before test cases.

test: fix "antd-use-table" e2e test issues

---

documentation/docs/api-reference/mui/theming.md

fixed: wrong example code.
Page: https://refine.dev/docs/api-reference/mui/theming/#overriding-variables
Styling tested manually.
closes #4631

fix(docs): material-ui overriding theme example code sample

---

documentation/src/components/blog/featured-blog-post-item/index.js
documentation/src/theme/BlogPostItem/index.js

fix(docs): blog page tag overflow

---

documentation/src/pages/about/index.tsx

fixed: `not-prose`class moved to parent otherwise it doesn't work. with that fix child's default classes are removed.
preview: https://64b7efd4dbe8441bc27fdfd8--refine-doc-preview.netlify.app/about/

fix(docs): about page team members image align

---

examples/form-antd-use-drawer-form/package.json
examples/form-antd-use-form/package.json
examples/form-antd-use-modal-form/package.json
examples/form-antd-use-steps-form/package.json

There are build problems for Codesandbox examples of the hooks below
- [useDrawerForm](https://refine.dev/docs/api-reference/antd/hooks/form/useDrawerForm/#example)
- [useForm](https://refine.dev/docs/api-reference/antd/hooks/form/useForm/#example)
- [useModalForm](https://refine.dev/docs/api-reference/antd/hooks/form/useModalForm/#example)
- [useStepsForm](https://refine.dev/docs/api-reference/antd/hooks/form/useStepsForm/#example)
The error is `Error: Cannot find module '@vitejs/plugin-react'`
closes #4699 
-   [x] …

fix(docs): @vitejs/plugin-react was missing for some ant design hooks

---

.changeset/silent-rockets-tickle.md
packages/create-refine-app/package.json

Bumped `superplate-cli` version to `1.17.2` for latest prompt changes for `create-refine-app`.

chore: bump superplate-cli version for create-refine-app

---

documentation/blog/2023-05-03-react-date-picker.md

fixed the following:
To: 
Closes issue #4702 

docs: correct symbol for date picker

---

.changeset/nice-readers-happen.md
packages/inferencer/src/components/shared-code-viewer/index.tsx
packages/inferencer/src/inferencers/chakra-ui/__tests__/__snapshots__/create.test.tsx.snap
packages/inferencer/src/inferencers/chakra-ui/__tests__/__snapshots__/edit.test.tsx.snap
packages/inferencer/src/inferencers/chakra-ui/__tests__/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/chakra-ui/__tests__/__snapshots__/list.test.tsx.snap
packages/inferencer/src/inferencers/chakra-ui/__tests__/__snapshots__/show.test.tsx.snap
packages/inferencer/src/inferencers/headless/__tests__/__snapshots__/create.test.tsx.snap
packages/inferencer/src/inferencers/headless/__tests__/__snapshots__/edit.test.tsx.snap
packages/inferencer/src/inferencers/headless/__tests__/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/headless/__tests__/__snapshots__/list.test.tsx.snap
packages/inferencer/src/inferencers/headless/__tests__/__snapshots__/show.test.tsx.snap
packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/create.test.tsx.snap
packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/edit.test.tsx.snap
packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/list.test.tsx.snap
packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/show.test.tsx.snap
packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/create.test.tsx.snap
packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/edit.test.tsx.snap
packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/list.test.tsx.snap
packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/show.test.tsx.snap

Added a classname to the inferencer's code viewer component to determine a simple selector for the code viewer.

chore(inferencer): add classname to code viewer

---

documentation/src/components/blog/featured-blog-post-item/index.js
documentation/src/theme/BlogPostItem/index.js

`refine-prose` class giving default margin to img elements. (it works only in production).
This causes an overflow problem on a blog item. 
```css
@media (min-width: 1536px)
.refine-prose :where(img):not(:where([class~=not-prose] *)) {
margin-bottom: 2em;
margin-top: 2em;
}
```
To remove `refine-prose` class, `not-prose` class added to the parent.
before:
after:

fix(docs): blog post image overflow

---

package.json

Updated the `lint-staged` command to use only staged files

fix: lint staged command

---

.changeset/beige-pants-speak.md
packages/core/src/components/telemetry/index.spec.tsx
packages/core/src/components/telemetry/index.tsx

Use `fetch` for telemetry calls as a fallback for `Image` when it's not available. This fixes an issue where telemetry calls would fail in some environments.
To make sure `fetch` is called only once, added a ref check before the effect.

fix(core): telemetry call fallback

---

.changeset/good-bags-explode.md
documentation/docs/api-reference/core/components/refine-config.md
documentation/docs/faq.md
packages/core/package.json
packages/core/src/components/containers/refine/index.tsx
packages/core/src/contexts/refine/IRefineContext.ts
packages/core/src/definitions/helpers/handleRefineOptions/index.ts

Removed `@tanstack/react-query-devtools` package and its usage from refine's core. This means that you will no longer see the dev tools icon in the bottom right corner of your app by default. If you want to use the dev tools, you can install the package (`@tanstack/react-query-devtools`) and use it in your app. 
`options.reactQuery.devtoolConfig` property has been removed from the `<Refine>` components props. This option will no longer be functional and will be removed in the next major release. If you have any configuration for the dev tools, you can pass it to the `ReactQueryDevtools` component directly.
-   [x] Examples are …

refactor(core): remove `@tanstack/react-query-devtools` dependency

---

documentation/docs/api-reference/antd/components/auth-page.md

Updated auth-page.md in ant design doc for a missing tag
closes #4768

docs: Correct auth-page.md missing closing tag

---

examples/field-material-ui-use-autocomplete/src/App.tsx

fixed: Material UI styles added to `field-material-ui-use-autocomplete` example.
before: 
after:

fix(examples): fix layout of field-material-ui-use-autocomplete

---

examples/base-antd/src/pages/posts/list.tsx

without `getDefaultFilter`, `<Table />` can't add a filtered indicator to UI(filtering/fetching logic still works). To resolve that problem, `getDefaultFilter` added to `<Table />`

fix(examples): add defaultFitleredValue to base-antd example

---

.changeset/lazy-trainers-boil.md
packages/chakra-ui/src/components/themedLayoutV2/index.tsx

fixes: #4730 
Fixed an issue in the sticky header feature of Chakra UI.

fix: to fix sticky header issue on Chakra UI use overflow "clip" instead of "auto"

---

.changeset/silly-pumas-vanish.md
documentation/docs/packages/documentation/data-providers/supabase.md
packages/supabase/src/dataProvider/index.ts
packages/supabase/test/getList/index.mock.ts
packages/supabase/test/getList/index.spec.ts

The supabase `getList` provider method uses the `count=exact` parameter. This makes the query very slow on large tables. As described [here](https://postgrest.org/en/stable/references/api/tables_views.html#exact-count).
Exposing the `count` property  of the `getList` method.
A test has been added, testing the header is set correctly.
Put …

[FEAT] supabase getList count option

---

examples/form-antd-mutation-mode/cypress/e2e/all.cy.ts

added `check({ force: true })` because inputs are absolute and on small viewports, inputs can be covered by another element. (z-index does not solves the cypress error)

fix(examples): form-antd-mutation-mode e2e test

---

examples/with-nextjs-next-auth/pages/_app.tsx

Fix build error for `with-nextjs-next-auth` example

fix: build error for `with-nextjs-next-auth` example

---

.changeset/quiet-tigers-work.md
packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/create.test.tsx.snap
packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/edit.test.tsx.snap
packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/list.test.tsx.snap
packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/show.test.tsx.snap
packages/mui/src/components/crud/create/index.tsx
packages/mui/src/components/crud/edit/index.tsx
packages/mui/src/components/crud/list/index.tsx
packages/mui/src/components/crud/show/index.tsx

This class has a negative margin:
```css
MuiCardHeader-action {
-webkit-flex: 0 0 auto;
-ms-flex: 0 0 auto;
flex: 0 0 auto;
-webkit-align-self: flex-start;
-ms-flex-item-align: flex-start;
align-self: flex-start;
margin-top: -4px;
margin-right: -8px;
margin-bottom: -4px;
}
```
Because of that, header buttons are not aligned properly along the header title.
To fix that, the margin property is set to 0.
￼
closes #4816 
-   [x] Tests …

fix(mui): list component header buttons not aligned

---

examples/app-crm/src/components/deal-kanban-won-lost-drop/index.module.css
examples/app-crm/src/components/deal-kanban-won-lost-drop/index.tsx

added: when the grabbed card is over on the won-lost drop area, the color should change

fix(app-crm) kanban won-lost drop area colors

---

examples/app-crm/src/components/quotes/pdf-export.tsx
examples/app-crm/src/routes/quotes/show/index.tsx

fixed: quote-pdf renders old data due to the `invalidate` issue. To fix that, we refetch new data before quote-pdf modal opens.
> I didn't use `useInvalidate` after fields were updated because all forms and quote-pdf in the same resource(quotes/detail). If we use `useInvalidate`, all `auto-save` forms will be flickering.

fix(app-crm): quote-pdf renders old data

---

examples/app-crm/src/components/company/card-view.tsx
examples/app-crm/src/components/company/table-view.tsx
examples/app-crm/src/components/custom-avatar-group.tsx

feat(app-crm): add custom avatar group

---

documentation/docs/faq.md

Added FAQ section about the `pagination.mode: "client"` usage with client side filtering and sorting.

docs: add FAQ section about client-side pagination with "client" mode

---

.changeset/nine-eagles-flow.md
packages/antd/tsup.config.ts
packages/chakra-ui/tsup.config.ts
packages/core/tsup.config.ts
packages/inferencer/tsup.config.ts
packages/kbar/tsup.config.ts
packages/mantine/tsup.config.ts
packages/mui/tsup.config.ts
packages/react-hook-form/tsup.config.ts
packages/react-table/tsup.config.ts

Updated our `esbuild` config to keep names of the components and hooks in releases for better debugging experience.

build: keep names on build

---

.changeset/early-radios-juggle.md
.changeset/quiet-ladybugs-wonder.md
.changeset/ten-dryers-yell.md
packages/chakra-ui/tsup.config.ts
packages/connect/tsup.config.ts
packages/core/tsup.config.ts
packages/hasura/tsup.config.ts
packages/inferencer/tsup.config.ts
packages/mui/tsup.config.ts
packages/nestjs-query/tsup.config.ts
packages/nhost/package.json
packages/nhost/tsup.config.ts
packages/shared/get-refine-core-version.ts
packages/shared/lodash-replace-plugin.ts
packages/shared/mark-as-external-plugin.ts
packages/shared/remove-test-ids-plugin.ts
packages/shared/replace-core-version-plugin.ts
packages/ui-tests/tsup.config.ts
packages/ui-types/tsup.config.ts

Moved the `esbuild` plugins to `packages/shared` for shared usage and fixed the `lodash` replacement plugin to skip unwanted files.

build: update `esbuild` plugins

---

examples/blog-refine-nextui/package.json

fixed: `blog-refine-nextui` dependency versions

fix: blog-refine-nextui lerna hoisted versions

---

.changeset/forty-kangaroos-remember.md
packages/devtools/package.json
packages/devtools/src/components/devtools-selector.tsx
packages/devtools/src/components/selector-hint.tsx
packages/devtools/src/panel.tsx

Added the ability to highlight in monitor with `click` instead of `space`

chore(devtools): click to highlight with selector

---

.changeset/rude-boxes-tease.md
packages/devtools-ui/jest.config.js
packages/devtools-ui/src/components/monitor-applied-filter-group.tsx
packages/devtools-ui/src/hooks/use-local-storage.test.ts
packages/devtools-ui/src/hooks/use-local-storage.ts
packages/devtools-ui/src/pages/monitor.tsx
packages/devtools-ui/src/utils/local-storage.test.ts
packages/devtools-ui/src/utils/local-storage.ts

fix: filtering monitor from DOM selector
feat: persistently store monitor filter in local storage
From now on, the monitor filter will be stored in local storage and will be restored on page load.

chore(devtools-ui): persistently store monitor filters in local storage

---

.changeset/grumpy-cameras-wonder.md

Recently, [we've updated README.md in most of the packages](https://github.com/refinedev/refine/pull/4989/files#diff-5b847048ab9829c8231dbb3630de903065ed83f63f693cb4f73454801a318919) but didn't do a patch release. This PR adds patch changeset for all relevant packages.

chore: add changeset for packages with README update

---

.changeset/modern-spies-warn.md
packages/cli/ANNOUNCEMENTS.md
packages/cli/package.json
packages/cli/src/cli.ts
packages/cli/src/commands/runner/dev/index.ts
packages/cli/src/components/announcement-message/index.tsx
packages/cli/src/definitions/announcement.ts
packages/cli/src/utils/announcement/index.tsx

refine CLI will now show announcements dynamically when there's an update from the refine team.

feat(cli): add dynamic announcements

---

.changeset/friendly-buttons-sit.md
packages/antd/refine.config.js
packages/antd/src/components/themedLayoutV2/sider/index.tsx
packages/chakra-ui/refine.config.js
packages/mantine/refine.config.js
packages/mui/refine.config.js

feat: deprecated `<ThemedLayout />` and `<Layout />` components removed from `swizzle`.
From now on, users can swizzle `<ThemedLayoutV2 />` component instead.
feat: swizzled `<ThemedLayoutV2 />` component destination changed to `src/components/layout/` from `src/components/themedLayout`.

feat: remove deprecated layout components from swizzle

---

.changeset/heavy-cows-happen.md
packages/mui/src/definitions/dataGrid/index.spec.ts
packages/mui/src/definitions/dataGrid/index.ts

MUI defines the operator for each column types in [here](https://github.com/mui/mui-x/tree/2d09dbc6e5d03c4e66765d225ef93d3984e300fc/packages/grid/x-data-grid/src/colDef). However, there were not enough conversion cases for the following operators, so I added them to the mapping.
- isAnyof: used in Numeric, SingleSelect, String
- contains: used in String,
- startsWith: used in String
- endsWith: used in String
I …

fix: add missing DataGrid operator conversion cases

---

.changeset/giant-islands-bathe.md
packages/hasura/src/dataProvider/index.ts
packages/hasura/src/utils/generateFilters.ts
packages/hasura/src/utils/generateUseListSubscription.ts
packages/hasura/test/utils/generateFilters.spec.ts

When using the Hasura provider with the 'graphql-default' naming convention, snake-case hasura operators (e.g. _is_null) were not converted to the correct case, causing query errors.
This problem is now fixed. Now the snake_case operator is converted according to the given naming convention (e.g. hasura-default: _is_null, graphql-default: _isNull).
- Snake case hasura operator correctly converted to case added.
- …

fix: convert hasura operator with graphql-default

---

.changeset/purple-fireants-collect.md
.changeset/thin-dryers-hear.md
packages/devtools-server/src/constants.ts
packages/devtools-server/src/serve-proxy.ts
packages/devtools-server/src/setup-server.ts
packages/devtools/src/utilities/use-selector.tsx

Devtools server was picking up the wrong port to run when there's a `PORT` environment variable. This causes showing the wrong page content in the devtools panel.

fix(devtools): conflicting `port` variable when using with `dev` command

---

.changeset/modern-cougars-arrive.md
packages/cli/package.json
packages/cli/src/commands/devtools/index.ts
packages/cli/src/components/update-warning-table/utils.tsx
packages/cli/src/utils/package/index.ts
packages/cli/src/utils/refine/index.ts

feat: From now on, `npm run refine devtools init` updates `@refinedev/core` to latest version.

feat(cli): check core package is up to date for devtools

---

.changeset/twelve-emus-invent.md
examples/base-antd/src/App.tsx
packages/core/src/contexts/data/IDataContext.ts
packages/core/src/index.tsx

feat: The parameter types of data provider methods have been exported.
From now on, you can use parameter types of Data Provider methods.
```ts
import type {
DataProvider,
GetListResponse
// mew exported types
GetListParams,
GetManyParams,
GetOneParams,
CreateParams,
CreateManyParams,
UpdateParams,
UpdateManyParams,
DeleteOneParams,
DeleteManyParams,
CustomParams,
} from "@refinedev/core";
const myDataProvider: DataProvider = {
getList: async (params: GetListParams): Promise<GetListResponse<any>> => {
return { data: [], total: 0 };
},
};
```
closes #4897
-   [x] …

feat(core): export parameter types of dataprovider methods

---

.changeset/fluffy-beers-drive.md
documentation/docs/api-reference/core/hooks/live/useSubscription.md
documentation/docs/api-reference/core/providers/live-provider.md
packages/core/src/contexts/live/ILiveContext.ts
packages/core/src/hooks/data/useInfiniteList.spec.tsx
packages/core/src/hooks/data/useInfiniteList.ts
packages/core/src/hooks/data/useList.spec.tsx
packages/core/src/hooks/data/useList.ts
packages/core/src/hooks/data/useMany.spec.tsx
packages/core/src/hooks/data/useMany.ts
packages/core/src/hooks/data/useOne.spec.tsx
packages/core/src/hooks/data/useOne.ts
packages/core/src/hooks/live/useResourceSubscription/index.ts
packages/core/src/hooks/live/useSubscription/index.spec.ts
packages/core/src/hooks/live/useSubscription/index.ts
packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap
packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/list.test.tsx.snap

feat: pass `dataPorviderName` to `liveProvider.subscription` method.
From now on, you can use the `dataProviderName` to distinguish between different data providers.
[Refer to documentation for more info about multiple data providers ->](https://refine.dev/docs/api-reference/core/providers/data-provider/#multiple-data-providers)
```ts
import { useForm, useList } from "@refinedev/core";
useList({
dataProviderName: "first-data-provider",
});
useForm({
dataProviderName: "second-data-provider",
});
```
```ts
import { LiveProvider } from "@refinedev/core";
export const liveProvider = (client: any): LiveProvider => {
return {
subscribe: ({ channel, types, params, callback, dataProviderName }) => {
console.log({ dataProviderName }); //  "second-data-provider"
},
};
};
```
-   [x] Corresponding …

feat(core): add `dataProviderName` to `liveProvider.subscribe` method

---

documentation/src/refine-theme/top-announcement.tsx

fixed: light mode announcement text color is wrong

fix(docs): light mode announcement text color is wrong

---

documentation/src/refine-theme/top-announcement.tsx

fix: "not-prose" className added to top announcement to remove "prose" styles 

fix(docs): add "not-prose" to top-announcement

---

.changeset/rude-terms-turn.md
packages/antd/src/components/undoableNotification/index.tsx
packages/antd/src/providers/notificationProvider/index.spec.tsx
packages/antd/src/providers/notificationProvider/index.tsx

fix: `undoableNotification` does not work when using `useNotificationProvider` due to a different `notification` instance.

fix(antd): undoableNotification doesn't work with useNotificationProvider

---

.changeset/large-beds-cry.md
packages/mui/src/definitions/dataGrid/index.spec.ts
packages/mui/src/definitions/dataGrid/index.ts
packages/mui/src/hooks/useDataGrid/index.ts

fix: map missing operators for useDataGrid hook.
-   number field, added `isAnyOf` operator.
-   string field, added `startsWith`, `endsWith` and `isAnyOf` operators.
fix: `isNull` and `isNotNull` doesn't trigger request.
When filter has a value `""`, it's ignored and doesn't trigger request.
Previously `isNull` and `isNotNull` operators weren't handled correctly and had value `""` by default.
With this change, these operators has `true` value, so they won't be ignored.

fix(mui): missing operators and bug with isNull, isNotNull operators

---

documentation/src/components/banner/banner-examples.tsx
documentation/src/components/banner/banner-image-with-text.tsx
documentation/src/components/banner/banner-sidebar.tsx

We were publishing duplicated events, so we are changing the name of the banner events.

chore(docs): update event name for banner events

---

.changeset/calm-drinks-happen.md
packages/antd/src/components/themedLayoutV2/index.tsx

fixed: antd default `<ThemedSiderV2 />` is not collapsing.

fix(antd): default sider is not collapsing

---

.changeset/calm-drinks-happen.md
packages/antd/src/components/themedLayoutV2/index.tsx

fixed: antd default `<ThemedSiderV2 />` is not collapsing.

fix(antd): sider not collapsing

---

.changeset/mighty-beds-glow.md
packages/devtools-server/src/index.ts

Updated the devtools running log after a successful start to a less eye-catching and distractive one to avoid taking focus from the actual development server logs.
Old:
New:

chore(devtools-server): update running log

---

.changeset/seven-pillows-sneeze.md
packages/core/src/hooks/auditLog/useLog/index.spec.ts
packages/core/src/hooks/auditLog/useLog/index.ts

Prevent calling `useGetIdentity` if `auditLogProvider.create` is not defined and audit logging is not possible for the case.

fix(core): prevent redundant `getIdentity` call in `useLog`

---

.changeset/little-beers-greet.md
packages/cli/src/commands/devtools/index.ts
packages/cli/src/utils/package/index.ts

Update `@refinedev/core` version check for devtools runner to do a wider check to locate the package and its version. If the location is not found, it will start devtools without a version check.

fix(cli): core version check for devtools

---

examples/data-provider-sanity/package.json

Fixes current example, without `liveProvider`. 
As `refine-sanity` is with `1.1.0` currently, it can't use `1.2.0`. Which was left to be reverted, and is fixed with this PR.
-  * [x] Corresponding issues are not needed
-  * [x] Docs are not needed
-  * [x] Examples are not needed
-  * [x] TypeScript definitions are not needed
-  * [x] Tests are not needed
-  * [x] Changesets are not needed

fix(data-provider-sanity): downgraded refine-sanity

---

.changeset/giant-dryers-beg.md
packages/core/src/hooks/data/useList.spec.tsx
packages/core/src/hooks/data/useList.ts

Fixed the issue of `useList` hook requiring an empty object as prop even if there was no parameter passed to it.
Added an additional test for the case with only router inference. Tested with the rest of the scenarios and it worked fine.

fix(core): optional `useList` params

---

.changeset/fifty-forks-melt.md
packages/mantine/README.md

Since we are supporting `mantine@5` for now, installation command in the readme installs latest version 7 and it creates confusion.
Updated mantine package readme to explicitly install version 5 for all mantine dependencies.

chore: update mantine installation command

---

.changeset/eleven-doors-repeat.md
packages/antd/package.json

Fixes: https://github.com/refinedev/refine/issues/5172

chore: bump @ant-design/pro-layout dependency version

---

.changeset/neat-ants-perform.md
packages/core/src/definitions/helpers/menu/create-tree.ts
packages/core/src/hooks/menu/useMenu.tsx

Using relative path insteead of path alias because path alias causes imported types being any during build/compilation process
closes #5179

fix: use relative path instead of path alias to import FlatTreeItem

---

documentation/src/components/sandpack/index.tsx
documentation/src/refine-theme/changing-text-element.tsx

Added section with sandpack content that is hidden for the users but crawlable for AI and bots. This will allow our chatbot to use code written in sandpack examples.

docs(beta): readable sandpack component

---

.changeset/selfish-fans-swim.md
.changeset/sharp-pots-deliver.md
packages/create-refine-app/package.json
packages/create-refine-app/src/greeting/index.ts
packages/create-refine-app/src/index.ts

Added a small intro animation when `create-refine-app` starts.
https://github.com/refinedev/refine/assets/11361964/32ecd3bd-27f0-45aa-bdc6-70c9da3b4fd2

feat(create-refine-app): intro animation

---

.changeset/cool-planets-bake.md
.changeset/cyan-falcons-know.md
packages/antd/src/components/autoSaveIndicator/index.tsx
packages/chakra-ui/src/components/autoSaveIndicator/index.tsx
packages/core/refine.config.js
packages/core/src/components/autoSaveIndicator/index.spec.tsx
packages/core/src/components/autoSaveIndicator/index.tsx
packages/core/src/components/index.ts
packages/core/src/interfaces/autoSave.ts
packages/mantine/src/components/autoSaveIndicator/index.tsx
packages/mui/src/components/autoSaveIndicator/index.tsx

- Added `<AutoSaveIndicator />` component to `@refinedev/core`
- Added `elements: { success, error, loading, idle }` prop to `AutoSaveIndicatorProps` to allow customizing state elements.
- Updated `@refinedev/antd`, `@refinedev/mantine`, `@refinedev/chakra-ui` and `@refinedev/mui` to use `<AutoSaveIndicator />` component of `@refinedev/core` with customized elements.
- 

feat(core): add `<AutoSaveIndicator />` component

---

documentation/docs/api-reference/core/hooks/useTable/index.md

This PR adds import statements to the `useTable` documentation under `Core API/Hooks/useTable`, as some properties are only available with `import { useTable } from "@refinedev/core"`. For example, changing examples such as:
```tsx
useTable({
pagination: {
pageSize: 20,
},
});
``` 
to:
```tsx
import { useTable } from "@refinedev/core"
useTable({
pagination: {
pageSize: 20,
},
});
``` 
It was confusing for myself …

docs: clarify imports for useTable core examples

---

.changeset/pretty-adults-search.md
packages/cli/package.json

Fixed the version of `node-emoji` to `2.1.0`. Since `v2.1.1` depends on an ESM-only package, it breaks the build.

fix(cli): fix node-emoji version to 2.1.0

---

.changeset/clever-meals-melt.md
packages/cli/package.json

Updated `node-emoji` package to `2.1.2` which fixes the cause of the bug.
https://github.com/omnidan/node-emoji/pull/154
fixes: #5279

fix: update node-emoji package for @refinedev/cli package

---

.changeset/early-mayflies-promise.md
packages/cli/package.json

Bump `node-emoji` dependency resolution to `^2.1.3` to fix broken CJS builds. Thanks to @JoshuaKGoldberg
Fixes #5279

fix(cli): bump `node-emoji` to `^2.1.3`

---

documentation/docusaurus.config.js

There was a change from `/api-references` to `/api-reference` which the redirects were not handled properly. Added a client redirect configuration to handle them.

docs: handle missing redirects

---

.changeset/good-hats-shop.md
.changeset/weak-bats-repair.md
packages/cli/src/commands/runner/dev/index.ts
packages/devtools-server/src/index.ts
packages/devtools-server/src/serve-ws.ts
packages/devtools-server/src/setup-server.ts

- `@refinedev/devtools-server`: Added error conditions on WS and HTTP servers to prevent crashing if ports are already in use.
- `@refinedev/cli`: Updated `--devtools` flag in dev command to allow disabling devtools by `--devtools=false`.
Resolves #5215
Resolves #5294

chore(devtools): avoid errors when ports are already in use

---

documentation/docs/getting-started/overview.md

Little typo with miss space char in the docs

docs: fixed typo on getting started page

---

documentation/docs/tutorial/4-adding-crud-pages/chakra-ui/adding-sort-and-filters.md

Fixed wrong code format like that:
https://refine.dev/docs/tutorial/adding-crud-pages/chakra-ui/adding-sort-and-filters/#sort-and-filters

docs: fixed wrong code formating in tutotial pages (chakra-ui)

---

documentation/src/css/custom.css
documentation/src/pages/about/index.tsx
documentation/src/pages/templates/index.tsx
documentation/src/refine-theme/common-themed-image.tsx
documentation/src/refine-theme/enterprise-flexibility.tsx
documentation/src/refine-theme/enterprise-frequent-updates.tsx
documentation/src/refine-theme/enterprise-get-support.tsx
documentation/src/refine-theme/enterprise-hero-section.tsx
documentation/src/refine-theme/enterprise-sso-mutlifactor-auth.tsx
documentation/src/refine-theme/templates-hero.tsx

While the images are conditionally rendered according to the `colorMode`, they are not rehydrated properly in the first render and are opened as default dark mode.
This issue is fixed by using https://docusaurus.io/docs/docusaurus-core#browseronly

fix(docs): images dont respect color mode

---

.github/workflows/build-example-chunks.js
.github/workflows/e2e-examples.js
.github/workflows/examples-build.yml
examples/base-antd/README.md

Updated `build-examples` workflows to only run build & tests for examples affected from the changed packages of the owner branch.
Previously it was trying to do the same but fails due to `lerna`'s `--since` command not working properly.
Previously this error has caused missing the broken e2e tests in `server-side-validation-material-ui` example.

ci(examples): updated example build script

---

documentation/docs/core/components/auto-save-indicator/index.md
documentation/docs/core/components/auto-save-indicator/usage.tsx
documentation/docs/guides-concepts/forms/index.md
documentation/docs/ui-integrations/ant-design/components/auto-save-indicator/index.md
documentation/docs/ui-integrations/chakra-ui/components/auto-save-indicator/index.md
documentation/docs/ui-integrations/mantine/components/auto-save-indicator/index.md
documentation/docs/ui-integrations/material-ui/components/auto-save-indicator/index.md
documentation/sidebars.js
documentation/src/css/custom.css

- Added API documentation for `<AutoSaveIndicator />` component of `@refinedev/core`.
- Updated UI integration versions to include info about the core's implementation.

docs(core): add `<AutoSaveIndicator />` docs

---

documentation/src/refine-theme/common-header/mobile-menu-modal.tsx
documentation/src/refine-theme/common-header/mobile-nav-item.tsx

fix(docs): landing mobile menu borders

---

.changeset/cyan-mangos-sneeze.md
packages/mantine/src/providers/notificationProvider.tsx

fixed: `useNotification.close("notification-key")` not working.
Closes #5433

fix(mantine): useNotification.close not working

---

.changeset/ten-numbers-warn.md
documentation/docs/routing/hooks/use-go/index.md
packages/core/src/hooks/router/use-go/index.spec.tsx
packages/core/src/hooks/router/use-go/index.tsx

Added the ability to pass `meta` properties when using `useGo`'s `go` function with `to` as a resource object. This allows you to pass additional path parameters to the path defined in the resources array within the `<Refine />` component. Resolves [#5451](https://github.com/refinedev/refine/issues/5451)
Assume we have the following resource defined in the `<Refine />` component:
```tsx
{
name: "posts",
list: "/posts",
edit: "/:foo/posts/:id/edit",
}
```
```tsx
import { useGo } from "@refinedev/core";
const MyButton = () => {
const go = useGo();
return (
<Button
onClick={() => {
go({
to: {
resource: "posts",
action: "edit",
id: "1",
meta: {
foo: "bar",
},
},
type: "push",
});
// generated path will be "/bar/posts/1/edit"
}}
>
Go Posts
</Button>
);
};
```
Resolves #5451
Please check all …

feat(core): add `meta` field to `useGo`

---

.changeset/hungry-dolls-dress.md
packages/antd/src/components/fields/markdown/index.tsx
packages/chakra-ui/src/components/fields/markdown/index.tsx
packages/mantine/src/components/fields/markdown/index.tsx
packages/mui/src/components/fields/markdown/index.tsx

Updated the usage of `remark-gfm` and casted as `any` to avoid type inconsistencies between `remark-gfm` and `react-markdown`.
closing #5463

fix(remark-gfm): cast as `any` to avoid type inconsistencies

---

cypress/support/commands/mantine/index.ts

Updated `fillForm` method for Mantine UI integrations in e2e test commands.

test(e2e): update mantine's form fill command to delay in textareas

---

.github/workflows/master-push.yml

Updated `master-push` action to use @refine-bot instead of Github Bot to commit changes.

ci(changesets): use refine bot to commit versions

---

documentation/src/css/custom.css
documentation/src/refine-theme/template-detail.tsx

- "run on your local" section moved to the top of description
- minor UI improvements
after:
before:

feat(docs): ui improvements on templates page

---

documentation/docs/data/packages/nestjs-query/index.md
documentation/docs/guides-concepts/data-fetching/index.md
packages/core/src/interfaces/metaData/graphqlQueryOptions.ts

- Updated data fetching guide's GraphQL section to explain newly added `meta.gqlQuery` and `meta.gqlMutation` fields.
- Added JSDoc comments to `GraphQLQueryOptions` interface.
- Upated example URL in `nestjs-query` docs.

docs: update data fetching guide graphql section

---

examples/app-crm/src/App.tsx
examples/app-crm/src/components/index.ts
examples/app-crm/src/components/layout/algolia-search/wrapper.tsx
examples/app-crm/src/components/layout/header.tsx
examples/app-crm/src/providers/search-client.tsx

We are exceeding our Algolia quote quickly, since credentials are hardcoded and spending quota on development environment.
- Removed hardcoded Algolia App ID and Api key.
- Now `app-crm` will check for ENV variables and conditionally render Algolia search.

feat(app-crm): disable algolia on local environment

---

documentation/docs/authorization/access-control-provider/index.md

The "buttons" section of the Access Control Provider has been made more understandable.
page: https://refine.dev/docs/authorization/access-control-provider/#buttons

feat(docs): update description of access control provider buttons

---

documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md

fix: Documentation alignment issue
Explanation:
- Fixed the documentation of generated query params and updated them in doc.
Closing issues:
- Closes #5509 
Self Check before Merge:

feat(doc): generated query params in doc - #5509

---

documentation/docs/guides-concepts/audit-logs/index.md
documentation/docs/guides-concepts/general-concepts/index.md

Added missing Audit Log Provider section to General Concepts guide.

docs: add audit log provider section to general concepts

---

.changeset/tricky-waves-approve.md
packages/devtools-server/package.json
packages/devtools-ui/package.json

Updated `@ory/client` version to `1.5.2` to fix audit warning.
https://github.com/ory/sdk/issues/289#issuecomment-1916527928

chore: update @ory/client version to 1.5.2

---

.changeset/six-adults-smell.md
packages/create-refine-app/package.json

Updated `create-refine-app`'s `superplate-cli` dependency to `1.19.0`.

chore(create-refine-app): update superplate-cli dependency to 1.19.0

---

.changeset/fluffy-seahorses-care.md
packages/nextjs-router/src/pages/bindings.tsx

fix: `meta` has corrupted route parameters.
`parse` function from `@refinedev/nextjs-router` provides returns search params as following structure:
```json
{
"pageSize": "25",
"current": "1",
"sorters[0][field]": "status",
"sorters[0][order]": "asc",
"filters[0][field]": "status",
"filters[0][value]": "draft",
"filters[0][operator]": "contains"
}
```
This structure is not predictable and not sanitazble. So, `parse` function has been updated to provide following structure:
```json
{
"pageSize": "25",
"current": "1",
"sorters": [
{
"field": "status",
"order": "asc"
}
],
"filters": [
{
"field": "status",
"value": "draft",
"operator": "contains"
}
]
}
```
-   [x] Docs are …

fix(nextjs-router): bindings.parse returns corrupted data

---

.changeset/early-pigs-add.md
packages/create-refine-app/src/example/index.ts

Updated post creation message to suggest "dev" command, instead of "start".

chore(create-refine-app): suggest dev command instead of start

---

examples/template-antd/src/App.tsx
examples/template-chakra-ui/src/App.tsx
examples/template-mantine/src/App.tsx
examples/template-material-ui/src/App.tsx
examples/with-storybook-antd/src/App.tsx
examples/with-storybook-material-ui/src/App.tsx

Some of the examples were using deprecated WelcomePage imports.

chore(examples): update WelcomePage from core in examples

---

packages/live-previews/src/scope/auth0.tsx
packages/live-previews/src/scope/common.tsx
packages/live-previews/src/scope/keycloak.tsx
packages/live-previews/src/utils/use-code.ts

Fixed the issue with keycloak Auth Provider when used inside the preview of the scaffolder.
Resolves #5625
Keycloak provider was mocked for preview purposes but it was accessing the hooks before they're initialized, causing navigations to not work properly.
Added a small context and an handler to pass navigation methods to outside of React and used them inside the mock.

fix(live-previews): unresponsive keycloak sign in

---

documentation/docs/ui-integrations/material-ui/introduction/index.md

The documentation provided an incorrect code sample that utilized the notifications provider from the Ant Design UI package instead of the intended Material UI notifications provider. This commit updates the code sample to import and use the Material UI notifications provider from @refinedev/mui as recommended in the documentation.
Changes:
- Updated import statement to import the notification provider from @refinedev/mui.
- Updated the code sample to use the Material UI notifications provider in the <Refine /> component.
The current behavior is that the documentation provides an incorrect code sample using the notifications provider from the Ant Design UI package instead of the Material UI notifications provider.
The new behavior is that the documentation code sample is updated to import …

Fix: Use Material UI notifications provider in documentation code sample

---

documentation/src/refine-theme/landing-hero-section.tsx

When the "Get Started" button is clicked twice, it results in a redirection to the URL "/docs/docs," which subsequently leads to a 404 error page.
Clicking the "Get Started" button should initiate a single redirection to the relevant destination without causing any navigational errors.
[https://github.com/refinedev/refine/issues/5627](url)
Although this might not be considered a technical bug in the software, it's still frustrating for users when they accidentally click the "Get Started" button twice and end up being redirected unnecessarily.

fix(docs): here section get started button double click issue

---

.changeset/violet-games-exercise.md
documentation/docs/routing/integrations/next-js/provider-client-server.tsx
packages/cli/templates/provider/demo-access-control-provider.tsx
packages/cli/templates/provider/demo-data-provider.tsx

Currently, exported accessControlProvider object has wrong type, and also can params had to be set explicitly because of that.
Now accessControlProvider has `AccessControlProvider` type, also we don't need to have explicit CanParams.

fix(cli): demo access control provider's type is wrong.

---

documentation/src/refine-theme/landing-hero-showcase-section.tsx

newly uploaded images remain in the local cache of some browsers, so the new ones do not show up.
new images are uploaded with a different name to prevent them from staying in the local cache.
Some users see old images on landing pages because of CDN or local cache.

feat(docs): update landing showcase finefoods image names

---

examples/app-crm/src/routes/contacts/components/comment/comment-list.tsx

Closes #5651
According to issue #5651 the app-crm example is trying to delete contacts instead of contact notes due to the delete button using the route resource (which is contact, as the notes widgets is inside the contact view),
After adding the resource (```contactNotes```) explicitly to the delete note button the example application `app-crm`  can now delete contact notes sucessfully.

fix(app-crm): set resource of delete contact note button

---

.changeset/ten-readers-poke.md
packages/mui/src/components/themedLayoutV2/sider/index.tsx

There is unexpected/unnecessary margin on ThemeSiderV2 (MUI). 
fixes #5724 (issue)
This 8px margin is really standing out when there are a lot of resources, images of margin are attached in #5724 issue.

fix(mui): unnecessary margin on MUI ThemedSiderV2

---

documentation/tutorial/ui-libraries/intro/material-ui/react-router/sandpack.tsx

Example at mui tutorial is failing at https://refine.dev/tutorial/ui-libraries/layout/material-ui/react-router/
Fixed.

fix(docs): add missing dependency to mui tutorial

---

documentation/tutorial/ui-libraries/crud-components/material-ui/react-router/index.md

Add a single space before the word 'It' in [CRUD Components](https://refine.dev/tutorial/ui-libraries/crud-components/material-ui/react-router/#show-view) for better readability.

style(docs): add space before 'it'

---

.changeset/blue-roses-happen.md
packages/cli/package.json
packages/codemod/package.json
packages/devtools-server/package.json

Current version `jscodeshift` has vulnerability reports. Updated to `0.15.2`. 

chore: update jscodeshift version to 0.15.2

---

packages/cli/package.json
packages/cli/src/utils/codeshift/index.ts
packages/codemod/package.json
packages/devtools-server/package.json

After `jscodeshift` upgrade, CLI's antd transformer spec was failing because of extra parentheses.
Fixed it by constructing a new jsxElement in `wrapElement` helper.

fix(cli): jscodeshift failing spec

---

.changeset/popular-moose-dance.md
packages/devtools-server/package.json
packages/devtools-server/tsup.config.ts
packages/devtools-ui/package.json
packages/devtools-ui/tsup.config.ts
packages/devtools/tsup.config.ts

Fixed lodash imports in ESM builds which requires `lodash-es` imports to use `.js` extension to work properly unless the bundler is configured to handle non-fully-specified imports.
Resolves [#5822](https://github.com/refinedev/refine/issues/5822)

fix(devtools): lodash imports in ESM builds

---

documentation/tutorial/ui-libraries/crud-components/material-ui/react-router/sandpack.tsx
documentation/tutorial/ui-libraries/refactoring/material-ui/react-router/sandpack.tsx

The browser view crashes on tutorial section of  `crud components` and `notifications`
Browser view does not crash
fixes #5871

docs(tutorial): fixed browser view crash

---

.changeset/selfish-taxis-admire.md
documentation/docs/packages/tanstack-table/use-table/index.md
packages/react-table/src/useTable/index.ts
packages/react-table/src/utils/column-filters-to-crud-filters/index.spec.ts
packages/react-table/src/utils/column-filters-to-crud-filters/index.ts
packages/react-table/src/utils/crud-filters-to-column-filters/index.spec.ts
packages/react-table/src/utils/crud-filters-to-column-filters/index.ts
packages/react-table/src/utils/get-removed-filters/index.spec.ts
packages/react-table/src/utils/get-removed-filters/index.ts
packages/react-table/src/utils/index.ts

`useTable` hook was ignoring the conditional filters with `"and"` and `"or"` operators, causing custom filtering logic inside the table to not work as expected and omitting the filters from the query. This PR enables working with conditional filters and fixes the disappearing filters issue.
To customize the `key` value of the conditional filter, you can use the `filterKey` property in the column's `meta` property. This property will be used as the key for the filter when setting the filter value to the table from `@refinedev/core`'s filter state and when setting the filter value to the filter state from the table.
```tsx
// An example of how to use the `filterKey` property in the column's `meta` property
const columns: ColumnDef<IPost> = [
{
id: "title",
header: "Title",
accessorKey: …
```

refactor(react-table): allow conditional filters on `useTable`

---

.changeset/eleven-kangaroos-hope.md
examples/data-provider-strapi-v4/cypress/e2e/all.cy.ts
examples/data-provider-supabase/cypress/e2e/all.cy.ts
examples/form-antd-mutation-mode/cypress/e2e/all.cy.ts
examples/inferencer-mantine/cypress/e2e/all.cy.ts
examples/table-antd-table-filter/cypress/e2e/all.cy.ts
examples/table-chakra-ui-basic/cypress/e2e/all.cy.ts
examples/table-mantine-basic/cypress/e2e/all.cy.ts
examples/table-material-ui-table-filter/cypress/e2e/all.cy.ts
packages/core/src/definitions/helpers/index.ts
packages/core/src/definitions/helpers/prepare-query-context/index.ts
packages/core/src/hooks/data/useCustom.ts
packages/core/src/hooks/data/useInfiniteList.ts
packages/core/src/hooks/data/useList.ts
packages/core/src/hooks/data/useMany.ts
packages/core/src/hooks/data/useOne.ts

In query hooks, `signal` was accessed directly by destructuring which was causing issues in development mode with duplicated requests. This change accesses `queryContext` instead of destructured `signal` properly to prevent `@tanstack/react-query` from setting `abortSignalConsumed` flag unexpectedly.
Resolves #5843

refactor(core): prevent early access to `signal` from query context

---

.changeset/loud-toes-eat.md
packages/devtools-server/package.json
packages/devtools-server/src/serve-proxy.ts

Fixed the authentication flow and cookie handling for Safari. Flow was broken due to setting/accessing cookies with cross domain. Now devtools users will be able to authenticate and use the devtools server using Safari.
Resolves [#5753](https://github.com/refinedev/refine/issues/5753)

fix(devtools-server): broken auth flow in safari

---

.changeset/clean-dryers-grow.md
.changeset/clean-elephants-matter.md
.changeset/cyan-wolves-cry.md
.changeset/flat-suns-push.md
.changeset/forty-pianos-beam.md
.changeset/shiny-colts-nail.md
packages/core/src/hooks/accessControl/useCan/index.ts
packages/core/src/hooks/auditLog/useLogList/index.ts
packages/core/src/hooks/data/useInfiniteList.ts
packages/core/src/hooks/data/useList.ts
packages/core/src/hooks/data/useMany.ts
packages/core/src/hooks/data/useOne.ts
packages/devtools-internal/src/get-trace.ts
packages/devtools-internal/src/get-xray.ts
packages/devtools-internal/src/listeners.ts
packages/devtools-internal/src/use-query-subscription.tsx
packages/devtools-server/package.json
packages/devtools-server/src/index.ts
packages/devtools-server/tsconfig.declarations.json
packages/devtools-server/tsconfig.json
packages/devtools-shared/src/event-types.ts
packages/devtools-ui/package.json
packages/devtools-ui/src/components/invalidate-button.tsx
packages/devtools-ui/src/components/json-viewer.tsx
packages/devtools-ui/src/components/monitor-details.tsx
packages/devtools-ui/src/style.css
packages/devtools-ui/src/utils/get-resource-value.ts

-  `@refinedev/devtools-ui` `@refinedev/devtools-shared` `@refinedev/devtools-internal` `@refinedev/core`
Added the resource name to the devtools xray calls to allow resource names to be displayed in the devtools even with custom query keys.
- `@refinedev/devtools-server`
Moved `@refinedev/devtools-ui` dependency to `devDependencies` since only the `vite` output is used in the server.
- `@refinedev/devtools-ui` `@refinedev/devtools-shared` `@refinedev/devtools-internal` `@refinedev/core`
Updated resource name displaying logic to use `resourceName` from activity records to make sure `resource` is correctly displayed with custom query keys.
- `@refinedev/devtools-internal` `@refinedev/devtools-shared` `@refinedev/devtools-server` …

feat(devtools): devtools improvements

---

.changeset/dull-spies-sparkle.md
packages/core/src/hooks/auth/useOnError/index.ts

Currently when user doesn't define an `authProvider.onError` method, `useOnError` calls (made internally when a query or a mutation fails) will log an error to the console in development environments as `"no mutationFn found"`. 
Provided a fallback function to `useOnError` to prevent this error to be logged without changing any functionality of the hook.

fix(core): add fallback mutation function for `useOnError`

---

.changeset/few-terms-fetch.md
packages/core/src/contexts/notification/types.ts
packages/mui/src/providers/notificationProvider/index.spec.tsx
packages/mui/src/providers/notificationProvider/index.tsx
packages/mui/src/providers/refineSnackbarProvider/index.tsx

Anchor position,preventDuplicate,disableWindowBlurListener are hard coded in mui useNotificationsProvider
these values can now be provided as per usage
fixes #5847

feat(mui): configurable `anchorOrigin` for `useNotificationProvider`

---

documentation/docs/data/hooks/use-table/index.md
documentation/docs/packages/tanstack-table/use-table/index.md
documentation/docs/ui-integrations/ant-design/hooks/use-table/index.md
documentation/docs/ui-integrations/material-ui/hooks/use-data-grid/index.md

We don't have a description of `getDefaultFilter` in the documentation.
`getDefaultFilter` description added.
pages:
- http://refine.dev/docs/data/hooks/use-table/#filtering
- http://refine.dev/docs/ui-integrations/ant-design/hooks/use-table/#initial-filter-and-sorter
- http://refine.dev/docs/ui-integrations/material-ui/hooks/use-data-grid/#filtering
- http://refine.dev/docs/packages/tanstack-table/use-table/#filtering

feat(docs): add getDefaultFilter description

---

.changeset/ninety-pots-smell.md
packages/mui/src/definitions/dataGrid/index.ts

`transformMuiOperatorToCrudOperator` return type is wrong.
Return type updated to `Exclude<CrudOperators, "or" | "and">` to satisfy `LogicalFilter` type.

fix(mui): transformMuiOperatorToCrudOperator return type

---

.changeset/ninety-cameras-give.md
packages/core/src/components/authenticated/index.spec.tsx
packages/core/src/components/authenticated/index.tsx

If user is not authenticated, `<Authenticated />` redirects to the provided route and appends the current route to the `to` parameter. With this change, if the current route is the root (`/`), the `to` parameter will be omitted.
RK-642

refactor(core): omit `to` parameter at root on unauthenticated redirects

---

.changeset/shiny-cougars-visit.md
.changeset/wise-dots-agree.md
packages/devtools-server/src/serve-proxy.ts
packages/devtools-shared/src/context.tsx
packages/devtools-ui/src/utils/auth.ts

When users create a new project or their devtools token expires, their console is polluted with network errors due to missing authentication. This PR removes these errors by handling auth requests in a user-friendly way.
When `<DevtoolsProvider />` component is mounted in apps with React's strict mode, it will try to initialize the websocket connection twice and first one will be closed immediately before the connection is established. This PR will delay closing the websocket connection until it's established properly to prevent these errors from appearing in the console.
RK-640 RK-641

fix(devtools): avoid polluting user console

---

.changeset/chatty-beds-smoke.md
.changeset/stupid-rules-pull.md
.changeset/tender-hats-lick.md
documentation/docs/guides-concepts/development/index.md
packages/cli/src/commands/devtools/index.ts
packages/cli/src/commands/runner/dev/index.ts
packages/devtools-server/src/cli.ts
packages/devtools-server/src/constants.ts
packages/devtools-server/src/index.ts
packages/devtools-server/src/serve-proxy.ts
packages/devtools-server/src/serve-ws.ts
packages/devtools-server/src/setup-server.ts
packages/devtools-shared/src/context.tsx

This PR combines WebSocket and Http server ports into one (5001) to simplify the configuration and avoid port conflicts. Previously the WebSocket server was running on port 5002 and the Http server on port 5001. Now both servers are running on port 5001.
Additionally, this PR includes a fix in `@refinedev/cli` and prevents `dev` command from exiting if devtools server fails to start.

refactor(devtools): use same port for ws and http

---

packages/live-previews/src/scope/google.tsx
packages/live-previews/src/scope/map.tsx
packages/live-previews/src/utils/replace-imports.ts

In the live preview code we're replacing imports with provided scopes of packages.
Example:
```tsx
import { Button } from "@mui/material";
```
will be replaced with:
```tsx
const { Button } = MuiMaterial;
```
In some cases, imports may be made with subpaths/scopess of a package;
Example:
```tsx
import Button from "@mui/material/Button";
```
In this case we've been replacing it with the same structure:
```tsx
const { Button } = MuiMaterial;
```
This replacement was using the default import name (in this case `Button`) but it was flawed because the default import name don't have to match the actual export name.
Example: 
```tsx
import Button$1 from "@mui/material/Button";
```
In this case, a broken replacement is made:
```tsx …
```

fix(live-previews): fix replacement of the scoped default imports

---

documentation/README.md
package.json
pnpm-lock.yaml

`"@netlify/plugin-nextjs@4"` doesn't work with `next@14`. To work with `next@14`, the plugin is updated to `@5`

feat: update netlify nextjs plugin

---

documentation/src/refine-theme/doc-sidebar.tsx

feat(docs): sidebar link color is wrong

---

documentation/package.json
package.json

`pnpm run dev:docs` gives following error:
[error.log.md](https://github.com/refinedev/refine/files/15434855/error.log.md)
Fixed with removing `--`

fix: `dev:docs` script not working

---

.changeset/happy-parents-yawn.md
packages/nestjs-query/src/utils/index.ts
packages/nestjs-query/test/utils/generateFilters.spec.ts

The following filter operators do not work.
- `containss`
- `ncontainss`
- `startswiths`
- `nstartswiths`
- `endswiths`
- `nendswiths`
- `nbetween`
The following filter operators work correctly.
- `containss`
- `ncontainss`
- `startswiths`
- `nstartswiths`
- `endswiths`
- `nendswiths`
- `nbetween`
fixes #6008

fix(nestjs-query): implement unimplemented operators

---

examples/invoicer/src/components/form/form-item-upload-logo-draggable/index.tsx
packages/devtools/src/components/devtools-pin.tsx
packages/devtools/src/components/devtools-selector.tsx
packages/nestjs-query/test/utils/generateFilters.spec.ts

chore: lint fixes

---

examples/win95/src/routes/video-club/tapes/select-title.tsx
examples/win95/src/routes/video-club/titles/list.tsx

---
fixed: `genres` filter operator

fix(win95): genres filter should use `ina`

---

packages/live-previews/pages/preview.tsx
packages/live-previews/src/utils/use-code.ts

Added option to handle `hash` query parameter for live previews. This will be used to fetch lzstring from the bucket with given hash to avoid 414 status code.

feat: add hash query param to live previews

---

.changeset/sharp-lies-wash.md
packages/nestjs-query/src/utils/index.ts
packages/nestjs-query/test/utils/generateFilters.spec.ts

- Cannot specify `0` as filter value
- Cannot specify `""` as filter value
- Can specify `0` as filter value
- Can specify `""` as filter value
fixes #6022

fix(nestjs-query): can specify `0` as filter value

---

.changeset/slow-cougars-sit.md
packages/cli/src/utils/swizzle/import.test.ts
packages/cli/src/utils/swizzle/import.ts

When exporting elements with `swizzle` command, it will try to replace and combine imports from Refine packages. This process was broken if the target file was using `import type` syntax. This PR updates swizzle command to handle `import type` syntax separately.
Resolves #6035

fix(cli): type imports in swizzle command

---

.changeset/smooth-maps-arrive.md
.changeset/tall-geckos-help.md
.changeset/twenty-insects-eat.md
packages/devtools-server/src/reload-on-change.ts
packages/hasura/src/utils/upperCaseValues.ts
packages/inferencer/src/use-relation-fetch/index.ts

ESM bundle of `@refinedev/hasura` was broken due to incorrect lodash import. Import has been replaced with subdirectory import to get handled properly in the bundling process.
Fixes [#6044](https://github.com/refinedev/refine/issues/6044)
`@refinedev/devtools-server` was using `lodash` imports from root which are interpreted as CJS imports in the ESM bundle. To avoid any future issues, lodash imports have been replaced with subdirectory imports.
ESM bundle of `@refinedev/inferencer` was broken due to incorrect lodash import. Import has been replaced with subdirectory import to get handled properly in the bundling process.

fix: replace lodash imports from root with subpath imports

---

.changeset/hip-ears-shave.md
.changeset/wet-pianos-arrive.md
packages/devtools-server/package.json
packages/devtools-server/src/serve-proxy.ts
packages/devtools-ui/src/components/header-auth-status.tsx
packages/devtools-ui/src/utils/auth.ts
packages/devtools-ui/src/utils/me.ts

##Changes
Fixes #6047 
Devtools was failing to determine the auth status and always end up redirecting to the login page regardless of the actual auth status. This was due to the missing check on the auth request that was causing all valid responses treated as unauthenticated.

fix(devtools): failing auth status checks

---

documentation/docs/core/hooks/utilities/use-menu/index.md
documentation/versioned_docs/version-3.xx.xx/api-reference/core/hooks/ui/useMenu.md

In useMenu, we have the renderMenuItems function that takes an array of items but doesn't make use of it, instead iterates over the state in the parent function. We can either remove the items that we pass to the function or actually use it. 
Uses the function parameter. 

docs(snippet): use correct constant in function iteration

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
nx.json

Since we were missing `attw` and `publint` scripts in `nx.json`, they weren't recognized by lerna and they weren't running in CI workflows.
Also moved `publint` and `attw` scripts above `test` step, since they run faster and we can get feedback earlier in case something is wrong.
fixes (issue)

fix: attw and publint scripts won't run

---

.github/workflows/release.yml
.github/workflows/scripts/update-lock.sh
package.json

release workflow can't properly update `pnpm-lock.yaml` for every run. After running `changeset version` command, which updates package.json of all packages and examples, `pnpm-lock.yaml` file needs to be updated to have latest version.
Previously we had sh file to handle changeset version and running pnpm install but that doesn't seems to be working reliably.
Following the suggestions in [this issue](https://github.com/changesets/action/issues/203), added `version-packages` script to root package.json and updated release workflow's changeset job to run version-packages script instead.
fixes (issue)

fix: release workflow can't update pnpm-lock.yaml

---

.github/workflows/scripts/build-example-chunks.js

Build example chunks script checks examples with e2e specs and balances chunks to have roughly same amount of e2e specs, since e2e specs takes longer to run, we don't want to have a chunk that takes 60 minutes while another takes 10.
Previously, we've moved cypress specs from examples directories to `cypress/e2e` folder and overlooked how this script checks e2e examples.
fixes (issue)

fix: check cypress dir for e2e specs

---

.changeset/pretty-snails-shake.md
packages/devtools-internal/src/use-query-subscription.tsx

Currently, `@refinedev/devtools-internal` returns noop function when bundled for production, yet the notation is not correctly interpreted by some bundlers. This PR fixes the issue by moving the empty return and noop functions to a separate definition.
Resolves #6030

fix(devtools-internal): fix noop return on hooks for production builds

---

.changeset/thin-adults-complain.md
packages/core/src/hooks/useSelect/index.spec.ts
packages/core/src/hooks/useSelect/index.ts

Debounce behavior on `onSearch`  is not working correctly when use inside `Controller` of react-hook-form causing re-fechting  multiple times.
Update `onSearch` to memoized value to prevent from re-fetching instead on return as inlined.
fix(core): update debounce behavior on `onSearch` in `useSelect`
Fixes https://github.com/refinedev/refine/issues/6096

fix(core): update debounce behavior on `onSearch` in `useSelect`

---

.changeset/cold-olives-allow.md
packages/mui/src/components/themedLayoutV2/index.tsx

Due to the changes in CSS rendering in latest Google Chrome updates, `<DataGrid />` components are not properly sized when used inside `<ThemedLayoutV2 />` component. The `overflow: clip` property in the layout content is causing either miscalculations on the data grid width or causing an overflow on the container and overlapping with the sidebar.
This change replaces the `overflow: clip` property with `min-height` and `min-width` properties to ensure the layout content is properly rendered and responsive to the content inside it.
Resolves #6077
Preview for `finefoods-material-ui` example: https://deploy-preview-6144--finefoods-admin-mui.netlify.app

fix(mui): broken `<DataGrid />` sizing in `<ThemedLayoutV2 />`

---

documentation/docs/ui-integrations/ant-design/hooks/use-drawer-form/index.md
documentation/docs/ui-integrations/ant-design/hooks/use-modal-form/index.md
documentation/src/refine-theme/common-admonition.tsx
documentation/src/refine-theme/css/custom.css

Updated the Ant Design's `useModalForm` and `useDrawerForm` docs to clarify the differences between `onFinish()` and `formProps.onFinish()` method in return values. 
Resolves #6181

docs(ant-design): explain the differences between `onFinish` and `formProps.onFinish`

---

documentation/docs/notification/notification-provider/index.md

Corrected the import path from @refinedev/chakra to @refinedev/chakra-ui. Fixed the notification provider usage, ensuring useNotificationProvider is used instead of notificationProvider().
fixes (issue)

fix(docs): correct import path and notification provider usage

---

.changeset/popular-bees-smash.md
.changeset/warm-pots-relax.md
documentation/docs/notification/notification-provider/index.md
packages/antd/src/components/pages/auth/components/forgotPassword/index.tsx
packages/antd/src/components/pages/auth/components/register/index.tsx
packages/chakra-ui/src/components/pages/auth/components/forgotPassword/index.tsx
packages/chakra-ui/src/components/pages/auth/components/register/index.tsx
packages/mantine/src/components/pages/auth/components/forgotPassword/index.tsx
packages/mantine/src/components/pages/auth/components/register/index.tsx
packages/mui/src/components/pages/auth/components/forgotPassword/index.tsx
packages/mui/src/components/pages/auth/components/register/index.tsx

fix(auth-page): fix wrong translation keys in `type="register"` and `type="forgotPassword"`
In `type="forgotPassword"`:
- `"pages.register.buttons.haveAccount"` is replaced with `"pages.forgotPassword.buttons.haveAccount"`
- `"pages.login.signin"` is replaced with `"pages.forgotPassword.signin"`
In `type="register"`:
- `"pages.login.divider"` is replaced with `"pages.register.divider"`
- `"pages.login.buttons.haveAccount"` is replaced with `"pages.register.buttons.haveAccount"`
- `"pages.login.signin"` is replaced with `"pages.register.signin"`
Wrong keys are kept as fallbacks in case the new keys are not found in the translation file. If you are using those keys in your project, make sure to update them accordingly. Fallback …

fix(auth-page): replace wrong translation keys

---

.changeset/quick-rats-eat.md
packages/cli/src/commands/add/sub-commands/provider/create-providers.ts
packages/cli/templates/assets/i18n/locale/en.json
packages/live-previews/public/locales/en/common.json

Currently `refine add provider i18n` command is only creating a demo i18n provider implementation but misses the translation files. This PR adds the base translation files for the i18n provider which is used by Refine internally in hooks, notifications and components.
Now `locale/en.json` will be added with primarily used translation keys and values for the i18n provider.
Resolves #5918

feat(cli): add example translation file to i18n provider template

---

.changeset/sour-ravens-begin.md
packages/core/src/hooks/data/useUpdateMany.spec.tsx
packages/core/src/hooks/data/useUpdateMany.ts

this is not working
```tsx
const { mutate } = useUpdateMany();
mutate({ invalidates: ["all"], resource: "posts", values: {}, ids: [1, 2, 3] });
```
now working
fixes #6209

fix(core): `invalidates` prop of `useUpdateMany` doesn't work

---

examples/app-crm-minimal/src/routes/companies/edit/form.tsx
examples/app-crm-minimal/src/routes/companies/list/create-modal.tsx
examples/app-crm/src/routes/scrumboard/sales/create.tsx
examples/app-crm/src/routes/scrumboard/sales/edit.tsx
examples/customization-offlayout-area/src/components/sider/index.tsx
examples/data-provider-sanity/src/pages/posts/list.tsx
examples/finefoods-antd/src/components/product/list-table/index.tsx
examples/finefoods-antd/src/pages/couriers/list.tsx
examples/table-material-ui-advanced/src/pages/dataGrid/index.tsx
examples/table-material-ui-data-grid-pro/src/pages/posts/list.tsx
examples/table-material-ui-use-data-grid/src/pages/posts/list.tsx
examples/table-material-ui-use-delete-many/src/pages/posts/list.tsx
examples/table-material-ui-use-update-many/src/pages/posts/list.tsx

The `use-select-query-result`(#6180) `codemod` is executed twice for all examples.

chore: run codemod `use-select-query-result` for all examples

---

.github/workflows/build-examples.yml
cypress/e2e/i18n-nextjs/all.cy.ts
cypress/e2e/i18n-react/all.cy.ts

There is no e2e test for i18n
i18n tests are added

test(cypress): add e2e for i18n-nextjs and i18n-react

---

.changeset/eleven-bottles-rush.md
packages/cli/src/commands/add/sub-commands/resource/create-resources.ts
packages/cli/src/commands/add/sub-commands/resource/index.test.ts
packages/cli/src/utils/package/index.ts
packages/cli/test/jest.setup.ts

CLI doesn't install `@refinedev/inferencer` package but it's required on generated resource components
From now on, `refinedev/cli` automatically installs `@refinedev/inferencer`.
fixes #6220

feat(cli): automatically install `@refinedev/inferencer` after resources are generated

---

.changeset/chilled-cherries-sin.md
packages/core/src/hooks/useSelect/index.ts

The type didn't allow to pass function in `optionValue` and `optionLabel`.
The type allows to pass function in `optionValue` and `optionLabel`.
fixes (#6223)

fix(core): fixed type issue in useSelect's `optionLabel` and `optionValue`

---

.changeset/odd-squids-invite.md
packages/cli/package.json
packages/cli/src/commands/add/sub-commands/resource/index.test.ts
packages/cli/src/utils/compile/index.ts
packages/cli/src/utils/resource/index.ts
packages/cli/templates/resource/components/create.tsx.hbs
packages/cli/templates/resource/components/edit.tsx.hbs
packages/cli/templates/resource/components/list.tsx.hbs
packages/cli/templates/resource/components/show.tsx.hbs
packages/cli/templates/resource/pages/next/create/page.tsx.hbs
packages/cli/templates/resource/pages/next/edit/[id]/page.tsx.hbs
packages/cli/templates/resource/pages/next/page.tsx.hbs
packages/cli/templates/resource/pages/next/show/[id]/page.tsx.hbs
pnpm-lock.yaml

`refine add resource blog-posts` command generates the following component:
```tsx
export const Blog-PostsList: React.FC = () => {};
```
which is an invalid component name.
With this PR this issue is fixed and generates this:
```tsx
export const BlogPostsList: React.FC = () => {};
```
fixes #6225

fix(cli): add resource generating invalid react component name

---

.changeset/odd-eggs-flash.md
.changeset/silver-candles-wait.md

Added august release missing changesets for `@refinedev/react-table` and `@refinedev/react-hook-form` packages.

chore(react-table-react-hook-form): add missing changesets

---

packages/shared/generate-declarations.js

To avoid silent failures due to spawned processes omitting stdout when stderr has a buffer. This has caused unknown errors thrown when Release action is running for publishing the packages. Typescript (`tsc`) logs the errors and warnings to `stdout` and `stderr` only containing a summary of the error. This leads to non-debuggable output for the CI.

build(type-generation): log errors and output properly

---

.changeset/few-turkeys-dance.md
packages/supabase/src/utils/generateFilter.ts
packages/supabase/test/getList/index.mock.ts
packages/supabase/test/getList/index.spec.ts

Consider the following filter:
```js
const filter: CrudFilter = {
operator: 'or',
value: [
{
field: 'name',
operator: 'contains',
value: 'foo',
}
],
};
```
resolve to (name.ilike.foo) giving no results
The filter should resolve to (name.ilike.%foo%) 
fixes (#6239)
If you consider having extra tests, I can add some to cover it fully

fix(supabase): parse nested values correctly when using conditional filters

---

.changeset/grumpy-lions-exercise.md
packages/devtools-server/package.json
packages/devtools-server/src/packages/update-package.ts
pnpm-lock.yaml

preferred-pm pulls in 24 dependencies, which is unnecessary for what it does: https://npmgraph.js.org/?q=preferred-pm
ref https://github.com/refinedev/refine/issues/6242
package-manager-detector has no dependencies: https://npmgraph.js.org/?q=package-manager-detector

chore(devtools-server): replace `preferred-pm` with `package-manager-detector`

---

.changeset/honest-peaches-deny.md
packages/core/src/hooks/use-resource-params/index.spec.ts
packages/core/src/hooks/use-resource-params/index.ts

`useResourceParams` hook was not reflecting the changes in the `id` prop immediately. This was due to the `id` state being set in the `useEffect` hook. This PR fixes the issue by setting the `id` state properly during render rather than after the render is complete.
Fixes #6259

fix(core): changes in `props.id` not reflected immediately in `useResourceParams` return type

---

.changeset/wicked-cherries-grow.md
packages/cli/src/commands/add/sub-commands/integration/packages/ant-design.ts
packages/cli/src/commands/add/sub-commands/integration/packages/react-router.ts
packages/cli/src/commands/runner/projectScripts.test.ts
packages/cli/src/commands/runner/projectScripts.ts
packages/cli/src/commands/runner/utils/index.ts
packages/cli/src/definitions/projectTypes.ts
packages/cli/src/utils/project/index.ts
packages/cli/src/utils/resource/index.spec.ts
packages/cli/src/utils/resource/index.ts

Scripts for Remix SPA mode are not supported.
It is now possible to execute the Remix SPA Mode script by selecting it from the platform options.
resolves #6127

feat(cli): add Remix SPA mode support

---

documentation/docs/guides-concepts/general-concepts/index.md

chore(docs): fix a typo in general concepts

---

documentation/tutorial/routing/inferring-parameters/react-router/index.md
documentation/tutorial/routing/inferring-parameters/react-router/sandpack.tsx
documentation/tutorial/ui-libraries/crud-components/ant-design/react-router/index.md
documentation/tutorial/ui-libraries/crud-components/ant-design/react-router/sandpack.tsx
documentation/tutorial/ui-libraries/crud-components/material-ui/react-router/index.md
documentation/tutorial/ui-libraries/crud-components/material-ui/react-router/sandpack.tsx
documentation/tutorial/ui-libraries/refactoring/ant-design/react-router/index.md
documentation/tutorial/ui-libraries/refactoring/ant-design/react-router/sandpack.tsx
documentation/tutorial/ui-libraries/refactoring/material-ui/react-router/index.md
documentation/tutorial/ui-libraries/refactoring/material-ui/react-router/sandpack.tsx

Deprecated `queryResult` was used in tutorial codes.
`query` is being used instead of it.
fixes #6284
N/A

chore(tutorial): update deprecated `queryResult` to `query`

---

documentation/docs/advanced-tutorials/upload/base64-upload.md

Currently, it shows a multipart example instead of base64.
fixes #6295
I wasn't able to run the fix locally (*JavaScript heap out of memory* :'D), so I'm not 100% sure if I changed it in the right way.

fix(docs): fix wrong example for base64 upload

---

documentation/docs/ui-integrations/ant-design/hooks/use-form/index.md

Shows refineCoreProps wrapped around submitOnEnter. 
Doesn't show that anymore.

docs(ant-design): useForm hook documentation fix for props

---

.changeset/large-turtles-smile.md
packages/nestjsx-crud/src/utils/mapOperator.ts
packages/nestjsx-crud/test/utils/mapOperator.spec.ts

The `between` operator doesn’t work correctly. It uses the `eq` (equal) operator instead of `between`.
The `between` operator now works as expected and filters values between the specified range.

feat(nestjsx-crud): add between operator

---

documentation/docusaurus.config.js

Due to the issue in DocSearch (https://github.com/algolia/docsearch/issues/2294) we need to add `hierarchy.lvl0` to make sure we use lvl0 when displaying search results.
Resolves #6344

docs(docsearch): add hierarchy.lvl0 to attributes to highlight

---

documentation/docs/core/refine-component/index.md

There is no explanation of what to use instead of deprecated props.
added description of what to use instead of deprecated props

feat(docs): add description to deprecated props on refine component

---

documentation/docs/data/packages/simple-rest/index.md

There is no example of how to give `httpClient` on simple-rest docs.
added an example of how to give `httpClient` to `@refinedev/simple-rest` data-provider.

feat(docs): show http-client on simple-rest usage

---

.changeset/fifty-moons-flash.md
packages/core/src/hooks/menu/useMenu.tsx

The `label` and `route` fields in `useMenu().menuItems` were marked as deprecated, but they are not deprecated. 
This change removes the deprecation warning for these fields because `useMenu` automatically handles the deprecation of these fields internally. 
width="150px"
src="https://github.com/user-attachments/assets/d400a469-f029-4902-b859-8852d0372b09" alt="reproducible example code screenshot" />
fixes #6352

fix(core): `label` and `route` fields of  `useMenu.menuItems` shouldn't be deprecated

---

.changeset/bright-toys-guess.md
packages/hasura/src/dataProvider/index.ts
packages/hasura/test/getOne/index.mock.ts
packages/hasura/test/getOne/index.spec.ts

fix(hasura): pass gqlVariables to getOne operation

---

.changeset/gorgeous-needles-guess.md
packages/strapi-v4/refine.config.js

following files are missing after swizzling.
- [transformErrorMessages.ts](https://github.com/refinedev/refine/blob/master/packages/strapi-v4/src/utils/transformErrorMessages.ts)
- [transformHttpError.ts](https://github.com/refinedev/refine/blob/master/packages/strapi-v4/src/utils/transformHttpError.ts)
following files should not be available for swizzle.
- src/providers/strapi-v4/hooks/index.ts
- src/providers/strapi-v4/hooks/upload.t
All missing files were added and unavailable files were removed from the swizzling process.
fixes #6397

fix(strapi-v4): has missing files after swizzling

---

.changeset/spotty-jokes-swim.md
packages/core/src/hooks/useTable/index.ts

Adding the `setFilters` as a dependency in the useEffect hook causes infinite loop since setFiltersFn are not wrapped in `useCallbacks`
No infinite loop
fixes #6385

fix(core): wrap `setFiltersFn` with `useCallback`

---

.changeset/beige-cougars-add.md
packages/chakra-ui/src/components/fields/email/index.tsx

In TSDoc description of the `<EmailField />` component, link to the official documentation of Chakra UI was broken and couldn't be opened. This PR fixes the link by updating the URL to the correct one.

chore(chakra-ui): fix broken tsdoc links

---

documentation/docs/notification/notification-provider/index.md

A couple of times on the page "an" was used before words like "notificationProvider" where the correct prefix would be "a"
fixes (issue)

chore: edit minor grammatical errors

---

.changeset/eight-drinks-compare.md
packages/react-hook-form/src/useForm/index.ts

Explicitly disabling `autoSave` doesn't work. Any value comes as true.
`autoSave` specification now works.
fixes #6458

fix(react-hook-form): onChange handler `autoSave` check in `useForm`

---

documentation/tutorial/essentials/forms/index.md

This addresses a documentation issue talked about here: https://github.com/refinedev/refine/issues/6479

fix(docs): use `event.currentTarget` instead of `event.target`

---

documentation/tutorial/routing/intro/react-router/sandpack.tsx

Updated the sandpack configuration in tutorial to use `react-router-dom` with version 6 until we release an update with the latest v7.
Fixes #6531

docs(tutorial): pin react-router-dom version to v6

---

examples/customization-rtl/index.html
examples/customization-rtl/src/App.tsx
examples/customization-rtl/src/global.css

The current font of RTL strings in languages such as Persian or Arabic is not aesthetically pleasing and causes problems in readability in some screens.
The ideal solution is to use a readable font that is widely used in these languages. I have used [Vazirmatn](https://github.com/rastikerdar/vazirmatn) which a popular font.
I have not opened an issue for this. I decided to interact with the viewers under the PR, If I may. **This PR only changes the code in `customization-rtl` template**.

feat(customization-rtl): use Vazirmatn font

---

.changeset/weak-snails-act.md
packages/core/src/hooks/data/useUpdate.spec.tsx
packages/core/src/hooks/data/useUpdate.ts

This throws an error:
```tsx
useUpdate({
id: "",
});
```
This no longer throws an error:
```tsx
useUpdate({
id: "",
});
```
fixes #6505

fix(core): `useUpdate` throws an error when id is an empty string. (`id=""`)

---

documentation/docs/routing/integrations/react-router/migration-guide-v6-to-v7.md

Updated link in docs which to react-router upgrade page, current link is 404

Fix link to react router upgrade page

---

documentation/docs/routing/integrations/react-router/migration-guide-v6-to-v7.md

- Remove the extra trailing double quote (`"`) after the `refine-codemod` command which causes the command to fail
- Update the example `@refinedev/react-router` version changes to `^1.0.1`, as the current version (as of 12/2024) is [`1.0.1`](https://www.npmjs.com/package/@refinedev/react-router?activeTab=versions) this will help prevent confusion when verifying the upgrade

docs(react-router-upgrade): remove extra double quote and correct version

---

documentation/docs/data/packages/strapi-v4/index.md
documentation/docs/guides-concepts/forms/index.md
documentation/src/components/sandpack/index.tsx
documentation/src/refine-theme/common-admonition.tsx
documentation/src/refine-theme/common-tab-item.tsx

- Updated heading hierarchy in some docs
- Added `<h6>` heading to sandpack snapshots
- Added hidden `<h5>` to tab item contents
- Replaced admonition titles with `<h5>` tags

docs: fix heading orders

---

documentation/tutorial/ui-libraries/intro/material-ui/react-router/sandpack.tsx

On tutorial, [this example](https://refine.dev/tutorial/ui-libraries/crud-components/material-ui/react-router/) gives following error: 
`"@mui/system": "latest"` dependency added to fix this problem

fix(docs): Material UI app not working on tutorial 

---

.changeset/unlucky-rules-complain.md
packages/core/src/hooks/data/useMany.spec.tsx
packages/core/src/hooks/data/useMany.ts

Added checks for `ids` and `resource` props to check in runtime if they are valid or not.
`useMany` will warn if `ids` or `resource` props are missing unless the query is manually enabled through `queryOptions.enabled` prop.

fix(core): add checks for `ids` and `resource` to `useMany`

---

documentation/src/components/browser-window/index.tsx
documentation/src/components/codesandbox-example/index.tsx
documentation/src/components/live-preview/index.tsx
documentation/src/components/sandpack/index.tsx
documentation/src/components/tooltip/index.tsx
documentation/src/refine-theme/common-copy-button.tsx
documentation/src/refine-theme/common-wordwrap-button.tsx
documentation/src/refine-theme/doc-thumbs-up-down-feedback-widget.tsx

- Added missing classes for Refine's custom elements
- Updated sandpack block to only print visible files in the hidden section

docs: add missing class selectors

---

.changeset/giant-carrots-deny.md
.changeset/perfect-donkeys-cheat.md
documentation/docs/core/refine-component/index.md
packages/core/src/contexts/refine/index.tsx
packages/core/src/definitions/helpers/handleRefineOptions/index.spec.ts
packages/core/src/hooks/data/useCreate.ts
packages/core/src/hooks/data/useCreateMany.ts
packages/core/src/hooks/data/useCustom.ts
packages/core/src/hooks/data/useCustomMutation.ts
packages/core/src/hooks/data/useDelete.ts
packages/core/src/hooks/data/useDeleteMany.ts
packages/core/src/hooks/data/useInfiniteList.ts
packages/core/src/hooks/data/useList.ts
packages/core/src/hooks/data/useMany.ts
packages/core/src/hooks/data/useOne.ts
packages/core/src/hooks/data/useUpdate.ts
packages/core/src/hooks/data/useUpdateMany.ts
packages/core/src/hooks/form/index.ts
packages/core/src/hooks/show/index.ts
packages/core/src/hooks/useLoadingOvertime/index.spec.tsx
packages/core/src/hooks/useLoadingOvertime/index.ts
packages/core/src/hooks/useSelect/index.ts
packages/core/src/hooks/useTable/index.spec.ts
packages/core/src/hooks/useTable/index.ts

Added missing `enabled` prop to `useLoadingOvertime` and added ability to globally configure through `options.overtime.enabled`.
Due to the nature of calculating elapsed time, an interval is set by the `interval` prop. This was causing unwanted updates in the return value and there was no way to disable it properly.
Updated Refine's data hooks and extensions to prevent duplicated overtime intervals from being created. This uses the `enabled` prop to prevent internal hooks from registering the intervals.
Prior to this change, `useTable` was initializing its own `useLoadingOvertime` hook but also propagated the `elapsedTime` from `useList` hook which is used internally by `useTable`. This caused duplicated intervals and unwanted …

refactor(core): remove duplicated overtime intervals

---

documentation/docs/data/packages/strapi-v4/index.md

----
`authProvider` example added to Strapi V4 doc.

fix(docs): add auth-provider example to strapi doc

---

.changeset/itchy-peas-pump.md
packages/antd/src/definitions/filter-mappers/index.ts
packages/antd/src/hooks/useThemedLayoutContext/index.ts
packages/cli/src/commands/add/sub-commands/integration/packages/index.ts
packages/cli/src/commands/check-updates/index.tsx
packages/cli/src/commands/update/interactive/index.ts
packages/cli/src/components/update-warning-table/table.ts
packages/cli/src/components/version-table/index.ts
packages/cli/src/telemetry/index.ts
packages/cli/src/update-notifier/index.tsx
packages/cli/src/utils/announcement/index.tsx
packages/cli/src/utils/env/index.ts
packages/cli/src/utils/package/index.ts
packages/cli/src/utils/project/index.ts
packages/cli/src/utils/resource/index.ts
packages/cli/src/utils/swizzle/index.ts
packages/core/src/definitions/helpers/generateDocumentTitle/index.ts
packages/core/src/definitions/helpers/safe-translate/index.ts
packages/kbar/src/components/refineKbar/index.tsx
packages/mantine/src/hooks/useThemedLayoutContext/index.ts

Since typescript doesn't resolve and replace path aliases, using them for the type imports will cause `d.ts` files to reference unresolvable paths and types.
While this doesn't break everything, it breaks the types in places where the path aliases are used for type imports.
This change removes the path aliases from the type imports and replaces them with relative imports.

fix(types): remove path aliases from type imports

---

documentation/docs/guides-concepts/authentication/auth-pages/mui.tsx
documentation/docs/guides-concepts/forms/server-side-validation-mui.tsx
documentation/docs/guides-concepts/general-concepts/auth-pages/mui.tsx
documentation/docs/guides-concepts/general-concepts/layout/mui.tsx
documentation/docs/ui-integrations/material-ui/introduction/previews/auth-page.tsx
documentation/docs/ui-integrations/material-ui/introduction/previews/basic-views.tsx
documentation/docs/ui-integrations/material-ui/introduction/previews/example.tsx
documentation/docs/ui-integrations/material-ui/introduction/previews/layout-next-js.tsx
documentation/docs/ui-integrations/material-ui/introduction/previews/layout-react-router-dom.tsx
documentation/docs/ui-integrations/material-ui/introduction/previews/layout-remix.tsx
documentation/docs/ui-integrations/material-ui/introduction/previews/theming.tsx
documentation/docs/ui-integrations/material-ui/introduction/previews/usage-next-js.tsx
documentation/docs/ui-integrations/material-ui/introduction/previews/usage-react-router-dom.tsx
documentation/docs/ui-integrations/material-ui/introduction/previews/usage-remix.tsx
documentation/tutorial/ui-libraries/intro/material-ui/react-router/sandpack.tsx

----
`mui/x-data-grid` throws an error on Sandpack:
because of this [tutorial](https://refine.dev/tutorial/ui-libraries/refactoring/material-ui/react-router/#) is not working.
This error is caused by [`mui/x-data-grid`](https://github.com/mui/mui-x/pull/15627), and until they release a fix, I have locked the version.

fix: `mui/x-data-grid` throws an error on sandpack

---

documentation/tutorial/ui-libraries/authentication/material-ui/react-router/index.md
documentation/tutorial/ui-libraries/notifications/material-ui/react-router/index.md

There are [Notifications](https://refine.dev/tutorial/ui-libraries/notifications/material-ui/react-router/)-related documentation part is mentioned in [Authentication](https://refine.dev/tutorial/ui-libraries/authentication/material-ui/react-router/) section:
The Notification related documentation has been removed from the Authentication part and added to the right place. 
fixes (issue)
#6668

fix(docs): repeated documentation and wrong placement

---

documentation/docs/ui-integrations/ant-design/hooks/use-select/_basic-usage-live-preview.md
documentation/docs/ui-integrations/ant-design/hooks/use-select/_crud-live-preview.md
documentation/docs/ui-integrations/ant-design/hooks/use-select/_default-value-live-preview.md
documentation/docs/ui-integrations/ant-design/hooks/use-select/_on-search-live-preview.md
documentation/docs/ui-integrations/ant-design/hooks/use-select/_sort-live-preview.md
documentation/docs/ui-integrations/ant-design/hooks/use-select/index.md
documentation/docs/ui-integrations/material-ui/hooks/use-auto-complete/_basic-usage-live-preview.md
documentation/docs/ui-integrations/material-ui/hooks/use-auto-complete/_crud-live-preview.md
documentation/docs/ui-integrations/material-ui/hooks/use-auto-complete/_default-value-live-preview.md
documentation/docs/ui-integrations/material-ui/hooks/use-auto-complete/_on-search-live-preview.md
documentation/docs/ui-integrations/material-ui/hooks/use-auto-complete/_sort-live-preview.md
documentation/docs/ui-integrations/material-ui/hooks/use-auto-complete/index.md

`defaultValue` prop of [`useAutoComplete`](https://refine.dev/docs/ui-integrations/material-ui/hooks/use-auto-complete/#defaultvalue) and [`useSelect`](https://refine.dev/docs/ui-integrations/ant-design/hooks/use-select/) descriptions are wrong.
Descriptions are updated to tell truth.
fixes #6685

fix(docs): wrong description of use-select and use-autocomplete

---

documentation/src/refine-theme/ai-landing-card.tsx
documentation/src/refine-theme/ai-landing-hero.tsx
documentation/src/refine-theme/ai-landing-manage-with-ease-scale-with-confidence.tsx
documentation/src/refine-theme/ai-landing-step-three.css
documentation/src/refine-theme/ai-landing-step-three.tsx

----
fix: aspect ratio of images

fix: update aspect ratios in ai-landing-card component

---

documentation/tutorial/authentication/data-provider-integration/sandpack.tsx
documentation/tutorial/essentials/tables/index.md
documentation/tutorial/essentials/tables/sandpack.tsx
documentation/tutorial/routing/inferring-parameters/react-router/sandpack.tsx
documentation/tutorial/routing/navigation/react-router/sandpack.tsx
documentation/tutorial/routing/syncing-state/react-router/sandpack.tsx

The last page number is not shown when `current + 1 === pageCount` due to a strict `<` comparison.
The condition has been updated to use `<=` to ensure the last page number is displayed properly.

docs: fix(pagination): show last page number when current + 1 equals pageCount

---

examples/pixels-admin/package.json
pnpm-lock.yaml

without this, the app fails at startup with the message: Error: The following dependencies are imported but could not be resolved:
dayjs/plugin/relativeTime (imported by /home/xxx/refine/pixels/pixels-admin/src/utility/time.ts)
dayjs (imported by /home/xxx/refine/pixels/pixels-admin/src/utility/time.ts)
Are they installed?
- [x ] The commit message follows our guidelines: https://refine.dev/docs/guides-concepts/contributing/#commit-convention
- [x ] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset
fails at startup
fixes failed startup

Added missing dependency dayjs

---

documentation/tutorial/ui-libraries/authentication/ant-design/react-router/index.md

- [] Related issue(s) linked
- [] Tests for the changes have been added
- [] Changesets have been added https://refine.dev/docs/guides-concepts/contributing/#creating-a-changeset
Removed a paragraph that didn't belong there. It doesn't seem to be misplaced, as a very similar paragraph exists in the notification part of the tutorial. Might be an old version that was misplaced.

docs(tutorial): remove unnecessary paragraph

---

documentation/docs/guides-concepts/forms/server-side-validation-antd.tsx
documentation/tutorial/ui-libraries/refactoring/ant-design/react-router/index.md

Removed the refineCoreProps from the ANTD examples in the tutorial. It was not intended to be placed there.

docs(tutorial): removed refineCoreProps from the ANTD example

---

.changeset/curvy-pumpkins-hammer.md
packages/hasura/src/dataProvider/index.ts
packages/hasura/test/createMany/index.mock.ts
packages/hasura/test/createMany/index.spec.ts

Hasura data provider doesn't respect meta.gqlVariables for createMany.
fixes #6775

fix(hasura): meta.gqlVariables passed to createMany Hasura data provider

---

.changeset/violet-wasps-study.md
packages/hasura/src/dataProvider/index.ts
packages/hasura/test/updateMany/index.mock.ts
packages/hasura/test/updateMany/index.spec.ts

Hasura data provider doesn't respect meta.gqlVariables for updateMany.
fixes #6775

fix(hasura): meta.gqlVariables passed to updateMany Hasura data provider

---

.changeset/sweet-games-juggle.md
packages/hasura/src/dataProvider/index.ts
packages/hasura/test/deleteMany/index.mock.ts
packages/hasura/test/deleteMany/index.spec.ts

Hasura data provider doesn't respect meta.gqlVariables for deleteMany.
fixes #6775

fix(hasura): meta.gqlVariables passed to deleteMany Hasura data provider

---

.changeset/witty-mirrors-sparkle.md
packages/hasura/src/dataProvider/index.ts
packages/hasura/test/custom/index.mock.ts
packages/hasura/test/custom/index.spec.ts

Hasura data provider doesn't respect meta.gqlVariables for custom.
fixes #6775

fix(hasura): meta.gqlVariables passed to custom Hasura data provider

---

.changeset/neat-tips-provide.md
packages/hasura/src/dataProvider/index.ts
packages/hasura/test/update/index.mock.ts
packages/hasura/test/update/index.spec.ts

Hasura data provider doesn't respect meta.gqlVariables for update.
fixes #6775

fix(hasura): meta.gqlVariables passed to update Hasura data provider

---

.changeset/friendly-feet-marry.md
.changeset/sweet-games-juggle.md
packages/hasura/src/dataProvider/index.ts
packages/hasura/test/deleteMany/index.mock.ts
packages/hasura/test/deleteMany/index.spec.ts
packages/hasura/test/deleteOne/index.mock.ts
packages/hasura/test/deleteOne/index.spec.ts

Here are the actual PRs:
- https://github.com/refinedev/refine/pull/6781
- https://github.com/refinedev/refine/pull/6780
They’ve been reopened because they were merged into the wrong target. (main)

fix(hasura): `meta.gqlVariables` passed to `deleteOne` and `deleteMany` Hasura DataProvider

---

documentation/tailwind.config.js

In this [PR](https://github.com/refinedev/refine/pull/6744/files#diff-b3200011e6db913ff360a955b68b6b13900f5565970cd5d5516a283c82e1be10), I accidentally broke the animation keyframes. This PR fixes that.

fix: landing packages animation doesn't work

---

documentation/src/pages/index.tsx
documentation/src/refine-theme/landing-ai-hero-section.tsx

---
Refine AI banner added to landing page.

feat(docs): add refine ai hero banner

---

.changeset/sharp-otters-burn.md
documentation/tutorial/authentication/data-provider-integration/sandpack.tsx

The authentication tutorial example in the documentation contains smart quotes (`“` and `”`) instead of standard ASCII quotes (`"`), which causes a TypeScript syntax error in code editors and sandpack previews.
Replaced the smart quotes with standard double quotes to ensure the code compiles correctly and behaves as expected.
```diff
- name: “Error”,
+ name: "Error",
```
Fixes #6814

fix(docs): correct syntax error in authentication tutorial

---

.changeset/sour-swans-tell.md
packages/mui/src/hooks/useDataGrid/index.ts

on page change, the datagrid resets to first page.
the paging is working now
fixes (issue)
#6828 #6798 
@ rkmackinnon solution from #6798

fix(useDataGrid): memorize row count

---

.changeset/famous-drinks-thank.md
.changeset/great-birds-nail.md
.changeset/sour-swans-tell.md
cypress/e2e/data-provider-strapi-v4/all.cy.ts
cypress/e2e/table-material-ui-cursor-pagination/all.cy.ts
packages/core/src/hooks/button/button-can-access/index.meta.spec.tsx
packages/core/src/hooks/button/button-can-access/index.tsx
packages/core/src/hooks/button/navigation-button/index.spec.tsx
packages/core/src/hooks/button/navigation-button/index.tsx
packages/mui/src/hooks/useDataGrid/index.spec.ts
packages/mui/src/hooks/useDataGrid/index.ts

- fix(mui): on page change, data-grid resets to first page (https://github.com/refinedev/refine/pull/6859)
- fix(mui): pass meta to use-update from use-data-grid (https://github.com/refinedev/refine/pull/6834)
- fix(mui): pass meta to use-update from use-data-grid (https://github.com/refinedev/refine/pull/6834)

release: June 2025

---

examples/with-remix-material-ui/app/entry.server.tsx
examples/with-remix-material-ui/app/root.tsx
examples/with-remix-material-ui/package.json
pnpm-lock.yaml

---
example is broken because of the following error:
```md
Error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
at throwOnInvalidObjectType (http://localhost:3000/build/_shared/chunk-F6FL47WC.js:9952:17)
at reconcileChildFibers2 (http://localhost:3000/build/_shared/chunk-F6FL47WC.js:10582:15)
at reconcileChildren (http://localhost:3000/build/_shared/chunk-F6FL47WC.js:14310:37)
at finishClassComponent (http://localhost:3000/build/_shared/chunk-F6FL47WC.js:14738:13)
at updateClassComponent (http://localhost:3000/build/_shared/chunk-F6FL47WC.js:14684:32)
at beginWork …
```

fix(with-remix-material-ui): example is broken

---

.changeset/fresh-ads-add.md
documentation/sidebars.js
packages/antd/src/hooks/drawer/useDrawer/index.tsx
packages/antd/src/hooks/index.ts

`useDrawer` is not exported from the antd package.
`useDrawer` is exported from the antd package.
resolves #6944

fix(antd): export `useDrawer` from package

---

.changeset/big-penguins-stare.md
.changeset/chilly-turkeys-sit.md
packages/inferencer/package.json
packages/inferencer/src/components/live/index.tsx
packages/live-previews/package.json
packages/live-previews/pages/preview.tsx
packages/live-previews/src/components/live-error.tsx
pnpm-lock.yaml

> Replace `@aliemir/react-live` with `react-live@4`
After Refine 5, outdated `react-live` package was unable to resolve components properly and caused rendering errors.
This update fixes the rendering errors.

chore: replace `react-live` dependency

---

.changeset/rich-bugs-brake.md
packages/core/src/hooks/data/useInfiniteList.spec.tsx
packages/core/src/hooks/data/useInfiniteList.ts

`useInfiniteList` always sends the initial `currentPage` to the data provider, so loading more requests re-fetch page 1.
Fixed by using `context.pageParam` from Tanstack Query
fixes #7034
This bug was caused by [this commit](https://github.com/refinedev/refine/commit/1a02f020fdc2030e7c7a702e3bd9bfddae2fe1c8)

fix(core):  `useInfiniteList` pagination not work

---

.changeset/late-drinks-boil.md
packages/rest/src/data-providers/nestjsx-crud/nestjsx-crud.options.ts

The `getMany` method in rest data provider was incorrectly handling response mapping. It was simply returning `await response.json()` without considering different response formats. This caused issues when the API returns data in `{ data: BaseRecord[] }` format instead of a direct array.
Now `getMany` properly handles both response formats:
- If response is an array: returns the array directly
- If response is an object with `data` property: returns `body.data`
This makes it consistent with `getList` method behavior and supports different API response structures.
fixes (no related issue)
This fix aligns the `getMany` method's `mapResponse` function with the same logic used in `getList`. The change ensures compatibility with APIs …

fix(rest): getMany mapResponse return value
