refinedev/refine

.github/workflows/pull-request.yml
=> fix: separate commit lint and lint jobs

documentation/docs/api-reference/mantine/hooks/form/useForm.md, documentation/docs/packages/documentation/react-hook-form/useForm.md
=> fix(docs): useForm examples for mantine and react-hook-form

packages/mui/src/components/layout/sider/index.tsx
=> fix(packages): fix button colors for MUI sider component

.changeset/strange-cats-sort.md, documentation/docs/migration-guide/3x-to-4x.md
=> fix(docs): update mantine install references

examples/audit-log-provider/src/App.tsx, examples/audit-log-provider/src/pages/posts/list.tsx
=> fix(examples): styling for audit-log-provider

packages/core/src/components/pages/auth/components/register/index.tsx
=> fix(core): redirect path on register page

examples/auth-mui/src/App.tsx
=> fix(examples): register doesnt redirect on auth-mui

examples/data-provider-airtable/src/App.tsx, examples/data-provider-appwrite/src/App.tsx, examples/data-provider-hasura/src/App.tsx, examples/data-provider-multiple/src/App.tsx, examples/data-provider-nestjsx-crud/src/App.tsx, examples/data-provider-nhost/src/App.tsx, examples/data-provider-strapi-graphql/src/App.tsx, examples/data-provider-strapi-v4/public/manifest.json, examples/data-provider-strapi-v4/src/App.tsx, examples/data-provider-strapi/public/manifest.json, examples/data-provider-strapi/src/App.tsx, examples/data-provider-supabase/src/App.tsx, examples/i18n-nextjs/pages/_app.tsx, examples/i18n-react/src/App.tsx, examples/import-export-antd/src/App.tsx, examples/import-export-mantine/src/App.tsx, examples/import-export-mui/src/App.tsx, examples/inferencer-antd/src/App.tsx, examples/inferencer-chakra-ui/src/App.tsx, examples/inferencer-headless/src/App.tsx, examples/inferencer-mantine/src/App.tsx, examples/inferencer-mui/src/App.tsx, examples/input-custom/src/App.tsx, examples/input-date-picker/src/App.tsx
Added default `options` and `UnsavedChangesNotifier` to examples starting with "c" and "d".
=> feat(v4-examples): add options to examples start with "i" and "d"

examples/upload-antd-base64/src/App.tsx, examples/upload-antd-multipart/src/App.tsx, examples/upload-chakra-ui-basic64/src/App.tsx, examples/upload-chakra-ui-multipart/src/App.tsx, examples/upload-mantine-base64/src/App.tsx, examples/upload-mantine-multipart/src/App.tsx, examples/upload-mui-base64/src/App.tsx, examples/upload-mui-multipart/src/App.tsx, examples/use-infinite-list/src/App.tsx, examples/use-modal-antd/src/App.tsx, examples/use-simple-list-antd/src/App.tsx
Added default options and UnsavedChangesNotifier component to examples starting with "u".
=> V4/add default options to examples start with "u"

packages/codemod/src/transformations/v4/fix-v4-deprecations.ts
Added `useSelect` codemod to handle the `pagination.mode`.
- If `useSelect` has `hasPagination` prop, `hasPagination` will be removed instead of `pagination.mode` will be added. 
- If `hasPagination` is true the `pagination.mode` would be "server". 
- If `hasPagination` is false the `pagination.mode` would be "off". 
- If `useSelect` has not `hasPagination` prop, `pagination.mode` will be added.
- `pagination.mode` would be `"server"`. Because in the previous version, the behavior is "server".
=> v4: add `useSelect` codemod

examples/pixels-admin/src/App.tsx, examples/pixels-admin/src/providers/authProvider.ts, examples/search/src/App.tsx
Fixed:
- Logout doesn't redirect
- Added options and WarnWhenUnsavedChangesNotifier
=> fix(examples): logout doesnt register on pixels-admin admin search

examples/use-simple-list-antd/package.json, examples/use-simple-list-antd/src/pages/posts/list.tsx
Sync location params with form items
=> feat(v4): sync location params between with form items

packages/cli/src/transformers/resource.ts
Updated the `create-resource` command for new resources definition.
=> fix(cli): update resource-create command for new resources type

examples/multi-tenancy-appwrite/src/App.tsx, examples/multi-tenancy-strapi/src/App.tsx, examples/multi-tenancy-strapi/src/authProvider.ts, examples/mutation-mode/src/App.tsx
=> fix(examples): fixes for multitenancy examples

packages/codemod/src/transformations/v4/fix-v4-deprecations.ts
=> fix(codemod): fix v3-deprecations codemod

packages/core/src/contexts/auth/index.tsx, packages/core/src/hooks/auth/useInvaliteAuthStore/index.ts, packages/core/src/hooks/auth/useLogin/index.ts, packages/core/src/hooks/auth/useLogout/index.ts, packages/core/src/hooks/auth/useRegister/index.ts
Fixed the auth store invalidation race condition between `useIsAuthenticated` and `go` redirect.
=> fix(v4-auth): auth race condition

examples/store/pages/404.tsx, examples/store/pages/_app.tsx, examples/store/pages/account/addresses.tsx, examples/store/pages/account/index.tsx, examples/store/pages/account/orders.tsx, examples/store/pages/account/profile.tsx, examples/store/pages/index.tsx, examples/store/pages/order/confirmed/[id].tsx, examples/store/pages/order/details/[id].tsx, examples/store/pages/product/[handle].tsx, examples/store/pages/search/[handle].tsx, examples/store/pages/search/index.tsx, examples/store/src/components/account/AccountLayout/AccountLayout.tsx, examples/store/src/components/auth/LoginView.tsx, examples/store/src/components/auth/SignUpView.tsx, examples/store/src/components/checkout/CheckoutTemplate/CheckoutTemplate.tsx, examples/store/src/components/common/Avatar/Avatar.tsx, examples/store/src/components/common/UserNav/CustomerMenuContent/CustomerMenuContent.tsx, examples/store/src/components/common/UserNav/UserNav.tsx, examples/store/src/components/orders/Help/Help.tsx, examples/store/src/components/orders/Items/Items.tsx, examples/store/src/components/orders/OrderCard/OrderCard.tsx, packages/medusa/src/authProvider/index.ts
=> v4: migrate store example to v4

documentation/docs/migration-guide/3x-to-4x.md, documentation/docs/migration-guide/router-provider.md
I did minor updates on migration guide
=> docs(migration-guide): minor updates

documentation/versioned_docs/version-3.xx.xx/advanced-tutorials/access-control.md, documentation/versioned_docs/version-3.xx.xx/advanced-tutorials/auth/auth0.md, documentation/versioned_docs/version-3.xx.xx/api-reference/core/hooks/data/useCustomMutation/index.md, documentation/versioned_docs/version-3.xx.xx/api-reference/mui/components/auth-page.md, documentation/versioned_docs/version-3.xx.xx/api-reference/mui/components/buttons/show.md, documentation/versioned_docs/version-3.xx.xx/api-reference/mui/components/fields/file.md, documentation/versioned_docs/version-3.xx.xx/api-reference/mui/components/fields/text.md, documentation/versioned_docs/version-3.xx.xx/api-reference/mui/hooks/useDataGrid/index.md, documentation/versioned_docs/version-3.xx.xx/examples/auth-provider/auth0.md, documentation/versioned_docs/version-3.xx.xx/examples/data-provider/hasura.md, documentation/versioned_docs/version-3.xx.xx/examples/data-provider/nhost.md, documentation/versioned_docs/version-3.xx.xx/tutorial/5-understanding-authprovider/1-create-authprovider.md
Added the lost changes in the 3.xx.xx versioned docs.
=> docs(3.xx.xx): add missing docs 

documentation/docs/tutorial/4-adding-crud-pages/chakra-ui/add-create-page.md
=> fix(documentation): fix preview for chakra create

examples/data-provider-appwrite/src/App.tsx
=> fix(example): data-provider-appwrite resource not found

.changeset/warm-feet-change.md, packages/create-refine-app/src/index.ts
the 'project' parameter has been added to `create refine-app`
`npx create refine-app -- -p refine-react`
=> fix: the 'project' parameter has been added.

.github/workflows/calibreapp-image-actions-dispatch.yml, .github/workflows/calibreapp-image-actions.yml, .github/workflows/examples-build.yml, .github/workflows/master-push.yml, .github/workflows/next-push.yml, .github/workflows/pull-request-doc.yml, .github/workflows/pull-request-previews.yml, .github/workflows/pull-request.yml, .github/workflows/push.yml, .github/workflows/store-deploy.yml
=> chore: update GH actions versions

documentation/docs/migration-guide/router-provider.md
added: warning for refine@4 uses react-router-dom@latest, refine@3 uses react-router-dom@6.3.0
=> feat(docs): add react router 6.5.0 warning

.changeset/violet-pigs-smoke.md, packages/inferencer/src/inferencers/mui/create.tsx, packages/inferencer/src/inferencers/mui/edit.tsx
=> fix(inferencer): controller imports from react-hook-form

documentation/docs/migration-guide/auth-provider.md
update auth provider migration guide for new auth hooks
=> feat(docs): add new hooks information to auth provider migration guide

documentation/docs/migration-guide/router-provider.md
Added information about the changes to the access control flow in routes.
=> docs(migration-guide): added access control issues to router changes

documentation/src/theme/Footer/Layout/index.js
I've fixed the dark theme issue of the GitHub sponsor button
=> fix: sponsor button dark theme

.changeset/perfect-boats-thank.md, packages/core/src/hooks/data/useCustom.ts
I've added custom query key support for useCustom hook. 
- #3671
=> feat: add custom query key support for useCustom hook

.changeset/quick-insects-shave.md, packages/antd/src/components/layout/header/index.tsx
I've fixed the text color of logged in user name on the header component
- #3718
=> fix: antd header text color

package.json, packages/core/src/hooks/data/useCustom.spec.tsx
Added tests for useCustom hook.
=> chore(core): add specs for useCustom hook

documentation/blog/2023-03-07-react-dnd.md, documentation/blog/2023-03-15-refine-vs-blitzjs.md
I added refine vs. blitz comparison
=> WIP: docs(blog): add blitz post

examples/finefoods-antd/src/components/product/create.tsx, examples/finefoods-antd/src/components/product/edit.tsx, examples/finefoods-antd/src/components/product/styled.tsx, examples/finefoods-antd/src/pages/products/list.tsx, examples/form-antd-use-drawer-form/src/pages/posts/list.tsx
Updated "fineefoods-antd" ant "antd-use-drawer-form" examples with fixed drawer content.
=> fix: drawer content views on examples

documentation/blog/2022-07-21-admin-panel-with-materialui-and-strapi.md, documentation/blog/2022-08-28-js-currying-functions.md, documentation/blog/2022-09-11-next-refine-pwa.md, documentation/blog/2023-01-23-redwood-vs-refine.md, documentation/blog/2023-02-23-refine-strapi-mantine.md, documentation/blog/2023-03-13-refine-v4-announcement.md, documentation/docusaurus.config.js, documentation/src/assets/nav-menu.ts, documentation/src/theme/BlogListPage/index.js
I remove hackathon content and update featured posts
=> docs(blog): remove hackathon content

documentation/blog/2023-03-07-react-dnd.md, documentation/blog/2023-03-17-react-dashboard-libraries.md
I added dashboard libraries post
=> docs(blog): add dashboard libraries post

documentation/blog/2023-03-17-react-dashboard-libraries.md
I updated top dashboard libraries post.
=> docs(blog): update dashboards post

.changeset/silver-cups-ring.md, packages/codemod/src/definitions/separated-imports/mui.ts
=> fix(codemod): missing import for LoadingButton

documentation/docs/advanced-tutorials/access-control.md, documentation/docs/api-reference/core/hooks/accessControl/useCan.md, documentation/docs/api-reference/core/hooks/auth/useGetIdentity.md, documentation/docs/api-reference/core/providers/accessControl-provider.md, documentation/docs/migration-guide/auth-provider.md, documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
=> fix(docs): add router references to access control provider docs

.changeset/new-cups-collect.md, .changeset/shy-berries-poke.md, examples/form-antd-use-drawer-form/src/pages/posts/list.tsx, packages/antd/src/hooks/form/useDrawerForm/index.spec.tsx, packages/antd/src/hooks/form/useDrawerForm/useDrawerForm.ts
Add new props to `useDrawerForm`.
close #3643
=> feat(antd): `autoSubmitClose`, `autoResetForm`, `defaultVisible` features to `useDrawerForm`

documentation/blog/2023-03-17-react-dashboard-libraries.md, documentation/blog/2023-03-22-react-admin-templates.md
I added react admin template post
=> docs(blog): add react admin templates post

.changeset/thirty-peaches-judge.md
Added missing changeset to #3944
=> chore: add missing changeset for #3944

documentation/docs/tutorial/1-getting-started/antd/3-generate-crud-pages.md, documentation/docs/tutorial/1-getting-started/chakra-ui/3-generate-crud-pages.md, documentation/docs/tutorial/1-getting-started/mantine/3-generate-crud-pages.md, documentation/docs/tutorial/1-getting-started/mui/3-generate-crud-pages.md
I've added `<NavigateToResource>` component
=> docs: add navigateToResource component on tutorial

.changeset/small-rabbits-fail.md, examples/theme-mui-demo/src/App.tsx, examples/theme-mui-demo/src/pages/dashboard/index.tsx, packages/mui/src/components/pages/auth/components/forgotPassword/index.tsx, packages/mui/src/components/pages/auth/components/login/index.tsx, packages/mui/src/components/pages/auth/components/register/index.tsx, packages/mui/src/components/pages/auth/components/styles.ts, packages/mui/src/components/pages/auth/components/updatePassword/index.tsx, packages/mui/src/components/themedLayout/header/index.tsx, packages/mui/src/components/themedLayout/index.tsx, packages/mui/src/components/themedLayout/sider/index.tsx, packages/mui/src/components/themedLayout/title/index.tsx, packages/mui/src/theme/index.ts, packages/mui/src/theme/palette/refinePalette.ts, packages/ui-types/src/types/layout.tsx
- #3944 implemented to `<ThemedSider>`
- `RefineThemes` colors updated. (used default bg colors on `<ThemedSider>` and `<ThemedHeader>`)
=> feat(mui): themed layout colors updated

examples/form-save-and-continue/src/pages/posts/edit.tsx, examples/form-save-and-continue/src/pages/posts/list.tsx
Fixed the console errors on the example.
=> fix: console errors on "form-save-and-continue" examples

.changeset/healthy-wolves-fry.md, packages/antd/src/components/themedLayout/sider/index.tsx
- #3944 implemented to `<ThemedSider>`
=> fix(antd): unsaved changes notifer on `<ThemedSider>`'s logout

.changeset/wise-lobsters-whisper.md, packages/hasura/src/dataProvider/index.ts
Added missing possible ID types to Hasura data provider.
closes #3981
=> fix: add missing ID types

README.md
=> chore: update README example

.changeset/tricky-cherries-repair.md, examples/inferencer-headless/package.json, packages/inferencer/src/create-inferencer/index.tsx
Updated the key generation of inferencer component to resolve mismatching data and view issues.
=> fix(inferencer): add proper keys to inferencer components

packages/core/src/hooks/data/useCustomMutation.ts, packages/core/src/hooks/form/useForm.ts
I explicitly won't create an issue for this Pull Request to further demonstarate another issue(I will create another issue afterwards).
I fixed the typings for useForm, because I was getting unknown type in VsCode. Src and screenshot: https://discord.com/channels/837692625737613362/1088080397314838679
Then I found out the same issue with useCustomMutation. I can revert the last commit if you want. But I'd suggest someone who knows codebase to go through all avaliable SuccessErrorNotification calls and see if …
=> WIP: Update Generic Typings for useForm and useCustomMutation Notifications

examples/pixels-admin/config-overrides.js
=> fix: broken examples

documentation/docs/api-reference/core/hooks/auth/useForgotPassword.md, documentation/docs/api-reference/core/hooks/auth/useGetIdentity.md, documentation/docs/api-reference/core/hooks/auth/useIsAuthenticated.md, documentation/docs/api-reference/core/hooks/auth/useLogin.md, documentation/docs/api-reference/core/hooks/auth/useLogout.md, documentation/docs/api-reference/core/hooks/auth/useOnError.md, documentation/docs/api-reference/core/hooks/auth/usePermissions.md, documentation/docs/api-reference/core/hooks/auth/useRegister.md, documentation/docs/api-reference/core/hooks/auth/useUpdatePassword.md
Added "error handling" section to auth hooks.
=> docs: add error handling sections for auth hooks

documentation/docs/packages/documentation/react-table/_partial-filtering-live-preview.md, documentation/docs/packages/documentation/react-table/index.md
- Added filtering section's live preview example.
- Added more details about filtering.
=> docs: add missing live-preview and more details about filtering

documentation/docs/faq.md
Added a new FAQ entry about adding a navigation link to the sider.
=> docs: add a new FAQ entry about adding a navigation link to the sider

.changeset/smooth-dots-impress.md, packages/core/src/components/gh-banner/index.tsx
Updated GitHub banner to Product Hunt banner temporarily.
=> fix: update GitHub banner to ProductHunt banner temporarily

documentation/docusaurus.config.js, documentation/src/css/custom.css, documentation/src/theme/Navbar/Layout/index.tsx, documentation/tailwind.config.js
=> docs: add ph announcement

documentation/docusaurus.config.js, documentation/src/css/custom.css, documentation/src/theme/Navbar/Layout/index.tsx
=> docs: remove ph announcement

.changeset/polite-kiwis-fix.md, packages/core/src/components/gh-banner/index.tsx
Update `<GithubBanner />` component with GitHub link and text.
=> chore(github-banner): update banner target

examples/data-provider-multiple/src/pages/posts/list.tsx
Update `expandIconPosition` for Antd `Collapse` component.
=> fix: update expandIconPosition for antd collapse component

documentation/README.md, package-lock.json, package.json, packages/live-previews/package.json
Add `@netlify/plugin-nextjs@4.32.2` as dev dependency.
=> chore(live-previews): add netlify nexjts plugin with fixed version

documentation/blog/2023-02-14-refine-pixels-1.md, documentation/blog/2023-04-10-refine-invoicer-1.md, documentation/src/pages/week-of-refine-strapi/index.tsx
Do not merge. I'll merge later on
=> docs(refineWeek): activate day 1

.changeset/nasty-bikes-check.md, packages/core/src/components/gh-banner/styles.ts
=> fix(core): z-index typo

examples/refine-week-invoice-generator/public/index.html, examples/refine-week-invoice-generator/src/App.tsx, examples/refine-week-invoice-generator/src/components/client/create.tsx, examples/refine-week-invoice-generator/src/components/client/edit.tsx, examples/refine-week-invoice-generator/src/components/company/create.tsx, examples/refine-week-invoice-generator/src/components/company/edit.tsx, examples/refine-week-invoice-generator/src/components/contact/create.tsx, examples/refine-week-invoice-generator/src/components/mission/create.tsx, examples/refine-week-invoice-generator/src/pages/contacts/edit.tsx, examples/refine-week-invoice-generator/src/pages/invoices/create.tsx, examples/refine-week-invoice-generator/src/pages/invoices/edit.tsx
=> Fix UI Issues in refine-week-invoice-generator

documentation/src/components/landing/section-bullets/index.tsx
=> fix: horizontal scroll bar on landing page

documentation/docs/contributing.md
Updated contribution docs to add note about following the commit convention.
=> feat: update contributing.md

documentation/blog/2023-04-12-refine-invoicer-3.md, documentation/src/pages/week-of-refine-strapi/index.tsx
=> docs(refineWeek): add part 3

README.md
I added refine.new to README's
=> chore: update GitHub README

documentation/blog/2023-04-14-refine-invoicer-5.md, documentation/src/pages/week-of-refine-strapi/index.tsx
=> docs(refineWeek): add last article

documentation/docs/getting-started/quickstart.md
=> docs(quick-start): update quick start

documentation/blog/2022-07-21-admin-panel-with-materialui-and-strapi.md, examples/blog-material-ui/src/constants.ts, examples/blog-ra-chakra-tutorial/src/constants.ts, examples/blog-react-admin-mantine/src/constants.ts, examples/data-provider-strapi-v4/src/constants.ts
The API URLs updated on examples and docs.
=> fix: update the Strapi API URLs

documentation/docs/tutorial/1-getting-started/0-intro.md
I added refine new to tutorial
=> docs(tutorial): add refine new to tutorial

documentation/docs/tutorial/1-getting-started/0-intro.md
=> docs(tutorial): update headless template

documentation/docs/api-reference/core/hooks/ui/useMenu.md
Added the "Properties" section to `useMenu` hook documentation.
=> docs: add the properties section to `useMenu` hook

documentation/src/theme/TagsList/index.js
=> docs: add order priority tags

.changeset/fuzzy-socks-do.md, packages/inferencer/src/create-inferencer/index.tsx
Fixed an issue that caused the duplicate field error.
=> fix: fix an issue that caused the duplicate field error

.changeset/olive-parents-hammer.md, packages/create-refine-app/package.json
feat: added Vite support.
Now with Vite support, you can create your app with Vite.
=> feat(create-refine-app): add vite support

.changeset/smart-coats-greet.md, packages/medusa/package.json, packages/medusa/refine.config.js, packages/medusa/src/dataProvider/index.ts, packages/medusa/src/index.ts, packages/medusa/src/utils/axios.ts, packages/medusa/src/utils/generateFilter.ts, packages/medusa/src/utils/index.ts, packages/medusa/src/utils/mapOperator.ts, packages/medusa/test/utils/generateFilter.spec.ts, packages/medusa/test/utils/mapOperator.spec.ts
=> feat(medusa): add swizzle to medusa

.changeset/neat-apricots-lay.md
Added changeset about `RefineThemedLayoutV2HeaderProps` type.
=> chore: add missing changeset of `@refinedev/ui-types` package

.changeset/new-years-pull.md
bump to the latest version of `@refinedev/ui-types`
=> chore: bump to latest version of `@refinedev/ui-types`

documentation/docs/api-reference/core/providers/notification-provider.md, documentation/src/assets/examples.ts
=> docs(example): update content and links

.changeset/healthy-bananas-teach.md, packages/inferencer/src/inferencers/antd/create.tsx, packages/inferencer/src/inferencers/antd/edit.tsx, packages/inferencer/src/inferencers/antd/list.tsx, packages/inferencer/src/inferencers/antd/show.tsx, packages/inferencer/src/inferencers/chakra-ui/create.tsx, packages/inferencer/src/inferencers/chakra-ui/edit.tsx, packages/inferencer/src/inferencers/chakra-ui/list.tsx, packages/inferencer/src/inferencers/chakra-ui/show.tsx, packages/inferencer/src/inferencers/headless/create.tsx, packages/inferencer/src/inferencers/headless/edit.tsx, packages/inferencer/src/inferencers/headless/list.tsx, packages/inferencer/src/inferencers/mantine/create.tsx, packages/inferencer/src/inferencers/mantine/edit.tsx, packages/inferencer/src/inferencers/mantine/list.tsx, packages/inferencer/src/inferencers/mantine/show.tsx, packages/inferencer/src/inferencers/mui/create.tsx, packages/inferencer/src/inferencers/mui/edit.tsx, packages/inferencer/src/inferencers/mui/list.tsx, packages/inferencer/src/inferencers/mui/show.tsx
To reduce build time, minimized the packages scope on inferencer.
fix #4249
=> refactor(inferencer): minimize the packages scope

documentation/blog/2023-05-12-git-diff.md
=> docs(blog): add git diff post

documentation/blog/2023-05-15-vite-js.md, documentation/blog/authors.yml, documentation/docs/getting-started/quickstart.md
=> docs(blog): vite post added

cypress/support/commands/chakra-ui/index.ts, cypress/support/e2e.ts, cypress/support/index.d.ts, examples/form-antd-use-drawer-form/cypress/e2e/all.cy.ts, examples/form-antd-use-modal-form/cypress/e2e/all.cy.ts, examples/form-chakra-ui-use-drawer-form/cypress.config.ts, examples/form-chakra-ui-use-drawer-form/cypress/e2e/all.cy.ts, examples/form-chakra-ui-use-drawer-form/cypress/tsconfig.json, examples/form-chakra-ui-use-drawer-form/package.json, examples/form-chakra-ui-use-drawer-form/src/components/createPostDrawer/index.tsx, examples/form-chakra-ui-use-drawer-form/src/components/editPostDrawer/index.tsx, examples/form-chakra-ui-use-form/cypress.config.ts, examples/form-chakra-ui-use-form/cypress/e2e/all.cy.ts, examples/form-chakra-ui-use-form/cypress/tsconfig.json, examples/form-chakra-ui-use-form/package.json, examples/form-chakra-ui-use-form/src/App.tsx, examples/form-chakra-ui-use-form/src/interfaces/index.d.ts, examples/form-chakra-ui-use-form/src/pages/posts/create.tsx, examples/form-chakra-ui-use-form/src/pages/posts/edit.tsx, examples/form-chakra-use-modal-form/cypress.config.ts, examples/form-chakra-use-modal-form/cypress/e2e/all.cy.ts, examples/form-chakra-use-modal-form/cypress/tsconfig.json, examples/form-chakra-use-modal-form/package.json, examples/form-chakra-use-modal-form/src/components/createPostModal/index.tsx, examples/form-chakra-use-modal-form/src/components/editPostModal/index.tsx, examples/form-chakra-use-modal-form/src/interfaces/index.d.ts
End-to-end (e2e) tests are added to examples.
Adding e2e tests to our examples will prevent us from introducing bugs when developing new features.
=> test(examples): add e2e to chakra-ui forms

documentation/blog/2023-05-16-next-redirects.md
I added next.js redirects post
=> docs(blog): add nextjs redirect post

cypress/support/commands/antd/index.ts, cypress/support/commands/chakra-ui/index.ts, cypress/support/e2e.ts, cypress/support/index.d.ts, examples/form-antd-custom-validation/cypress/e2e/all.cy.ts, examples/form-antd-use-drawer-form/cypress/e2e/all.cy.ts, examples/form-antd-use-form/cypress/e2e/all.cy.ts, examples/form-antd-use-form/src/App.tsx, examples/form-antd-use-form/src/pages/posts/edit.tsx, examples/form-chakra-ui-use-form/cypress/e2e/all.cy.ts, examples/form-chakra-ui-use-form/src/App.tsx, examples/form-chakra-ui-use-form/src/pages/posts/edit.tsx
- fixed: wait form render before clear inputs.
- fixed: wait API request to check response
=> test(examples):  fix race conditions

documentation/blog/2023-05-18-zustand.md, documentation/package.json
=> docs(blog): add zustand post

packages/core/src/hooks/auth/useForgotPassword/index.spec.ts, packages/core/src/hooks/auth/useLogin/index.spec.ts, packages/core/src/hooks/auth/useOnError/index.spec.ts, packages/core/src/hooks/auth/useRegister/index.spec.ts, packages/core/src/hooks/auth/useUpdatePassword/index.spec.ts
Increased test coverage of auth hooks.
=> test: increase test coverage of auth hooks

documentation/docs/tutorial/1-getting-started/0-intro.md
I updated the tutorial refine new links
=> docs(tutorial): update tutorial refine new links

documentation/blog/2023-05-03-react-date-picker.md, documentation/blog/2023-05-09-material-ui-modal.md, documentation/blog/2023-05-10-what-is-refine-new.md, documentation/blog/2023-05-12-git-diff.md, documentation/blog/2023-05-15-vite-js.md, documentation/blog/2023-05-16-next-redirects.md, documentation/blog/2023-05-18-zustand.md, documentation/blog/2023-05-21-typescript-enums.md, documentation/blog/2023-05-23-react-tooltip.md, documentation/blog/2023-05-25-docker-vs-kubernates.md
I added docker vs kubernetes post
=> docs(blog): add kubernetes post

documentation/blog/2023-05-26-react-unit-testing.md
I added react unit testing post
=> docs(blog): add react unit testing blog

documentation/blog/2023-05-26-react-unit-testing.md, documentation/blog/2023-05-29-next-js-server-actions.md
I added Next.js server actions post
=> docs(blog): add server actions post

cypress/fixtures/demo-auth-credentials.json, examples/with-nextjs/cypress.config.ts, examples/with-nextjs/cypress/e2e/all.cy.ts, examples/with-nextjs/cypress/fixtures/example.json, examples/with-nextjs/package.json, examples/with-nextjs/pages/posts/create/index.tsx, examples/with-nextjs/pages/posts/edit/[id].tsx, examples/with-nextjs/src/authProvider.ts
Add auth-provider and crud e2e tests on `with-nextjs` example
=> test(examples): add e2e test to `with-nextjs`

.changeset/eleven-walls-fry.md, .changeset/hungry-games-brush.md, .changeset/rude-squids-hide.md
The changesets are updated.
The tests are not affected.
=> chore: update the changesets

documentation/docs/api-reference/core/hooks/authentication/useForgotPassword.md, documentation/docs/api-reference/core/hooks/authentication/useLogin.md, documentation/docs/api-reference/core/hooks/authentication/useRegister.md, documentation/docs/api-reference/core/hooks/authentication/useUpdatePassword.md
Fixed form type errors on auth hook docs.
The tests are not affected.
=> docs: update type error on auth hook docs

documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
=> fix typo in tutorial

documentation/blog/2023-06-02-react-uselayouteffect.md, documentation/blog/authors.yml
I added add uselayouteffect post
=> docs(blog): add uselayouteffect post

documentation/blog/2023-05-18-zustand.md, documentation/blog/2023-06-04-bun-vs-node.md
=> docs(blog): add bun post

documentation/blog/2023-06-04-bun-vs-node.md
=> docs(blog): update article

examples/with-nextjs-appdir/app/(auth)/layout.tsx, examples/with-nextjs-appdir/app/[...catchAll]/page.tsx, examples/with-nextjs-appdir/app/not-found.tsx, examples/with-nextjs-appdir/app/page.tsx, examples/with-nextjs-appdir/src/authProvider.ts
Fixed some redirection issues.
Cypress tests run successfully.
=> fix: next app directory example

documentation/package-lock.json, documentation/package.json, documentation/src/refine-theme/common-theme-toggle.tsx, documentation/src/refine-theme/doc-header.tsx, documentation/src/refine-theme/doc-version-dropdown.tsx
feat: added version changer dropdown
=> docs: add version changer dropdown

documentation/src/components/select-tutorial-framework/index.tsx, documentation/src/components/tutorial-toc/index.tsx, documentation/src/components/unit-circle/index.tsx, documentation/src/css/custom.css, documentation/src/refine-theme/doc-item-layout.tsx
Added tutorial tracker with the new design.
=> docs: redesign tutorial tracker

documentation/blog/2023-06-09-tdd-vs-bdd.md
=> docs(blog): add tdd article

documentation/src/css/custom.css, documentation/src/refine-theme/common-layout.tsx, documentation/src/refine-theme/landing-hero-video.tsx, documentation/src/refine-theme/landing-playground-modal.tsx, documentation/src/refine-theme/landing-playground.tsx
Updated mobile view of the playground.
=> docs: refine.dev playground

documentation/src/refine-theme/common-footer.tsx, documentation/src/refine-theme/doc-header.tsx, documentation/src/refine-theme/doc-version-dropdown.tsx
=> feat(docs): add common footer

documentation/src/pages/about/index.tsx, documentation/src/refine-theme/common-codeblock-string.tsx, documentation/src/refine-theme/common-footer.tsx, documentation/src/refine-theme/common-tabs.tsx, documentation/src/refine-theme/landing-stats.tsx, documentation/tailwind.config.js
=> fix(docs): footer links

documentation/src/refine-theme/doc-header.tsx
=> fix(docs): mobile search

documentation/src/components/blog/featured-blog-post-items/index.js, documentation/src/pages/about/index.tsx, documentation/src/theme/BlogPostItems/index.js
=> fix: new refine.dev design issues

documentation/src/pages/about/index.tsx
fixed: about page title font-size
=> fix(docs): about page title

documentation/blog/2023-06-12-astro-js.md
=> docs(blog): add astro post

documentation/src/components/prop-tag/index.tsx, documentation/src/refine-theme/doc-sidebar.tsx
feat: [add margin to category on sidebar](https://github.com/refinedev/refine/commit/2f798d949d96d6185e513b657880c8a9b5dea2e4) 
feat: [feat(docs): update prop tag asterisk design](https://github.com/refinedev/refine/commit/c1fe5cbbf4a9952c017fa1db380df06f33a0da04)
=> feat(docs): add margin to category on sidebar

documentation/docusaurus.config.js, documentation/src/components/checklist-item/index.tsx, documentation/src/components/checklist/index.tsx, documentation/src/css/custom.css, documentation/src/refine-theme/common-codeblock-string.tsx, documentation/src/refine-theme/icons/check-list.tsx
- Updated the code block theme.
- Fix checklist design
=> docs: fix minor refine.dev issues

documentation/src/refine-theme/common-header/mobile-menu-modal.tsx, documentation/src/refine-theme/doc-sidebar-modal.tsx, documentation/src/refine-theme/landing-playground-modal.tsx
feat: animation durations decreased
feat: mobile sider header UI matched with common header
=> feat(docs): decrease animation duration on header modals

cypress/support/e2e.ts, examples/form-mantine-use-drawer-form/cypress/e2e/all.cy.ts, examples/form-mantine-use-modal-form/cypress/e2e/all.cy.ts, examples/form-material-ui-use-drawer-form/cypress/e2e/all.cy.ts, examples/form-material-ui-use-modal-form/cypress/e2e/all.cy.ts, examples/form-react-hook-form-use-form/cypress/e2e/all.cy.ts, examples/form-react-hook-form-use-modal-form/cypress/e2e/all.cy.ts
- form-mantine-use-drawer-form 
- form-mantine-use-modal-form 
- form-material-ui-use-drawer-form 
- form-material-ui-use-modal-form
=> fix(examples): e2e form tests

.changeset/ninety-dryers-know.md, packages/cli/templates/resource/create.tsx.hbs, packages/cli/templates/resource/edit.tsx.hbs, packages/cli/templates/resource/list.tsx.hbs, packages/cli/templates/resource/show.tsx.hbs
I added HeadlessInfrencer component support for the create-resource command
=> feat: added HeadlessInferencer support for the `create-resource` command

.changeset/light-llamas-remember.md, packages/create-refine-app/package.json, packages/create-refine-app/src/index.ts
Waits https://github.com/pankod/superplate/pull/347
Updated the initial commit message for the apps created with the `create-refine-app`.
=> feat(create-refine-app): add custom initial commit message

documentation/src/theme/BlogListPage/index.js
Added hackathon banner to blog page.
=> docs: add hackathon banner to blog

documentation/blog/2023-06-14-refine-hackathon-2.md, documentation/blog/authors.yml
=> docs(blog): add hackathon post

documentation/blog/2022-09-09-react-18.md, documentation/blog/2023-02-23-refine-strapi-mantine.md, documentation/blog/2023-05-10-what-is-refine-new.md, documentation/blog/2023-06-14-refine-hackathon-2.md, documentation/src/components/blog/promotion/index.js
I added hackathon banners and update featured images
=> docs(blog): add hackathon banner

documentation/blog/2023-06-16-typescript-record.md
=> docs(blog): typescript record type

documentation/docusaurus.config.js, documentation/src/components/tutorial-toc/index.tsx, documentation/src/refine-theme/common-header.tsx, documentation/src/refine-theme/doc-breadcrumbs.tsx, documentation/src/refine-theme/doc-sidebar-modal.tsx, documentation/src/refine-theme/doc-sidebar.tsx, documentation/static/img/refine_favicon.svg
Updated breadcrumbs, sidebar and tutorial TOC for algolia crawler.
=> docs: update navigation for crawlers

hackathon/hackathon-app-ideas.md, hackathon/readme-guideline.md
=> chore: update submission guideline

documentation/docs/faq.md
feat: added answer for "Module X has no exported member Y"
feat: added answer for "How can I remove Github Banner?"
=> feat(docs): add new answers to FAQ section

hackathon/refine-hackathon.md
=> chore: update announcement post

documentation/src/pages/index.tsx, documentation/src/refine-theme/icons/redo.tsx, documentation/src/refine-theme/landing-magic.tsx, documentation/src/refine-theme/landing-walkthrough-video.tsx, documentation/src/refine-theme/landing-walkthrough.tsx, documentation/tailwind.config.js
Added the new section with interactive video.
=> docs(landing): add walkthrough video section

README.md
Fixed broken image URLs in README.md
=> fix: update readme images

cypress/support/e2e.ts
fix: cypress wait time increased
=> fix: increase cypress wait time

documentation/blog/2023-06-23-grpc-vs-rest.md
=> docs(blog): add grpc post

documentation/src/components/integrations/layout/index.tsx, documentation/src/pages/index.tsx, documentation/src/refine-theme/common-doc-search-button.tsx, documentation/src/refine-theme/common-header.tsx, documentation/src/refine-theme/common-header/mobile-menu-modal.tsx, documentation/src/refine-theme/common-header/navbar-item.tsx, documentation/src/refine-theme/landing-header.tsx, documentation/src/refine-theme/landing-hero-top.tsx, documentation/tailwind.config.js
Update the `refine.new` header.
=> fix: update the `refine.dev` header

documentation/blog/2023-06-24-docker-run-command.md
=> docs(blog): add docker run post

documentation/docs/api-reference/core/hooks/authentication/useUpdatePassword.md, documentation/docs/api-reference/core/providers/i18n-provider.md
=> docs(core): add missing npm installs for i18n Provider docs

.changeset/dry-hounds-shake.md, .changeset/little-fishes-give.md, packages/antd/src/components/themedLayoutV2/sider/index.spec.tsx, packages/antd/test/jest.setup.ts, packages/chakra-ui/src/components/buttons/clone/index.tsx, packages/chakra-ui/src/components/buttons/list/index.tsx, packages/chakra-ui/src/components/crud/list/index.spec.tsx, packages/chakra-ui/src/components/fields/date/index.tsx, packages/chakra-ui/src/components/pages/ready/index.spec.tsx, packages/chakra-ui/src/components/themedLayoutV2/index.spec.tsx, packages/chakra-ui/src/components/themedLayoutV2/sider/index.spec.tsx, packages/inferencer/test/jest.setup.ts, packages/kbar/test/jest.setup.ts, packages/mantine/src/components/crud/list/index.spec.tsx, packages/mantine/test/jest.setup.ts, packages/mui/src/components/themedLayoutV2/sider/index.spec.tsx, packages/mui/test/jest.setup.ts, packages/ui-tests/src/test/jest.setup.ts
=> tests: add tests to themed layout

README.md
=> fix: align readme images

.changeset/blue-mayflies-pull.md, packages/cli/src/cli.ts, packages/cli/src/cloud-notifier/index.tsx, packages/cli/src/components/cloud-message/index.tsx, packages/core/src/components/containers/refine/index.tsx
This pull request adds an early access message for the "refine Cloud" service.
=> chore: add refine cloud early access message

documentation/src/pages/index.tsx, documentation/src/refine-theme/common-header.tsx, documentation/src/refine-theme/doc-header.tsx, documentation/src/refine-theme/landing-header.tsx, documentation/src/refine-theme/top-announcement.tsx
Added top announcement to the headers with a common component.
=> docs: add announcement to headers

examples/blog-refine-tremor/README.MD
I updated Tremor example README
=> chore: update tremor example README

packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/create.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/edit.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/show.test.tsx.snap
Updated the snapshots according to the Material UI's latest release.
=> test(inferencer): update material ui snapshots

documentation/blog/2023-07-02-refine-tremor-dashboard.md, documentation/blog/2023-07-04-react-query-intro.md, documentation/blog/authors.yml
=> docs(blog): add react query post

.changeset/beige-bulldogs-cheer.md, packages/inferencer/src/use-relation-fetch/index.ts
Added an additional info log and a link to the documentation into the inferencer components after relation requests are made.
Closes #4604
=> chore(inferencer): add additional inferencer log

documentation/docs/api-reference/antd/components/fields/markdown.md, documentation/docs/api-reference/chakra-ui/components/fields/markdown.md, documentation/docs/api-reference/mantine/components/fields/markdown.md, documentation/docs/api-reference/mui/components/fields/markdown.md
Updated Markdown Field previews in the documentation to contain markdown syntax for demonstration.
=> docs(markdown): update markdown field previews

documentation/docs/contributing.md
Fixed live preview section on contributing page.
=> fix(docs): live preview issue on contributing page

documentation/src/assets/examples.tsx
=> fix(docs): broken example links

documentation/blog/2023-07-09-react-server-components.md
I added server components post
=> docs(blog): add server components

examples/auth-google-login/src/pages/login.tsx, examples/with-nextjs-next-auth/pages/api/auth/[...nextauth].ts
Fixed all login with google examples.
=> fix: google auth in examples

documentation/blog/2023-06-24-docker-run-command.md, documentation/blog/2023-07-11-docker-volume.md
=> docs(blog): add docker volumes post

.changeset/forty-months-hang.md, documentation/docs/api-reference/core/hooks/data/useDelete/index.md, documentation/docs/api-reference/core/hooks/data/useDeleteMany/index.md, documentation/docs/api-reference/core/hooks/data/useUpdate/index.md, documentation/docs/api-reference/core/hooks/data/useUpdateMany/index.md, packages/core/src/hooks/data/useDelete.ts, packages/core/src/hooks/data/useDeleteMany.ts, packages/core/src/hooks/data/useUpdate.ts, packages/core/src/hooks/data/useUpdateMany.ts
Added more information about the `onCancel` property.
=> docs: add more information about `onCancel` property

documentation/docs/api-reference/core/providers/auth-provider.md, documentation/docs/tutorial/5-understanding-authprovider/1-create-authprovider.md
Add more information about auth provider like tutorial.
=> docs: updated auth provider doc

documentation/blog/2023-07-14-zsh-and-bash.md
=> docs(blog): add zsh post

hackathon/refine-hackathon.md
=> chore: fix submission dates

documentation/src/components/tooltip/styles.module.css
Closes #4666,
With less possible changes to the actual styling of the file.
=> fix: broken hover effect in the deprecated light mode

documentation/docs/tutorial/3-understanding-resources/0-intro.md
it's a very simple change in the documentation, I found a wrong route path and I change it (it's just a letter)
=> Update a route name in 0-intro.md file

documentation/src/components/tutorial-toc/index.tsx, documentation/src/refine-theme/blog-footer.tsx, documentation/src/refine-theme/landing-footer.tsx
documentation styles updated according to design
=> feat(docs): update footer items gap and width

documentation/docs/api-reference/antd/components/basic-views/list.md, documentation/docs/api-reference/mui/components/basic-views/list.md
fix typo for mui and  antd component List props
=> fix(docs): mui and antd component List

documentation/src/pages/about/index.tsx
page: https://refine.dev/about/
before:
after:
=> fix(docs): about page team member image height

documentation/src/refine-theme/footer-data.ts, documentation/src/utils/link-rel.ts
=> chore: add site link

documentation/blog/2023-06-14-refine-hackathon-2.md, hackathon/refine-hackathon.md
=> docs(blog): update hackathon contents

documentation/docs/advanced-tutorials/forms/custom-form-validation.md
Update `refine4` screenshots on `custom-form-validation`
=> docs: update `refine@4` screenshots on `custom-form-validation`

documentation/src/components/prop-tag/index.tsx, documentation/src/css/custom.css, documentation/src/refine-theme/css/custom.css, documentation/tailwind.config.js
=> docs: update documentation styles

documentation/blog/2023-03-17-react-dashboard-libraries.md, documentation/blog/2023-07-24-typescript-decorators.md
=> docs(blog): add decorators post

hackathon/refine-hackathon.md
=> chore: update hackathon README

documentation/docs/api-reference/core/providers/i18n-provider.md
=> Add FAQ section for adding automated translations with deepl-translate-github-action example

documentation/blog/2023-01-23-redwood-vs-refine.md, documentation/blog/2023-07-26-refine-primereact-dashboard.md, examples/blog-refine-primereact/README.MD
Minor update on PrimeReact README.
=> chore: update PrimeReact docs

documentation/docs/advanced-tutorials/mutation-mode.md
Update `refine4` screenshots on `mutation mode`
=> docs: update `refine@4` screenshots on `mutation mode`

documentation/docs/advanced-tutorials/auth/auth0.md
Update `refine4` screenshots on `auth0`
=>  docs: update `refine@4` screenshots on `auth0`

documentation/blog/2023-07-31-docker-compose.md
I added docker-compose article
=> docs(blog): add docker compose article

packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/list.test.tsx.snap
snapshot tests are updated because Material UI added `role="presentation"` property to DataGrid.
=> test(inferencer): update snapshot test

examples/finefoods-antd/src/components/title/index.tsx
=> fix(finefoods-antd): logo width

documentation/blog/2023-08-04-refine-hackathon-2-winners.md
Added refine hackathon winners blog post
=> docs(blog): add refine hackathon winners

documentation/blog/2023-08-08-fast-api.md, documentation/blog/authors.yml
=> docs(blog): add fast-api tutorial

examples/multi-tenancy-appwrite/README.md, examples/multi-tenancy-appwrite/netlify.toml, examples/multi-tenancy-appwrite/src/App.tsx, examples/multi-tenancy-appwrite/src/components/select/index.tsx, examples/multi-tenancy-appwrite/src/pages/orders/create.tsx, examples/multi-tenancy-appwrite/src/pages/orders/edit.tsx, examples/multi-tenancy-appwrite/src/pages/orders/list.tsx, examples/multi-tenancy-appwrite/src/pages/products/list.tsx, examples/multi-tenancy-appwrite/src/utility/appwriteClient.ts
Resources and credentials update for `multi-tenancy-appwrite`
=> fix: resources and credentials update for `multi-tenancy-appwrite`

documentation/src/refine-theme/landing-hero-top.tsx
Updated Hero texts for landing page.
=> feat(docs): update landing page hero text

documentation/blog/2023-08-12-react-admin-vs-refine.md, documentation/blog/authors.yml
=> docs(blog): add vs article

documentation/blog/2023-05-10-what-is-refine-new.md, documentation/blog/2023-08-12-react-admin-vs-refine.md
=> docs(blog): update blog

documentation/blog/2023-03-07-react-dnd.md, examples/blog-react-dnd/src/App.tsx
page: https://refine.dev/blog/react-draggable-components-with-react-dnd/
=> feat(docs): blog post update react-dnd

examples/app-crm/src/components/calender/upcoming-events/event/index.tsx, examples/app-crm/src/components/calender/upcoming-events/index.tsx, examples/app-crm/src/components/dashboard/deals-chart.tsx, examples/app-crm/src/components/dashboard/latest-activities/activity/index.tsx, examples/app-crm/src/components/dashboard/latest-activities/index.tsx, examples/app-crm/src/components/dashboard/tasks-chart.tsx, examples/app-crm/src/components/dashboard/total-count-card.tsx, examples/app-crm/src/components/dashboard/total-revenue-chart.tsx
Add skeleton on dashboard components.
=> feat(app-crm): add skeleton on dashboard components 

documentation/blog/2022-02-21-top-react-frameworks.md, documentation/docs/getting-started/quickstart.md
=> docs(blog): update  docs

README.md
Fixed README Typo (to)
https://github.com/refinedev/refine/issues/4855
=> Fixed README Typo

examples/app-crm/package.json, examples/app-crm/src/components/contact/card/index.tsx, examples/app-crm/src/interfaces/graphql.ts, examples/app-crm/src/providers/antd.ts, examples/app-crm/src/routes/contacts/wrapper/index.module.css, examples/app-crm/src/routes/contacts/wrapper/index.tsx, examples/app-crm/src/styles/index.css
Fix `Contact List` page ui issues.
=> fix: contact list page ui issues

examples/app-crm/src/components/deal-kanban-card/index.tsx, examples/app-crm/src/components/kanban/board/index.tsx, examples/app-crm/src/components/project-kanban-card/index.tsx
added: open detail page when kanban card clicked
=> feat(app-crm): open detail page when kanban card clicked

examples/app-crm/src/App.tsx, examples/app-crm/src/providers/resources.tsx, examples/app-crm/src/routes/companies/card-view.tsx, examples/app-crm/src/routes/companies/index.tsx, examples/app-crm/src/routes/companies/list.tsx, examples/app-crm/src/routes/companies/table-view.tsx, examples/app-crm/src/routes/contacts/wrapper/index.tsx, examples/app-crm/src/styles/antd.css, examples/app-crm/src/styles/index.css
=> feat(app-crm): companies list page

examples/app-crm/src/components/kanban/accordion-header-skeleton.tsx, examples/app-crm/src/components/kanban/accordion-header.tsx, examples/app-crm/src/components/kanban/accordion.tsx, examples/app-crm/src/components/kanban/checklist-form.tsx, examples/app-crm/src/components/kanban/comment-form.tsx, examples/app-crm/src/components/kanban/description-form.tsx, examples/app-crm/src/components/kanban/duedate-form.tsx, examples/app-crm/src/components/kanban/stage-form.tsx, examples/app-crm/src/components/kanban/users-form.tsx, examples/app-crm/src/routes/scrumboard/kanban/edit.tsx, examples/app-crm/src/styles/antd.css
=> fix: fix task edit modal issues

examples/app-crm/src/components/dashboard/latest-activities/index.tsx, examples/app-crm/src/components/kanban/comment-form.tsx, examples/app-crm/src/components/kanban/comment-list.tsx, examples/app-crm/src/providers/resources.tsx, examples/app-crm/src/routes/scrumboard/kanban/create-stage.tsx, examples/app-crm/src/routes/scrumboard/kanban/edit-stage.tsx, examples/app-crm/src/routes/scrumboard/kanban/list.tsx, examples/app-crm/src/routes/scrumboard/sales/create-stage.tsx, examples/app-crm/src/routes/scrumboard/sales/edit-stage.tsx, examples/app-crm/src/routes/scrumboard/sales/list.tsx, packages/nestjs-query-graphql/src/dataProvider/index.ts
The operation was removed in favor of the resource.
=> chore(app-crm): remove operation

.github/workflows/e2e-examples.js, .github/workflows/examples-build.yml, examples/base-antd/README.md
- Only run e2e tests if change is detected.
- Only run e2e tests on PR to `next` branch and pushes to `next` branch.
- On `next` branch, compare the changes with the `master` branch.
- Do not run on draft branches.
=> ci(examples-e2e): run tests if change is detected

examples/app-crm/src/providers/auth.ts
added: Randomly select email on <AuthForm />
=> feat(app-crm): Randomly select email on <AuthForm />

examples/app-crm/src/routes/companies/list.tsx, examples/app-crm/src/routes/scrumboard/kanban/list.tsx, examples/app-crm/src/routes/scrumboard/sales/list.tsx
- default companies view changed to card-view
- default sorters added to deal and task stages
=> chore(app-crm): ui improvements

examples/app-crm/src/components/kanban/board/index.module.css, examples/app-crm/src/components/kanban/board/index.tsx, examples/app-crm/src/components/kanban/column/index.module.css, examples/app-crm/src/components/kanban/column/index.tsx, examples/app-crm/src/components/kanban/item/index.tsx
added: overflow scroll to kanban columns
fixed: DND card gets lost when you drop into initial place. 
=> feat(app-crm): `overflow:scroll` added to kanban

examples/app-crm/src/App.tsx, examples/app-crm/src/components/index.ts, examples/app-crm/src/components/role-tag/index.tsx, examples/app-crm/src/routes/administration/index.tsx, examples/app-crm/src/routes/administration/settings.module.css, examples/app-crm/src/routes/administration/settings.tsx
feat: users table added to settings page
=> feat(app-crm): add users table to settings page

examples/app-crm/src/components/account-settings/index.module.css, examples/app-crm/src/components/account-settings/index.tsx, examples/app-crm/src/components/company/info-form.tsx, examples/app-crm/src/components/current-user.tsx, examples/app-crm/src/components/sider.tsx, examples/app-crm/src/components/single-element-form/index.module.css, examples/app-crm/src/components/single-element-form/index.tsx
Added a drawer to show & edit user infos.
=> chore: add user profile drawer to CRM example

examples/app-crm/src/routes/companies/list.tsx, examples/app-crm/src/routes/contacts/wrapper/index.tsx, examples/app-crm/src/routes/quotes/list.tsx
added: loading indicator to search input
=> feat(app-crm): add loading indicator to search input

examples/app-crm/src/components/participants/index.tsx
=> feat(app-crm): use custom avatar on participants

examples/app-crm/src/components/calendar/manage-categories/index.tsx, examples/app-crm/src/components/company/notes.tsx, examples/app-crm/src/components/contact/comment/comment-form.tsx, examples/app-crm/src/components/contact/comment/comment-list.tsx, examples/app-crm/src/components/kanban/comment-form.tsx, examples/app-crm/src/components/kanban/comment-list.tsx, examples/app-crm/src/routes/scrumboard/kanban/create-stage.tsx, examples/app-crm/src/routes/scrumboard/kanban/edit-stage.tsx, examples/app-crm/src/routes/scrumboard/kanban/list.tsx, examples/app-crm/src/routes/scrumboard/sales/create-details.tsx, examples/app-crm/src/routes/scrumboard/sales/create-stage.tsx, examples/app-crm/src/routes/scrumboard/sales/edit-stage.tsx, examples/app-crm/src/routes/scrumboard/sales/list.tsx
Fixed unrelated notification messages on CRM.
=> chore: update notification messages

examples/app-crm/src/components/kanban/board/index.module.css, examples/app-crm/src/components/kanban/column/index.module.css, examples/app-crm/src/components/kanban/column/index.tsx, examples/app-crm/src/routes/quotes/list.tsx, examples/app-crm/src/routes/quotes/show/index.tsx
added bottom padding to kanban
=> feat(app-crm): add bottom padding to kanban

examples/app-crm/src/components/company/card-view.tsx, examples/app-crm/src/components/contact/table-view.tsx, examples/app-crm/src/components/custom-avatar.tsx, examples/app-crm/src/components/dashboard/tasks-chart.tsx, examples/app-crm/src/components/title.tsx, examples/app-crm/src/providers/auth.ts, examples/app-crm/src/routes/contacts/list.tsx, examples/app-crm/src/routes/login.tsx
- added: registerPassword, updatePassword, and, forgotPassword methods to authProvider
- added: companies card-view column count fixed to 4
- added: contacts pageSize changed to 12
- added: when `img.src` is not undefined, CustomAvatar background-color removed
=> feat(app-crm): ui improvements

examples/app-crm/src/routes/contacts/show/index.tsx
Contact form was triggering the updateMutation twice and was using state. 
This has been fixed by using antd Form.Item.
=> refactor(app-crm): contact form for optimization

examples/app-crm/src/App.tsx, examples/app-crm/src/providers/auth.ts, examples/app-crm/src/providers/data.ts, examples/app-crm/src/routes/login.tsx
Added support for OAuth login to CRM example.
Also added `key` prop to `Authenticated` components to prevent race condition with redirects.
Needs to be merged after API changes are deployed.
=> feat(crm): Add OAuth logins

packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/create.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/edit.test.tsx.snap
Fix `@refinedev/inferencer` snapshot tests.
=> fix(inferencer):snapshot tests

documentation/blog/2023-09-06-daisy-ui-panel.md
=> docs(blog): add daisy ui post

documentation/blog/2023-09-11-tailwind-flex.md
=> docs(blog): add tailwind post

examples/finefoods-antd/src/pages/orders/list.tsx
fix initial value of the form cause it was not select selected option.
fixed #4863
=> fix(finefoods-antd): fix initial value of the form cause it was not select selected option

examples/app-crm/src/components/company/card-view.tsx, examples/app-crm/src/components/company/card/card.tsx, examples/app-crm/src/components/company/card/index.ts, examples/app-crm/src/components/company/card/skeleton.tsx, examples/app-crm/src/components/contact/card-view.tsx, examples/app-crm/src/components/contact/card/card.tsx, examples/app-crm/src/components/contact/card/index.module.css, examples/app-crm/src/components/contact/card/index.ts, examples/app-crm/src/components/contact/card/skeleton.tsx, examples/app-crm/src/routes/companies/list.tsx, examples/app-crm/src/routes/contacts/list.tsx
refactor: Use Ant Design `<List/>` component on the Companies and the Contacts page
=> refactor(app-crm): use antd list on company and quote card view

examples/app-crm/index.html, examples/app-crm/src/components/banner/index.module.css, examples/app-crm/src/components/banner/index.tsx, examples/app-crm/src/components/layout.tsx, examples/app-crm/src/components/sider.tsx
Added announcement banner to layout to redirect users to source code
=> feat(app-crm): add announcement banner to layout

hackathon/refine-hackathon.md
Misspelled the name in Refine Hackathon, it was written as "Rasir" not "Rasit"
closes #4941 
=> chore: edited misspelled name in Refine Hackathon

README.md
=> fix: readme typo and grammar

documentation/blog/2023-06-14-refine-hackathon-2.md, documentation/blog/2023-09-06-daisy-ui-panel.md
=> docs(blog): featured daisy ui post

.changeset/nine-plums-approve.md, .changeset/six-owls-attend.md, .changeset/smart-turtles-relax.md, packages/devtools-internal/CHANGELOG.md, packages/devtools-server/CHANGELOG.md, packages/devtools-server/src/constants.ts, packages/devtools-shared/CHANGELOG.md, packages/devtools-ui/CHANGELOG.md, packages/devtools-ui/src/pages/onboarding.tsx, packages/devtools/CHANGELOG.md, packages/devtools/package.json
- Fixed the feed content URL in `@refinedev/devtools-server`
- Fixed the Terms and Conditions and Privacy Policy URLs in onboarding page of `@refinedev/devtools-ui`
- Updated peer dependencies of `@refinedev/devtools`
=> fix(devtools): broken links in devtools UI

documentation/blog/2023-09-20-next-ui-panel.md, examples/blog-refine-nextui/README.MD
=> docs(blog): add NextUI post

documentation/docs/packages/list-of-packages.md, documentation/src/assets/integration-icons/hygraph.tsx, documentation/src/assets/integration-icons/index.ts, documentation/src/assets/integrations.ts, documentation/src/partials/data-provider/supported-data-providers.md
I added Hygraph integration to the docs
=> docs(integrations): add new integration

.changeset/afraid-berries-float.md, .changeset/three-yaks-trade.md, packages/devtools-server/package.json, packages/devtools-server/src/project-id/get-project-id-from-package-json.ts, packages/devtools-server/src/project-id/set-project-id-to-package-json.ts, packages/devtools-server/src/project-id/set-project-id-to-refine-component.ts, packages/devtools-server/src/project-id/transform.ts, packages/devtools-server/src/project-id/update-project-id.ts, packages/devtools-server/src/serve-api.ts, packages/devtools-server/src/serve-proxy.ts, packages/devtools-server/src/serve-ws.ts, packages/devtools-server/src/setup-server.ts, packages/devtools-ui/src/components/highlight.tsx, packages/devtools-ui/src/components/icons/check-alt.tsx, packages/devtools-ui/src/components/icons/copy.tsx, packages/devtools-ui/src/components/icons/hourglass.tsx, packages/devtools-ui/src/components/icons/sliding-background.tsx, packages/devtools-ui/src/components/icons/warning.tsx, packages/devtools-ui/src/components/layout.tsx, packages/devtools-ui/src/components/project-id-fix-banner.tsx, packages/devtools-ui/src/components/project-id-fix-modal.tsx, packages/devtools-ui/src/interfaces/api.ts, packages/devtools-ui/src/utils/project-id.ts, packages/devtools-ui/tailwind.config.js
Added the warning for missing project ids and auto-fix action from UI
=> chore(devtools): project id actions

.changeset/heavy-dogs-lie.md, packages/devtools-server/src/packages/get-available-packages.ts
Fixed some issues in package descriptions and usage instructions used in the package install screens
=> chore(devtools-server): update package instuctions

.changeset/stale-fireants-happen.md, packages/devtools-ui/src/components/monitor-filters.tsx, packages/devtools-ui/src/pages/monitor.tsx
=> feat(devtools): add multi-select-for-unique trace

packages/devtools/CHANGELOG.md
=> fix typo in usage command

.changeset/afraid-lemons-fly.md, .changeset/curvy-boats-wave.md, .changeset/flat-turtles-hope.md, .changeset/strong-pans-glow.md, .changeset/unlucky-eyes-check.md, .changeset/warm-baboons-reflect.md, packages/cli/package.json, packages/core/package.json, packages/devtools-internal/package.json, packages/devtools-server/package.json, packages/devtools-ui/package.json, packages/devtools/package.json
Fixed the dependency versions of devtools and related packages to enforce them to follow the releases and avoid mismatching versions between devtools packages.
=> refactor(devtools): fixed dependency versions

.changeset/slimy-spiders-design.md, .changeset/tiny-candles-buy.md, packages/devtools-server/src/feed/get-feed.ts, packages/devtools-ui/src/components/feed.tsx, packages/devtools-ui/src/components/json-viewer.tsx, packages/devtools-ui/src/components/layout.tsx, packages/devtools-ui/src/components/modal.tsx, packages/devtools-ui/src/components/monitor-details.tsx, packages/devtools-ui/src/components/monitor-table.tsx, packages/devtools-ui/src/components/owners.tsx, packages/devtools-ui/src/components/packages.tsx, packages/devtools-ui/src/components/project-id-fix-banner.tsx, packages/devtools-ui/src/components/resizable-pane.tsx, packages/devtools-ui/src/pages/monitor.tsx, packages/devtools-ui/src/pages/overview.tsx
- Updated the layout with overflowing content
- Adjusted the width of the JSON viewer modal for larger screens
- Added `target=_blank` to anchors in feed content
=> fix(devtools-ui): layout fixes

examples/app-crm/src/components/calendar/upcoming-events/event/index.tsx, examples/app-crm/src/routes/calendar/create.tsx, examples/app-crm/src/routes/calendar/edit.tsx, examples/app-crm/src/routes/calendar/show.tsx, examples/app-crm/src/routes/calendar/wrapper.tsx, examples/app-crm/src/routes/companies/components/deals-table.tsx, examples/app-crm/src/routes/contacts/components/card/card.tsx, examples/app-crm/src/routes/contacts/create.tsx, examples/app-crm/src/routes/contacts/show/index.tsx, examples/app-crm/src/routes/dashboard/components/deals-chart.tsx, examples/app-crm/src/routes/dashboard/components/tasks-chart.tsx, examples/app-crm/src/routes/dashboard/components/total-count-card/index.tsx, examples/app-crm/src/routes/dashboard/components/total-revenue-chart.tsx, examples/app-crm/src/routes/dashboard/index.tsx, examples/app-crm/src/routes/quotes/components/form-modal.tsx, examples/app-crm/src/routes/scrumboard/components/deal-kanban-card/index.tsx, examples/app-crm/src/routes/scrumboard/components/modal-footer.tsx, examples/app-crm/src/routes/scrumboard/kanban/create-stage.tsx, examples/app-crm/src/routes/scrumboard/kanban/create.tsx, examples/app-crm/src/routes/scrumboard/kanban/edit-stage.tsx, examples/app-crm/src/routes/scrumboard/kanban/edit.tsx, examples/app-crm/src/routes/scrumboard/kanban/list.tsx, examples/app-crm/src/routes/scrumboard/sales/create-details.tsx, examples/app-crm/src/routes/scrumboard/sales/create-stage.tsx, examples/app-crm/src/routes/scrumboard/sales/create.tsx, examples/app-crm/src/routes/scrumboard/sales/edit-stage.tsx, examples/app-crm/src/routes/scrumboard/sales/edit.tsx, examples/app-crm/src/routes/scrumboard/sales/list.tsx, examples/app-crm/tsconfig.json
- refactor `useNavigate` hook usages with `useNavigation` hook from `@refinedev/core`.
- get rid of unnecessary `useCustom` usages.
- Fix calculation for expected and realized revenues.
=> examples(crm): refactors

README.md, documentation/src/refine-theme/common-header/constants.ts, documentation/src/theme/BlogListPage/index.js
=> docs(hackathon): remove hackathon content

.changeset/lemon-kings-hear.md, packages/simple-rest/src/provider.ts
=> fix(simple-rest): fix persistent headers issue in custom method

documentation/blog/2023-10-02-refine-crm-overview.md, documentation/src/components/banner/banner-modal.tsx, documentation/src/components/banner/banner-random.tsx
=> docs(blog): add CRM overview

documentation/src/refine-theme/blog-footer.tsx, documentation/src/refine-theme/common-header.tsx, documentation/src/refine-theme/common-header/mobile-menu-modal.tsx, documentation/src/refine-theme/common-refine-logo.tsx, documentation/src/refine-theme/landing-footer.tsx, documentation/src/refine-theme/landing-header.tsx, documentation/src/utils/open-figma.ts
feat(docs): open figma when logo is clicked with right click
=> feat(docs): open figma when logo is clicked with right click

documentation/sidebars.js, documentation/src/refine-theme/doc-sidebar.tsx, documentation/src/refine-theme/top-announcement.tsx
feat: update dev tools announcement text
=> feat(docs): update devtools announcement text

documentation/docs/packages/list-of-packages.md, documentation/src/assets/integration-icons/index.ts, documentation/src/assets/integration-icons/sanity.tsx, documentation/src/assets/integrations.ts, documentation/src/partials/data-provider/supported-data-providers.md
I added Sanity integration to the docs.
=> docs(integration): add sanity integration

documentation/blog/2023-10-10-nextjs-vs-react.md
=> docs(blog): add nextjs vs react

documentation/blog/2023-10-12-react-createportal.md
I added react createPortal post
=> docs(blog): add react portal post

documentation/docs/contributing.md, documentation/docs/tutorial/2-understanding-dataprovider/2-create-dataprovider.md
Updated `pagination` data structure, `CrudSort` section reference, `custom` method headers, `filter` operator and start command.
=> updated docs

documentation/blog/2023-10-16-mojo.md, documentation/blog/authors.yml
=> docs(blog): add mojo post

documentation/blog/2023-10-16-mojo.md
=> docs(blog): update mojo post

packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/list.test.tsx.snap
=> chore(inferencer): update snapshots for mui

documentation/blog/2023-10-16-mojo.md, documentation/blog/2023-10-17-react-patterns.md
=> docs(blog): add react patterns post

documentation/blog/2023-10-18-docker-networking.md
I added docker networking post
=> docs(blog): add docker networking post

.changeset/violet-otters-compare.md, packages/devtools/src/components/devtools-pin.tsx, packages/devtools/src/components/icons/devtools-icon.tsx, packages/devtools/src/components/resizable-pane.tsx, packages/devtools/src/panel.tsx, packages/devtools/src/utilities/index.ts
Update panel and pin positioning for rounded numbers to avoid subpixel blurry rendering
=> chore(devtools): fix blurry renders

documentation/blog/2023-05-25-docker-vs-kubernates.md, documentation/blog/2023-10-18-docker-networking.md, documentation/blog/2023-10-19-kubecti-exec.md
=> docs(blog): add kubectl exec post

documentation/blog/2023-10-20-js-splice.md
=> docs(blog): add splice post

documentation/blog/2023-10-22-kubecti-restart-pod.md, examples/blog-refine-markdown/README.MD
=> docs(blog): add kubeclt restart pod

.changeset/eighty-months-yawn.md, packages/devtools-server/.gitignore, packages/devtools-server/package.json, packages/devtools-server/src/serve-proxy.ts, packages/devtools-ui/src/pages/login.tsx, packages/devtools-ui/src/utils/auth.ts
Updated the devtools server auth flows to cover wider use cases and environments.
=> chore(devtools): update auth flow

.changeset/afraid-steaks-cry.md, .changeset/tame-pianos-talk.md, packages/devtools-server/src/serve-api.ts, packages/devtools-ui/src/components/package-item.tsx, packages/devtools-ui/src/components/packages.tsx, packages/devtools-ui/src/utils/packages.ts
Add the ability to update all outdated packages with a single click
=> feat(devtools): update all button

documentation/blog/2023-10-23-js-substring.md
=> docs(blog): add JS substring post

documentation/src/partials/data-provider/supported-data-providers.md
=> feat(docs): add data-provider-jsonapi

.changeset/beige-needles-travel.md, packages/devtools-ui/package.json, packages/devtools-ui/src/components/halloween-ghosts.tsx, packages/devtools-ui/src/components/layout.tsx
🎃 halloween update: devtools panel is temporarily welcoming a group of ghosts 👻, don't worry they are harmless. 👻
=> chore(devtools-ui): add halloween easter egg 👻

documentation/blog/2023-10-26-htmx.md
=> docs(blog): add htmx post

README.md, documentation/blog/2023-10-27-kubecti-config.md
I added kubeclt post and update the README
=> docs(blog): add kubectl config post

documentation/src/components/video-modal-15k/index.tsx, documentation/src/refine-theme/common-layout.tsx, documentation/src/refine-theme/top-announcement.tsx
Added a video modal with the 15k journey video and show it only once
=> docs: add 15k video modal

documentation/blog/2023-10-29-react-slick.md
=> docs(blog): add react slick

examples/data-provider-sanity/README.md
I updated Sanity data provider example README
=> chore: update Sanity example README

documentation/src/components/banner/banner-examples.tsx, documentation/src/components/banner/banner-modal.tsx, documentation/src/components/banner/banner-random.tsx, documentation/src/components/banner/banner-sidebar.tsx
=> chore: update blog banners

documentation/blog/2023-10-31-react-table.md
=> docs(blog): add table post

documentation/src/css/custom.css, documentation/src/pages/index.tsx, documentation/src/refine-theme/landing-packages.tsx, documentation/tailwind.config.js
https://github.com/refinedev/refine/assets/23058882/a2928e50-b4a2-4a9a-af6b-e3a809c472e1
=> [new-landing]: add start faster section

documentation/src/pages/index.tsx, documentation/src/refine-theme/landing-trusted-by-developers.tsx, documentation/tailwind.config.js
https://github.com/refinedev/refine/assets/23058882/6779059a-125d-4fb4-9a94-55fb6c483fa2
=> [new-landing]: add trusted by developers

documentation/blog/2023-11-05-kubectl-port-forwarding.md
=> docs(blog): add kubectl port forward

documentation/blog/2023-11-07-ts-classes.md, documentation/blog/2023-11-09-react-error-boundaries.md
=> docs(blog): add react error post

documentation/src/assets/examples.tsx, documentation/src/pages/pricing/index.tsx, documentation/src/refine-theme/common-header/constants.ts, documentation/src/refine-theme/landing-community.tsx, documentation/src/refine-theme/landing-enterprise-developers.tsx
=> fix(docs): update community stats

documentation/src/refine-theme/landing-testimonial.tsx
=> feat(docs): update testimonial links

documentation/blog/2023-11-11-mantine-ui.md
=> docs(blog): add mantine ui

documentation/src/components/banner/banner-modal.tsx
Added missing gtag event for `<BannerModal />` component.
=> feat: add gtag event for banner modal

.changeset/funny-pets-cheer.md, .changeset/wild-oranges-compete.md, packages/create-refine-app/package.json, packages/create-refine-app/src/greeting/index.ts
Updated greeting message to persist after wizard is open
=> chore(create-refine-app): update greeting

.changeset/light-buttons-compete.md, packages/core/src/components/gh-banner/index.tsx
update GitHub support banner text
=> chore: update GitHub support banner text

documentation/src/components/blog/blog-post-page/index.js, documentation/src/components/blog/icons.tsx
=> fix(documentation): fix x logo color on blog post share

documentation/src/components/banner/banner-image-with-text.tsx
=> fix(documentation): fix banner overflow

documentation/docusaurus.config.js, documentation/plugins/clarity.js, documentation/plugins/clarity.ts
https://clarity.microsoft.com/ added to refine.dev
=> feat(docs): add clarity

documentation/blog/2023-11-15-ts-satisfies.md
=> docs(blog): add satisfies operator

documentation/blog/2023-11-17-react-svg.md
=> docs(blog): add react svg post

documentation/blog/2023-11-19-kubectl-delete-pod.md
=> docs(blog): add kubectl delete post

documentation/blog/2023-11-20-kubeclt-delete-pod.md
=> docs(blog): add kubectl del pod

README.md, documentation/blog/2023-11-21-js-vs-ts.md, packages/core/README.md
=> docs(blog): add ts vs js post

documentation/blog/2023-03-17-react-dashboard-libraries.md, documentation/blog/2023-03-22-react-admin-templates.md, examples/app-crm/README.md
=> docs(blog): update some posts

documentation/blog/2023-10-20-js-splice.md, documentation/blog/2023-10-22-kubecti-restart-pod.md, documentation/blog/2023-10-23-js-substring.md, documentation/blog/2023-10-26-htmx.md, documentation/blog/2023-10-27-kubecti-config.md, documentation/blog/2023-11-04-kubecti-image-pull.md, documentation/blog/2023-11-05-kubectl-port-forwarding.md, documentation/blog/2023-11-07-ts-classes.md, documentation/blog/2023-11-09-react-error-boundaries.md, documentation/blog/2023-11-11-mantine-ui.md, documentation/blog/2023-11-13-kubeclt-describe.md, documentation/blog/2023-11-15-ts-satisfies.md, documentation/blog/2023-11-17-react-svg.md, documentation/blog/2023-11-20-kubeclt-delete-pod.md, documentation/blog/2023-11-21-js-vs-ts.md, documentation/blog/2023-11-22-crash-loop-back.md
I added K8S crashloopback error post
=> docs(blog): add k8s error post

documentation/docs/packages/documentation/react-hook-form/introduction.md, documentation/docs/packages/documentation/react-hook-form/useForm.md, documentation/sidebars.js
=> feat(core): add introduction to react hook form

documentation/docs/guides-concepts/general-concepts/index.md
Updated the general concepts documentation with minor improvements for better clarity and accuracy.
=> chore: minor updates for general concepts doc

documentation/blog/2023-09-11-tailwind-flex.md, documentation/blog/2023-09-18-heroicons.md, documentation/blog/2023-09-20-next-ui-panel.md, documentation/blog/2023-10-02-refine-crm-overview.md, documentation/blog/2023-10-05-docker-swarm.md, documentation/blog/2023-10-06-react-hot-toast.md, documentation/blog/2023-10-10-nextjs-vs-react.md, documentation/blog/2023-10-12-react-createportal.md, documentation/blog/2023-10-18-docker-networking.md, documentation/blog/2023-10-19-kubecti-exec.md, documentation/blog/2023-11-23-react-virtual-dom.md, examples/app-crm/README.md
I added virtual dom posta and updated some posts.
=> docs(blog): add virtual dom post

examples/blog-refine-daisyui/README.MD, examples/blog-refine-digital-ocean/README.MD, examples/blog-refine-nextui/README.MD, examples/blog-refine-primereact/README.MD, examples/blog-refine-tremor/README.MD
I updated some of the example README's.
=> chore: update examples README

documentation/blog/2023-11-27-pnpm-guide.md
=> docs(blog): add pnpm post

documentation/blog/2021-10-6-migrating-react-admin-application-to-refine.md, documentation/blog/2021-11-26-refine-vs-react-admin.md, documentation/blog/2022-03-16-internal-tool-frameworks.md, documentation/blog/2023-07-04-react-query-intro.md, documentation/blog/2023-07-11-docker-volume.md, documentation/blog/2023-07-24-typescript-decorators.md, documentation/blog/2023-07-31-docker-compose.md, documentation/blog/2023-08-12-react-admin-vs-refine.md, documentation/blog/2023-08-16-react-web-socket.md, documentation/blog/2023-08-18-docker-exec.md, documentation/blog/2023-08-24-react-markdown.md, documentation/blog/2023-11-28-terraform-aws.md, documentation/blog/authors.yml
I added Terraform post and made minor updates
=> docs(blog): add terraform post

documentation/blog/2023-02-23-refine-strapi-mantine.md, documentation/blog/2023-05-23-react-tooltip.md, documentation/docs/guides-concepts/routing/index.md, documentation/docs/packages/documentation/command-palette.md, documentation/versioned_docs/version-3.xx.xx/further-readings/telemetry.md
Fixed broken links to documentation.
=> docs(fix): broken links

.changeset/hip-cars-relate.md, packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/list.test.tsx.snap
=> fix(inferencer): material ui snapshots tests

documentation/docs/guides-concepts/general-concepts/index.md
=> Fix typos in general-concepts index.md

examples/blog-refine-digital-ocean/README.MD
=> chore: update example README

documentation/docs/guides-concepts/data-fetching/one-to-many.tsx, documentation/docs/guides-concepts/data-fetching/use-list-with-filters.tsx, documentation/src/refine-theme/footer-data.ts, examples/data-provider-appwrite-tutorial-docs/README.md
Replaced some overlooked `next` branch references with `master.
=> chore: fix next branch references

documentation/blog/2023-08-12-react-admin-vs-refine.md, documentation/blog/2023-12-11-frameworks-2024.md
=> docs(blog): add front end frameworks post

documentation/blog/2023-12-12-k8s-cronjobs.md
=> docs(blog): add k8s cronjobs

documentation/blog/2023-12-13-stylex-post.md
=> docs(blog): add stylex post

documentation/blog/2023-07-02-refine-tremor-dashboard.md, documentation/blog/2023-08-12-react-admin-vs-refine.md, documentation/blog/2023-10-02-refine-crm-overview.md, documentation/blog/2023-12-14-k8s-persistent-volumes.md
I added persistent volumes post
=> docs(blog): add persistent volumes post

documentation/blog/2023-12-15-kubectl-cheat-sheet.md
=> docs(blog): add kubectl cheat sheet

documentation/src/pages/enterprise/index.tsx, documentation/src/refine-theme/enterprise-table.tsx
animation added to 
https://github.com/refinedev/refine/assets/23058882/c0dd6e51-bf3e-4aad-8cc2-5223e86c48d9
the enterprise table
=> feat(docs): enterprise page table animation

documentation/blog/2022-03-16-internal-tool-frameworks.md, documentation/blog/2023-12-19-chakra-ui.md, documentation/blog/authors.yml, documentation/versioned_docs/version-3.xx.xx/comparison.md
=> docs(blog): add chakra post

documentation/plugins/templates.js, documentation/plugins/templates.ts
fix: The template page's CRM application link was wrong.
=> fix(docs): templates page crm link

.changeset/strange-emus-grin.md, packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/create.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/edit.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/show.test.tsx.snap
=> fix(inferencer): material ui snapshot tests

documentation/blog/2023-07-26-refine-primereact-dashboard.md, documentation/blog/2023-09-06-daisy-ui-panel.md, documentation/blog/2023-12-20-web-development.md, documentation/src/theme/BlogPostItems/index.js
=> docs(blog): add web development post

documentation/blog/2023-11-21-js-vs-ts.md
=> docs(blog): update article slug

documentation/blog/2023-11-21-js-vs-ts.md, documentation/blog/2023-12-20-web-development.md
=> fix(blog): fix missing text, typos, flow

documentation/docs/guides-concepts/faq/index.md
Updated FAQ guide with up-to-date answers and new questions
=> docs(faq): update faq guide

documentation/blog/2023-12-25-kubectl-scale.md, documentation/blog/2023-12-26-build-an-app.md
=> docs(blog): add kubectl post

documentation/docs/guides-concepts/forms/index.md, documentation/docs/guides-concepts/forms/use-select-antd.tsx, documentation/docs/guides-concepts/forms/use-select-headless.tsx, documentation/docs/guides-concepts/forms/use-select-mantine.tsx, documentation/docs/guides-concepts/forms/use-select-material-ui.tsx
relationship section added to https://refine.dev/docs/guides-concepts/forms/
=> feat(docs): add relationships to form guide

documentation/src/refine-theme/landing-hero-showcase-section.tsx
Updated the button's text in landing page showcase section from "Examples" to "Templates" and updated the urls.
=> docs(landing-showcase): update button text

documentation/blog/2023-12-27-edit-crontab.md
=> docs(blog): add crontab post

documentation/blog/2023-12-28-kubectl-logs.md
=> docs(blog): add kubeclt logs post

documentation/blog/2023-12-29-admin-panel-frameworks.md
I added frameowrk for building admin panel post.
=> docs(blog): add frameworks post

examples/form-material-ui-mutation-mode/cypress/e2e/all.cy.ts
Fixed failing undoable e2e specs.
=> fix(examples/material-ui-mutation-mode): e2e undoable specs

documentation/blog/2024-01-03-k8s-image-pull.md
=> docs(blog): add image policy post

documentation/blog/2024-01-04-k8s-statefulset.md
=> docs(blog): add k8s stateful post

documentation/blog/2024-01-05-kubectl-version.md
=> docs(blog): add kubectl version post

examples/with-nextjs-appdir/app/layout.tsx
https://refine.dev/docs/ui-integrations/ant-design/theming/#usenotificationprovider-compatible-with-theme
=> fix(example with-nextjs-appdir): use useNotificationProvider

documentation/blog/2024-01-11-react-ecosystem-2024.md
=> docs(blog): add react ecosystem post

documentation/blog/2024-01-12-k8s-operators.md
=> docs(blog): add K8S operators post

documentation/docs/tutorial/4-adding-crud-pages/mantine/add-delete-feature.md
On this page https://refine.dev/docs/tutorial/adding-crud-pages/mantine/add-delete-feature/#adding-delete-feature-to-list-page, the example in the list section refers to antd, but we are currently in the Mantine documentation.
Just open the docs
closes #5519
-   [x] Changesets are provided or not …
=> docs(mantine): fix package reference

documentation/blog/2022-09-13-react-memo.md
I updated the React memo post.
=> docs(blog): update React memo post

documentation/blog/2022-09-16-react-use-memo.md, documentation/blog/2023-02-01-uri-vs-url.md, documentation/blog/2023-10-26-htmx.md
I updated GRPC & useMemo & HTMX posts.
=> Update grpc memo posts

examples/app-crm-minimal/src/components/layout/gh-banner/index.tsx, examples/app-crm/src/components/layout/gh-banner/index.tsx
=> feat(app-crm-minimal): align banner text to center

documentation/docs/ui-integrations/chakra-ui/components/themed-layout/index.md, documentation/docs/ui-integrations/mantine/components/themed-layout/index.md, documentation/docs/ui-integrations/material-ui/components/themed-layout/index.md
=> docs(fix): Fix ThemedTitleV2 typos and imports in docs

documentation/blog/2024-01-22-grpc-vs-rest.md, documentation/blog/2024-01-22-k8s-postgres.md
I updated grpc post and added new post on K8S
=> docs(blog): update grpc post

documentation/docs/guides-concepts/contributing/index.md
I added an Issue ID to the changeset format, so we can manage releases more easily.
=> chore: update changeset format

documentation/plugins/templates.js, documentation/plugins/templates.ts
This small documentation update doesn't need any test plan I guess.
closes https://github.com/refinedev/refine/issues/5557#event-11605476756
- …
=> Fix Pixels template link

documentation/docs/guides-concepts/general-concepts/index.md, package-lock.json, package.json
Added Headless Concept section to general concepts guide.
=> docs: add headless concept section to general concepts guide

.changeset/cool-trainers-whisper.md, packages/nextjs-router/src/index.ts
Updated index exports to provide appropriate types for the exported elements.
Current tests will also test for these changes.
Resolves #5548
=> fix(nextjs-router): type exports from index

.changeset/clean-rules-return.md, packages/inferencer/package.json
Updated type exports in `package.json` and included them in the `exports` field.
Current tests will test this PR accordingly.
Resolves #5528
=> fix(inferencer): exports from the `package.json`

examples/store/Dockerfile, examples/store/next.config.js, packages/live-previews/Dockerfile, packages/live-previews/next.config.js
Updated `Dockerfile` for `examples/store` and `packages/live-previews`.
=> fix: Store and Live Preview deployments

documentation/docs/core/interface-references/index.md
=> fix(docs): typo in interface references

.changeset/unlucky-mayflies-agree.md, packages/core/src/components/pages/config-success/index.spec.tsx, packages/core/src/components/pages/config-success/index.tsx
=> chore: update WelcomePage links

packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/list.test.tsx.snap
Updated failing inferencer snapshots.
=> fix(inferencer): update snaphots

packages/live-previews/package.json, packages/live-previews/pages/preview.tsx, packages/live-previews/src/scope/antd.tsx, packages/live-previews/src/scope/appwrite.tsx, packages/live-previews/src/scope/hasura.tsx, packages/live-previews/src/scope/map.tsx, packages/live-previews/src/scope/nestjs-query.tsx, packages/live-previews/src/utils/check-package.ts
feat: added following missing dependencies to live-previews:
- @uiw/react-md-editor
- uuid
- @types/uuid
- graphql-tag
- graphql-ws
=> feat(live-previews): add missing dependencies

packages/live-previews/next.config.js, packages/live-previews/package.json, packages/live-previews/src/scope/antd.tsx, packages/live-previews/src/scope/map.tsx
missing dependency added to nestjs-query
=> fix(live-previews): missing nestjs-query-dependency

documentation/docusaurus.config.js, documentation/src/css/custom.css, documentation/src/refine-theme/common-layout.tsx, documentation/src/refine-theme/doc-page-layout.tsx
Kapa AI widget added to refine.dev
=> feat(docs): add kapa ai widget

examples/data-provider-strapi-v4/src/App.tsx
A quick fix for an obvious typo
=> Fix typo: mesage -> message

documentation/docs/examples/form/mantine/useDrawerForm.md, documentation/docs/ui-integrations/mantine/introduction/index.md
fixes #5659
Changesets are not added as this is a documentation change without affecting packages.
=> docs: updated Mantine references in docs

documentation/docs/examples/form/chakra-ui/useDrawerForm.md, documentation/docs/examples/form/chakra-ui/useForm.md, documentation/docs/ui-integrations/chakra-ui/introduction/index.md
fixes #5658
Changesets are not added as this is a documentation change without affecting packages.
=> docs: updated Chakra UI references in docs

documentation/src/refine-theme/landing-hero-showcase-section.tsx
=> feat(docs): add new finefoods image to landing showcase

examples/finefoods-antd/src/components/product/drawer-show/index.tsx
after closing [product drawer](https://example.admin.refine.dev/products), browser tab is closing
The browser tab not closing
=> fix(finefoods-antd): remove window.close on finefoods antd

documentation/README.md
`start` script doesn't exist, replaced with `dev` one
=> docs(readme): improved readme

examples/data-provider-supabase/src/pages/posts/create.tsx, examples/data-provider-supabase/src/pages/posts/edit.tsx, examples/data-provider-supabase/src/pages/posts/list.tsx
=> fix: supabase example error

examples/data-provider-supabase/src/pages/posts/create.tsx, examples/data-provider-supabase/src/pages/posts/edit.tsx, examples/data-provider-supabase/src/pages/posts/list.tsx
=> Revert "fix: supabase example error"

documentation/docs/guides-concepts/routing/remix/use-table-usage.tsx, documentation/docs/routing/integrations/remix/index.md, documentation/docs/ui-integrations/ant-design/introduction/previews/layout-remix.tsx, documentation/docs/ui-integrations/ant-design/introduction/previews/usage-remix.tsx, documentation/docs/ui-integrations/chakra-ui/introduction/previews/layout-remix.tsx, documentation/docs/ui-integrations/chakra-ui/introduction/previews/usage-remix.tsx, documentation/docs/ui-integrations/mantine/introduction/previews/layout-remix.tsx, documentation/docs/ui-integrations/mantine/introduction/previews/usage-remix.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/layout-remix.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/usage-remix.tsx, examples/with-remix-antd/app/routes/_auth.tsx, examples/with-remix-antd/app/routes/_protected.posts._index.tsx, examples/with-remix-antd/app/routes/_protected.posts.edit.$id.tsx, examples/with-remix-antd/app/routes/_protected.posts.show.$id.tsx, examples/with-remix-antd/app/routes/_protected.tsx, examples/with-remix-auth/app/root.tsx, examples/with-remix-auth/app/routes/_auth.tsx, examples/with-remix-auth/app/routes/_protected.tsx, examples/with-remix-auth/app/routes/auth.$provider._index.tsx, examples/with-remix-auth/app/routes/auth.$provider.callback.tsx, examples/with-remix-auth/app/routes/auth.logout.tsx, examples/with-remix-headless/app/routes/_auth.tsx, examples/with-remix-headless/app/routes/_protected.posts._index.tsx, examples/with-remix-headless/app/routes/_protected.posts.create.tsx, examples/with-remix-headless/app/routes/_protected.posts.edit.$id.tsx, examples/with-remix-headless/app/routes/_protected.tsx, examples/with-remix-material-ui/app/routes/_auth.tsx, examples/with-remix-material-ui/app/routes/_layout.tsx
Type is not set correctly.
Type is set correctly.
fixes #5721
=> fix(remix): rename `LoaderArgs/ActionArgs` to `LoaderFunctionArgs/ActionFunctionArgs`

documentation/src/refine-theme/doc-item-layout.tsx
The emoji survey widget is removed in favor of thumbs up/down feedback widget
=> feat(docs): remove emoji survey widget

.github/workflows/pull-request.yml, documentation/docs/guides-concepts/authentication/auth-pages/mui.tsx, documentation/docs/guides-concepts/forms/server-side-validation-mui.tsx, documentation/docs/guides-concepts/general-concepts/auth-pages/mui.tsx, documentation/docs/guides-concepts/general-concepts/layout/mui.tsx, documentation/docs/guides-concepts/notifications/notifications-mantine.tsx, documentation/docs/guides-concepts/notifications/notifications-mui.tsx, documentation/docs/guides-concepts/tables/example/chakra-ui.tsx, documentation/docs/guides-concepts/tables/example/mantine.tsx, documentation/docs/guides-concepts/tables/example/material-ui.tsx, documentation/docs/guides-concepts/tables/example/search-material-ui.tsx, documentation/docs/guides-concepts/tables/index.md, documentation/docs/ui-integrations/material-ui/introduction/previews/auth-page.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/basic-views.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/example.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/layout-next-js.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/layout-react-router-dom.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/layout-remix.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/theming.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/usage-next-js.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/usage-react-router-dom.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/usage-remix.tsx
Currently Sandpack examples with MUI are failing due to missing dependency added recently.
=> fix(docs): add missing dependency to mui docs

documentation/src/refine-theme/landing-sweet-spot.tsx
Has a typo on the landing page
Typo fixed
=> fix(docs): landing page typo

documentation/docs/ui-integrations/ant-design/introduction/index.md, documentation/docs/ui-integrations/chakra-ui/introduction/index.md, documentation/docs/ui-integrations/mantine/introduction/index.md, documentation/docs/ui-integrations/material-ui/introduction/index.md
=> fix(docs): Correct spelling of "buttun" to "button"

.github/workflows/master-push.yml
- use `actions/checkout@v4`
- Removed redundant `Workflow run cleanup action` step. It's not needed for `actions/checkout@v4`
- Removed redundant setup-node step.
DNS record will be updated after merge, before deployment.
=> feat(live-previews): use AWS k8s config for deployment

documentation/docs/guides-concepts/faq/index.md
Added a new question to the FAQ guide about common network errors logged to the console by the browser (devtools and inferencer)
RK-604
=> docs(faq): section about network errors in faq

.changeset/breezy-pandas-think.md, .changeset/orange-eyes-swim.md, packages/cli/package.json, packages/codemod/package.json
=> chore(cli): update `semver` package to `7.5.2`.

.changeset/dirty-cameras-repeat.md
Added changesets to reflect README.md changes made in the #5729
=> chore: add readme changesets

documentation/docs/core/hooks/utilities/buttons/index.md, documentation/docs/routing/hooks/use-resource-params/index.md, documentation/docs/routing/hooks/use-resource/index.md, documentation/sidebars.js
- Added `useResourceParams` hook docs
- Added button hooks from `@refinedev/core`
=> docs(core): add button hook docs

documentation/docs/ui-integrations/mantine/hooks/use-select/index.md
=> added 's' to filter

documentation/package-lock.json, documentation/package.json
Updated `@codesandbox/sandpack-react` version to latest that includes some module fixes in the bundler.
Resolves #5802
=> docs(sandpack): bump version

documentation/docs/ui-integrations/ant-design/components/buttons/clone-button/index.md, documentation/docs/ui-integrations/ant-design/components/buttons/edit-button/index.md, documentation/docs/ui-integrations/ant-design/components/buttons/show-button/index.md
=> fix(docs): broken live previews for antd clone, edit, show button pages

examples/data-provider-strapi-v4/README.md, examples/data-provider-strapi/README.md
I updated Strapi data providers README's.
=> chore: update data provider README s

.changeset/rude-suns-agree.md, packages/nextjs-router/src/app/bindings.tsx, packages/nextjs-router/src/common/parse-table-params.ts, packages/nextjs-router/src/pages/bindings.tsx, packages/react-router-v6/src/bindings.tsx, packages/remix/src/bindings.tsx, packages/remix/src/parse-table-params.ts, packages/strapi-v4/src/dataProvider.ts, packages/strapi-v4/src/helpers/auth.ts, packages/strapi-v4/src/utils/generateFilter.ts
Updated `qs` imports and usage to prevent issues with ESM builds and to ensure correctly importing the module.
Resolves #5846
Resolves #5831
=> fix: qs imports and usage in ESM builds

examples/blog-react-hook-dynamic-form/src/pages/userEdit.tsx
…rray changes
Updated the usage of `useFieldArray` and `useForm` to make sure re-render occurs after the fields are updated with API response
Resolves #5894
=> chore(react-hook-dynamic-form): update edit page to watch for array fields

documentation/docs/guides-concepts/development/index.md
Updated the devtools guide with alternative running methods, required ports and privacy sections. 
Resolves #5840
=> docs(deployment): improve devtools section

examples/app-crm/src/routes/companies/list.tsx, examples/app-crm/src/routes/contacts/list.tsx, examples/app-crm/src/routes/quotes/list.tsx
fixes #5798
https://github.com/refinedev/refine/assets/23058882/d033c7c7-b225-4ba8-a90c-f05fb7e947d0
=> fix(app-crm): search input should work sync with location

documentation/docs/guides-concepts/i18n/i18n-headless.tsx
=> docs(i18n): fix `changeLocale` reference in i18n headless example

.github/workflows/master-push.yml, .github/workflows/pull-request-doc.yml
- updated `pnpm deploy` to `pnpm run deploy`.
- removed `--ignore-workspace` flag from documentation pnpm commands.
=> fix(ci): documentation deploy workflow

packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/create.test.tsx.snap, packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/edit.test.tsx.snap
`inferencer` snapshot tests are updated.
=> fix(inferencer): update mui snapshots

examples/invoicer/netlify.toml
=> fix(invoicer): remove netlify config

examples/blog-refine-digital-ocean/README.MD, examples/invoicer/README.md
=> chore: update invoicer README

.changeset/big-planets-raise.md, packages/cli/src/commands/runner/projectScripts.ts
=> fix(cli): remove hardcoded path prefix from remix bin command

documentation/docs/ui-integrations/ant-design/components/filter-dropdown/index.md, packages/antd/src/definitions/filter-mappers/index.ts
=> chore(docs): fix typos

.github/workflows/example-previews-comment.yml
=> chore(actions): fix example-reviews-comment workflow

packages/live-previews/netlify.toml, packages/live-previews/package.json, pnpm-lock.yaml
Added netlify plugin to live-previews to fix deployment issue.
=> feat(live-previews): add netlify plugin

.github/workflows/example-previews-comment.yml
=> fix(ci): preview comment date compare script

examples/auth-keycloak/package.json, packages/live-previews/package.json, pnpm-lock.yaml
=> fix(auth-keycloak): update keycloak-js dependency to latest

.github/workflows/documentation.yml
Updated `actions/checkout` action to fetch all git history.
Resolves #6129
=> ci(docs): fetch all git history for proper authorship attribution

documentation/docs/guides-concepts/authentication/auth-pages/mui.tsx, documentation/docs/guides-concepts/forms/server-side-validation-mui.tsx, documentation/docs/guides-concepts/forms/use-select-material-ui.tsx, documentation/docs/guides-concepts/general-concepts/auth-pages/mui.tsx, documentation/docs/guides-concepts/general-concepts/layout/mui.tsx, documentation/docs/guides-concepts/notifications/notifications-mui.tsx, documentation/docs/guides-concepts/tables/example/material-ui.tsx, documentation/docs/guides-concepts/tables/example/search-material-ui.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/auth-page.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/basic-views.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/example.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/layout-next-js.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/layout-react-router-dom.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/layout-remix.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/theming.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/usage-next-js.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/usage-react-router-dom.tsx, documentation/docs/ui-integrations/material-ui/introduction/previews/usage-remix.tsx, documentation/tutorial/ui-libraries/intro/material-ui/react-router/sandpack.tsx
Pinned dependencies to avoid compatibility issues with Sandpack and fixed the preview in Layout section of the Material UI tutorial.
Resolves #6186
=> docs(tutorial): fix layout preview in material ui tutorial

examples/data-provider-appwrite-tutorial-docs/src/App.tsx, examples/data-provider-appwrite-tutorial-docs/src/interfaces/index.d.ts, examples/data-provider-appwrite-tutorial-docs/src/pages/categories/create.tsx, examples/data-provider-appwrite-tutorial-docs/src/pages/categories/edit.tsx, examples/data-provider-appwrite-tutorial-docs/src/pages/categories/index.tsx, examples/data-provider-appwrite-tutorial-docs/src/pages/categories/list.tsx, examples/data-provider-appwrite-tutorial-docs/src/pages/categories/show.tsx, examples/data-provider-appwrite-tutorial-docs/src/pages/posts/create.tsx, examples/data-provider-appwrite-tutorial-docs/src/pages/posts/edit.tsx, examples/data-provider-appwrite-tutorial-docs/src/pages/posts/list.tsx, examples/data-provider-appwrite-tutorial-docs/src/pages/posts/show.tsx, examples/data-provider-appwrite-tutorial-docs/src/utility/appwriteClient.ts, examples/data-provider-appwrite-tutorial-docs/src/utility/auth-provider.ts, examples/data-provider-appwrite-tutorial-docs/src/utility/index.ts, examples/data-provider-appwrite-tutorial-docs/src/utility/status.ts, examples/data-provider-appwrite/src/App.tsx, examples/data-provider-appwrite/src/interfaces/index.d.ts, examples/data-provider-appwrite/src/pages/categories/create.tsx, examples/data-provider-appwrite/src/pages/categories/edit.tsx, examples/data-provider-appwrite/src/pages/categories/index.tsx, examples/data-provider-appwrite/src/pages/categories/list.tsx, examples/data-provider-appwrite/src/pages/categories/show.tsx, examples/data-provider-appwrite/src/pages/posts/create.tsx, examples/data-provider-appwrite/src/pages/posts/edit.tsx, examples/data-provider-appwrite/src/pages/posts/list.tsx, examples/data-provider-appwrite/src/pages/posts/show.tsx, examples/data-provider-appwrite/src/utility/appwriteClient.ts, examples/data-provider-appwrite/src/utility/auth-provider.ts, examples/data-provider-appwrite/src/utility/index.ts, examples/data-provider-appwrite/src/utility/status.ts
Updated Appwrite examples (`data-provider-appwrite` and `data-provider-appwrite-tutorial-docs`) examples to use Appwrite Cloud instance.
Resolves #6167
=> chore(appwrite): update appwrite examples with cloud

documentation/docs/authentication/hooks/use-permissions/index.md
=> fix(docs): small markdown formatting fix

.changeset/odd-rats-travel.md, packages/devtools-ui/package.json, packages/devtools-ui/src/components/add-package-drawer.tsx, packages/devtools-ui/src/components/add-package.item.tsx, packages/devtools-ui/src/components/button.tsx, packages/devtools-ui/src/components/input.tsx, packages/devtools-ui/src/components/monitor-filters.tsx, packages/devtools-ui/src/components/packages.tsx, packages/devtools-ui/src/pages/onboarding.tsx, pnpm-lock.yaml
There is no client-side validation and loading state in devtools onboarding form
following improvements were made:
- client-side validation
- loading indicator
- error handling
https://github.com/user-attachments/assets/0177c8c5-d967-418b-af6e-ce7d5ae94702
=> feat(devtools): Improve onboarding page design

examples/app-crm-minimal/README.MD, examples/app-crm-minimal/src/routes/dashboard/components/upcoming-events/index.tsx, examples/app-crm-minimal/src/routes/dashboard/components/upcoming-events/queries.ts
=> fix(typo): correct typo in examples/app-crm-minimal

documentation/docs/packages/react-hook-form/introduction/index.md
=> docs(react-hook-form): fix typo in links

documentation/src/refine-theme/doc-survey-widget.tsx, documentation/src/refine-theme/tutorial-create-file-button.tsx, documentation/src/refine-theme/tutorial-parameter-dropdown.tsx, documentation/src/refine-theme/tutorial-update-file-button.tsx
- Fixed the broken styling in feedback widget of the tutorial
- Updated the colors of the file update buttons to match with the tutorial's color range
=> docs(tutorial): styling issues with the feedback widget

documentation/src/refine-theme/landing-hero-section.tsx
=> chore(docs): update CTA button text

documentation/src/refine-theme/landing-hero-showcase-section.tsx
=> feat(docs): update refine hr showcase images

documentation/src/assets/nav-menu.ts, documentation/src/refine-theme/common-header/constants.ts
meet Refine link was wrong.
meet Refine link updated.
=> fix(docs): meet refine link

documentation/plugins/templates.js, documentation/plugins/templates.ts
Fixed the live demo url of Refine HR template in `/templates`.
=> docs(templates): update refine-hr live demo

documentation/docs/ui-integrations/chakra-ui/components/basic-views/create/index.md, documentation/docs/ui-integrations/chakra-ui/components/basic-views/edit/index.md, documentation/docs/ui-integrations/chakra-ui/components/basic-views/list/index.md, documentation/docs/ui-integrations/chakra-ui/components/basic-views/show/index.md, documentation/docs/ui-integrations/chakra-ui/components/breadcrumb/index.md, documentation/docs/ui-integrations/chakra-ui/components/buttons/clone-button/index.md, documentation/docs/ui-integrations/chakra-ui/components/buttons/create-button/index.md, documentation/docs/ui-integrations/chakra-ui/components/buttons/delete-button/index.md, documentation/docs/ui-integrations/chakra-ui/components/buttons/edit-button/index.md, documentation/docs/ui-integrations/chakra-ui/components/buttons/export-button/index.md, documentation/docs/ui-integrations/chakra-ui/components/buttons/import-button/index.md, documentation/docs/ui-integrations/chakra-ui/components/buttons/list-button/index.md, documentation/docs/ui-integrations/chakra-ui/components/buttons/refresh-button/index.md, documentation/docs/ui-integrations/chakra-ui/components/buttons/save-button/index.md, documentation/docs/ui-integrations/chakra-ui/components/buttons/show-button/index.md, documentation/docs/ui-integrations/chakra-ui/components/fields/boolean-field/index.md, documentation/docs/ui-integrations/chakra-ui/components/fields/date-field/index.md, documentation/docs/ui-integrations/chakra-ui/components/fields/email-field/index.md, documentation/docs/ui-integrations/chakra-ui/components/fields/file-field/index.md, documentation/docs/ui-integrations/chakra-ui/components/fields/number-field/index.md, documentation/docs/ui-integrations/chakra-ui/components/fields/tag-field/index.md, documentation/docs/ui-integrations/chakra-ui/components/fields/text-field/index.md, documentation/docs/ui-integrations/chakra-ui/components/fields/url-field/index.md
Updated broken links to official documentation of Chakra UI with the correct ones.
=> docs(chakra-ui): fix broken links from chakra-ui docs

.changeset/ten-radios-rush.md, packages/core/src/contexts/metaContext/index.spec.tsx, packages/core/src/contexts/metaContext/index.tsx, packages/core/src/hooks/useMeta/index.ts, packages/core/src/index.tsx
---
I added `MetaContext` to share data between components, providers, and hooks.
> 🚨 Designed for internal use only.
=> feat(core): add `<MetaContext />`

documentation/docs/data/hooks/use-one/index.md
=> docs(use-one): fix typo

documentation/docs/advanced-tutorials/real-time.md, documentation/docs/advanced-tutorials/web3/ethereum-signin.md, documentation/docs/data/packages/strapi-v4/index.md, documentation/docs/guides-concepts/contributing/index.md, documentation/docs/routing/router-provider/index.md
Commits 5b8cbf39373a1783f8e568d5dd5f42dcffa370bd and cc36402c0089bfbd2c9f84cc7ce0a3530aaf65b2 moved bunch of files without updating the sources.
The PR fixes all the broken github resources.
fixes (issue)
=> fix: update github references

packages/chakra-ui/README.md, packages/mantine/README.md
The `readme.md` files contain incorrect examples.
The examples have been updated.
=> fix: code examples in Mantine and Chakra UI README.md files

.github/workflows/refine-registry-release.yml, package.json, patches/@changesets__git@3.0.0.patch, pnpm-lock.yaml
=> feat: add refine registry release workflow

documentation/src/refine-theme/common-header.tsx, documentation/src/refine-theme/icons/refine-logo xmas.tsx
=> feat(docs): add xmas refine logo

documentation/docs/packages/list-of-packages/index.md, documentation/src/assets/integration-icons/chakra-v3.tsx, documentation/src/assets/integration-icons/index.ts, documentation/src/assets/integrations.ts, documentation/src/pages/integrations/index.tsx
This commit adds the integration support package link for Chakra UI v3. 
This is to support the latest version of Chakra UI.
Currently, there is no support for Chakra UI (v3) latest as UI framework.
This changeset adds support for using Chakra UI (v3) as UI framework.
None
=> docs(chakra-ui-v3): Add integration package for Chakra UI v3 [:sparkle:]

documentation/src/components/sandpack/index.tsx
Removed `<h3>` tag from sandpack SSR snapshots and replaced with a single `<div>`
=> docs(sandpack): update code file snapshots

documentation/docs/ui-integrations/ant-design/components/breadcrumb/index.md
--- 
Imports was wrong, fixed.
=> fix(docs): antd breadcrumb example

documentation/docs/advanced-tutorials/forms/custom-form-validation.md, documentation/docs/data/hooks/use-infinite-list/_basic-usage-live-preview.md, documentation/docs/data/hooks/use-infinite-list/_filtering-live-preview.md, documentation/docs/data/hooks/use-infinite-list/_sorting-live-preview.md, documentation/docs/data/hooks/use-list/_basic-usage-live-preview.md, documentation/docs/data/hooks/use-list/_filtering-live-preview.md, documentation/docs/data/hooks/use-list/_pagination-live-preview.md, documentation/docs/data/hooks/use-list/_sorting-live-preview.md, documentation/docs/data/hooks/use-many/_basic-usage-live-preview.md, documentation/docs/data/hooks/use-one/_basic-usage-live-preview.md, documentation/docs/data/hooks/use-select/_basic-usage-live-preview.md, documentation/docs/data/hooks/use-select/_default-value-live-preview.md, documentation/docs/data/hooks/use-select/_on-search-live-preview.md, documentation/docs/data/hooks/use-select/_sort-live-preview.md, documentation/docs/data/hooks/use-show/_basic-usage-live-preview.md, documentation/docs/data/hooks/use-table/_partial-basic-usage-live-preview.md, documentation/docs/data/hooks/use-table/_partial-filtering-live-preview.md, documentation/docs/data/hooks/use-table/_partial-pagination-live-preview.md, documentation/docs/data/hooks/use-table/_partial-relational-data-live-preview.md, documentation/docs/data/hooks/use-table/_partial-sorting-live-preview.md, documentation/docs/data/packages/supabase/index.md
----
All live-previews examples updated to react-router v7
=> feat(docs): upgrade live-preview examples to react router v7

documentation/docs/ui-integrations/material-ui/components/buttons/delete-button/index.md, documentation/docs/ui-integrations/material-ui/components/buttons/export-button/index.md, documentation/docs/ui-integrations/material-ui/components/buttons/import-button/index.md, documentation/src/refine-theme/common-header.tsx, documentation/src/refine-theme/landing-footer.tsx, documentation/src/refine-theme/top-announcement.tsx, packages/mui/src/components/buttons/delete/index.tsx, packages/mui/src/components/buttons/export/index.tsx, packages/mui/src/components/buttons/import/index.tsx, packages/mui/src/components/buttons/refresh/index.tsx, packages/mui/src/components/buttons/save/index.tsx
-----
- Refine Xmas Logo replaced with common Refine Logo
- Refine AI Top banner no longer appears on the "/ai" page
- fixed: Refine AI Top banner is broken on "/about" page
- Material UI's TS DOCS updated.
=> feat(docs): design updates

documentation/docs/ui-integrations/ant-design/hooks/use-editable-table/_partial-use-editable-table-live-preview.md
----
fixed: `useEditableTable` example.
=> fix(docs):  `useEditableTable` example on antd doc

documentation/src/assets/team.ts
=> chore: update team

documentation/src/pages/terms-of-service/index.tsx
Added ToS to `/terms-of-service` page of refine.dev
=> docs: add /terms-of-service page

documentation/docs/packages/react-hook-form/use-form/index.md, documentation/docs/packages/react-hook-form/use-modal-form/index.md, documentation/docs/packages/react-hook-form/use-steps-form/index.md, documentation/docs/packages/tanstack-table/examples/_partial-basic-usage-live-preview.md, documentation/docs/packages/tanstack-table/examples/_partial-filtering-live-preview.md, documentation/docs/packages/tanstack-table/examples/_partial-pagination-live-preview.md, documentation/docs/packages/tanstack-table/examples/_partial-relational-live-preview.md, documentation/docs/packages/tanstack-table/examples/_partial-sorting-live-preview.md, packages/live-previews/src/scope/common.tsx
---
live preview examples updated to react router v6
=> fix: live preview examples

documentation/docs/guides-concepts/forms/server-side-validation-antd.tsx, documentation/tutorial/ui-libraries/refactoring/ant-design/react-router/index.md
Removed the refineCoreProps from the ANTD examples in the tutorial. It was not intended to be placed there.
@DoguhanOzgurAkca
=> docs(tutorial): removed refineCoreProps from the ANTD example

.changeset/six-cooks-check.md, packages/hasura/src/dataProvider/index.ts, packages/hasura/test/create/index.mock.ts, packages/hasura/test/create/index.spec.ts
Hasura data provider doesn't respect meta.gqlVariables for create.
fixes #6775
=> fix(hasura): meta.gqlVariables passed to create Hasura data provider

documentation/tutorial/authentication/data-provider-integration/index.md, documentation/tutorial/authentication/data-provider-integration/sandpack.tsx, documentation/tutorial/routing/redirects/react-router/sandpack.tsx, documentation/tutorial/ui-libraries/authentication/ant-design/react-router/index.md
=> Error type warning

documentation/src/components/banner/banner-random.tsx, documentation/src/refine-theme/ai-landing-join-the-waitlist-cta.tsx
=> refactor: update call-to-action text from for ai

documentation/docusaurus.config.js, documentation/plugins/ahref.js, documentation/plugins/ahref.ts
=> feat(docs): added ahref web analytics

documentation/src/refine-theme/ai-faq.tsx, documentation/src/refine-theme/ai-landing-hero.tsx
---
* Updated the hero text of the `/ai` page:
* **Before:** “Instant React Dashboards”
* **After:** “Instant Internal Software”
* Formatted the FAQ section texts.
=> fix(docs): update call-to-action text in AI landing hero

documentation/src/assets/team.ts, documentation/src/pages/about/index.tsx
---
new team members added to https://refine.dev/about/
=> feat(docs): add new members

hackathon/hackathon-app-ideas.md
The Hackathon-app-ideas README jumps straight into the list of app ideas without any context or introduction.
Added a short introductory paragraph at the top of the README to give users context and improve clarity.
fixes (no issue linked)
This is a minor documentation enhancement to improve the reader’s experience. Let me know if further tweaks are needed!
=> docs: add intro context to README for better clarity

documentation/src/refine-theme/ai-landing-step-list.tsx
- [] Related issue(s) linked
- [] Tests for the changes have been added
fixes typo at refine AI site
=> docs: fix typo at refine AI 

.changeset/gorgeous-hornets-grin.md, packages/cli/src/commands/runner/projectScripts.ts
Bun use `node_modules/.bin/vite.exe`, refine cli can't recognise it.
partially #6402
=> fix(cli): bun compatability

.changeset/orange-planes-love.md, packages/create-refine-app/package.json, pnpm-lock.yaml
=> chore(create-refine-app): bump superplate-cli version to v20.0.1

.changeset/eight-masks-warn.md
=> chore: add changeset for antd dummy release

.changeset/good-zoos-wave.md, .changeset/metal-emus-camp.md, packages/codemod/src/transformations/refine4-to-refine5.ts, packages/codemod/src/transformations/v5/mutation-result-to-mutation-property.test.ts, packages/codemod/src/transformations/v5/mutation-result-to-mutation-property.ts, packages/codemod/src/transformations/v5/use-query-and-result-fields-in-useOne-hook.test.ts, packages/codemod/src/transformations/v5/use-query-and-result-fields-in-useOne-hook.ts
=> fix: update mutation hooks to use isLoading instead of isPending

documentation/docs/migration-guide/4x-to-5x.md
fix: add react query v5 installation to migration guide
=> fix: add react query v5 installation to migration guide

.changeset/old-starfishes-stare.md, packages/core/src/hooks/data/useCustom.ts, packages/core/src/hooks/data/useInfiniteList.ts, packages/core/src/hooks/data/useList.ts, packages/core/src/hooks/data/useMany.ts, packages/core/src/hooks/data/useOne.ts
=> fix(core): error notification infinite render issue

packages/core/src/hooks/accessControl/useCan/index.ts, packages/core/src/hooks/data/useCreate.ts, packages/core/src/hooks/data/useCreateMany.ts, packages/core/src/hooks/data/useCustom.ts, packages/core/src/hooks/data/useCustomMutation.ts, packages/core/src/hooks/data/useDelete.ts, packages/core/src/hooks/data/useDeleteMany.ts, packages/core/src/hooks/data/useInfiniteList.ts, packages/core/src/hooks/data/useList.ts, packages/core/src/hooks/data/useMany.ts, packages/core/src/hooks/data/useOne.ts, packages/core/src/hooks/data/useUpdate.ts, packages/core/src/hooks/data/useUpdateMany.ts, packages/core/src/hooks/form/types.ts, packages/core/src/hooks/show/types.ts, packages/core/src/hooks/useTable/index.ts
fix: replace old tanstack v4 links in tsdocs
=> fix: replace old tanstack v4 links in tsdocs
